import { directoryCompanies } from "./directory-companies";
import { directoryCompanies2 } from "./directory-companies-2";
import { directoryCompanies3 } from "./directory-companies-3";
import { directoryCompanies4 } from "./directory-companies-4";
import { directoryCompanies5 } from "./directory-companies-5";
import { directoryCompanies6 } from "./directory-companies-6";
import { directoryCompanies7 } from "./directory-companies-7";
import { remoteCompanies } from "./remote-companies";
import { targetTechCompanies } from "./target-tech-companies";
import { locationOverrides } from "./location-overrides";
import { bangaloreMapCompanies } from "./bangalore-map-companies";

const featuredStartups = [
  {slug:"razorpay",name:"Razorpay",initials:"RZ",description:"Full-stack financial solutions for businesses to accept, process and disburse payments.",city:"Bengaluru",neighborhood:"Koramangala",sector:"FinTech",stage:"Series C+",size:"500+",tech:["Java","React","Kubernetes","AWS"],hiring:true,founders:["Harshil Mathur","Shashank Kumar"],founded:2014,color:"#ff5b2e",roles:18,lat:12.9352,lng:77.6245},
  {slug:"postman",name:"Postman",initials:"PM",description:"The collaboration platform used by millions of developers to build and use APIs.",city:"Bengaluru",neighborhood:"Indiranagar",sector:"Developer Tools",stage:"Series C+",size:"500+",tech:["Node.js","TypeScript","React","AWS"],hiring:true,founders:["Abhinav Asthana","Ankit Sobti","Abhijit Kane"],founded:2014,color:"#ff8c42",roles:9,lat:12.9719,lng:77.6412},
  {slug:"meesho",name:"Meesho",initials:"ME",description:"Internet commerce platform making e-commerce accessible to millions of Indian consumers.",city:"Bengaluru",neighborhood:"Bellandur",sector:"E-commerce",stage:"Series C+",size:"500+",tech:["Java","Go","React","Kubernetes"],hiring:true,founders:["Vidit Aatrey","Sanjeev Barnwal"],founded:2015,color:"#f04aa2",roles:21,lat:12.9255,lng:77.6765},
  {slug:"cred",name:"CRED",initials:"CR",description:"Members-only platform rewarding creditworthy individuals for responsible financial behaviour.",city:"Bengaluru",neighborhood:"Indiranagar",sector:"FinTech",stage:"Series C+",size:"500+",tech:["Go","React","Kubernetes","AWS"],hiring:true,founders:["Kunal Shah"],founded:2018,color:"#d8ff43",roles:14,lat:12.9784,lng:77.6408},
  {slug:"swiggy",name:"Swiggy",initials:"SW",description:"Consumer-first convenience platform spanning food delivery, quick commerce, dining and other local services.",city:"Bengaluru",neighborhood:"Pattandur Agrahara",sector:"Consumer",stage:"Public",size:"500+",tech:["Java","Python","React","Redis"],hiring:true,founders:["Sriharsha Majety","Lakshmi Nandan Reddy Obul"],founded:2014,color:"#fc8019",roles:26,lat:12.9897,lng:77.7280},
  {slug:"whatfix",name:"Whatfix",initials:"WF",description:"Digital adoption platform helping enterprises improve software user experiences.",city:"Bengaluru",neighborhood:"HSR Layout",sector:"SaaS",stage:"Series C+",size:"500+",tech:["Java","React","TypeScript","AWS"],hiring:true,founders:["Khadim Batti","Vara Kumar"],founded:2014,color:"#1778f2",roles:11,lat:12.9116,lng:77.6389},
  {slug:"slice",name:"slice",initials:"SL",description:"Consumer payments company building simple, transparent financial products for young Indians.",city:"Bengaluru",neighborhood:"Koramangala",sector:"FinTech",stage:"Series C+",size:"500+",tech:["Go","Python","React","PostgreSQL"],hiring:true,founders:["Rajan Bajaj"],founded:2016,color:"#7b61ff",roles:8,lat:12.9346,lng:77.6266},
  {slug:"smallcase",name:"smallcase",initials:"SC",description:"Investment products and infrastructure that help Indians build diversified portfolios.",city:"Bengaluru",neighborhood:"Richmond Town",sector:"FinTech",stage:"Series C+",size:"201–500",tech:["Node.js","TypeScript","React","AWS"],hiring:false,founders:["Vasanth Kamath","Rohan Gupta","Anugrah Shrivastava"],founded:2015,color:"#5865f2",roles:0,lat:12.9634,lng:77.5995},
  {slug:"nference",name:"nference",initials:"NF",description:"Biomedical data platform helping scientists discover and develop personalized diagnostics and treatments.",city:"Bengaluru",neighborhood:"Murugeshpalya",sector:"AI",stage:"Series C+",size:"201–500",tech:["Python","AI/ML","React","AWS"],hiring:true,founders:["Murali Aravamudan","Venky Soundararajan"],founded:2013,color:"#06d6a0",roles:6,lat:12.9584,lng:77.6552},
  {slug:"scaler",name:"Scaler",initials:"SC",description:"Technology education platform helping professionals accelerate their software careers.",city:"Bengaluru",neighborhood:"HSR Layout",sector:"EdTech",stage:"Series B",size:"500+",tech:["Python","React","Node.js","MongoDB"],hiring:true,founders:["Anshuman Singh","Abhimanyu Saxena"],founded:2019,color:"#0f67ff",roles:10,lat:12.9141,lng:77.6446},
  {slug:"darwinbox",name:"Darwinbox",initials:"DB",description:"Cloud-based human capital management platform serving enterprises across more than 130 countries.",city:"Hyderabad",neighborhood:"HITEC City",sector:"SaaS",stage:"Series C+",size:"500+",tech:["Java","Spring Boot","React","PostgreSQL"],hiring:true,founders:["Chaitanya Peddi","Rohit Chennamaneni","Jayant Paleti","Vineet Singh"],founded:2015,color:"#7459ff",roles:12,lat:17.4435,lng:78.3772},
  {slug:"browserstack",name:"BrowserStack",initials:"BS",description:"Cloud web and mobile testing platform for developers and quality teams.",city:"Mumbai",neighborhood:"Andheri East",sector:"Developer Tools",stage:"Series B",size:"500+",tech:["Ruby","React","Kubernetes","AWS"],hiring:true,founders:["Ritesh Arora","Nakul Aggarwal"],founded:2011,color:"#00a896",roles:15,lat:19.1136,lng:72.8697},
  {slug:"agrostar",name:"AgroStar",initials:"AS",description:"AgriTech platform providing farm advisory, agricultural inputs and market access to Indian farmers.",city:"Pune",neighborhood:"Wadgaon Sheri",sector:"ClimateTech",stage:"Series C+",size:"500+",tech:["Python","Go","React","MongoDB"],hiring:false,founders:["Shardul Sheth","Sitanshu Sheth"],founded:2013,color:"#06a77d",roles:0,lat:18.5517,lng:73.9328},
  {slug:"chargebee",name:"Chargebee",initials:"CB",description:"Revenue infrastructure for AI, SaaS and consumer subscription businesses.",city:"Chennai",neighborhood:"Perungudi",sector:"SaaS",stage:"Series C+",size:"500+",tech:["Java","React","Redis","AWS"],hiring:true,founders:["Krish Subramanian","Rajaraman Santhanam","Saravanan KP"],founded:2011,color:"#118ab2",roles:7,lat:12.9629,lng:80.2445},
  {slug:"devtron",name:"Devtron",initials:"DT",description:"Open-source platform that simplifies Kubernetes adoption for engineering teams.",city:"Delhi NCR",neighborhood:"Gurugram",sector:"Developer Tools",stage:"Series A",size:"51–200",tech:["Go","React","Kubernetes","PostgreSQL"],hiring:true,founders:["Prashant Ghildiyal","Nishant Kumar"],founded:2019,color:"#ef476f",roles:5,lat:28.4595,lng:77.0266},
  {slug:"zerodha",name:"Zerodha",initials:"ZE",description:"Online investment platform offering trading and investing in stocks, derivatives, mutual funds and bonds.",city:"Bengaluru",neighborhood:"J.P. Nagar",sector:"FinTech",stage:"Bootstrapped",size:"500+",tech:["Python","TypeScript","React","PostgreSQL"],hiring:true,founders:["Nithin Kamath","Nikhil Kamath"],founded:2010,color:"#387ed1",roles:1,lat:12.9077,lng:77.5850},
  {slug:"phonepe",name:"PhonePe",initials:"PP",description:"Digital payments and financial services platform for consumers and merchants across India.",city:"Bengaluru",neighborhood:"Bellandur",sector:"FinTech",stage:"Series C+",size:"500+",tech:["Java","Go","React","Kubernetes"],hiring:true,founders:["Sameer Nigam","Rahul Chari","Burzin Engineer"],founded:2015,color:"#5f259f",roles:1,lat:12.9279,lng:77.6271},
  {slug:"groww",name:"Groww",initials:"GR",description:"Investment platform enabling customers to invest in stocks, mutual funds, ETFs, IPOs and other financial products.",city:"Bengaluru",neighborhood:"Bellandur",sector:"FinTech",stage:"Public",size:"500+",tech:["Java","Kotlin","React","AWS"],hiring:true,founders:["Lalit Keshre","Harsh Jain","Neeraj Singh","Ishan Bansal"],founded:2016,color:"#00d09c",roles:1,lat:12.9265,lng:77.6762},
  {slug:"ather-energy",name:"Ather Energy",initials:"AE",description:"Electric vehicle company designing and manufacturing connected electric scooters and charging infrastructure.",city:"Bengaluru",neighborhood:"I.B.C. Knowledge Park",sector:"ClimateTech",stage:"Public",size:"500+",tech:["Python","Android","React","Embedded Systems"],hiring:true,founders:["Tarun Mehta","Swapnil Jain"],founded:2013,color:"#20b486",roles:1,lat:12.9291,lng:77.5995},
  {slug:"juspay",name:"Juspay",initials:"JP",description:"Payments infrastructure company building checkout, orchestration and authentication products for enterprises and banks.",city:"Bengaluru",neighborhood:"Koramangala",sector:"FinTech",stage:"Series C+",size:"500+",tech:["Haskell","Java","React","AWS"],hiring:true,founders:["Vimal Kumar","Sheetal Lalwani"],founded:2012,color:"#1769ff",roles:1,lat:12.9352,lng:77.6245},
  {slug:"rapido",name:"Rapido",initials:"RA",description:"Mobility platform connecting customers with bike-taxi, auto and cab captains in cities across India.",city:"Bengaluru",neighborhood:"HSR Layout",sector:"Mobility",stage:"Series C+",size:"500+",tech:["Go","Java","React","Kubernetes"],hiring:true,founders:["Aravind Sanka","Pavan Guntupalli","Rishikesh SR"],founded:2015,color:"#ffd400",roles:1,lat:12.9116,lng:77.6389},
  {slug:"porter",name:"Porter",initials:"PO",description:"Technology-enabled logistics platform providing on-demand trucks, two-wheelers and packers and movers services.",city:"Bengaluru",neighborhood:"Bommanahalli",sector:"Logistics",stage:"Series C+",size:"500+",tech:["Python","Go","React","PostgreSQL"],hiring:true,founders:["Pranav Goel","Uttam Digga","Vikas Choudhary"],founded:2014,color:"#0057d9",roles:1,lat:12.8997,lng:77.6241},
  {slug:"inmobi",name:"InMobi",initials:"IM",description:"Advertising technology company providing mobile marketing and monetization platforms for brands and publishers.",city:"Bengaluru",neighborhood:"Kadubeesanahalli",sector:"AdTech",stage:"Series C+",size:"500+",tech:["Java","Python","React","Kubernetes"],hiring:true,founders:["Naveen Tewari","Amit Gupta","Abhay Singhal","Mohit Saxena"],founded:2007,color:"#00a9e0",roles:1,lat:12.9394,lng:77.6948},
  {slug:"nobroker",name:"NoBroker",initials:"NB",description:"Real-estate platform connecting property owners and customers without traditional brokerage.",city:"Bengaluru",neighborhood:"Kaikondrahalli",sector:"PropTech",stage:"Series C+",size:"500+",tech:["Java","React","Node.js","AWS"],hiring:true,founders:["Amit Sharma","Akhil Gupta","Saurabh Garg"],founded:2014,color:"#ff385c",roles:1,lat:12.9145,lng:77.6779},
  {slug:"practo",name:"Practo",initials:"PR",description:"Digital healthcare platform helping patients find doctors, book appointments and access healthcare services.",city:"Bengaluru",neighborhood:"Koramangala",sector:"HealthTech",stage:"Series C+",size:"500+",tech:["Java","Python","React","AWS"],hiring:true,founders:["Shashank ND","Abhinav Lal"],founded:2008,color:"#14bef0",roles:1,lat:12.9279,lng:77.6271},
  {slug:"udaan",name:"udaan",initials:"UD",description:"B2B commerce platform connecting small retailers with manufacturers and wholesalers across India.",city:"Bengaluru",neighborhood:"Bellandur",sector:"B2B Commerce",stage:"Series C+",size:"500+",tech:["Java","Kotlin","React","Kubernetes"],hiring:true,founders:["Amod Malviya","Sujeet Kumar","Vaibhav Gupta"],founded:2016,color:"#f15b40",roles:1,lat:12.9255,lng:77.6765},
  {slug:"licious",name:"Licious",initials:"LI",description:"Consumer food brand delivering fresh meat, seafood and ready-to-cook products through its online platform.",city:"Bengaluru",neighborhood:"Domlur",sector:"Consumer",stage:"Series C+",size:"500+",tech:["Java","Python","React","AWS"],hiring:true,founders:["Abhay Hanjura","Vivek Gupta"],founded:2015,color:"#e41e49",roles:1,lat:12.9611,lng:77.6387},
  {slug:"sharechat",name:"ShareChat",initials:"SH",description:"Social media company operating ShareChat and Moj for Indian-language content and creator communities.",city:"Bengaluru",neighborhood:"Bellandur",sector:"Consumer",stage:"Series C+",size:"500+",tech:["Go","Java","React","Kubernetes"],hiring:true,founders:["Ankush Sachdeva","Bhanu Pratap Singh","Farid Ahsan"],founded:2015,color:"#7a42f4",roles:1,lat:12.9275,lng:77.6810},
  {slug:"simplilearn",name:"Simplilearn",initials:"SI",description:"Digital learning platform offering professional certification and postgraduate programs in technology and business.",city:"Bengaluru",neighborhood:"HSR Layout",sector:"EdTech",stage:"Series C+",size:"500+",tech:["Java","PHP","React","AWS"],hiring:true,founders:["Krishna Kumar"],founded:2010,color:"#1179ef",roles:1,lat:12.9121,lng:77.6446},
  {slug:"ninjacart",name:"Ninjacart",initials:"NC",description:"Fresh-produce supply-chain platform connecting farmers, retailers and businesses through technology.",city:"Bengaluru",neighborhood:"Kadubeesanahalli",sector:"AgriTech",stage:"Series C+",size:"500+",tech:["Java","Python","React","Kubernetes"],hiring:true,founders:["Thirukumaran Nagarajan","Vasudevan Chinnathambi","Sharath Loganathan","Karthik Ravindran","Sachin Jose"],founded:2015,color:"#6bbf45",roles:1,lat:12.9394,lng:77.6948},
  {slug:"flipkart",name:"Flipkart",initials:"FK",description:"Digital commerce marketplace connecting Indian customers with sellers and brands across product categories.",city:"Bengaluru",neighborhood:"Bellandur",sector:"E-commerce",stage:"Acquired",size:"500+",tech:[],hiring:true,founders:["Sachin Bansal","Binny Bansal"],founded:2007,color:"#2874f0",roles:1,lat:12.9272,lng:77.6762},
  {slug:"myntra",name:"Myntra",initials:"MY",description:"Fashion and lifestyle commerce platform offering apparel, footwear, accessories and beauty products.",city:"Bengaluru",neighborhood:"Kadubeesanahalli",sector:"E-commerce",stage:"Acquired",size:"500+",tech:[],hiring:true,founders:["Mukesh Bansal","Ashutosh Lawania","Vineet Saxena"],founded:2007,color:"#ff3f6c",roles:1,lat:12.9391,lng:77.6974},
  {slug:"ola",name:"Ola",initials:"OL",description:"Mobility platform providing ride-hailing and transportation services across Indian cities.",city:"Bengaluru",neighborhood:"Koramangala",sector:"Mobility",stage:"Series C+",size:"500+",tech:[],hiring:true,founders:["Bhavish Aggarwal","Ankit Bhati"],founded:2010,color:"#cddc39",roles:1,lat:12.9358,lng:77.6248},
  {slug:"ola-electric",name:"Ola Electric",initials:"OE",description:"Electric vehicle manufacturer building electric scooters, energy products and supporting technology.",city:"Bengaluru",neighborhood:"Koramangala",sector:"ClimateTech",stage:"Public",size:"500+",tech:[],hiring:true,founders:["Bhavish Aggarwal"],founded:2017,color:"#111111",roles:1,lat:12.9345,lng:77.6281},
  {slug:"delhivery",name:"Delhivery",initials:"DL",description:"Integrated logistics company providing parcel, freight, warehousing and supply-chain services.",city:"Delhi NCR",neighborhood:"Gurugram",sector:"Logistics",stage:"Public",size:"500+",tech:[],hiring:true,founders:["Sahil Barua","Mohit Tandon","Bhavesh Manglani","Kapil Bharati","Suraj Saharan"],founded:2011,color:"#e31837",roles:1,lat:28.4598,lng:77.0732},
  {slug:"freshworks",name:"Freshworks",initials:"FW",description:"Software company providing customer support, IT service management, CRM and employee experience products.",city:"Chennai",neighborhood:"Perungudi",sector:"SaaS",stage:"Public",size:"500+",tech:[],hiring:true,founders:["Girish Mathrubootham","Shan Krishnasamy"],founded:2010,color:"#0bce83",roles:1,lat:12.9698,lng:80.2431},
  {slug:"zoho",name:"Zoho",initials:"ZO",description:"Technology company offering a broad suite of cloud business software for organizations worldwide.",city:"Chennai",neighborhood:"Estancia IT Park",sector:"SaaS",stage:"Bootstrapped",size:"500+",tech:[],hiring:true,founders:["Sridhar Vembu","Tony Thomas"],founded:1996,color:"#f4b400",roles:1,lat:12.8014,lng:80.0254},
  {slug:"zomato",name:"Zomato",initials:"ZM",description:"Consumer internet company operating restaurant discovery, food delivery and related services.",city:"Delhi NCR",neighborhood:"Gurugram",sector:"Consumer",stage:"Public",size:"500+",tech:[],hiring:true,founders:["Deepinder Goyal","Pankaj Chaddah"],founded:2008,color:"#e23744",roles:1,lat:28.4512,lng:77.0714},
  {slug:"paytm",name:"Paytm",initials:"PT",description:"Digital payments and financial services platform serving consumers and merchants in India.",city:"Delhi NCR",neighborhood:"Noida",sector:"FinTech",stage:"Public",size:"500+",tech:[],hiring:true,founders:["Vijay Shekhar Sharma"],founded:2010,color:"#00b9f1",roles:1,lat:28.5672,lng:77.3209},
  {slug:"policybazaar",name:"Policybazaar",initials:"PB",description:"Online insurance marketplace helping consumers compare and purchase insurance products.",city:"Delhi NCR",neighborhood:"Gurugram",sector:"FinTech",stage:"Public",size:"500+",tech:[],hiring:true,founders:["Yashish Dahiya","Alok Bansal","Avaneesh Nirjar"],founded:2008,color:"#0065ff",roles:1,lat:28.4744,lng:77.0806},
  {slug:"makemytrip",name:"MakeMyTrip",initials:"MM",description:"Online travel company offering flight, hotel, holiday, bus and rail booking services.",city:"Delhi NCR",neighborhood:"Gurugram",sector:"TravelTech",stage:"Public",size:"500+",tech:[],hiring:true,founders:["Deep Kalra"],founded:2000,color:"#e41d3d",roles:1,lat:28.4639,lng:77.0490},
  {slug:"dream11",name:"Dream11",initials:"D11",description:"Fantasy sports platform where users create teams for live sporting events and enter contests.",city:"Mumbai",neighborhood:"Lower Parel",sector:"Gaming",stage:"Series C+",size:"500+",tech:[],hiring:true,founders:["Harsh Jain","Bhavit Sheth"],founded:2008,color:"#d71920",roles:1,lat:18.9987,lng:72.8258},
  {slug:"nykaa",name:"Nykaa",initials:"NY",description:"Omnichannel consumer company offering beauty, personal care, wellness and fashion products.",city:"Mumbai",neighborhood:"Lower Parel",sector:"E-commerce",stage:"Public",size:"500+",tech:[],hiring:true,founders:["Falguni Nayar"],founded:2012,color:"#fc2779",roles:1,lat:18.9979,lng:72.8264},
  {slug:"upstox",name:"Upstox",initials:"UP",description:"Online investment platform providing trading and investing access across financial products.",city:"Mumbai",neighborhood:"Prabhadevi",sector:"FinTech",stage:"Series C+",size:"500+",tech:[],hiring:true,founders:["Ravi Kumar","Raghu Kumar","Shrini Viswanath"],founded:2009,color:"#6f32be",roles:1,lat:19.0166,lng:72.8295},
  {slug:"pine-labs",name:"Pine Labs",initials:"PL",description:"Merchant commerce platform providing payment terminals, online payments and financial services.",city:"Delhi NCR",neighborhood:"Noida",sector:"FinTech",stage:"Series C+",size:"500+",tech:[],hiring:true,founders:["Lokvir Kapoor","Rajul Garg","Tarun Upadhyay"],founded:1998,color:"#00a79d",roles:1,lat:28.5781,lng:77.3152},
  {slug:"bharatpe",name:"BharatPe",initials:"BP",description:"Financial technology company providing payment and credit products for merchants.",city:"Delhi NCR",neighborhood:"Gurugram",sector:"FinTech",stage:"Series C+",size:"500+",tech:[],hiring:true,founders:["Ashneer Grover","Shashvat Nakrani"],founded:2018,color:"#00a5a8",roles:1,lat:28.4779,lng:77.0687},
  {slug:"cleartax",name:"ClearTax",initials:"CT",description:"Financial technology platform providing tax filing, invoicing, compliance and wealth products.",city:"Bengaluru",neighborhood:"HSR Layout",sector:"FinTech",stage:"Series C+",size:"500+",tech:[],hiring:true,founders:["Archit Gupta","Ankit Solanki","Srivatsan Chari"],founded:2011,color:"#1464f4",roles:1,lat:12.9143,lng:77.6411},
  {slug:"cashfree-payments",name:"Cashfree Payments",initials:"CF",description:"Payments platform offering collections, payouts, identity verification and banking infrastructure.",city:"Bengaluru",neighborhood:"Koramangala",sector:"FinTech",stage:"Series C+",size:"500+",tech:[],hiring:true,founders:["Akash Sinha","Reeju Datta"],founded:2015,color:"#6c47ff",roles:1,lat:12.9332,lng:77.6218},
  {slug:"open-money",name:"OPEN",initials:"OP",description:"Business banking platform providing accounts, payments, expense management and financial operations tools.",city:"Bengaluru",neighborhood:"Koramangala",sector:"FinTech",stage:"Series C+",size:"500+",tech:[],hiring:true,founders:["Anish Achuthan","Mabel Chacko","Deena Jacob","Ajeesh Achuthan"],founded:2017,color:"#6246ea",roles:1,lat:12.9321,lng:77.6269},
  {slug:"coindcx",name:"CoinDCX",initials:"CD",description:"Cryptocurrency platform providing digital-asset investing and trading services in India.",city:"Mumbai",neighborhood:"Bandra Kurla Complex",sector:"FinTech",stage:"Series C+",size:"500+",tech:[],hiring:true,founders:["Sumit Gupta","Neeraj Khandelwal"],founded:2018,color:"#2d5bff",roles:1,lat:19.0652,lng:72.8691},
  {slug:"coinswitch",name:"CoinSwitch",initials:"CS",description:"Financial technology platform offering cryptocurrency investing and wealth products.",city:"Bengaluru",neighborhood:"Bellandur",sector:"FinTech",stage:"Series C+",size:"500+",tech:[],hiring:true,founders:["Ashish Singhal","Govind Soni","Vimal Sagar Tiwari"],founded:2017,color:"#6d5dfc",roles:1,lat:12.9294,lng:77.6802},
  {slug:"unacademy",name:"Unacademy",initials:"UA",description:"Online learning platform providing live classes and educational content for examinations and professional goals.",city:"Bengaluru",neighborhood:"Domlur",sector:"EdTech",stage:"Series C+",size:"500+",tech:[],hiring:true,founders:["Gaurav Munjal","Roman Saini","Hemesh Singh"],founded:2015,color:"#08bd80",roles:1,lat:12.9619,lng:77.6380},
  {slug:"vedantu",name:"Vedantu",initials:"VE",description:"Online tutoring platform connecting students with teachers through live interactive classes.",city:"Bengaluru",neighborhood:"HSR Layout",sector:"EdTech",stage:"Series C+",size:"500+",tech:[],hiring:true,founders:["Vamsi Krishna","Pulkit Jain","Anand Prakash","Saurabh Saxena"],founded:2014,color:"#ff6d34",roles:1,lat:12.9102,lng:77.6431},
  {slug:"urban-company",name:"Urban Company",initials:"UC",description:"Technology marketplace connecting customers with trained professionals for home and beauty services.",city:"Delhi NCR",neighborhood:"Gurugram",sector:"Consumer",stage:"Series C+",size:"500+",tech:[],hiring:true,founders:["Abhiraj Singh Bhal","Varun Khaitan","Raghav Chandra"],founded:2014,color:"#212121",roles:1,lat:28.4487,lng:77.0754},
  {slug:"ofbusiness",name:"OfBusiness",initials:"OF",description:"B2B commerce and financing platform serving small and medium enterprises in manufacturing and infrastructure.",city:"Delhi NCR",neighborhood:"Gurugram",sector:"B2B Commerce",stage:"Series C+",size:"500+",tech:[],hiring:true,founders:["Asish Mohapatra","Ruchi Kalra","Bhuvan Gupta","Nitin Jain","Chandranshu Gupta"],founded:2015,color:"#2347a4",roles:1,lat:28.4695,lng:77.0821},
  {slug:"moglix",name:"Moglix",initials:"MO",description:"B2B commerce and supply-chain platform for industrial goods, procurement and enterprise solutions.",city:"Delhi NCR",neighborhood:"Noida",sector:"B2B Commerce",stage:"Series C+",size:"500+",tech:[],hiring:true,founders:["Rahul Garg"],founded:2015,color:"#ef3e36",roles:1,lat:28.5812,lng:77.3176},
  {slug:"pharmeasy",name:"PharmEasy",initials:"PE",description:"Digital healthcare platform providing medicine delivery, diagnostic tests and related services.",city:"Mumbai",neighborhood:"Lal Bahadur Shastri Marg",sector:"HealthTech",stage:"Series C+",size:"500+",tech:[],hiring:true,founders:["Dharmil Sheth","Dhaval Shah"],founded:2015,color:"#10847e",roles:1,lat:19.1112,lng:72.9087},
  {slug:"innovaccer",name:"Innovaccer",initials:"IN",description:"Healthcare data platform helping providers unify information and improve care delivery.",city:"Delhi NCR",neighborhood:"Noida",sector:"HealthTech",stage:"Series C+",size:"500+",tech:[],hiring:true,founders:["Abhinav Shashank","Sandeep Gupta","Kunal Lakhara"],founded:2014,color:"#5d4fff",roles:1,lat:28.5355,lng:77.3910},
  {slug:"hasura",name:"Hasura",initials:"HA",description:"Data API platform helping developers connect applications to databases and services.",city:"Bengaluru",neighborhood:"Indiranagar",sector:"Developer Tools",stage:"Series C+",size:"201–500",tech:[],hiring:true,founders:["Tanmai Gopal","Rajoshi Ghosh"],founded:2017,color:"#1eb4d4",roles:1,lat:12.9788,lng:77.6404},
  {slug:"leadsquared",name:"LeadSquared",initials:"LS",description:"Sales execution and marketing automation platform for high-velocity customer acquisition teams.",city:"Bengaluru",neighborhood:"J.P. Nagar",sector:"SaaS",stage:"Series C+",size:"500+",tech:[],hiring:true,founders:["Nilesh Patel","Prashant Singh","Sudhakar Gorti"],founded:2011,color:"#ff6b35",roles:1,lat:12.9067,lng:77.5902},
  {slug:"ensembl",name:"Ensembl AI",initials:"EA",description:"Applied AI infrastructure for reliable enterprise decision systems.",city:"Ahmedabad",neighborhood:"Prahlad Nagar",sector:"AI",stage:"Seed",size:"11–50",tech:["Python","AI/ML","TypeScript","AWS"],hiring:true,founders:["Aarav Shah"],founded:2022,color:"#ffd166",roles:4,lat:23.0120,lng:72.5108},
];

const additionalStartups = [
  {slug:"blackbuck",name:"BlackBuck",initials:"BB",description:"Digital trucking platform connecting shippers and truck operators across India.",city:"Bengaluru",neighborhood:"Bellandur",sector:"Logistics",stage:"Public",size:"500+",tech:[],hiring:true,founders:["Rajesh Yabaji","Chanakya Hridaya","Ramasubramaniam B"],founded:2015,color:"#1667d9",roles:1,lat:12.9248,lng:77.6815},
  {slug:"apna",name:"apna",initials:"AP",description:"Jobs and professional networking platform focused on India’s workforce.",city:"Bengaluru",neighborhood:"HSR Layout",sector:"HRTech",stage:"Series C+",size:"500+",tech:[],hiring:true,founders:["Nirmit Parikh"],founded:2019,color:"#5423e7",roles:1,lat:12.9134,lng:77.6468},
  {slug:"khatabook",name:"Khatabook",initials:"KB",description:"Digital bookkeeping and business tools for small merchants.",city:"Bengaluru",neighborhood:"Indiranagar",sector:"FinTech",stage:"Series C+",size:"201–500",tech:[],hiring:true,founders:["Ravish Naresh","Jaideep Poonia","Dhanesh Kumar","Naresh Kumar"],founded:2019,color:"#5b42f3",roles:1,lat:12.9758,lng:77.6417},
  {slug:"navi",name:"Navi",initials:"NV",description:"Financial services company offering loans, insurance and investment products through technology.",city:"Bengaluru",neighborhood:"Bellandur",sector:"FinTech",stage:"Series C+",size:"500+",tech:[],hiring:true,founders:["Sachin Bansal","Ankit Agarwal"],founded:2018,color:"#00b386",roles:1,lat:12.9267,lng:77.6831},
  {slug:"jupiter",name:"Jupiter",initials:"JU",description:"Digital money-management platform offering savings, payments and financial insights.",city:"Bengaluru",neighborhood:"Koramangala",sector:"FinTech",stage:"Series C+",size:"201–500",tech:[],hiring:true,founders:["Jitendra Gupta"],founded:2019,color:"#ff784f",roles:1,lat:12.9367,lng:77.6297},
  {slug:"fi",name:"Fi",initials:"FI",description:"Money-management application offering digital banking and investment experiences.",city:"Bengaluru",neighborhood:"Bellandur",sector:"FinTech",stage:"Series C+",size:"201–500",tech:[],hiring:true,founders:["Sujith Narayanan","Sumit Gwalani"],founded:2019,color:"#181818",roles:1,lat:12.9301,lng:77.6786},
  {slug:"kreditbee",name:"KreditBee",initials:"KB",description:"Digital lending platform providing personal credit and financial products.",city:"Bengaluru",neighborhood:"Marathahalli",sector:"FinTech",stage:"Series C+",size:"500+",tech:[],hiring:true,founders:["Madhusudan Ekambaram","Wan Hong"],founded:2018,color:"#f4b400",roles:1,lat:12.9562,lng:77.7014},
  {slug:"yulu",name:"Yulu",initials:"YU",description:"Shared electric mobility platform operating connected two-wheelers and battery infrastructure.",city:"Bengaluru",neighborhood:"Whitefield",sector:"Mobility",stage:"Series C+",size:"201–500",tech:[],hiring:true,founders:["Amit Gupta","RK Misra","Naveen Dachuri","Hemant Gupta"],founded:2017,color:"#19b56b",roles:1,lat:12.9698,lng:77.7499},
  {slug:"bounce",name:"Bounce",initials:"BO",description:"Electric mobility company building scooters and battery-swapping services.",city:"Bengaluru",neighborhood:"HSR Layout",sector:"Mobility",stage:"Series C+",size:"201–500",tech:[],hiring:true,founders:["Vivekananda Hallekere","Anil G","Varun Agni"],founded:2014,color:"#ffcf00",roles:1,lat:12.9094,lng:77.6487},
  {slug:"cultfit",name:"cult.fit",initials:"CF",description:"Health and fitness platform offering gyms, group workouts and wellness services.",city:"Bengaluru",neighborhood:"Bellandur",sector:"HealthTech",stage:"Series C+",size:"500+",tech:[],hiring:true,founders:["Mukesh Bansal","Ankit Nagori"],founded:2016,color:"#6c3cff",roles:1,lat:12.9229,lng:77.6842},
  {slug:"curefoods",name:"Curefoods",initials:"CU",description:"Cloud-kitchen and food-brand platform operating digital-first restaurant concepts.",city:"Bengaluru",neighborhood:"Bellandur",sector:"FoodTech",stage:"Series C+",size:"500+",tech:[],hiring:true,founders:["Ankit Nagori"],founded:2020,color:"#e84b36",roles:1,lat:12.9283,lng:77.6884},
  {slug:"rebel-foods",name:"Rebel Foods",initials:"RF",description:"Internet restaurant company operating multiple food brands and cloud kitchens.",city:"Mumbai",neighborhood:"Powai",sector:"FoodTech",stage:"Series C+",size:"500+",tech:[],hiring:true,founders:["Jaydeep Barman","Kallol Banerjee"],founded:2011,color:"#e42529",roles:1,lat:19.1175,lng:72.9060},
  {slug:"zetwerk",name:"Zetwerk",initials:"ZW",description:"Manufacturing network connecting companies with suppliers for industrial production.",city:"Bengaluru",neighborhood:"Bellandur",sector:"B2B Commerce",stage:"Series C+",size:"500+",tech:[],hiring:true,founders:["Amrit Acharya","Srinath Ramakkrushnan","Vishal Chaudhary","Rahul Sharma"],founded:2018,color:"#1868db",roles:1,lat:12.9318,lng:77.6862},
  {slug:"perfios",name:"Perfios",initials:"PF",description:"B2B financial technology platform providing data, decisioning and analytics products.",city:"Bengaluru",neighborhood:"Bellandur",sector:"FinTech",stage:"Series C+",size:"500+",tech:[],hiring:true,founders:["V R Govindarajan","Debasish Chakraborty"],founded:2008,color:"#1676d2",roles:1,lat:12.9241,lng:77.6742},
  {slug:"signzy",name:"Signzy",initials:"SZ",description:"Digital banking infrastructure company focused on onboarding, identity and compliance workflows.",city:"Bengaluru",neighborhood:"Koramangala",sector:"FinTech",stage:"Series B",size:"201–500",tech:[],hiring:true,founders:["Ankit Ratan","Arpit Ratan","Ankur Pandey"],founded:2015,color:"#4f46e5",roles:1,lat:12.9328,lng:77.6197},
  {slug:"exotel",name:"Exotel",initials:"EX",description:"Cloud communications platform providing voice, messaging and customer engagement tools.",city:"Bengaluru",neighborhood:"HSR Layout",sector:"SaaS",stage:"Series C+",size:"500+",tech:[],hiring:true,founders:["Shivakumar Ganesan","Vijay Sharma","Ishwar Sridharan"],founded:2011,color:"#5d4fff",roles:1,lat:12.9158,lng:77.6394},
  {slug:"capillary",name:"Capillary Technologies",initials:"CT",description:"Customer loyalty and engagement software company serving consumer brands.",city:"Bengaluru",neighborhood:"Whitefield",sector:"SaaS",stage:"Series C+",size:"500+",tech:[],hiring:true,founders:["Aneesh Reddy","Krishna Mehra","Sunil Suresh"],founded:2008,color:"#ef5b25",roles:1,lat:12.9821,lng:77.7267},
  {slug:"moengage",name:"MoEngage",initials:"ME",description:"Customer engagement platform helping brands personalize communications across channels.",city:"Bengaluru",neighborhood:"Koramangala",sector:"SaaS",stage:"Series C+",size:"500+",tech:[],hiring:true,founders:["Raviteja Dodda","Yashwanth Kumar"],founded:2014,color:"#315efb",roles:1,lat:12.9381,lng:77.6233},
  {slug:"webengage",name:"WebEngage",initials:"WE",description:"Customer data and marketing automation platform for consumer businesses.",city:"Mumbai",neighborhood:"Andheri East",sector:"SaaS",stage:"Series B",size:"201–500",tech:[],hiring:true,founders:["Avlesh Singh","Ankit Utreja"],founded:2011,color:"#ff6b35",roles:1,lat:19.1114,lng:72.8721},
  {slug:"gupshup",name:"Gupshup",initials:"GU",description:"Conversational engagement platform enabling businesses to communicate across messaging channels.",city:"Mumbai",neighborhood:"Bandra Kurla Complex",sector:"SaaS",stage:"Series C+",size:"500+",tech:[],hiring:true,founders:["Beerud Sheth","Rakesh Mathur"],founded:2004,color:"#5d2de1",roles:1,lat:19.0668,lng:72.8704},
  {slug:"yellow-ai",name:"Yellow.ai",initials:"YA",description:"Enterprise conversational AI platform for customer service and employee experiences.",city:"Bengaluru",neighborhood:"Koramangala",sector:"AI",stage:"Series C+",size:"500+",tech:[],hiring:true,founders:["Raghu Ravinutala","Rashid Khan"],founded:2016,color:"#f8c900",roles:1,lat:12.9309,lng:77.6224},
  {slug:"observe-ai",name:"Observe.AI",initials:"OA",description:"Contact-center AI platform for conversation intelligence and agent performance.",city:"Bengaluru",neighborhood:"HSR Layout",sector:"AI",stage:"Series C+",size:"201–500",tech:[],hiring:true,founders:["Swapnil Jain","Akash Singh","Sharath Keshava Narayana"],founded:2017,color:"#7657ff",roles:1,lat:12.9126,lng:77.6367},
  {slug:"krutrim",name:"Krutrim",initials:"KR",description:"Artificial intelligence company building language models and AI computing infrastructure.",city:"Bengaluru",neighborhood:"Koramangala",sector:"AI",stage:"Series A",size:"201–500",tech:[],hiring:true,founders:["Bhavish Aggarwal"],founded:2023,color:"#111111",roles:1,lat:12.9372,lng:77.6261},
  {slug:"sarvam-ai",name:"Sarvam AI",initials:"SA",description:"AI company building generative models and platforms for Indian languages and use cases.",city:"Bengaluru",neighborhood:"Indiranagar",sector:"AI",stage:"Series A",size:"51–200",tech:[],hiring:true,founders:["Vivek Raghavan","Pratyush Kumar"],founded:2023,color:"#ff7a30",roles:1,lat:12.9744,lng:77.6451},
  {slug:"pixxel",name:"Pixxel",initials:"PX",description:"Space technology company building hyperspectral earth-imaging satellites and data products.",city:"Bengaluru",neighborhood:"HSR Layout",sector:"SpaceTech",stage:"Series B",size:"201–500",tech:[],hiring:true,founders:["Awais Ahmed","Kshitij Khandelwal"],founded:2019,color:"#4a4dff",roles:1,lat:12.9087,lng:77.6422},
  {slug:"bellatrix",name:"Bellatrix Aerospace",initials:"BA",description:"Space company developing propulsion systems and orbital transportation technologies.",city:"Bengaluru",neighborhood:"Indian Institute of Science",sector:"SpaceTech",stage:"Series A",size:"51–200",tech:[],hiring:true,founders:["Rohan M Ganapathy","Yashas Karanam"],founded:2015,color:"#182b49",roles:1,lat:13.0219,lng:77.5671},
  {slug:"skyroot",name:"Skyroot Aerospace",initials:"SR",description:"Space launch company developing launch vehicles for small satellite missions.",city:"Hyderabad",neighborhood:"Gachibowli",sector:"SpaceTech",stage:"Series C+",size:"201–500",tech:[],hiring:true,founders:["Pawan Kumar Chandana","Naga Bharath Daka"],founded:2018,color:"#ed4c2e",roles:1,lat:17.4431,lng:78.3517},
  {slug:"agnikul",name:"Agnikul Cosmos",initials:"AC",description:"Space technology company designing customizable launch vehicles for small satellites.",city:"Chennai",neighborhood:"IIT Madras Research Park",sector:"SpaceTech",stage:"Series B",size:"201–500",tech:[],hiring:true,founders:["Srinath Ravichandran","Moin SPM"],founded:2017,color:"#e14b32",roles:1,lat:12.9915,lng:80.2420},
  {slug:"redbus",name:"redBus",initials:"RB",description:"Online bus-ticketing platform connecting travelers with bus operators.",city:"Bengaluru",neighborhood:"Domlur",sector:"TravelTech",stage:"Acquired",size:"500+",tech:[],hiring:true,founders:["Phanindra Sama","Sudhakar Pasupunuri","Charan Padmaraju"],founded:2006,color:"#d84e55",roles:1,lat:12.9595,lng:77.6401},
  {slug:"bigbasket",name:"bigbasket",initials:"BB",description:"Online grocery platform delivering food, household and daily-use products.",city:"Bengaluru",neighborhood:"Domlur",sector:"E-commerce",stage:"Acquired",size:"500+",tech:[],hiring:true,founders:["Hari Menon","Vipul Parekh","Abhinay Choudhari","V S Sudhakar","Ramesh Padmanabhan"],founded:2011,color:"#84c225",roles:1,lat:12.9632,lng:77.6354},
  {slug:"dailyhunt",name:"Dailyhunt",initials:"DH",description:"Indian-language news and content platform operated by VerSe Innovation.",city:"Bengaluru",neighborhood:"Bellandur",sector:"Consumer",stage:"Series C+",size:"500+",tech:[],hiring:true,founders:["Virendra Gupta","Umang Bedi"],founded:2007,color:"#e72b3e",roles:1,lat:12.9237,lng:77.6791},
  {slug:"pocket-aces",name:"Pocket Aces",initials:"PA",description:"Digital entertainment company producing and distributing youth-focused content.",city:"Mumbai",neighborhood:"Andheri West",sector:"Media",stage:"Acquired",size:"201–500",tech:[],hiring:true,founders:["Aditi Shrivastava","Ashwin Suresh","Anirudh Pandita"],founded:2013,color:"#f04b45",roles:1,lat:19.1364,lng:72.8296},
  {slug:"games24x7",name:"Games24x7",initials:"G24",description:"Digital gaming company operating skill-game and casual-game products.",city:"Mumbai",neighborhood:"Lower Parel",sector:"Gaming",stage:"Series C+",size:"500+",tech:[],hiring:true,founders:["Bhavin Pandya","Trivikraman Thampy"],founded:2006,color:"#ff5b35",roles:1,lat:18.9968,lng:72.8244},
  {slug:"mpl",name:"Mobile Premier League",initials:"MPL",description:"Mobile gaming and esports platform offering competitive digital games.",city:"Bengaluru",neighborhood:"Koramangala",sector:"Gaming",stage:"Series C+",size:"500+",tech:[],hiring:true,founders:["Sai Srinivas Kiran G","Shubham Malhotra"],founded:2018,color:"#e31b23",roles:1,lat:12.9341,lng:77.6315},
  {slug:"lenskart",name:"Lenskart",initials:"LK",description:"Omnichannel eyewear company offering prescription glasses, sunglasses and contact lenses.",city:"Delhi NCR",neighborhood:"Gurugram",sector:"E-commerce",stage:"Series C+",size:"500+",tech:[],hiring:true,founders:["Peyush Bansal","Amit Chaudhary","Sumeet Kapahi"],founded:2010,color:"#00bac6",roles:1,lat:28.4748,lng:77.0887},
  {slug:"firstcry",name:"FirstCry",initials:"FC",description:"Omnichannel retailer focused on baby, kids and maternity products.",city:"Pune",neighborhood:"Rajashree Business Park",sector:"E-commerce",stage:"Public",size:"500+",tech:[],hiring:true,founders:["Supam Maheshwari","Amitava Saha"],founded:2010,color:"#1c78bc",roles:1,lat:18.5793,lng:73.7377},
  {slug:"cars24",name:"CARS24",initials:"C24",description:"Technology platform for buying, selling and financing used vehicles.",city:"Delhi NCR",neighborhood:"Gurugram",sector:"AutoTech",stage:"Series C+",size:"500+",tech:[],hiring:true,founders:["Vikram Chopra","Mehul Agrawal","Gajendra Jangid","Ruchit Agarwal"],founded:2015,color:"#f8c345",roles:1,lat:28.4567,lng:77.0729},
  {slug:"cardekho",name:"CarDekho",initials:"CD",description:"Automotive marketplace providing vehicle research, listings and financial services.",city:"Jaipur",neighborhood:"Girnar Colony",sector:"AutoTech",stage:"Series C+",size:"500+",tech:[],hiring:true,founders:["Amit Jain","Anurag Jain"],founded:2008,color:"#f15a29",roles:1,lat:26.8628,lng:75.7957},
  {slug:"spinny",name:"Spinny",initials:"SP",description:"Full-stack platform for buying and selling inspected used cars.",city:"Delhi NCR",neighborhood:"Gurugram",sector:"AutoTech",stage:"Series C+",size:"500+",tech:[],hiring:true,founders:["Niraj Singh","Mohan Singh","Ramanshu Mahaur"],founded:2015,color:"#7f54b3",roles:1,lat:28.4681,lng:77.0661},
  {slug:"acko",name:"ACKO",initials:"AK",description:"Digital insurance company offering motor, health and embedded insurance products.",city:"Bengaluru",neighborhood:"HSR Layout",sector:"InsurTech",stage:"Series C+",size:"500+",tech:[],hiring:true,founders:["Varun Dua"],founded:2016,color:"#6b39ef",roles:1,lat:12.9112,lng:77.6513},
  {slug:"digit-insurance",name:"Digit Insurance",initials:"DI",description:"General insurance company offering motor, health, travel and business coverage.",city:"Bengaluru",neighborhood:"Kormangala",sector:"InsurTech",stage:"Public",size:"500+",tech:[],hiring:true,founders:["Kamesh Goyal"],founded:2016,color:"#ffcc00",roles:1,lat:12.9287,lng:77.6256},
  {slug:"insurancedekho",name:"InsuranceDekho",initials:"ID",description:"Insurance distribution platform helping consumers compare and purchase policies.",city:"Delhi NCR",neighborhood:"Gurugram",sector:"InsurTech",stage:"Series C+",size:"500+",tech:[],hiring:true,founders:["Ankit Agrawal","Ish Babbar"],founded:2016,color:"#ff5630",roles:1,lat:28.4712,lng:77.0769},
  {slug:"fam",name:"Fam",initials:"FM",description:"Financial technology platform building payment experiences for young consumers.",city:"Bengaluru",neighborhood:"HSR Layout",sector:"FinTech",stage:"Series A",size:"201–500",tech:[],hiring:true,founders:["Sambhav Jain","Kush Taneja"],founded:2019,color:"#191919",roles:1,lat:12.9169,lng:77.6438},
  {slug:"jar",name:"Jar",initials:"JR",description:"Digital savings platform helping users save and invest small amounts regularly.",city:"Bengaluru",neighborhood:"HSR Layout",sector:"FinTech",stage:"Series B",size:"201–500",tech:[],hiring:true,founders:["Nishchay AG","Misbah Ashraf"],founded:2021,color:"#f4b740",roles:1,lat:12.9099,lng:77.6375},
  {slug:"mobikwik",name:"MobiKwik",initials:"MW",description:"Digital payments and financial services platform for consumers and merchants.",city:"Delhi NCR",neighborhood:"Gurugram",sector:"FinTech",stage:"Public",size:"500+",tech:[],hiring:true,founders:["Bipin Preet Singh","Upasana Taku"],founded:2009,color:"#1178d4",roles:1,lat:28.4797,lng:77.0904},
  {slug:"easemytrip",name:"EaseMyTrip",initials:"EMT",description:"Online travel platform offering flights, hotels, holidays and transport bookings.",city:"Delhi NCR",neighborhood:"Patparganj",sector:"TravelTech",stage:"Public",size:"500+",tech:[],hiring:true,founders:["Nishant Pitti","Rikant Pittie","Prashant Pitti"],founded:2008,color:"#2196d2",roles:1,lat:28.6288,lng:77.2925},
  {slug:"ixigo",name:"ixigo",initials:"IX",description:"Online travel platform for train, flight, bus and hotel planning and booking.",city:"Delhi NCR",neighborhood:"Gurugram",sector:"TravelTech",stage:"Public",size:"500+",tech:[],hiring:true,founders:["Aloke Bajpai","Rajnish Kumar"],founded:2007,color:"#ee2e6c",roles:1,lat:28.4727,lng:77.0918},
  {slug:"yatra",name:"Yatra",initials:"YT",description:"Online travel company offering bookings for flights, hotels, trains and holidays.",city:"Delhi NCR",neighborhood:"Gurugram",sector:"TravelTech",stage:"Public",size:"500+",tech:[],hiring:true,founders:["Dhruv Shringi","Manish Amin","Sabina Chopra"],founded:2006,color:"#e42b2b",roles:1,lat:28.4624,lng:77.0856},
  {slug:"boat",name:"boAt",initials:"BT",description:"Consumer electronics brand offering audio products, wearables and accessories.",city:"Delhi NCR",neighborhood:"Gurugram",sector:"Consumer",stage:"Series C+",size:"500+",tech:[],hiring:true,founders:["Aman Gupta","Sameer Mehta"],founded:2016,color:"#e32128",roles:1,lat:28.4662,lng:77.0587},
  {slug:"mamaearth",name:"Mamaearth",initials:"ME",description:"Personal care brand operated by Honasa Consumer across beauty and wellness categories.",city:"Delhi NCR",neighborhood:"Gurugram",sector:"Consumer",stage:"Public",size:"500+",tech:[],hiring:true,founders:["Varun Alagh","Ghazal Alagh"],founded:2016,color:"#69a842",roles:1,lat:28.4561,lng:77.0865},
  {slug:"appsmith",name:"Appsmith",initials:"AS",description:"Open-source low-code platform for building internal applications and business software.",city:"Bengaluru",neighborhood:"Bengaluru",sector:"Developer Tools",stage:"Series B",size:"201–500",tech:["JavaScript","TypeScript","React"],hiring:false,founders:["Abhishek Nayak","Arpit Mohan","Nikhil Nandagopal"],founded:2019,color:"#ff6d2e",roles:0,lat:12.9716,lng:77.5946},
  {slug:"freshtohome",name:"FreshToHome",initials:"FH",description:"Online fresh fish and meat commerce company serving households in India and the Middle East.",city:"Bengaluru",neighborhood:"Bengaluru",sector:"E-commerce",stage:"Series C+",size:"500+",tech:[],hiring:false,founders:["Shan Kadavil","Mathew Joseph"],founded:2015,color:"#00a651",roles:0,lat:12.9688,lng:77.6001},
  {slug:"blue-tokai",name:"Blue Tokai Coffee Roasters",initials:"BT",description:"Specialty coffee company operating cafés, roasteries and direct-to-consumer commerce.",city:"Delhi NCR",neighborhood:"Gurugram",sector:"Consumer",stage:"Series C+",size:"500+",tech:[],hiring:false,founders:["Matt Chitharanjan","Namrata Asthana","Shivam Shahi"],founded:2013,color:"#176b87",roles:0,lat:28.4618,lng:77.0314},
  {slug:"the-whole-truth",name:"The Whole Truth",initials:"TWT",description:"Clean-label packaged food brand producing protein bars, snacks and nutrition products.",city:"Mumbai",neighborhood:"Mumbai",sector:"Consumer",stage:"Series B",size:"201–500",tech:[],hiring:false,founders:["Shashank Mehta"],founded:2019,color:"#f2c94c",roles:0,lat:19.0791,lng:72.8832},
  {slug:"epigamia",name:"Epigamia",initials:"EP",description:"Consumer food brand offering yogurt, dairy snacks and related packaged products.",city:"Mumbai",neighborhood:"Mumbai",sector:"Consumer",stage:"Series C+",size:"201–500",tech:[],hiring:false,founders:["Rohan Mirchandani","Uday Thakker","Rahul Jain"],founded:2015,color:"#7a2f8f",roles:0,lat:19.0727,lng:72.8721},
  {slug:"slurrp-farm",name:"Slurrp Farm",initials:"SF",description:"Children’s food brand producing millet-based breakfast, snack and meal products.",city:"Delhi NCR",neighborhood:"Gurugram",sector:"Consumer",stage:"Series B",size:"51–200",tech:[],hiring:false,founders:["Meghana Narayan","Shauravi Malik"],founded:2016,color:"#f47a38",roles:0,lat:28.4551,lng:77.0382},
];

const cityCenters: Record<string,{lat:number;lng:number;neighborhood:string}> = {
  Bengaluru:{lat:12.9716,lng:77.5946,neighborhood:"Bengaluru"}, Chennai:{lat:13.0827,lng:80.2707,neighborhood:"Chennai"}, Hyderabad:{lat:17.3850,lng:78.4867,neighborhood:"Hyderabad"}, Mumbai:{lat:19.0760,lng:72.8777,neighborhood:"Mumbai"}, Pune:{lat:18.5204,lng:73.8567,neighborhood:"Pune"}, "Delhi NCR":{lat:28.4595,lng:77.0266,neighborhood:"Delhi NCR"}, Jaipur:{lat:26.9124,lng:75.7873,neighborhood:"Jaipur"}, Ahmedabad:{lat:23.0225,lng:72.5714,neighborhood:"Ahmedabad"}, Kochi:{lat:9.9312,lng:76.2673,neighborhood:"Kochi"}, Chandigarh:{lat:30.7333,lng:76.7794,neighborhood:"Chandigarh"},
};

const bulkCompanyDirectory = [
  ["druva","Druva","druva.com","Pune","SaaS"],["icertis","Icertis","icertis.com","Pune","SaaS"],["mindtickle","Mindtickle","mindtickle.com","Pune","SaaS"],["highradius","HighRadius","highradius.com","Hyderabad","SaaS"],["kissflow","Kissflow","kissflow.com","Chennai","SaaS"],
  ["wingify","Wingify","wingify.com","Delhi NCR","SaaS"],["lambdatest","LambdaTest","lambdatest.com","Delhi NCR","Developer Tools"],["testsigma","Testsigma","testsigma.com","Bengaluru","Developer Tools"],["hackerrank","HackerRank","hackerrank.com","Bengaluru","Developer Tools"],["hackerearth","HackerEarth","hackerearth.com","Bengaluru","Developer Tools"],
  ["atlan","Atlan","atlan.com","Delhi NCR","SaaS"],["hevo-data","Hevo Data","hevodata.com","Bengaluru","SaaS"],["fyle","Fyle","fylehq.com","Bengaluru","FinTech"],["vymo","Vymo","vymo.com","Bengaluru","SaaS"],["clevertap","CleverTap","clevertap.com","Mumbai","SaaS"],
  ["netcore-cloud","Netcore Cloud","netcorecloud.com","Mumbai","SaaS"],["amagi","Amagi","amagi.com","Bengaluru","MediaTech"],["facilio","Facilio","facilio.com","Chennai","SaaS"],["keka","Keka","keka.com","Hyderabad","HRTech"],["greythr","greytHR","greythr.com","Bengaluru","HRTech"],
  ["billdesk","BillDesk","billdesk.com","Mumbai","FinTech"],["ccavenue","CCAvenue","ccavenue.com","Mumbai","FinTech"],["payu-india","PayU India","payu.in","Delhi NCR","FinTech"],["instamojo","Instamojo","instamojo.com","Bengaluru","FinTech"],["lendingkart","Lendingkart","lendingkart.com","Ahmedabad","FinTech"],
  ["axio","axio","axio.co.in","Bengaluru","FinTech"],["moneytap","MoneyTap","moneytap.com","Bengaluru","FinTech"],["indmoney","INDmoney","indmoney.com","Delhi NCR","FinTech"],["scripbox","Scripbox","scripbox.com","Bengaluru","FinTech"],["kuvera","Kuvera","kuvera.in","Bengaluru","FinTech"],
  ["et-money","ET Money","etmoney.com","Delhi NCR","FinTech"],["5paisa","5paisa","5paisa.com","Mumbai","FinTech"],["angel-one","Angel One","angelone.in","Mumbai","FinTech"],["bankbazaar","BankBazaar","bankbazaar.com","Chennai","FinTech"],["paisabazaar","Paisabazaar","paisabazaar.com","Delhi NCR","FinTech"],
  ["turtlemint","Turtlemint","turtlemint.com","Mumbai","InsurTech"],["renewbuy","RenewBuy","renewbuy.com","Delhi NCR","InsurTech"],["plum-insurance","Plum","plumhq.com","Bengaluru","InsurTech"],["onsurity","Onsurity","onsurity.com","Bengaluru","InsurTech"],["snapdeal","Snapdeal","snapdeal.com","Delhi NCR","E-commerce"],
  ["shopclues","ShopClues","shopclues.com","Delhi NCR","E-commerce"],["pepperfry","Pepperfry","pepperfry.com","Mumbai","E-commerce"],["wakefit","Wakefit","wakefit.co","Bengaluru","Consumer"],["woodenstreet","WoodenStreet","woodenstreet.com","Jaipur","E-commerce"],["livspace","Livspace","livspace.com","Bengaluru","PropTech"],
  ["homelane","HomeLane","homelane.com","Bengaluru","PropTech"],["bluestone","BlueStone","bluestone.com","Bengaluru","E-commerce"],["caratlane","CaratLane","caratlane.com","Chennai","E-commerce"],["sugar-cosmetics","SUGAR Cosmetics","sugarcosmetics.com","Mumbai","Consumer"],["plum-goodness","Plum Goodness","plumgoodness.com","Mumbai","Consumer"],
  ["minimalist","Minimalist","beminimalist.co","Jaipur","Consumer"],["wow-skin-science","WOW Skin Science","buywow.in","Bengaluru","Consumer"],["country-delight","Country Delight","countrydelight.in","Delhi NCR","Consumer"],["milkbasket","Milkbasket","milkbasket.com","Delhi NCR","E-commerce"],["zepto","Zepto","zeptonow.com","Mumbai","E-commerce"],
  ["blinkit","Blinkit","blinkit.com","Delhi NCR","E-commerce"],["dealshare","DealShare","dealshare.in","Jaipur","E-commerce"],["citymall","CityMall","citymall.live","Delhi NCR","E-commerce"],["elasticrun","ElasticRun","elastic.run","Pune","B2B Commerce"],["infra-market","Infra.Market","infra.market","Mumbai","B2B Commerce"],
  ["tata-1mg","Tata 1mg","1mg.com","Delhi NCR","HealthTech"],["medibuddy","MediBuddy","medibuddy.in","Bengaluru","HealthTech"],["mfine","MFine","mfine.co","Bengaluru","HealthTech"],["healthifyme","HealthifyMe","healthifyme.com","Bengaluru","HealthTech"],["portea","Portea","portea.com","Bengaluru","HealthTech"],
  ["pristyn-care","Pristyn Care","pristyncare.com","Delhi NCR","HealthTech"],["healthkart","HealthKart","healthkart.com","Delhi NCR","HealthTech"],["truemeds","Truemeds","truemeds.in","Mumbai","HealthTech"],["orange-health","Orange Health Labs","orangehealth.in","Bengaluru","HealthTech"],["redcliffe-labs","Redcliffe Labs","redcliffelabs.com","Delhi NCR","HealthTech"],
  ["physics-wallah","Physics Wallah","pw.live","Delhi NCR","EdTech"],["upgrad","upGrad","upgrad.com","Mumbai","EdTech"],["emeritus","Emeritus","emeritus.org","Mumbai","EdTech"],["classplus","Classplus","classplusapp.com","Delhi NCR","EdTech"],["teachmint","Teachmint","teachmint.com","Bengaluru","EdTech"],
  ["lead-group","LEAD Group","leadschool.in","Mumbai","EdTech"],["collegedekho","CollegeDekho","collegedekho.com","Delhi NCR","EdTech"],["careers360","Careers360","careers360.com","Delhi NCR","EdTech"],["testbook","Testbook","testbook.com","Mumbai","EdTech"],["adda247","Adda247","adda247.com","Delhi NCR","EdTech"],
  ["ecom-express","Ecom Express","ecomexpress.in","Delhi NCR","Logistics"],["xpressbees","Xpressbees","xpressbees.com","Pune","Logistics"],["shadowfax","Shadowfax","shadowfax.in","Bengaluru","Logistics"],["shiprocket","Shiprocket","shiprocket.in","Delhi NCR","Logistics"],["shipsy","Shipsy","shipsy.io","Delhi NCR","Logistics"],
  ["fareye","FarEye","fareye.com","Delhi NCR","Logistics"],["locus","Locus","locus.sh","Bengaluru","Logistics"],["loadshare","LoadShare","loadshare.net","Bengaluru","Logistics"],["rivigo","Rivigo","rivigo.com","Delhi NCR","Logistics"],["shipyaari","Shipyaari","shipyaari.com","Mumbai","Logistics"],
  ["blusmart","BluSmart","blu-smart.com","Delhi NCR","Mobility"],["driveu","DriveU","driveu.in","Bengaluru","Mobility"],["battery-smart","Battery Smart","batterysmart.in","Delhi NCR","ClimateTech"],["sun-mobility","SUN Mobility","sunmobility.com","Bengaluru","ClimateTech"],["euler-motors","Euler Motors","eulermotors.com","Delhi NCR","ClimateTech"],
  ["altigreen","Altigreen","altigreen.com","Bengaluru","ClimateTech"],["river-mobility","River","rivermobility.com","Bengaluru","Mobility"],["ultraviolette","Ultraviolette","ultraviolette.com","Bengaluru","Mobility"],["simple-energy","Simple Energy","simpleenergy.in","Bengaluru","Mobility"],["dehaat","DeHaat","agrevolution.in","Delhi NCR","AgriTech"],
] as const;

const bulkStartups = bulkCompanyDirectory.map(([slug,name,,city,sector],index)=>({
  slug,name,initials:name.replace(/[^A-Za-z0-9 ]/g,"").split(/\s+/).map(x=>x[0]).join("").slice(0,3).toUpperCase(),
  description:`${name} operates in India’s ${sector} ecosystem. Core identity, domain and primary city are sourced from the company’s official website.`,
  city,neighborhood:cityCenters[city].neighborhood,sector,stage:"Private",size:"Not disclosed",tech:[],hiring:false,founders:[],founded:null,color:["#1769ff","#6c47ff","#00a884","#ef5b35","#f4b400"][index%5],roles:0,
  lat:cityCenters[city].lat+((index%9)-4)*0.002,lng:cityCenters[city].lng+((index%11)-5)*0.002,locationPrecision:"CITY" as const,
}));

const directoryStartups = directoryCompanies.map((company,index)=>({
  slug:company.slug,name:company.name,
  initials:company.name.replace(/[^A-Za-z0-9 ]/g,"").split(/\s+/).map(x=>x[0]).join("").slice(0,3).toUpperCase(),
  description:`${company.name} is an India-associated ${company.sector} organization listed in Wikidata with an official website. Details beyond the directory source require further verification.`,
  city:company.city,neighborhood:company.city,sector:company.sector,stage:"Directory sourced",size:"Not disclosed",tech:[],hiring:false,founders:[],founded:company.founded,
  color:["#1769ff","#6c47ff","#00a884","#ef5b35","#f4b400"][index%5],roles:0,lat:company.lat,lng:company.lng,locationPrecision:"CITY" as const,verificationStatus:"DIRECTORY_SOURCE" as const,
}));

const directoryStartups2 = directoryCompanies2.map((company,index)=>({
  slug:company.slug,name:company.name,
  initials:company.name.replace(/[^A-Za-z0-9 ]/g,"").split(/\s+/).map(x=>x[0]).join("").slice(0,3).toUpperCase(),
  description:`${company.name} is an India-associated ${company.sector} organization listed in Wikidata with an official website. Details beyond the directory source require further verification.`,
  city:company.city,neighborhood:company.city,sector:company.sector,stage:"Directory sourced",size:"Not disclosed",tech:[],hiring:false,founders:[],founded:company.founded,
  color:["#2148c0","#8b5cf6","#079669","#e0522d","#d49b00"][index%5],roles:0,lat:company.lat,lng:company.lng,locationPrecision:"CITY" as const,verificationStatus:"DIRECTORY_SOURCE" as const,
}));

const directoryStartups3 = directoryCompanies3.map((company,index)=>({
  slug:company.slug,name:company.name,
  initials:company.name.replace(/[^A-Za-z0-9 ]/g,"").split(/\s+/).map(x=>x[0]).join("").slice(0,3).toUpperCase(),
  description:`${company.name} is an India-associated ${company.sector} organization listed in Wikidata with an official website. Details beyond the directory source require further verification.`,
  city:company.city,neighborhood:company.city,sector:company.sector,stage:"Directory sourced",size:"Not disclosed",tech:[],hiring:false,founders:[],founded:company.founded,
  color:["#174ea6","#7c3aed","#05845b","#c74625","#b88600"][index%5],roles:0,lat:company.lat,lng:company.lng,locationPrecision:"CITY" as const,verificationStatus:"DIRECTORY_SOURCE" as const,
}));

const directoryStartups4 = directoryCompanies4.map((company,index)=>({
  slug:company.slug,name:company.name,
  initials:company.name.replace(/[^A-Za-z0-9 ]/g,"").split(/\s+/).map(x=>x[0]).join("").slice(0,3).toUpperCase(),
  description:`${company.name} is an India-associated ${company.sector} organization listed in Wikidata with an official website. Details beyond the directory source require further verification.`,
  city:company.city,neighborhood:company.city,sector:company.sector,stage:"Directory sourced",size:"Not disclosed",tech:[],hiring:false,founders:[],founded:company.founded,
  color:["#174ea6","#7c3aed","#05845b","#c74625","#b88600"][index%5],roles:0,lat:company.lat,lng:company.lng,locationPrecision:"CITY" as const,verificationStatus:"DIRECTORY_SOURCE" as const,
}));

const directoryStartups5 = directoryCompanies5.map((company,index)=>({
  slug:company.slug,name:company.name,
  initials:company.name.replace(/[^A-Za-z0-9 ]/g,"").split(/\s+/).map(x=>x[0]).join("").slice(0,3).toUpperCase(),
  description:`${company.name} is an India-headquartered organization with an official website and headquarters location listed in Wikidata. Additional profile details require further verification.`,
  city:company.city,neighborhood:company.city,sector:company.sector,stage:"Directory sourced",size:"Not disclosed",tech:[],hiring:false,founders:[],founded:company.founded,
  color:["#174ea6","#7c3aed","#05845b","#c74625","#b88600"][index%5],roles:0,lat:company.lat,lng:company.lng,locationPrecision:"CITY" as const,verificationStatus:"DIRECTORY_SOURCE" as const,
}));

const directoryStartups6 = directoryCompanies6.map((company,index)=>({
  slug:company.slug,name:company.name,
  initials:company.name.replace(/[^A-Za-z0-9 ]/g,"").split(/\s+/).map(x=>x[0]).join("").slice(0,3).toUpperCase(),
  description:`${company.name} is an India-headquartered ${company.industry} company with an official website and headquarters location listed in Wikidata.`,
  city:company.city,neighborhood:company.city,sector:company.sector,stage:"Directory sourced",size:"Not disclosed",tech:[],hiring:false,founders:[],founded:company.founded,
  color:["#2457ff","#7c3aed","#00a896","#ff6b35","#ef476f"][index%5],roles:0,lat:company.lat,lng:company.lng,locationPrecision:"CITY" as const,verificationStatus:"DIRECTORY_SOURCE" as const,
}));

const directoryStartups7 = directoryCompanies7.map((company,index)=>({
  slug:company.slug,name:company.name,
  initials:company.name.replace(/[^A-Za-z0-9 ]/g,"").split(/\s+/).map(x=>x[0]).join("").slice(0,3).toUpperCase(),
  description:`${company.name} is an organization headquartered in ${company.city} with an official website and headquarters record listed in Wikidata.`,
  city:company.city,neighborhood:company.city,sector:company.sector,stage:"Directory sourced",size:"Not disclosed",tech:[],hiring:false,founders:[],founded:company.founded,
  color:["#ff6b35","#7c5cff","#00a896","#ffd166","#ef476f"][index%5],roles:0,lat:company.lat,lng:company.lng,locationPrecision:"CITY" as const,verificationStatus:"DIRECTORY_SOURCE" as const,
}));

const bangaloreMapStartups = bangaloreMapCompanies.map((company,index)=>({
  slug:company.slug,name:company.name,
  initials:company.name.replace(/[^A-Za-z0-9 ]/g,"").split(/\s+/).map(x=>x[0]).join("").slice(0,3).toUpperCase(),
  description:company.description,
  city:"Bengaluru",neighborhood:company.area,sector:company.sector,stage:company.stage,size:company.size,
  tech:[],hiring:Boolean(company.careers&&!company.careers.includes("linkedin.com/jobs/search")),founders:[...company.founders],founded:company.founded,
  color:["#ff6b35","#7c5cff","#00a896","#ffd166","#ef476f"][index%5],roles:0,lat:company.lat,lng:company.lng,
  locationPrecision:"OFFICE" as const,locationSource:company.source,verificationStatus:"BANGALORE_MAP_SOURCE" as const,
}));

const remoteDirectoryStartups = remoteCompanies.map((company,index)=>({
  slug:company.slug,name:company.name,
  initials:company.name.replace(/[^A-Za-z0-9 ]/g,"").split(/\s+/).map(x=>x[0]).join("").slice(0,3).toUpperCase(),
  description:`${company.name} is a remote-friendly technology company listed by the community-maintained Remote In Tech directory. Headquarters location is not asserted by this record.`,
  city:"India",neighborhood:"Location unverified",sector:"Remote Technology",stage:"Remote directory",size:"Not disclosed",tech:[],hiring:false,founders:[],founded:null,
  color:["#174ea6","#7c3aed","#05845b","#c74625","#b88600"][index%5],roles:0,lat:20.5937,lng:78.9629,locationPrecision:"UNKNOWN" as const,verificationStatus:"COMMUNITY_SOURCE" as const,
}));

const targetTechStartups = targetTechCompanies.map((company,index)=>({
  slug:company.slug,name:company.name,
  initials:company.name.replace(/[^A-Za-z0-9 ]/g,"").split(/\s+/).map(x=>x[0]).join("").slice(0,3).toUpperCase(),
  description:company.slug==="netradyne"
    ? "Netradyne builds AI-powered fleet safety and performance technology using edge AI, computer vision, and deep learning. Its official contact page lists a Bengaluru office."
    : `${company.name} is a technology employer tracked by the SDE target-company directory. An Indian city is not asserted until a reliable office-level source is attached.`,
  city:company.city,neighborhood:company.city==="India"?"Location unverified":company.city,sector:company.sector,stage:"Target employer",size:"Not disclosed",tech:[],hiring:false,founders:[],founded:null,
  color:["#2457ff","#7c3aed","#00a896","#ff6b35","#ef476f"][index%5],roles:0,
  lat:"lat" in company?company.lat:20.5937,lng:"lng" in company?company.lng:78.9629,
  locationPrecision:(company.city==="India"?"UNKNOWN":"OFFICE") as "UNKNOWN"|"OFFICE",
  locationSource:company.source,
  verificationStatus:"TARGET_LIST" as const,
}));

export const citySlugs: Record<string,string> = {bangalore:"Bengaluru",bengaluru:"Bengaluru",hyderabad:"Hyderabad",pune:"Pune",mumbai:"Mumbai",delhi:"Delhi NCR",chennai:"Chennai",ahmedabad:"Ahmedabad"};
export const cityToSlug = (city: string) => city
  .toLowerCase()
  .normalize("NFKD")
  .replace(/[^a-z0-9]+/g, "-")
  .replace(/^-+|-+$/g, "");

export const startupLinks: Record<string, { website: string; careers: string }> = {
  ...Object.fromEntries(bangaloreMapCompanies.map(company=>[company.slug,{website:company.website,careers:company.careers}])),
  ...Object.fromEntries(targetTechCompanies.map(company=>[company.slug,{website:company.website,careers:company.careers}])),
  ...Object.fromEntries(remoteCompanies.map(company=>[company.slug,{website:company.website,careers:company.careers}])),
  ...Object.fromEntries(directoryCompanies7.map(company=>[company.slug,{website:company.website,careers:`https://www.linkedin.com/jobs/search/?keywords=${encodeURIComponent(company.name)}`}])) ,
  ...Object.fromEntries(directoryCompanies6.map(company=>[company.slug,{website:company.website,careers:`https://www.linkedin.com/jobs/search/?keywords=${encodeURIComponent(company.name)}`}])) ,
  ...Object.fromEntries(directoryCompanies5.map(company=>[company.slug,{website:company.website,careers:`https://www.linkedin.com/jobs/search/?keywords=${encodeURIComponent(company.name)}`}])) ,
  ...Object.fromEntries(directoryCompanies4.map(company=>[company.slug,{website:company.website,careers:`https://www.linkedin.com/jobs/search/?keywords=${encodeURIComponent(company.name)}`}])),
  ...Object.fromEntries(directoryCompanies3.map(company=>[company.slug,{website:company.website,careers:`https://www.linkedin.com/jobs/search/?keywords=${encodeURIComponent(company.name)}`}])),
  ...Object.fromEntries(directoryCompanies2.map(company=>[company.slug,{website:company.website,careers:`https://www.linkedin.com/jobs/search/?keywords=${encodeURIComponent(company.name)}`}])),
  ...Object.fromEntries(directoryCompanies.map(company=>[company.slug,{website:company.website,careers:`https://www.linkedin.com/jobs/search/?keywords=${encodeURIComponent(company.name)}`}])),
  ...Object.fromEntries(bulkCompanyDirectory.map(([slug,name,domain])=>[slug,{website:`https://${domain}/`,careers:`https://www.linkedin.com/jobs/search/?keywords=${encodeURIComponent(name)}`}])),
  razorpay: { website: "https://razorpay.com/", careers: "https://razorpay.com/careers/" },
  postman: { website: "https://www.postman.com/", careers: "https://www.postman.com/company/careers/" },
  meesho: { website: "https://www.meesho.com/", careers: "https://www.meesho.io/jobs" },
  cred: { website: "https://cred.club/", careers: "https://careers.cred.club/" },
  swiggy: { website: "https://www.swiggy.com/", careers: "https://careers.swiggy.com/" },
  whatfix: { website: "https://whatfix.com/", careers: "https://whatfix.com/careers" },
  slice: { website: "https://slice.bank.in/", careers: "https://slice.bank.in/careers" },
  smallcase: { website: "https://www.smallcase.com/", careers: "https://app.pyjamahr.com/careers?company=smallcase&company_uuid=2615584222" },
  nference: { website: "https://nference.com/", careers: "https://nference.com/careers" },
  scaler: { website: "https://www.scaler.com/", careers: "https://www.scaler.com/careers" },
  darwinbox: { website: "https://darwinbox.com/", careers: "https://darwinbox.com/careers" },
  browserstack: { website: "https://www.browserstack.com/", careers: "https://www.browserstack.com/careers" },
  agrostar: { website: "https://corporate.agrostar.in/", careers: "https://www.linkedin.com/company/agrostar-in/jobs/" },
  chargebee: { website: "https://www.chargebee.com/", careers: "https://www.chargebee.com/careers" },
  devtron: { website: "https://devtron.ai/", careers: "https://www.linkedin.com/company/devtron-labs/jobs/" },
  zerodha: { website: "https://zerodha.com/", careers: "https://zerodha.com/careers/" },
  phonepe: { website: "https://www.phonepe.com/", careers: "https://www.phonepe.com/careers/" },
  groww: { website: "https://groww.in/", careers: "https://groww.in/careers" },
  "ather-energy": { website: "https://www.atherenergy.com/", careers: "https://www.atherenergy.com/careers" },
  juspay: { website: "https://juspay.io/", careers: "https://juspay.io/careers" },
  rapido: { website: "https://rapido.bike/", careers: "https://rapido.bike/Careers" },
  porter: { website: "https://porter.in/", careers: "https://porter.in/careers" },
  inmobi: { website: "https://www.inmobi.com/", careers: "https://www.inmobi.com/company/careers" },
  nobroker: { website: "https://www.nobroker.in/", careers: "https://www.nobroker.in/careers" },
  practo: { website: "https://www.practo.com/", careers: "https://www.practo.com/company/careers" },
  udaan: { website: "https://udaan.com/", careers: "https://udaan.com/careers" },
  licious: { website: "https://www.licious.in/", careers: "https://www.licious.in/careers" },
  sharechat: { website: "https://sharechat.com/", careers: "https://sharechat.com/careers" },
  simplilearn: { website: "https://www.simplilearn.com/", careers: "https://www.simplilearn.com/careers" },
  ninjacart: { website: "https://ninjacart.com/", careers: "https://ninjacart.com/careers" },
  flipkart: { website: "https://www.flipkart.com/", careers: "https://www.flipkartcareers.com/" },
  myntra: { website: "https://www.myntra.com/", careers: "https://careers.myntra.com/" },
  ola: { website: "https://www.olacabs.com/", careers: "https://www.linkedin.com/company/olacabs/jobs/" },
  "ola-electric": { website: "https://www.olaelectric.com/", careers: "https://www.olaelectric.com/careers" },
  delhivery: { website: "https://www.delhivery.com/", careers: "https://www.delhivery.com/careers" },
  freshworks: { website: "https://www.freshworks.com/", careers: "https://www.freshworks.com/company/careers/" },
  zoho: { website: "https://www.zoho.com/", careers: "https://www.zoho.com/careers/" },
  zomato: { website: "https://www.zomato.com/", careers: "https://www.linkedin.com/company/zomato/jobs/" },
  paytm: { website: "https://paytm.com/", careers: "https://paytm.com/careers/" },
  policybazaar: { website: "https://www.policybazaar.com/", careers: "https://www.linkedin.com/company/policybazaar/jobs/" },
  makemytrip: { website: "https://www.makemytrip.com/", careers: "https://careers.makemytrip.com/" },
  dream11: { website: "https://www.dream11.com/", careers: "https://www.linkedin.com/company/dream11/jobs/" },
  nykaa: { website: "https://www.nykaa.com/", careers: "https://careers.nykaa.com/" },
  upstox: { website: "https://upstox.com/", careers: "https://upstox.com/careers/" },
  "pine-labs": { website: "https://www.pinelabs.com/", careers: "https://www.pinelabs.com/careers" },
  bharatpe: { website: "https://bharatpe.com/", careers: "https://bharatpe.com/career/" },
  cleartax: { website: "https://cleartax.in/", careers: "https://cleartax.in/s/careers" },
  "cashfree-payments": { website: "https://www.cashfree.com/", careers: "https://www.cashfree.com/careers/" },
  "open-money": { website: "https://open.money/", careers: "https://open.money/careers/" },
  coindcx: { website: "https://coindcx.com/", careers: "https://www.linkedin.com/company/coindcx/jobs/" },
  coinswitch: { website: "https://coinswitch.co/", careers: "https://www.linkedin.com/company/coinswitch/jobs/" },
  unacademy: { website: "https://unacademy.com/", careers: "https://unacademy.com/careers" },
  vedantu: { website: "https://www.vedantu.com/", careers: "https://www.vedantu.com/careers" },
  "urban-company": { website: "https://www.urbancompany.com/", careers: "https://www.linkedin.com/company/urban-company/jobs/" },
  ofbusiness: { website: "https://www.ofbusiness.com/", careers: "https://www.linkedin.com/company/ofbusiness/jobs/" },
  moglix: { website: "https://www.moglix.com/", careers: "https://www.linkedin.com/company/moglix/jobs/" },
  pharmeasy: { website: "https://pharmeasy.in/", careers: "https://careers.pharmeasy.in/" },
  innovaccer: { website: "https://innovaccer.com/", careers: "https://innovaccer.com/careers" },
  hasura: { website: "https://hasura.io/", careers: "https://hasura.io/careers/" },
  leadsquared: { website: "https://www.leadsquared.com/", careers: "https://leadsquared.com/careers/" },
  blackbuck:{website:"https://www.blackbuck.com/",careers:"https://www.linkedin.com/company/blackbuck/jobs/"},
  apna:{website:"https://apna.co/",careers:"https://apna.co/careers"},
  khatabook:{website:"https://khatabook.com/",careers:"https://www.linkedin.com/company/khatabook/jobs/"},
  navi:{website:"https://navi.com/",careers:"https://navi.com/careers"},
  jupiter:{website:"https://jupiter.money/",careers:"https://jupiter.money/careers/"},
  fi:{website:"https://fi.money/",careers:"https://fi.money/careers"},
  kreditbee:{website:"https://www.kreditbee.in/",careers:"https://www.kreditbee.in/careers"},
  yulu:{website:"https://www.yulu.bike/",careers:"https://www.linkedin.com/company/yulu/jobs/"},
  bounce:{website:"https://bounceinfinity.com/",careers:"https://www.linkedin.com/company/bounce-share/jobs/"},
  cultfit:{website:"https://www.cult.fit/",careers:"https://www.linkedin.com/company/cult-fit/jobs/"},
  curefoods:{website:"https://curefoods.in/",careers:"https://www.linkedin.com/company/curefoods/jobs/"},
  "rebel-foods":{website:"https://www.rebelfoods.com/",careers:"https://www.rebelfoods.com/careers"},
  zetwerk:{website:"https://www.zetwerk.com/",careers:"https://www.zetwerk.com/careers/"},
  perfios:{website:"https://www.perfios.ai/",careers:"https://www.perfios.ai/careers"},
  signzy:{website:"https://www.signzy.com/",careers:"https://www.signzy.com/careers"},
  exotel:{website:"https://exotel.com/",careers:"https://exotel.com/careers/"},
  capillary:{website:"https://www.capillarytech.com/",careers:"https://www.capillarytech.com/careers/"},
  moengage:{website:"https://www.moengage.com/",careers:"https://www.moengage.com/careers/"},
  webengage:{website:"https://webengage.com/",careers:"https://webengage.com/careers/"},
  gupshup:{website:"https://www.gupshup.io/",careers:"https://www.gupshup.io/careers"},
  "yellow-ai":{website:"https://yellow.ai/",careers:"https://yellow.ai/careers/"},
  "observe-ai":{website:"https://www.observe.ai/",careers:"https://www.observe.ai/careers"},
  krutrim:{website:"https://www.olakrutrim.com/",careers:"https://www.linkedin.com/company/olakrutrim/jobs/"},
  "sarvam-ai":{website:"https://www.sarvam.ai/",careers:"https://www.sarvam.ai/careers"},
  pixxel:{website:"https://www.pixxel.space/",careers:"https://www.pixxel.space/careers"},
  bellatrix:{website:"https://bellatrixaerospace.com/",careers:"https://www.linkedin.com/company/bellatrix-aerospace/jobs/"},
  skyroot:{website:"https://www.skyroot.in/",careers:"https://www.skyroot.in/careers"},
  agnikul:{website:"https://agnikul.in/",careers:"https://agnikul.in/careers"},
  redbus:{website:"https://www.redbus.in/",careers:"https://www.linkedin.com/company/redbus/jobs/"},
  bigbasket:{website:"https://www.bigbasket.com/",careers:"https://www.bigbasket.com/careers/"},
  dailyhunt:{website:"https://www.dailyhunt.com/",careers:"https://www.linkedin.com/company/dailyhunt/jobs/"},
  "pocket-aces":{website:"https://pocketaces.in/",careers:"https://www.linkedin.com/company/pocket-aces/jobs/"},
  games24x7:{website:"https://www.games24x7.com/",careers:"https://www.games24x7.com/careers"},
  mpl:{website:"https://www.mpl.live/",careers:"https://www.linkedin.com/company/mobile-premier-league/jobs/"},
  lenskart:{website:"https://www.lenskart.com/",careers:"https://hiring.lenskart.com/"},
  firstcry:{website:"https://www.firstcry.com/",careers:"https://www.firstcry.com/careers"},
  cars24:{website:"https://www.cars24.com/",careers:"https://www.cars24.com/careers/"},
  cardekho:{website:"https://www.cardekho.com/",careers:"https://careers.cardekho.com/"},
  spinny:{website:"https://www.spinny.com/",careers:"https://www.spinny.com/careers/"},
  acko:{website:"https://www.acko.com/",careers:"https://www.acko.com/careers/"},
  "digit-insurance":{website:"https://www.godigit.com/",careers:"https://www.godigit.com/careers"},
  insurancedekho:{website:"https://www.insurancedekho.com/",careers:"https://www.linkedin.com/company/insurancedekho/jobs/"},
  fam:{website:"https://www.famapp.in/",careers:"https://www.linkedin.com/company/famapp/jobs/"},
  jar:{website:"https://web.myjar.app/",careers:"https://www.linkedin.com/company/jarapp/jobs/"},
  mobikwik:{website:"https://www.mobikwik.com/",careers:"https://www.mobikwik.com/careers"},
  easemytrip:{website:"https://www.easemytrip.com/",careers:"https://www.easemytrip.com/careers.html"},
  ixigo:{website:"https://www.ixigo.com/",careers:"https://www.ixigo.com/about/careers/"},
  yatra:{website:"https://www.yatra.com/",careers:"https://www.yatra.com/online/careers"},
  boat:{website:"https://www.boat-lifestyle.com/",careers:"https://www.linkedin.com/company/boat-lifestyle/jobs/"},
  mamaearth:{website:"https://mamaearth.in/",careers:"https://www.linkedin.com/company/mamaearth/jobs/"},
  appsmith:{website:"https://www.appsmith.com/",careers:"https://www.appsmith.com/careers"},
  freshtohome:{website:"https://www.freshtohome.com/",careers:"https://www.linkedin.com/company/freshtohome/jobs/"},
  "blue-tokai":{website:"https://bluetokaicoffee.com/",careers:"https://www.linkedin.com/company/blue-tokai-coffee-roasters/jobs/"},
  "the-whole-truth":{website:"https://thewholetruthfoods.com/",careers:"https://www.linkedin.com/company/the-whole-truth-foods/jobs/"},
  epigamia:{website:"https://epigamiastore.com/",careers:"https://www.linkedin.com/company/epigamia/jobs/"},
  "slurrp-farm":{website:"https://slurrpfarm.com/",careers:"https://www.linkedin.com/company/slurrp-farm/jobs/"},
};

const allStartupRecords = [...featuredStartups, ...additionalStartups, ...bulkStartups, ...directoryStartups, ...directoryStartups2, ...directoryStartups3, ...directoryStartups4, ...directoryStartups5, ...directoryStartups6, ...directoryStartups7, ...bangaloreMapStartups, ...remoteDirectoryStartups, ...targetTechStartups]
  .filter((startup) => startup.slug !== "ensembl")
  .map((startup) => {
    const override=locationOverrides[startup.slug as keyof typeof locationOverrides];
    return {
      ...startup,
      ...(override?{city:override.city,neighborhood:override.city,lat:override.lat,lng:override.lng,locationPrecision:"CITY" as const,locationSource:override.source}:{}),
      logoUrl: `https://www.google.com/s2/favicons?domain_url=${encodeURIComponent(startupLinks[startup.slug].website)}&sz=128`,
      isDemo: false,
    };
  });

export const startups = allStartupRecords.filter((startup,index,records)=>records.findIndex(item=>item.slug===startup.slug)===index);
export const mappedStartups = startups.filter(startup=>startup.city!=="India");
export const locationUnverifiedStartups = startups.filter(startup=>startup.city==="India");

export const startupSources: Record<string, string> = {
  ...Object.fromEntries(bangaloreMapCompanies.map(company=>[company.slug,company.source])),
  ...Object.fromEntries(targetTechCompanies.map(company=>[company.slug,company.source])),
  ...Object.fromEntries(remoteCompanies.map(company=>[company.slug,company.source])),
  ...Object.fromEntries(directoryCompanies7.map(company=>[company.slug,company.source])),
  ...Object.fromEntries(directoryCompanies6.map(company=>[company.slug,company.source])),
  ...Object.fromEntries(directoryCompanies5.map(company=>[company.slug,company.source])),
  ...Object.fromEntries(directoryCompanies4.map(company=>[company.slug,company.website])),
  ...Object.fromEntries(directoryCompanies3.map(company=>[company.slug,company.website])),
  ...Object.fromEntries(directoryCompanies2.map(company=>[company.slug,company.website])),
  ...Object.fromEntries(directoryCompanies.map(company=>[company.slug,company.website])),
  ...Object.fromEntries(bulkCompanyDirectory.map(([slug,,domain])=>[slug,`https://${domain}/`])),
  razorpay: "https://razorpay.com/newsroom/leadership-team/",
  postman: "https://www.postman.com/company/about-postman/",
  meesho: "https://www.meesho.io/life",
  cred: "https://newsroom.cred.club/",
  swiggy: "https://www.swiggy.com/corporate/",
  whatfix: "https://whatfix.com/about-us/",
  slice: "https://slice.bank.in/",
  smallcase: "https://www.smallcase.com/about",
  nference: "https://nference.com/about-us",
  scaler: "https://www.scaler.com/about/",
  darwinbox: "https://darwinbox.com/blog/the-darwinbox-story-why-are-we",
  browserstack: "https://www.browserstack.com/company",
  agrostar: "https://corporate.agrostar.in/about-us",
  chargebee: "https://www.chargebee.com/company/",
  devtron: "https://devtron.ai/about",
  zerodha: "https://zerodha.com/about/",
  phonepe: "https://www.phonepe.com/about-us/",
  groww: "https://groww.in/about-us",
  "ather-energy": "https://www.atherenergy.com/about",
  juspay: "https://juspay.io/about",
  rapido: "https://rapido.bike/About",
  porter: "https://porter.in/about-us",
  inmobi: "https://www.inmobi.com/company/",
  nobroker: "https://www.nobroker.in/about/about-us/",
  practo: "https://www.practo.com/company/about",
  udaan: "https://udaan.com/about-us",
  licious: "https://www.licious.in/about-us",
  sharechat: "https://sharechat.com/about",
  simplilearn: "https://www.simplilearn.com/about-us",
  ninjacart: "https://ninjacart.com/about-us/",
  flipkart: "https://corporate.flipkart.net/about-us",
  myntra: "https://careers.myntra.com/",
  ola: "https://www.olacabs.com/about",
  "ola-electric": "https://www.olaelectric.com/about",
  delhivery: "https://www.delhivery.com/about-us",
  freshworks: "https://www.freshworks.com/company/about/",
  zoho: "https://www.zoho.com/aboutus.html",
  zomato: "https://www.zomato.com/who-we-are",
  paytm: "https://paytm.com/about-us/",
  policybazaar: "https://www.policybazaar.com/about-us/",
  makemytrip: "https://www.makemytrip.com/about-us/company_profile.php",
  dream11: "https://about.dream11.in/",
  nykaa: "https://www.nykaa.com/who_are_we",
  upstox: "https://upstox.com/about/",
  "pine-labs": "https://www.pinelabs.com/about-us",
  bharatpe: "https://bharatpe.com/about/",
  cleartax: "https://cleartax.in/s/about-us",
  "cashfree-payments": "https://www.cashfree.com/about-us/",
  "open-money": "https://open.money/about-us/",
  coindcx: "https://coindcx.com/about-us/",
  coinswitch: "https://coinswitch.co/about-us",
  unacademy: "https://unacademy.com/about",
  vedantu: "https://www.vedantu.com/about-us",
  "urban-company": "https://www.urbancompany.com/about",
  ofbusiness: "https://www.ofbusiness.com/about-us",
  moglix: "https://business.moglix.com/about-us/",
  pharmeasy: "https://pharmeasy.in/about-us",
  innovaccer: "https://innovaccer.com/about-us",
  hasura: "https://hasura.io/company/",
  leadsquared: "https://www.leadsquared.com/about-us/",
  blackbuck:"https://www.blackbuck.com/",apna:"https://apna.co/about-us",khatabook:"https://khatabook.com/about/",navi:"https://navi.com/about-us",jupiter:"https://jupiter.money/about/",fi:"https://fi.money/about",kreditbee:"https://www.kreditbee.in/about-us",yulu:"https://www.yulu.bike/about-us",bounce:"https://bounceinfinity.com/pages/about-us",cultfit:"https://www.cult.fit/about",curefoods:"https://curefoods.in/","rebel-foods":"https://www.rebelfoods.com/about-us",zetwerk:"https://www.zetwerk.com/about-us/",perfios:"https://www.perfios.ai/about-us",signzy:"https://www.signzy.com/about-us",exotel:"https://exotel.com/about-us/",capillary:"https://www.capillarytech.com/about-us/",moengage:"https://www.moengage.com/about-us/",webengage:"https://webengage.com/about-us/",gupshup:"https://www.gupshup.io/about-us","yellow-ai":"https://yellow.ai/about-us/","observe-ai":"https://www.observe.ai/about-us",krutrim:"https://www.olakrutrim.com/","sarvam-ai":"https://www.sarvam.ai/",pixxel:"https://www.pixxel.space/about",bellatrix:"https://bellatrixaerospace.com/",skyroot:"https://www.skyroot.in/about-us",agnikul:"https://agnikul.in/about-us",redbus:"https://www.redbus.in/info/aboutus",bigbasket:"https://www.bigbasket.com/about-us/",dailyhunt:"https://www.dailyhunt.com/about", "pocket-aces":"https://pocketaces.in/",games24x7:"https://www.games24x7.com/about-us",mpl:"https://www.mpl.live/about",lenskart:"https://www.lenskart.com/about-us",firstcry:"https://www.firstcry.com/aboutus",cars24:"https://www.cars24.com/about-us/",cardekho:"https://www.cardekho.com/info/about_us",spinny:"https://www.spinny.com/about-us/",acko:"https://www.acko.com/about-us/","digit-insurance":"https://www.godigit.com/about",insurancedekho:"https://www.insurancedekho.com/about-us",fam:"https://www.famapp.in/",jar:"https://web.myjar.app/",mobikwik:"https://www.mobikwik.com/about",easemytrip:"https://www.easemytrip.com/about-us.html",ixigo:"https://www.ixigo.com/about",yatra:"https://www.yatra.com/online/about-yatra",boat:"https://www.boat-lifestyle.com/pages/who-are-we",mamaearth:"https://mamaearth.in/our-story",
  appsmith:"https://www.appsmith.com/about-us",
  freshtohome:"https://www.freshtohome.com/about-us", "blue-tokai":"https://bluetokaicoffee.com/pages/about-us", "the-whole-truth":"https://thewholetruthfoods.com/pages/about-us", epigamia:"https://epigamiastore.com/pages/about-us",
  "slurrp-farm":"https://slurrpfarm.com/pages/about-us",
};

export const remoteWork: Record<string,{type:"REMOTE_FIRST"|"REMOTE_OR_HYBRID"|"ROLE_DEPENDENT";label:string;source:string;summary:string;checkedAt:string}> = {
  ...Object.fromEntries(remoteCompanies.map(company=>[company.slug,{
    type:(company.policy==="fully-remote"||company.policy==="remote-first"?"REMOTE_FIRST":company.policy==="hybrid"?"REMOTE_OR_HYBRID":"ROLE_DEPENDENT") as "REMOTE_FIRST"|"REMOTE_OR_HYBRID"|"ROLE_DEPENDENT",
    label:company.policy==="fully-remote"?"Fully remote":company.policy==="remote-first"?"Remote-first":company.policy==="hybrid"?"Remote or hybrid":"Remote-friendly",
    source:company.source,
    summary:`Remote In Tech classifies ${company.name} as ${company.policy.replace(/-/g," ")} for ${company.region.replace(/-/g," ")} roles. Check the linked company careers page for current eligibility.`,
    checkedAt:"2026-08-21",
  }])),
  hasura:{type:"REMOTE_OR_HYBRID",label:"Remote or hybrid",source:"https://hasura.io/careers/",summary:"Hasura describes a globally distributed team with remote work or office collaboration.",checkedAt:"2026-08-21"},
  wingify:{type:"REMOTE_FIRST",label:"Remote-first",source:"https://wingify.com/careers/",summary:"Wingify explicitly describes itself as remote-first, with home-office and coworking support.",checkedAt:"2026-08-21"},
  atlan:{type:"REMOTE_FIRST",label:"Remote-first",source:"https://atlan.com/careers/",summary:"Atlan describes a remote-first team spanning more than 15 countries.",checkedAt:"2026-08-21"},
  hackerrank:{type:"ROLE_DEPENDENT",label:"Remote roles available",source:"https://www.hackerrank.com/careers/home",summary:"HackerRank labels individual roles as remote, hybrid, or on-site.",checkedAt:"2026-08-21"},
  browserstack:{type:"REMOTE_FIRST",label:"Remote-first",source:"https://www.browserstack.com/company",summary:"BrowserStack states that it officially became a remote-first company and supports working from where employees thrive.",checkedAt:"2026-08-21"},
  appsmith:{type:"REMOTE_FIRST",label:"Fully remote",source:"https://www.appsmith.com/careers",summary:"Appsmith describes fully remote work, home-office support, and a distributed team.",checkedAt:"2026-08-21"},
};
