export const directoryCompanies = [
  {
    "slug": "enmero",
    "name": "Enmero",
    "website": "https://www.enmero.in",
    "hq": "India",
    "industry": "software industry",
    "founded": 2025,
    "score": 18,
    "city": "India",
    "sector": "Software",
    "lat": 20.575699999999998,
    "lng": 78.9389
  },
  {
    "slug": "spixy",
    "name": "Spixy",
    "website": "https://spixy.in",
    "hq": "Bengaluru",
    "industry": "sharing economy",
    "founded": 2025,
    "score": 18,
    "city": "Bengaluru",
    "sector": "Sharing Economy",
    "lat": 12.9566,
    "lng": 77.5736
  },
  {
    "slug": "magnut-ai",
    "name": "Magnut AI",
    "website": "https://magnutai.com",
    "hq": "Pune",
    "industry": "artificial intelligence",
    "founded": 2025,
    "score": 18,
    "city": "Pune",
    "sector": "Artificial Intelligence",
    "lat": 18.508399999999998,
    "lng": 73.8387
  },
  {
    "slug": "mesrai",
    "name": "Mesrai",
    "website": "https://www.mesrai.com",
    "hq": "Bengaluru",
    "industry": "software industry",
    "founded": 2025,
    "score": 18,
    "city": "Bengaluru",
    "sector": "Software",
    "lat": 12.9626,
    "lng": 77.5796
  },
  {
    "slug": "actioneer",
    "name": "Actioneer",
    "website": "https://actioneer.com",
    "hq": "Mountain View",
    "industry": "artificial intelligence",
    "founded": 2025,
    "score": 18,
    "city": "India",
    "sector": "Artificial Intelligence",
    "lat": 20.587699999999998,
    "lng": 78.9509
  },
  {
    "slug": "vadavision",
    "name": "Vadavision",
    "website": "https://www.vadavision.com",
    "hq": "Chandigarh",
    "industry": "information technology industry",
    "founded": 2023,
    "score": 18,
    "city": "Chandigarh",
    "sector": "Information Technology",
    "lat": 30.7303,
    "lng": 76.7704
  },
  {
    "slug": "schogle",
    "name": "Schogle",
    "website": "https://schogle.com/",
    "hq": "Bankura",
    "industry": "educational technology",
    "founded": 2023,
    "score": 18,
    "city": "India",
    "sector": "Educational Technology",
    "lat": 20.5937,
    "lng": 78.9569
  },
  {
    "slug": "9pic-ai",
    "name": "9Pic AI",
    "website": "https://9pic.ai",
    "hq": "Bengaluru",
    "industry": "image hosting service",
    "founded": 2022,
    "score": 18,
    "city": "Bengaluru",
    "sector": "Image Hosting",
    "lat": 12.9746,
    "lng": 77.5916
  },
  {
    "slug": "nesta-toys",
    "name": "Nesta Toys",
    "website": "https://nestatoys.in",
    "hq": "Nagpur",
    "industry": "retail",
    "founded": 2021,
    "score": 18,
    "city": "India",
    "sector": "Retail",
    "lat": 20.5997,
    "lng": 78.9629
  },
  {
    "slug": "abcence",
    "name": "Abcence",
    "website": "https://abcence.com/",
    "hq": "Kolkata",
    "industry": "IT service management",
    "founded": 2020,
    "score": 18,
    "city": "Kolkata",
    "sector": "IT Management",
    "lat": 22.5816,
    "lng": 88.3669
  },
  {
    "slug": "ippopay",
    "name": "IppoPay",
    "website": "https://www.ippopay.com",
    "hq": "Chennai",
    "industry": "economics of banking",
    "founded": 2020,
    "score": 18,
    "city": "Chennai",
    "sector": "Economics Of Banking",
    "lat": 13.094700000000001,
    "lng": 80.2767
  },
  {
    "slug": "magnence",
    "name": "Magnence",
    "website": "https://magnence.com",
    "hq": "Bengaluru",
    "industry": "artificial intelligence",
    "founded": 2020,
    "score": 18,
    "city": "Bengaluru",
    "sector": "Artificial Intelligence",
    "lat": 12.986600000000001,
    "lng": 77.6036
  },
  {
    "slug": "ecarter-technologies",
    "name": "Ecarter Technologies",
    "website": "https://ecarter.co",
    "hq": "Noida",
    "industry": "software industry",
    "founded": 2020,
    "score": 18,
    "city": "Delhi NCR",
    "sector": "Software",
    "lat": 28.4775,
    "lng": 77.0386
  },
  {
    "slug": "tantrshell",
    "name": "TantrShell",
    "website": "https://tantrshell.online",
    "hq": "Pune",
    "industry": "cloud computing",
    "founded": 2020,
    "score": 18,
    "city": "Pune",
    "sector": "Cloud Computing",
    "lat": 18.502399999999998,
    "lng": 73.8717
  },
  {
    "slug": "mytravaly",
    "name": "MyTravaly",
    "website": "https://www.mytravaly.com",
    "hq": "Bengaluru",
    "industry": "travel industry",
    "founded": 2019,
    "score": 18,
    "city": "Bengaluru",
    "sector": "Travel",
    "lat": 12.9566,
    "lng": 77.6126
  },
  {
    "slug": "mytravaly",
    "name": "MyTravaly",
    "website": "https://mytravaly.in",
    "hq": "Bengaluru",
    "industry": "travel industry",
    "founded": 2019,
    "score": 18,
    "city": "Bengaluru",
    "sector": "Travel",
    "lat": 12.9596,
    "lng": 77.6156
  },
  {
    "slug": "mytravaly",
    "name": "MyTravaly",
    "website": "https://mytravaly.com.bd",
    "hq": "Bengaluru",
    "industry": "travel industry",
    "founded": 2019,
    "score": 18,
    "city": "Bengaluru",
    "sector": "Travel",
    "lat": 12.9626,
    "lng": 77.6186
  },
  {
    "slug": "brixial",
    "name": "Brixial",
    "website": "https://www.aggrim.com",
    "hq": "Bikaner",
    "industry": "business-to-business",
    "founded": 2019,
    "score": 18,
    "city": "India",
    "sector": "Business-To-Business",
    "lat": 20.587699999999998,
    "lng": 78.9389
  },
  {
    "slug": "brixial",
    "name": "Brixial",
    "website": "https://www.brixial.net",
    "hq": "Bikaner",
    "industry": "business-to-business",
    "founded": 2019,
    "score": 18,
    "city": "India",
    "sector": "Business-To-Business",
    "lat": 20.5907,
    "lng": 78.9419
  },
  {
    "slug": "digisurface",
    "name": "DigiSurface",
    "website": "https://digisurface.co",
    "hq": "Gurgaon",
    "industry": "artificial intelligence",
    "founded": 2019,
    "score": 18,
    "city": "Delhi NCR",
    "sector": "Artificial Intelligence",
    "lat": 28.4595,
    "lng": 77.0086
  },
  {
    "slug": "whitehat-jr",
    "name": "WhiteHat Jr",
    "website": "https://www.whitehatjr.com/",
    "hq": "Mumbai",
    "industry": "education industry",
    "founded": 2018,
    "score": 18,
    "city": "Mumbai",
    "sector": "Education",
    "lat": 19.079,
    "lng": 72.8627
  },
  {
    "slug": "playbae",
    "name": "Playbae",
    "website": "https://playbae.in/",
    "hq": "Gurgaon",
    "industry": "video game industry",
    "founded": 2018,
    "score": 18,
    "city": "Delhi NCR",
    "sector": "Video Game",
    "lat": 28.4655,
    "lng": 77.0146
  },
  {
    "slug": "jk-tech-hub",
    "name": "JK Tech Hub",
    "website": "https://jktechhub.com",
    "hq": "Rajkot",
    "industry": "software industry",
    "founded": 2018,
    "score": 18,
    "city": "India",
    "sector": "Software",
    "lat": 20.6027,
    "lng": 78.9539
  },
  {
    "slug": "verbose-techlabs-llp",
    "name": "Verbose TechLabs LLP",
    "website": "https://verbosetechlabs.com",
    "hq": "New Delhi",
    "industry": "Q130147025",
    "founded": 2017,
    "score": 18,
    "city": "Delhi NCR",
    "sector": "Other",
    "lat": 28.4715,
    "lng": 77.0206
  },
  {
    "slug": "villamart",
    "name": "Villamart",
    "website": "https://www.villamart.in/",
    "hq": "Bhubaneswar",
    "industry": "agriculture",
    "founded": 2017,
    "score": 18,
    "city": "Bhubaneswar",
    "sector": "Agriculture",
    "lat": 20.3111,
    "lng": 85.8215
  },
  {
    "slug": "supergaming",
    "name": "SuperGaming",
    "website": "https://www.supergaming.com/",
    "hq": "Pune",
    "industry": "video game industry",
    "founded": 2017,
    "score": 18,
    "city": "Pune",
    "sector": "Video Game",
    "lat": 18.5384,
    "lng": 73.8567
  },
  {
    "slug": "evocris-energy",
    "name": "Evocris Energy",
    "website": "https://www.evocrisx.com",
    "hq": "New Delhi",
    "industry": "energy industry",
    "founded": 2017,
    "score": 18,
    "city": "Delhi NCR",
    "sector": "Energy",
    "lat": 28.441499999999998,
    "lng": 77.0296
  },
  {
    "slug": "ithink-logistics",
    "name": "iThink Logistics",
    "website": "https://www.ithinklogistics.com",
    "hq": "Mumbai",
    "industry": "logistics",
    "founded": 2017,
    "score": 18,
    "city": "Mumbai",
    "sector": "Logistics",
    "lat": 19.061,
    "lng": 72.8837
  },
  {
    "slug": "getwidget",
    "name": "GetWidget",
    "website": "https://hireflutterdev.com/",
    "hq": "Bengaluru",
    "industry": "artificial intelligence",
    "founded": 2017,
    "score": 18,
    "city": "Bengaluru",
    "sector": "Artificial Intelligence",
    "lat": 12.9596,
    "lng": 77.6036
  },
  {
    "slug": "getwidget",
    "name": "GetWidget",
    "website": "https://www.getwidget.dev",
    "hq": "Bengaluru",
    "industry": "artificial intelligence",
    "founded": 2017,
    "score": 18,
    "city": "Bengaluru",
    "sector": "Artificial Intelligence",
    "lat": 12.9626,
    "lng": 77.6066
  },
  {
    "slug": "unstop",
    "name": "Unstop",
    "website": "https://unstop.com/",
    "hq": "New Delhi",
    "industry": "recruitment",
    "founded": 2017,
    "score": 18,
    "city": "Delhi NCR",
    "sector": "Recruitment",
    "lat": 28.4535,
    "lng": 77.0416
  },
  {
    "slug": "oswald-labs",
    "name": "Oswald Labs",
    "website": "https://oswaldlabs.com",
    "hq": "New Delhi",
    "industry": "accessibility",
    "founded": 2016,
    "score": 18,
    "city": "Delhi NCR",
    "sector": "Accessibility",
    "lat": 28.4565,
    "lng": 77.0446
  },
  {
    "slug": "bix-bytes-solutions-pvt-ltd",
    "name": "Bix Bytes Solutions Pvt Ltd",
    "website": "https://www.bixbytessolutions.com/de/",
    "hq": "Zurich",
    "industry": "software development",
    "founded": 2016,
    "score": 18,
    "city": "India",
    "sector": "Software Development",
    "lat": 20.5937,
    "lng": 78.9839
  },
  {
    "slug": "lucid-labs",
    "name": "Lucid Labs",
    "website": "https://lucidlabs.in/",
    "hq": "New Delhi",
    "industry": "video game industry",
    "founded": 2015,
    "score": 18,
    "city": "Delhi NCR",
    "sector": "Video Game",
    "lat": 28.4625,
    "lng": 77.0506
  },
  {
    "slug": "m2p",
    "name": "M2P",
    "website": "https://m2pfintech.com",
    "hq": "Chennai",
    "industry": "fintech",
    "founded": 2015,
    "score": 18,
    "city": "Chennai",
    "sector": "Fintech",
    "lat": 13.088700000000001,
    "lng": 80.2467
  },
  {
    "slug": "zelthy",
    "name": "Zelthy",
    "website": "https://www.zelthy.com/",
    "hq": "Seattle",
    "industry": "pharmaceutical industry",
    "founded": 2015,
    "score": 18,
    "city": "India",
    "sector": "Pharmaceutical",
    "lat": 20.6027,
    "lng": 78.9419
  },
  {
    "slug": "ekfrazo-technologies",
    "name": "Ekfrazo Technologies",
    "website": "https://ekfrazo.com",
    "hq": "Bengaluru",
    "industry": "artificial intelligence",
    "founded": 2015,
    "score": 18,
    "city": "Bengaluru",
    "sector": "Artificial Intelligence",
    "lat": 12.983600000000001,
    "lng": 77.5766
  },
  {
    "slug": "atyantik-technologies",
    "name": "Atyantik Technologies",
    "website": "https://atyantik.com",
    "hq": "Vadodara",
    "industry": "software industry",
    "founded": 2015,
    "score": 18,
    "city": "Ahmedabad",
    "sector": "Software",
    "lat": 23.0375,
    "lng": 72.5564
  },
  {
    "slug": "oyo-rooms",
    "name": "OYO Rooms",
    "website": "https://www.oyorooms.com",
    "hq": "Gurgaon",
    "industry": "hospitality service",
    "founded": 2013,
    "score": 18,
    "city": "Delhi NCR",
    "sector": "Hospitality",
    "lat": 28.4775,
    "lng": 77.0146
  },
  {
    "slug": "vantage-circle",
    "name": "Vantage Circle",
    "website": "https://www.vantagecircle.com/",
    "hq": "New Delhi",
    "industry": "software industry",
    "founded": 2011,
    "score": 18,
    "city": "Delhi NCR",
    "sector": "Software",
    "lat": 28.441499999999998,
    "lng": 77.0176
  },
  {
    "slug": "ola-cabs",
    "name": "Ola Cabs",
    "website": "https://www.olacabs.com/",
    "hq": "Bengaluru",
    "industry": "information technology",
    "founded": 2010,
    "score": 18,
    "city": "Bengaluru",
    "sector": "Information Technology",
    "lat": 12.9566,
    "lng": 77.5886
  },
  {
    "slug": "yash-future-tech-solutions",
    "name": "Yash Future Tech Solutions",
    "website": "https://www.yashfuturetech.com/",
    "hq": "Jodhpur",
    "industry": "video game industry",
    "founded": 2010,
    "score": 18,
    "city": "India",
    "sector": "Video Game",
    "lat": 20.581699999999998,
    "lng": 78.9599
  },
  {
    "slug": "redpulse-software",
    "name": "Redpulse Software",
    "website": "https://redpulsesoftware.in",
    "hq": "Karur district",
    "industry": "information technology",
    "founded": 2010,
    "score": 18,
    "city": "India",
    "sector": "Information Technology",
    "lat": 20.584699999999998,
    "lng": 78.9629
  },
  {
    "slug": "wow-momo",
    "name": "Wow! Momo",
    "website": "https://www.wowmomo.com/",
    "hq": "Kolkata",
    "industry": "food service",
    "founded": 2008,
    "score": 18,
    "city": "Kolkata",
    "sector": "Food",
    "lat": 22.5666,
    "lng": 88.3669
  },
  {
    "slug": "indapoint-technologies",
    "name": "IndaPoint Technologies",
    "website": "https://www.indapoint.com",
    "hq": "Vadodara",
    "industry": "artificial intelligence",
    "founded": 2006,
    "score": 18,
    "city": "Ahmedabad",
    "sector": "Artificial Intelligence",
    "lat": 23.0195,
    "lng": 72.5774
  },
  {
    "slug": "mcube",
    "name": "MCUBE",
    "website": "https://mcube.com",
    "hq": "India",
    "industry": "Cloud communications",
    "founded": 2006,
    "score": 18,
    "city": "India",
    "sector": "Cloud Communications",
    "lat": 20.5937,
    "lng": 78.9719
  },
  {
    "slug": "gluster",
    "name": "Gluster",
    "website": "https://www.gluster.org/",
    "hq": "Bengaluru",
    "industry": "software industry",
    "founded": 2005,
    "score": 18,
    "city": "Bengaluru",
    "sector": "Software",
    "lat": 12.9746,
    "lng": 77.6066
  },
  {
    "slug": "i-solution-microsystems-private-limited",
    "name": "I Solution Microsystems Private Limited",
    "website": "https://www.isolutiononline.com/",
    "hq": "Jaipur",
    "industry": "software industry",
    "founded": 2004,
    "score": 18,
    "city": "Jaipur",
    "sector": "Software",
    "lat": 26.918400000000002,
    "lng": 75.8023
  },
  {
    "slug": "logicboxes",
    "name": "LogicBoxes",
    "website": "https://logicboxes.com",
    "hq": "Mumbai",
    "industry": "software industry",
    "founded": 2002,
    "score": 18,
    "city": "Mumbai",
    "sector": "Software",
    "lat": 19.085,
    "lng": 72.8957
  },
  {
    "slug": "ispring",
    "name": "iSpring",
    "website": "https://www.ispringsolutions.com",
    "hq": "Alexandria",
    "industry": "information technology",
    "founded": 2001,
    "score": 18,
    "city": "India",
    "sector": "Information Technology",
    "lat": 20.6057,
    "lng": 78.9839
  },
  {
    "slug": "ispring",
    "name": "iSpring",
    "website": "https://www.ispring.ru",
    "hq": "Yoshkar-Ola",
    "industry": "information technology",
    "founded": 2001,
    "score": 18,
    "city": "India",
    "sector": "Information Technology",
    "lat": 20.6087,
    "lng": 78.9869
  },
  {
    "slug": "one97-communications",
    "name": "One97 Communications",
    "website": "https://www.one97.com/",
    "hq": "Delhi",
    "industry": "e-commerce",
    "founded": 2000,
    "score": 18,
    "city": "Delhi NCR",
    "sector": "E-Commerce",
    "lat": 28.4775,
    "lng": 77.0026
  },
  {
    "slug": "dhruva-interactive",
    "name": "Dhruva Interactive",
    "website": "https://dhruva.com/",
    "hq": "Bengaluru",
    "industry": "video game industry",
    "founded": 1997,
    "score": 18,
    "city": "Bengaluru",
    "sector": "Video Game",
    "lat": 12.9536,
    "lng": 77.5736
  },
  {
    "slug": "rediff-com",
    "name": "rediff.com",
    "website": "https://www.rediff.com/",
    "hq": "Mumbai",
    "industry": "online service",
    "founded": 1996,
    "score": 18,
    "city": "Mumbai",
    "sector": "Online",
    "lat": 19.061,
    "lng": 72.8597
  },
  {
    "slug": "allorasoft-private-limited",
    "name": "Allorasoft Private Limited",
    "website": "http://allorasoft.com",
    "hq": "New Delhi",
    "industry": "software industry",
    "founded": 2022,
    "score": 17,
    "city": "Delhi NCR",
    "sector": "Software",
    "lat": 28.447499999999998,
    "lng": 77.0116
  },
  {
    "slug": "yestracker-gps",
    "name": "Yestracker GPS",
    "website": "http://www.yestracker.in/",
    "hq": "Bengaluru",
    "industry": "telematics",
    "founded": 2020,
    "score": 17,
    "city": "Bengaluru",
    "sector": "Telematics",
    "lat": 12.9626,
    "lng": 77.5826
  },
  {
    "slug": "moonfrog",
    "name": "Moonfrog",
    "website": "http://www.moonfroglabs.com/",
    "hq": "Bengaluru",
    "industry": "video game industry",
    "founded": 2013,
    "score": 17,
    "city": "Bengaluru",
    "sector": "Video Game",
    "lat": 12.9656,
    "lng": 77.5856
  },
  {
    "slug": "aaroh",
    "name": "Aaroh",
    "website": "http://www.aaroh.co.in",
    "hq": "Bikaner",
    "industry": "software industry",
    "founded": 2009,
    "score": 17,
    "city": "India",
    "sector": "Software",
    "lat": 20.5907,
    "lng": 78.9569
  },
  {
    "slug": "trine-games",
    "name": "Trine Games",
    "website": "http://www.trinegames.com",
    "hq": "Mumbai",
    "industry": "video game industry",
    "founded": 2006,
    "score": 17,
    "city": "Mumbai",
    "sector": "Video Game",
    "lat": 19.076,
    "lng": 72.8747
  },
  {
    "slug": "gameshastra",
    "name": "Gameshastra",
    "website": "http://www.gameshastra.com/",
    "hq": "Hyderabad",
    "industry": "video game industry",
    "founded": 2006,
    "score": 17,
    "city": "Hyderabad",
    "sector": "Video Game",
    "lat": 17.388,
    "lng": 78.4867
  },
  {
    "slug": "microsoft-india",
    "name": "Microsoft India",
    "website": "http://www.microsoft.com/India/",
    "hq": "Gurgaon",
    "industry": "software industry",
    "founded": 1999,
    "score": 17,
    "city": "Delhi NCR",
    "sector": "Software",
    "lat": 28.4655,
    "lng": 77.0296
  },
  {
    "slug": "octro-inc",
    "name": "Octro, Inc.",
    "website": "https://www.octro.com",
    "hq": "New Delhi",
    "industry": "video game industry",
    "founded": null,
    "score": 17,
    "city": "Delhi NCR",
    "sector": "Video Game",
    "lat": 28.4685,
    "lng": 77.0326
  },
  {
    "slug": "pushcrew",
    "name": "Pushcrew",
    "website": "https://pushcrew.com/",
    "hq": "Pune",
    "industry": "push notification",
    "founded": null,
    "score": 17,
    "city": "Pune",
    "sector": "Push Notification",
    "lat": 18.5324,
    "lng": 73.8657
  },
  {
    "slug": "aiaj-technocrats",
    "name": "AIAJ Technocrats",
    "website": "https://aiaj.tech/",
    "hq": "Nagpur",
    "industry": "software industry",
    "founded": null,
    "score": 17,
    "city": "India",
    "sector": "Software",
    "lat": 20.6087,
    "lng": 78.9749
  },
  {
    "slug": "golegally",
    "name": "GoLegally",
    "website": "https://golegally.com",
    "hq": "Chandigarh",
    "industry": "legal tech",
    "founded": null,
    "score": 17,
    "city": "Chandigarh",
    "sector": "Legal Tech",
    "lat": 30.7513,
    "lng": 76.7944
  },
  {
    "slug": "cyfi",
    "name": "CYFI",
    "website": "https://cyfi.nestatoys.com/",
    "hq": "Nagpur",
    "industry": "e-learning",
    "founded": null,
    "score": 17,
    "city": "India",
    "sector": "E-Learning",
    "lat": 20.575699999999998,
    "lng": 78.9809
  },
  {
    "slug": "arpsyndicate",
    "name": "ARPSyndicate",
    "website": "https://www.arpsyndicate.io/",
    "hq": "New Delhi",
    "industry": "cyber threat intelligence",
    "founded": null,
    "score": 17,
    "city": "Delhi NCR",
    "sector": "Cyber Threat Intelligence",
    "lat": 28.444499999999998,
    "lng": 77.0476
  },
  {
    "slug": "xigma-games",
    "name": "Xigma Games",
    "website": "http://www.xigmagames.com/",
    "hq": "Bengaluru",
    "industry": "video game industry",
    "founded": null,
    "score": 16,
    "city": "Bengaluru",
    "sector": "Video Game",
    "lat": 12.9596,
    "lng": 77.6186
  },
  {
    "slug": "novax-ai",
    "name": "NovaX AI",
    "website": "https://novaxai.in",
    "hq": "",
    "industry": "artificial intelligence",
    "founded": 2025,
    "score": 15,
    "city": "India",
    "sector": "Artificial Intelligence",
    "lat": 20.584699999999998,
    "lng": 78.9389
  },
  {
    "slug": "train-rex",
    "name": "Train Rex",
    "website": "https://trainrexofficial.com",
    "hq": "",
    "industry": "medical technology",
    "founded": 2025,
    "score": 15,
    "city": "India",
    "sector": "Medical Technology",
    "lat": 20.587699999999998,
    "lng": 78.9419
  },
  {
    "slug": "daksh902",
    "name": "Daksh902",
    "website": "https://daksh902.com",
    "hq": "",
    "industry": "mobile app",
    "founded": 2025,
    "score": 15,
    "city": "India",
    "sector": "Mobile App",
    "lat": 20.5907,
    "lng": 78.9449
  },
  {
    "slug": "exuverse",
    "name": "Exuverse",
    "website": "https://www.exuverse.com/",
    "hq": "",
    "industry": "artificial intelligence",
    "founded": 2025,
    "score": 15,
    "city": "India",
    "sector": "Artificial Intelligence",
    "lat": 20.5937,
    "lng": 78.9479
  },
  {
    "slug": "blankline",
    "name": "Blankline",
    "website": "https://blankline.org/",
    "hq": "",
    "industry": "artificial intelligence",
    "founded": 2024,
    "score": 15,
    "city": "India",
    "sector": "Artificial Intelligence",
    "lat": 20.5967,
    "lng": 78.9509
  },
  {
    "slug": "yash12007",
    "name": "Yash12007",
    "website": "https://www.yash12007.com",
    "hq": "",
    "industry": "software development",
    "founded": 2023,
    "score": 15,
    "city": "India",
    "sector": "Software Development",
    "lat": 20.5997,
    "lng": 78.9539
  },
  {
    "slug": "desku",
    "name": "Desku",
    "website": "https://desku.io",
    "hq": "India",
    "industry": "",
    "founded": 2021,
    "score": 15,
    "city": "India",
    "sector": "Other",
    "lat": 20.6027,
    "lng": 78.9569
  },
  {
    "slug": "botsense",
    "name": "BotSense",
    "website": "https://botsense.io",
    "hq": "Indore",
    "industry": "",
    "founded": 2021,
    "score": 15,
    "city": "Indore",
    "sector": "Other",
    "lat": 22.7316,
    "lng": 75.8547
  },
  {
    "slug": "superdove-games",
    "name": "Superdove Games",
    "website": "https://superdove.games",
    "hq": "",
    "industry": "video game industry",
    "founded": 2020,
    "score": 15,
    "city": "India",
    "sector": "Video Game",
    "lat": 20.6087,
    "lng": 78.9629
  },
  {
    "slug": "pixsoffice",
    "name": "Pixsoffice",
    "website": "https://pixsoffice.com/",
    "hq": "",
    "industry": "software",
    "founded": 2018,
    "score": 15,
    "city": "India",
    "sector": "Software",
    "lat": 20.6117,
    "lng": 78.9659
  },
  {
    "slug": "ubisoft-mumbai",
    "name": "Ubisoft Mumbai",
    "website": "https://www.ubisoft.com/en-US/studio/mumbai.aspx",
    "hq": "Mumbai",
    "industry": "",
    "founded": 2018,
    "score": 15,
    "city": "Mumbai",
    "sector": "Other",
    "lat": 19.058,
    "lng": 72.8837
  },
  {
    "slug": "fast-themes",
    "name": "Fast Themes",
    "website": "https://fastthemes.com",
    "hq": "",
    "industry": "web development",
    "founded": 2014,
    "score": 15,
    "city": "India",
    "sector": "Web Development",
    "lat": 20.578699999999998,
    "lng": 78.9719
  },
  {
    "slug": "enacton-technologies",
    "name": "EnactOn Technologies",
    "website": "https://www.enacton.com/",
    "hq": "",
    "industry": "software industry",
    "founded": 2013,
    "score": 15,
    "city": "India",
    "sector": "Software",
    "lat": 20.581699999999998,
    "lng": 78.9749
  },
  {
    "slug": "skywebtech",
    "name": "SkyWebTech",
    "website": "https://www.skywebtech.net",
    "hq": "",
    "industry": "web development",
    "founded": 2008,
    "score": 15,
    "city": "India",
    "sector": "Web Development",
    "lat": 20.584699999999998,
    "lng": 78.9779
  },
  {
    "slug": "renew-power",
    "name": "ReNew Power",
    "website": "http://renewpower.in/",
    "hq": "Gurgaon",
    "industry": "",
    "founded": 2011,
    "score": 14,
    "city": "Delhi NCR",
    "sector": "Other",
    "lat": 28.4535,
    "lng": 77.0446
  },
  {
    "slug": "crass-infotech",
    "name": "CRASS Infotech",
    "website": "https://crassinfotech.com",
    "hq": "",
    "industry": "video game industry",
    "founded": null,
    "score": 14,
    "city": "India",
    "sector": "Video Game",
    "lat": 20.5907,
    "lng": 78.9839
  },
  {
    "slug": "crass-studios",
    "name": "CRASS Studios",
    "website": "https://crassstudios.com",
    "hq": "",
    "industry": "video game industry",
    "founded": null,
    "score": 14,
    "city": "India",
    "sector": "Video Game",
    "lat": 20.5937,
    "lng": 78.9869
  },
  {
    "slug": "hygnal",
    "name": "hygnal",
    "website": "https://www.hygnal.com",
    "hq": "Bengaluru",
    "industry": "",
    "founded": null,
    "score": 14,
    "city": "Bengaluru",
    "sector": "Other",
    "lat": 12.9746,
    "lng": 77.5706
  },
  {
    "slug": "e-khool-lms",
    "name": "e-KHOOL LMS",
    "website": "https://ekhool.com/",
    "hq": "",
    "industry": "Edutech",
    "founded": null,
    "score": 14,
    "city": "India",
    "sector": "Edutech",
    "lat": 20.5997,
    "lng": 78.9419
  },
  {
    "slug": "byju-s",
    "name": "BYJU’s",
    "website": "https://byjus.com",
    "hq": "Bengaluru",
    "industry": "",
    "founded": null,
    "score": 14,
    "city": "Bengaluru",
    "sector": "Other",
    "lat": 12.9806,
    "lng": 77.5766
  },
  {
    "slug": "fleksa",
    "name": "fleksa",
    "website": "https://www.fleksa.com",
    "hq": "",
    "industry": "food technology",
    "founded": null,
    "score": 14,
    "city": "India",
    "sector": "Food Technology",
    "lat": 20.6057,
    "lng": 78.9479
  },
  {
    "slug": "elite-billing",
    "name": "Elite Billing",
    "website": "https://elitebilling.in",
    "hq": "Erode",
    "industry": "",
    "founded": null,
    "score": 14,
    "city": "India",
    "sector": "Other",
    "lat": 20.6087,
    "lng": 78.9509
  },
  {
    "slug": "kdk-softwares",
    "name": "KDK Softwares",
    "website": "https://www.kdksoftware.com/",
    "hq": "Jaipur",
    "industry": "",
    "founded": null,
    "score": 14,
    "city": "Jaipur",
    "sector": "Other",
    "lat": 26.930400000000002,
    "lng": 75.7783
  },
  {
    "slug": "geoiq",
    "name": "GeoIQ",
    "website": "https://geoiq.io/",
    "hq": "Bengaluru",
    "industry": "",
    "founded": null,
    "score": 14,
    "city": "Bengaluru",
    "sector": "Other",
    "lat": 12.9536,
    "lng": 77.5886
  },
  {
    "slug": "borentis",
    "name": "Borentis",
    "website": "https://borentis.com",
    "hq": "",
    "industry": "retail",
    "founded": null,
    "score": 14,
    "city": "India",
    "sector": "Retail",
    "lat": 20.578699999999998,
    "lng": 78.9599
  },
  {
    "slug": "vialoop",
    "name": "ViaLoop",
    "website": "https://vialoop.in",
    "hq": "",
    "industry": "fleet management",
    "founded": null,
    "score": 14,
    "city": "India",
    "sector": "Fleet Management",
    "lat": 20.581699999999998,
    "lng": 78.9629
  },
  {
    "slug": "musicmuni-labs",
    "name": "MusicMuni Labs",
    "website": "https://musicmuni.com",
    "hq": "Bengaluru",
    "industry": "",
    "founded": null,
    "score": 14,
    "city": "Bengaluru",
    "sector": "Other",
    "lat": 12.9626,
    "lng": 77.5976
  },
  {
    "slug": "wincredible-technologies",
    "name": "Wincredible Technologies",
    "website": "https://wincredibletech.com",
    "hq": "",
    "industry": "software development",
    "founded": null,
    "score": 14,
    "city": "India",
    "sector": "Software Development",
    "lat": 20.587699999999998,
    "lng": 78.9689
  },
  {
    "slug": "fos-automations",
    "name": "FOS Automations",
    "website": "https://fosautomations.com/",
    "hq": "",
    "industry": "",
    "founded": 2025,
    "score": 12,
    "city": "India",
    "sector": "Other",
    "lat": 20.5907,
    "lng": 78.9719
  },
  {
    "slug": "panthm-ai-labs",
    "name": "PANTHM AI Labs",
    "website": "https://panthm.com",
    "hq": "",
    "industry": "",
    "founded": 2024,
    "score": 12,
    "city": "India",
    "sector": "Other",
    "lat": 20.5937,
    "lng": 78.9749
  },
  {
    "slug": "kommify",
    "name": "Kommify",
    "website": "https://kommify.com/",
    "hq": "",
    "industry": "",
    "founded": 2024,
    "score": 12,
    "city": "India",
    "sector": "Other",
    "lat": 20.5967,
    "lng": 78.9779
  },
  {
    "slug": "omnaya-studios",
    "name": "Omnaya Studios",
    "website": "https://omnayastudios.com",
    "hq": "",
    "industry": "",
    "founded": null,
    "score": 11,
    "city": "India",
    "sector": "Other",
    "lat": 20.5997,
    "lng": 78.9809
  },
  {
    "slug": "mojoomla",
    "name": "Mojoomla",
    "website": "https://mojoomla.com/",
    "hq": "",
    "industry": "",
    "founded": null,
    "score": 11,
    "city": "India",
    "sector": "Other",
    "lat": 20.6027,
    "lng": 78.9839
  },
  {
    "slug": "the-nexus-pivot",
    "name": "The Nexus Pivot",
    "website": "https://thenexuspivot.com/",
    "hq": "",
    "industry": "",
    "founded": null,
    "score": 11,
    "city": "India",
    "sector": "Other",
    "lat": 20.6057,
    "lng": 78.9869
  },
  {
    "slug": "fusionsync-ai",
    "name": "FusionSync AI",
    "website": "https://www.fusionsync.ai",
    "hq": "Mohali",
    "industry": "artificial intelligence",
    "founded": 2025,
    "score": 8,
    "city": "Chandigarh",
    "sector": "Artificial Intelligence",
    "lat": 30.7483,
    "lng": 76.7554
  },
  {
    "slug": "idopia-services-private-limited",
    "name": "Idopia Services Private Limited",
    "website": "https://wealthnorth.in/",
    "hq": "Pune",
    "industry": "financial sector",
    "founded": 2025,
    "score": 8,
    "city": "Pune",
    "sector": "Financial Sector",
    "lat": 18.5384,
    "lng": 73.8357
  },
  {
    "slug": "smol-cat-films",
    "name": "Smol Cat Films",
    "website": "https://www.smolcatfilms.com",
    "hq": "Mumbai",
    "industry": "film industry",
    "founded": 2024,
    "score": 8,
    "city": "Mumbai",
    "sector": "Film",
    "lat": 19.058,
    "lng": 72.8597
  },
  {
    "slug": "aplus-foods",
    "name": "Aplus Foods",
    "website": "https://www.aplus.food",
    "hq": "Nawanshahr",
    "industry": "e-commerce",
    "founded": 2024,
    "score": 8,
    "city": "India",
    "sector": "E-Commerce",
    "lat": 20.578699999999998,
    "lng": 78.9479
  },
  {
    "slug": "panjwani-projects-private-limited",
    "name": "Panjwani Projects Private Limited",
    "website": "https://panjwanigroup.in",
    "hq": "Vadodara",
    "industry": "real estate development",
    "founded": 2023,
    "score": 8,
    "city": "Ahmedabad",
    "sector": "Real Estate Development",
    "lat": 23.0105,
    "lng": 72.5594
  },
  {
    "slug": "free-mind-consultancy",
    "name": "Free Mind Consultancy",
    "website": "https://www.freemindconsult.com",
    "hq": "Pune",
    "industry": "artificial intelligence",
    "founded": 2023,
    "score": 8,
    "city": "Pune",
    "sector": "Artificial Intelligence",
    "lat": 18.5114,
    "lng": 73.8477
  },
  {
    "slug": "ryxillyfy-glaid",
    "name": "Ryxillyfy Glaid",
    "website": "https://www.ryxillyfyglaid.com",
    "hq": "Patna",
    "industry": "automotive industry",
    "founded": 2023,
    "score": 8,
    "city": "Patna",
    "sector": "Automotive",
    "lat": 25.5881,
    "lng": 85.1316
  },
  {
    "slug": "rahul-guhathakurta-huf-office",
    "name": "Rahul Guhathakurta HUF Office",
    "website": "https://www.rghuf.com",
    "hq": "Ahmedabad",
    "industry": "financial management",
    "founded": 2022,
    "score": 8,
    "city": "Ahmedabad",
    "sector": "Financial Management",
    "lat": 23.0195,
    "lng": 72.5684
  },
  {
    "slug": "diagnobuddy-in-private-limited",
    "name": "Diagnobuddy.in Private Limited",
    "website": "https://diagnobuddy.in/",
    "hq": "New Delhi",
    "industry": "Diagnostic Pathology",
    "founded": 2022,
    "score": 8,
    "city": "Delhi NCR",
    "sector": "Diagnostic Pathology",
    "lat": 28.4595,
    "lng": 77.0266
  },
  {
    "slug": "kaushik-films-entertainment-company",
    "name": "Kaushik Films & Entertainment Company",
    "website": "https://kfaec.com/",
    "hq": "Jattari",
    "industry": "entertainment",
    "founded": 2021,
    "score": 8,
    "city": "India",
    "sector": "Entertainment",
    "lat": 20.5967,
    "lng": 78.9659
  },
  {
    "slug": "happyfares",
    "name": "HappyFares",
    "website": "https://happyfares.in/",
    "hq": "Guwahati",
    "industry": "travel agency",
    "founded": 2020,
    "score": 8,
    "city": "Guwahati",
    "sector": "Travel Agency",
    "lat": 26.1505,
    "lng": 91.7422
  },
  {
    "slug": "ikkayi",
    "name": "Ikkayi",
    "website": "https://ikkayi.com",
    "hq": "New Delhi",
    "industry": "retail",
    "founded": 2020,
    "score": 8,
    "city": "Delhi NCR",
    "sector": "Retail",
    "lat": 28.4685,
    "lng": 77.0356
  },
  {
    "slug": "evidyalam",
    "name": "eVidyalam",
    "website": "https://www.evidyalam.com",
    "hq": "Saharanpur",
    "industry": "education",
    "founded": 2020,
    "score": 8,
    "city": "India",
    "sector": "Education",
    "lat": 20.6057,
    "lng": 78.9749
  },
  {
    "slug": "infoobox",
    "name": "infoobox",
    "website": "https://infoobox.com",
    "hq": "Gurgaon",
    "industry": "web technology",
    "founded": 2020,
    "score": 8,
    "city": "Delhi NCR",
    "sector": "Web Technology",
    "lat": 28.4745,
    "lng": 77.0416
  },
  {
    "slug": "minorplayz-kids-corner-llp",
    "name": "Minorplayz Kids Corner LLP",
    "website": "https://krazycaterpillar.com/",
    "hq": "Pune",
    "industry": "game industry",
    "founded": 2020,
    "score": 8,
    "city": "Pune",
    "sector": "Game",
    "lat": 18.5384,
    "lng": 73.8747
  },
  {
    "slug": "sort-string-solutions",
    "name": "Sort String Solutions",
    "website": "https://sortstring.com",
    "hq": "Lucknow",
    "industry": "software industry",
    "founded": 2020,
    "score": 8,
    "city": "Lucknow",
    "sector": "Software",
    "lat": 26.828699999999998,
    "lng": 80.9672
  },
  {
    "slug": "gynoveda",
    "name": "Gynoveda",
    "website": "https://gynoveda.com",
    "hq": "Mumbai",
    "industry": "Ayurveda",
    "founded": 2019,
    "score": 8,
    "city": "Mumbai",
    "sector": "Ayurveda",
    "lat": 19.061,
    "lng": 72.9017
  },
  {
    "slug": "intrcity-smartbus",
    "name": "IntrCity SmartBus",
    "website": "https://www.intrcity.com/",
    "hq": "Noida",
    "industry": "passenger transport",
    "founded": 2019,
    "score": 8,
    "city": "Delhi NCR",
    "sector": "Passenger Transport",
    "lat": 28.447499999999998,
    "lng": 77.0026
  },
  {
    "slug": "grahaa-space",
    "name": "Grahaa Space",
    "website": "https://www.grahaa.space/",
    "hq": "Mahalakshmipuram",
    "industry": "space industry",
    "founded": 2018,
    "score": 8,
    "city": "India",
    "sector": "Space",
    "lat": 20.584699999999998,
    "lng": 78.9419
  },
  {
    "slug": "corpseed-ites-pvt-ltd",
    "name": "Corpseed ITES Pvt Ltd",
    "website": "https://www.corpseed.com/",
    "hq": "Noida",
    "industry": "consulting company",
    "founded": 2018,
    "score": 8,
    "city": "Delhi NCR",
    "sector": "Consulting",
    "lat": 28.4535,
    "lng": 77.0086
  },
  {
    "slug": "nikahforever",
    "name": "NikahForever",
    "website": "https://www.nikahforever.com",
    "hq": "New Delhi",
    "industry": "online dating service",
    "founded": 2018,
    "score": 8,
    "city": "Delhi NCR",
    "sector": "Online Dating",
    "lat": 28.4565,
    "lng": 77.0116
  },
  {
    "slug": "tentackles",
    "name": "Tentackles",
    "website": "https://tentackles.com",
    "hq": "Bengaluru",
    "industry": "creative industries",
    "founded": 2018,
    "score": 8,
    "city": "Bengaluru",
    "sector": "Creative Industries",
    "lat": 12.9716,
    "lng": 77.5826
  },
  {
    "slug": "vodafone-idea",
    "name": "Vodafone Idea",
    "website": "https://www.myvi.in/",
    "hq": "Mumbai",
    "industry": "telecommunications industry",
    "founded": 2018,
    "score": 8,
    "city": "Mumbai",
    "sector": "Telecommunications",
    "lat": 19.079,
    "lng": 72.8687
  },
  {
    "slug": "shubhapallaba",
    "name": "Shubhapallaba",
    "website": "https://bangla.shubhapallaba.com",
    "hq": "Bhadrak",
    "industry": "publishing house",
    "founded": 2018,
    "score": 8,
    "city": "India",
    "sector": "Publishing House",
    "lat": 20.5997,
    "lng": 78.9569
  },
  {
    "slug": "shubhapallaba",
    "name": "Shubhapallaba",
    "website": "https://hindi.shubhapallaba.com",
    "hq": "Bhadrak",
    "industry": "publishing house",
    "founded": 2018,
    "score": 8,
    "city": "India",
    "sector": "Publishing House",
    "lat": 20.6027,
    "lng": 78.9599
  },
  {
    "slug": "shubhapallaba",
    "name": "Shubhapallaba",
    "website": "https://punjabi.shubhapallaba.com",
    "hq": "Bhadrak",
    "industry": "publishing house",
    "founded": 2018,
    "score": 8,
    "city": "India",
    "sector": "Publishing House",
    "lat": 20.6057,
    "lng": 78.9629
  },
  {
    "slug": "shubhapallaba",
    "name": "Shubhapallaba",
    "website": "https://sanskrit.shubhapallaba.com",
    "hq": "Bhadrak",
    "industry": "publishing house",
    "founded": 2018,
    "score": 8,
    "city": "India",
    "sector": "Publishing House",
    "lat": 20.6087,
    "lng": 78.9659
  },
  {
    "slug": "shubhapallaba",
    "name": "Shubhapallaba",
    "website": "https://shubhapallaba.in",
    "hq": "Bhadrak",
    "industry": "publishing house",
    "founded": 2018,
    "score": 8,
    "city": "India",
    "sector": "Publishing House",
    "lat": 20.6117,
    "lng": 78.9689
  },
  {
    "slug": "shubhapallaba",
    "name": "Shubhapallaba",
    "website": "https://telugu.shubhapallaba.com/",
    "hq": "Bhadrak",
    "industry": "publishing house",
    "founded": 2018,
    "score": 8,
    "city": "India",
    "sector": "Publishing House",
    "lat": 20.575699999999998,
    "lng": 78.9719
  },
  {
    "slug": "shubhapallaba",
    "name": "Shubhapallaba",
    "website": "https://www.shubhapallaba.com",
    "hq": "Bhadrak",
    "industry": "publishing house",
    "founded": 2018,
    "score": 8,
    "city": "India",
    "sector": "Publishing House",
    "lat": 20.578699999999998,
    "lng": 78.9749
  },
  {
    "slug": "copperking-india",
    "name": "CopperKing India",
    "website": "https://copperkingindia.com",
    "hq": "Thane district",
    "industry": "industrial manufacturing",
    "founded": 2018,
    "score": 8,
    "city": "Mumbai",
    "sector": "Industrial Manufacturing",
    "lat": 19.064,
    "lng": 72.8927
  },
  {
    "slug": "maxxgro-agrology-limited",
    "name": "MaxxGro Agrology Limited",
    "website": "https://maxxgro.in",
    "hq": "Gurgaon",
    "industry": "chemical industry",
    "founded": 2018,
    "score": 8,
    "city": "Delhi NCR",
    "sector": "Chemical",
    "lat": 28.450499999999998,
    "lng": 77.0446
  },
  {
    "slug": "the-web-people",
    "name": "The Web People",
    "website": "https://thewebpeople.in",
    "hq": "Puttur",
    "industry": "web design",
    "founded": 2017,
    "score": 8,
    "city": "India",
    "sector": "Web Design",
    "lat": 20.587699999999998,
    "lng": 78.9839
  },
  {
    "slug": "virtual-auditor",
    "name": "Virtual Auditor",
    "website": "https://virtualauditor.in/",
    "hq": "Chennai",
    "industry": "accounting",
    "founded": 2017,
    "score": 8,
    "city": "Chennai",
    "sector": "Accounting",
    "lat": 13.0797,
    "lng": 80.2947
  },
  {
    "slug": "codenex-solutions-llp",
    "name": "Codenex Solutions LLP",
    "website": "https://codenex.in/",
    "hq": "Kerala",
    "industry": "information technology",
    "founded": 2016,
    "score": 8,
    "city": "Kochi",
    "sector": "Information Technology",
    "lat": 9.9312,
    "lng": 76.2433
  },
  {
    "slug": "autumn-art",
    "name": "Autumn Art",
    "website": "https://www.autumnartbooks.com/",
    "hq": "Patiala",
    "industry": "publishing",
    "founded": 2016,
    "score": 8,
    "city": "India",
    "sector": "Publishing",
    "lat": 20.5967,
    "lng": 78.9419
  },
  {
    "slug": "scope-forex",
    "name": "Scope Forex",
    "website": "https://www.scopeforex.com",
    "hq": "Chennai",
    "industry": "foreign exchange market",
    "founded": 2015,
    "score": 8,
    "city": "Chennai",
    "sector": "Foreign Exchange Market",
    "lat": 13.088700000000001,
    "lng": 80.2527
  },
  {
    "slug": "society-for-agriculture-and-arid-ecology-research",
    "name": "Society for Agriculture and Arid Ecology Research",
    "website": "https://saaer.org.in",
    "hq": "Bikaner",
    "industry": "higher education",
    "founded": 2015,
    "score": 8,
    "city": "India",
    "sector": "Higher Education",
    "lat": 20.6027,
    "lng": 78.9479
  },
  {
    "slug": "vige-dr",
    "name": "Vige.Dr",
    "website": "https://vigevetlabs.xyz",
    "hq": "Puducherry",
    "industry": "veterinary medicine",
    "founded": 2014,
    "score": 8,
    "city": "India",
    "sector": "Veterinary Medicine",
    "lat": 20.6057,
    "lng": 78.9509
  },
  {
    "slug": "toppr",
    "name": "Toppr",
    "website": "https://www.toppr.com/",
    "hq": "Mumbai",
    "industry": "educational technology",
    "founded": 2013,
    "score": 8,
    "city": "Mumbai",
    "sector": "Educational Technology",
    "lat": 19.091,
    "lng": 72.8687
  },
  {
    "slug": "utazzo-holidays",
    "name": "Utazzo Holidays",
    "website": "https://utazzo.com",
    "hq": "Gurgaon",
    "industry": "tourism industry",
    "founded": 2012,
    "score": 8,
    "city": "Delhi NCR",
    "sector": "Tourism",
    "lat": 28.4775,
    "lng": 77.0206
  },
  {
    "slug": "utazzo-holidays",
    "name": "Utazzo Holidays",
    "website": "https://utazzoholidays.com/",
    "hq": "Gurgaon",
    "industry": "tourism industry",
    "founded": 2012,
    "score": 8,
    "city": "Delhi NCR",
    "sector": "Tourism",
    "lat": 28.441499999999998,
    "lng": 77.0236
  },
  {
    "slug": "s3-movies",
    "name": "S3 Movies",
    "website": "https://s3movies.com/",
    "hq": "Bhubaneswar",
    "industry": "entertainment",
    "founded": 2012,
    "score": 8,
    "city": "Bhubaneswar",
    "sector": "Entertainment",
    "lat": 20.2811,
    "lng": 85.8245
  },
  {
    "slug": "california-burrito",
    "name": "California Burrito",
    "website": "https://www.californiaburrito.in/",
    "hq": "Bengaluru",
    "industry": "fast food",
    "founded": 2012,
    "score": 8,
    "city": "Bengaluru",
    "sector": "Fast Food",
    "lat": 12.9596,
    "lng": 77.5976
  },
  {
    "slug": "ar-music-studios",
    "name": "AR Music Studios",
    "website": "https://armsrecordlabel.com",
    "hq": "Mumbai",
    "industry": "show business",
    "founded": 2012,
    "score": 8,
    "city": "Mumbai",
    "sector": "Show Business",
    "lat": 19.067,
    "lng": 72.8837
  },
  {
    "slug": "ar-music-studios",
    "name": "AR Music Studios",
    "website": "https://armusicstudios.com",
    "hq": "Mumbai",
    "industry": "show business",
    "founded": 2012,
    "score": 8,
    "city": "Mumbai",
    "sector": "Show Business",
    "lat": 19.07,
    "lng": 72.8867
  },
  {
    "slug": "akinik-publications",
    "name": "AkiNik Publications",
    "website": "https://www.akinik.com",
    "hq": "Delhi",
    "industry": "academic publishing",
    "founded": 2012,
    "score": 8,
    "city": "Delhi NCR",
    "sector": "Academic Publishing",
    "lat": 28.4565,
    "lng": 77.0386
  },
  {
    "slug": "qaina",
    "name": "Qaina",
    "website": "https://qaina.net/",
    "hq": "New Delhi",
    "industry": "website",
    "founded": 2011,
    "score": 8,
    "city": "Delhi NCR",
    "sector": "Website",
    "lat": 28.4595,
    "lng": 77.0416
  },
  {
    "slug": "advanced-fluro-private-limited",
    "name": "Advanced Fluro Private Limited",
    "website": "https://aftubes.com",
    "hq": "Vasai",
    "industry": "plastics industry",
    "founded": 2011,
    "score": 8,
    "city": "India",
    "sector": "Plastics",
    "lat": 20.5967,
    "lng": 78.9809
  },
  {
    "slug": "elion-technologies-and-consulting-private-limited",
    "name": "Elion Technologies and Consulting Private Limited",
    "website": "https://elion.co.in",
    "hq": "New Delhi",
    "industry": "management consulting industry",
    "founded": 2010,
    "score": 8,
    "city": "Delhi NCR",
    "sector": "Management Consulting",
    "lat": 28.4655,
    "lng": 77.0476
  },
  {
    "slug": "tamil-nadu-generation-and-distribution-corporation",
    "name": "Tamil Nadu Generation and Distribution Corporation",
    "website": "https://www.tangedco.org/",
    "hq": "Chennai",
    "industry": "electricity supply company",
    "founded": 2010,
    "score": 8,
    "city": "Chennai",
    "sector": "Electricity Supply",
    "lat": 13.091700000000001,
    "lng": 80.2947
  },
  {
    "slug": "mascot-press-india",
    "name": "Mascot Press India",
    "website": "https://www.mascotpress.in",
    "hq": "Delhi",
    "industry": "information technology",
    "founded": 2010,
    "score": 8,
    "city": "Delhi NCR",
    "sector": "Information Technology",
    "lat": 28.4715,
    "lng": 77.0026
  },
  {
    "slug": "digital-craft-pvt-ltd",
    "name": "Digital Craft Pvt Ltd",
    "website": "https://www.giftsco.in",
    "hq": "Bengaluru",
    "industry": "promotional merchandise",
    "founded": 2010,
    "score": 8,
    "city": "Bengaluru",
    "sector": "Promotional Merchandise",
    "lat": 12.986600000000001,
    "lng": 77.5736
  },
  {
    "slug": "star-studio18",
    "name": "Star Studio18",
    "website": "https://www.startv.com/about-us/movies/",
    "hq": "Mumbai",
    "industry": "cinematography",
    "founded": 2008,
    "score": 8,
    "city": "Mumbai",
    "sector": "Cinematography",
    "lat": 19.094,
    "lng": 72.8597
  },
  {
    "slug": "viacom18",
    "name": "Viacom18",
    "website": "https://www.viacom18.com/",
    "hq": "Mumbai",
    "industry": "television",
    "founded": 2007,
    "score": 8,
    "city": "Mumbai",
    "sector": "Television",
    "lat": 19.058,
    "lng": 72.8627
  },
  {
    "slug": "value-plus-retail-pvt-ltd",
    "name": "Value Plus Retail Pvt. Ltd.",
    "website": "https://www.valueplusretail.com",
    "hq": "Noida",
    "industry": "consumer electronics industry",
    "founded": 2007,
    "score": 8,
    "city": "Delhi NCR",
    "sector": "Consumer Electronics",
    "lat": 28.444499999999998,
    "lng": 77.0146
  },
  {
    "slug": "more",
    "name": "More",
    "website": "https://www.moreretail.in/",
    "hq": "Mumbai",
    "industry": "retail",
    "founded": 2007,
    "score": 8,
    "city": "Mumbai",
    "sector": "Retail",
    "lat": 19.064,
    "lng": 72.8687
  },
  {
    "slug": "indus-towers",
    "name": "Indus Towers",
    "website": "https://www.industowers.com/",
    "hq": "New Delhi",
    "industry": "telecommunications industry",
    "founded": 2007,
    "score": 8,
    "city": "Delhi NCR",
    "sector": "Telecommunications",
    "lat": 28.450499999999998,
    "lng": 77.0206
  },
  {
    "slug": "shriram-life-insurance",
    "name": "Shriram Life Insurance",
    "website": "https://www.shriramlife.com/",
    "hq": "Hyderabad",
    "industry": "life insurance",
    "founded": 2005,
    "score": 8,
    "city": "Hyderabad",
    "sector": "Life Insurance",
    "lat": 17.379,
    "lng": 78.4837
  },
  {
    "slug": "hearty-mart",
    "name": "Hearty Mart",
    "website": "https://heartymart.com",
    "hq": "Ahmedabad",
    "industry": "retail chain",
    "founded": 2004,
    "score": 8,
    "city": "Ahmedabad",
    "sector": "Retail Chain",
    "lat": 23.0195,
    "lng": 72.5714
  },
  {
    "slug": "behindwoods-com",
    "name": "behindwoods.com",
    "website": "https://www.behindwoods.com",
    "hq": "Chennai",
    "industry": "Tamil cinema",
    "founded": 2004,
    "score": 8,
    "city": "Chennai",
    "sector": "Tamil Cinema",
    "lat": 13.0827,
    "lng": 80.2737
  },
  {
    "slug": "lemon-tree-hotels",
    "name": "Lemon Tree Hotels",
    "website": "https://www.lemontreehotels.com/",
    "hq": "New Delhi",
    "industry": "hospitality industry",
    "founded": 2002,
    "score": 8,
    "city": "Delhi NCR",
    "sector": "Hospitality",
    "lat": 28.4625,
    "lng": 77.0326
  },
  {
    "slug": "reliance-infrastructure",
    "name": "Reliance Infrastructure",
    "website": "https://www.rinfra.com/",
    "hq": "Mumbai",
    "industry": "public utility",
    "founded": 2002,
    "score": 8,
    "city": "Mumbai",
    "sector": "Public Utility",
    "lat": 19.082,
    "lng": 72.8867
  },
  {
    "slug": "you-broadband",
    "name": "YOU Broadband",
    "website": "https://www.youbroadband.in/",
    "hq": "Andheri",
    "industry": "telecommunications industry",
    "founded": 2001,
    "score": 8,
    "city": "India",
    "sector": "Telecommunications",
    "lat": 20.6027,
    "lng": 78.9749
  },
  {
    "slug": "brihans-natural-products",
    "name": "Brihans Natural Products",
    "website": "https://brihansnatural.com/",
    "hq": "Pune",
    "industry": "cosmetics industry",
    "founded": 2000,
    "score": 8,
    "city": "Pune",
    "sector": "Cosmetics",
    "lat": 18.5324,
    "lng": 73.8717
  },
  {
    "slug": "inox-leisure-limited",
    "name": "INOX Leisure Limited",
    "website": "https://www.inoxmovies.com/",
    "hq": "Mumbai",
    "industry": "entertainment industry",
    "founded": 1999,
    "score": 8,
    "city": "Mumbai",
    "sector": "Entertainment",
    "lat": 19.091,
    "lng": 72.8957
  },
  {
    "slug": "pista-house",
    "name": "Pista House",
    "website": "https://www.pistahouse.in",
    "hq": "Moghlapura",
    "industry": "food industry",
    "founded": 1997,
    "score": 8,
    "city": "India",
    "sector": "Food",
    "lat": 20.6117,
    "lng": 78.9839
  },
  {
    "slug": "titagarh-rail-systems",
    "name": "Titagarh Rail Systems",
    "website": "https://titagarh.in/",
    "hq": "Kolkata",
    "industry": "rail transport",
    "founded": 1997,
    "score": 8,
    "city": "Kolkata",
    "sector": "Rail Transport",
    "lat": 22.5546,
    "lng": 88.3879
  },
  {
    "slug": "gateway-group-of-companies",
    "name": "Gateway Group of Companies",
    "website": "https://www.thegatewaycorp.com",
    "hq": "Ahmedabad",
    "industry": "IT service management",
    "founded": 1997,
    "score": 8,
    "city": "Ahmedabad",
    "sector": "IT Management",
    "lat": 23.0075,
    "lng": 72.5474
  },
  {
    "slug": "ramoji-film-city",
    "name": "Ramoji Film City",
    "website": "https://www.ramojifilmcity.com/",
    "hq": "Hyderabad",
    "industry": "film industry",
    "founded": 1996,
    "score": 8,
    "city": "Hyderabad",
    "sector": "Film",
    "lat": 17.373,
    "lng": 78.4657
  },
  {
    "slug": "au-small-finance-bank",
    "name": "AU Small Finance Bank",
    "website": "https://www.au.bank.in",
    "hq": "Jaipur",
    "industry": "financial services",
    "founded": 1996,
    "score": 8,
    "city": "Jaipur",
    "sector": "Financials",
    "lat": 26.9034,
    "lng": 75.7693
  },
  {
    "slug": "zoho-corporation",
    "name": "Zoho Corporation",
    "website": "https://www.zoho.com/",
    "hq": "India",
    "industry": "software industry",
    "founded": 1996,
    "score": 8,
    "city": "India",
    "sector": "Software",
    "lat": 20.587699999999998,
    "lng": 78.9479
  },
  {
    "slug": "zoho-corporation",
    "name": "Zoho Corporation",
    "website": "https://www.zohocorp.com/",
    "hq": "India",
    "industry": "software industry",
    "founded": 1996,
    "score": 8,
    "city": "India",
    "sector": "Software",
    "lat": 20.5907,
    "lng": 78.9509
  },
  {
    "slug": "adani-power",
    "name": "Adani Power",
    "website": "https://www.adanipower.com/",
    "hq": "Ahmedabad",
    "industry": "energy industry",
    "founded": 1996,
    "score": 8,
    "city": "Ahmedabad",
    "sector": "Energy",
    "lat": 23.0225,
    "lng": 72.5624
  },
  {
    "slug": "powertech-pollution-controls-pvt-ltd",
    "name": "Powertech Pollution Controls Pvt. Ltd",
    "website": "https://www.powertechindia.com/",
    "hq": "Bengaluru",
    "industry": "industrial equipment",
    "founded": 1996,
    "score": 8,
    "city": "Bengaluru",
    "sector": "Industrial Equipment",
    "lat": 12.9746,
    "lng": 77.5886
  },
  {
    "slug": "bfn-furniture",
    "name": "BFN Furniture",
    "website": "https://www.bfnfurniture.com/",
    "hq": "Haryana",
    "industry": "furniture industry",
    "founded": 1996,
    "score": 8,
    "city": "India",
    "sector": "Furniture",
    "lat": 20.5997,
    "lng": 78.9599
  },
  {
    "slug": "airports-authority-of-india",
    "name": "Airports Authority of India",
    "website": "https://www.aai.aero/",
    "hq": "New Delhi",
    "industry": "aviation",
    "founded": 1995,
    "score": 8,
    "city": "Delhi NCR",
    "sector": "Aviation",
    "lat": 28.4685,
    "lng": 77.0266
  },
  {
    "slug": "suzlon-energy",
    "name": "Suzlon Energy",
    "website": "https://www.suzlon.com/",
    "hq": "Pune",
    "industry": "renewable energy industry",
    "founded": 1995,
    "score": 8,
    "city": "Pune",
    "sector": "Renewable Energy",
    "lat": 18.5324,
    "lng": 73.8597
  },
  {
    "slug": "idea-cellular",
    "name": "Idea Cellular",
    "website": "https://www.ideacellular.com/",
    "hq": "Gandhinagar",
    "industry": "telecommunications industry",
    "founded": 1995,
    "score": 8,
    "city": "India",
    "sector": "Telecommunications",
    "lat": 20.6087,
    "lng": 78.9689
  },
  {
    "slug": "aekam-pharma-ltd",
    "name": "AEKAM PHARMA LTD",
    "website": "http://aekampharma.in/",
    "hq": "Ubha",
    "industry": "pharmaceutical industry",
    "founded": 2022,
    "score": 7,
    "city": "India",
    "sector": "Pharmaceutical",
    "lat": 20.6117,
    "lng": 78.9719
  },
  {
    "slug": "bhagirathi-films",
    "name": "Bhagirathi Films",
    "website": "http://www.bhagirathifilms.com/",
    "hq": "Mumbai",
    "industry": "entertainment",
    "founded": 2015,
    "score": 7,
    "city": "Mumbai",
    "sector": "Entertainment",
    "lat": 19.058,
    "lng": 72.8897
  },
  {
    "slug": "rhythm-boyz-entertainment",
    "name": "Rhythm Boyz Entertainment",
    "website": "http://www.rhythmboyzentertainment.com/",
    "hq": "Amritsar",
    "industry": "entertainment industry",
    "founded": 2013,
    "score": 7,
    "city": "India",
    "sector": "Entertainment",
    "lat": 20.578699999999998,
    "lng": 78.9779
  },
  {
    "slug": "utazzo-holidays",
    "name": "Utazzo Holidays",
    "website": "http://www.makeyoutravel.com/",
    "hq": "Gurgaon",
    "industry": "tourism industry",
    "founded": 2012,
    "score": 7,
    "city": "Delhi NCR",
    "sector": "Tourism",
    "lat": 28.447499999999998,
    "lng": 77.0446
  },
  {
    "slug": "friday-film-house",
    "name": "Friday Film House",
    "website": "http://www.fridayfilmhouse.com",
    "hq": "India",
    "industry": "film production",
    "founded": 2012,
    "score": 7,
    "city": "India",
    "sector": "Film Production",
    "lat": 20.584699999999998,
    "lng": 78.9839
  },
  {
    "slug": "bharatbenz",
    "name": "BharatBenz",
    "website": "http://www.bharatbenz.com/",
    "hq": "Chennai",
    "industry": "automotive industry",
    "founded": 2011,
    "score": 7,
    "city": "Chennai",
    "sector": "Automotive",
    "lat": 13.0767,
    "lng": 80.2947
  },
  {
    "slug": "sml-mahindra",
    "name": "SML Mahindra",
    "website": "http://smlisuzu.com/",
    "hq": "Chandigarh",
    "industry": "automotive industry",
    "founded": 2011,
    "score": 7,
    "city": "Chandigarh",
    "sector": "Automotive",
    "lat": 30.7303,
    "lng": 76.7554
  },
  {
    "slug": "phantom-films",
    "name": "Phantom Films",
    "website": "http://www.phantoms.in/",
    "hq": "Mumbai",
    "industry": "entertainment",
    "founded": 2011,
    "score": 7,
    "city": "Mumbai",
    "sector": "Entertainment",
    "lat": 19.076,
    "lng": 72.8567
  },
  {
    "slug": "hachette-india",
    "name": "Hachette India",
    "website": "http://hachetteindia.com/",
    "hq": "Gurgaon",
    "industry": "publishing",
    "founded": 2008,
    "score": 7,
    "city": "Delhi NCR",
    "sector": "Publishing",
    "lat": 28.4625,
    "lng": 77.0086
  },
  {
    "slug": "jio",
    "name": "Jio",
    "website": "http://www.jio.com",
    "hq": "Navi Mumbai",
    "industry": "mobile phone industry",
    "founded": 2007,
    "score": 7,
    "city": "Mumbai",
    "sector": "Mobile Phone",
    "lat": 19.082,
    "lng": 72.8627
  },
  {
    "slug": "omics-publishing-group",
    "name": "OMICS Publishing Group",
    "website": "http://www.omicsonline.org/",
    "hq": "Hyderabad",
    "industry": "predatory publishing",
    "founded": 2007,
    "score": 7,
    "city": "Hyderabad",
    "sector": "Predatory Publishing",
    "lat": 17.394000000000002,
    "lng": 78.4747
  },
  {
    "slug": "reliance-communications",
    "name": "Reliance Communications",
    "website": "http://www.rcom.co.in/",
    "hq": "Navi Mumbai",
    "industry": "telecommunications industry",
    "founded": 2004,
    "score": 7,
    "city": "Mumbai",
    "sector": "Telecommunications",
    "lat": 19.088,
    "lng": 72.8687
  },
  {
    "slug": "asia-motorworks",
    "name": "Asia MotorWorks",
    "website": "http://www.amwmotors.com/",
    "hq": "Mumbai",
    "industry": "automotive industry",
    "founded": 2002,
    "score": 7,
    "city": "Mumbai",
    "sector": "Automotive",
    "lat": 19.091,
    "lng": 72.8717
  },
  {
    "slug": "mylan-india",
    "name": "Mylan (India)",
    "website": "http://www.mylan.in",
    "hq": "Hyderabad",
    "industry": "pharmaceutical industry",
    "founded": 2001,
    "score": 7,
    "city": "Hyderabad",
    "sector": "Pharmaceutical",
    "lat": 17.403000000000002,
    "lng": 78.4837
  },
  {
    "slug": "spice-telecom",
    "name": "Spice Telecom",
    "website": "http://www.spiceindia.com/",
    "hq": "Mohali",
    "industry": "telecommunications industry",
    "founded": 1997,
    "score": 7,
    "city": "Chandigarh",
    "sector": "Telecommunications",
    "lat": 30.7153,
    "lng": 76.7794
  },
  {
    "slug": "utv-motion-pictures",
    "name": "UTV Motion Pictures",
    "website": "http://corporate.disney.in/disney-companies/studios",
    "hq": "Mumbai",
    "industry": "film production",
    "founded": 1996,
    "score": 7,
    "city": "Mumbai",
    "sector": "Film Production",
    "lat": 19.061,
    "lng": 72.8807
  },
  {
    "slug": "pooja-entertainment",
    "name": "Pooja Entertainment",
    "website": "http://poojaentertainmentandfilms.in/",
    "hq": "Mumbai",
    "industry": "entertainment",
    "founded": 1995,
    "score": 7,
    "city": "Mumbai",
    "sector": "Entertainment",
    "lat": 19.064,
    "lng": 72.8837
  },
  {
    "slug": "odyssey",
    "name": "Odyssey",
    "website": "http://www.odyssey.in",
    "hq": "Chennai",
    "industry": "retail",
    "founded": 1995,
    "score": 7,
    "city": "Chennai",
    "sector": "Retail",
    "lat": 13.0737,
    "lng": 80.2797
  },
  {
    "slug": "friends-communication",
    "name": "Friends Communication",
    "website": "https://www.friendscomm.in/",
    "hq": "Kolkata",
    "industry": "entertainment industry",
    "founded": null,
    "score": 7,
    "city": "Kolkata",
    "sector": "Entertainment",
    "lat": 22.5666,
    "lng": 88.3759
  }
] as const;

