export const directoryCompanies5 = [
  {
    "slug": "rajshri-productions",
    "name": "Rajshri Productions",
    "website": "http://www.rajshri.com/",
    "hq": "Mumbai",
    "industry": "company",
    "founded": null,
    "score": 12,
    "city": "Mumbai",
    "sector": "Other",
    "lat": 19.075833333,
    "lng": 72.8775,
    "source": "http://www.wikidata.org/entity/Q2723181"
  },
  {
    "slug": "smart-bazaar",
    "name": "Smart Bazaar",
    "website": "https://reliancesmartbazaar.com/",
    "hq": "Mumbai",
    "industry": "company",
    "founded": null,
    "score": 12,
    "city": "Mumbai",
    "sector": "Other",
    "lat": 19.075833333,
    "lng": 72.8775,
    "source": "http://www.wikidata.org/entity/Q3631008"
  },
  {
    "slug": "india-post",
    "name": "India Post",
    "website": "https://www.indiapost.gov.in",
    "hq": "New Delhi",
    "industry": "company",
    "founded": null,
    "score": 12,
    "city": "New Delhi",
    "sector": "Other",
    "lat": 28.613888888,
    "lng": 77.208888888,
    "source": "http://www.wikidata.org/entity/Q3519720"
  },
  {
    "slug": "indian-register-of-shipping",
    "name": "Indian Register of Shipping",
    "website": "http://www.irclass.org",
    "hq": "Powai",
    "industry": "company",
    "founded": null,
    "score": 12,
    "city": "Powai",
    "sector": "Other",
    "lat": 19.1176,
    "lng": 72.906,
    "source": "http://www.wikidata.org/entity/Q1661258"
  },
  {
    "slug": "tata-coffee",
    "name": "Tata Coffee",
    "website": "http://www.tatacoffee.com/",
    "hq": "Bengaluru",
    "industry": "company",
    "founded": null,
    "score": 12,
    "city": "Bengaluru",
    "sector": "Other",
    "lat": 12.9791198,
    "lng": 77.5912997,
    "source": "http://www.wikidata.org/entity/Q795209"
  },
  {
    "slug": "bhushan-steel",
    "name": "Bhushan Steel",
    "website": "http://www.bhushan-group.org/",
    "hq": "New Delhi",
    "industry": "company",
    "founded": null,
    "score": 12,
    "city": "New Delhi",
    "sector": "Other",
    "lat": 28.613888888,
    "lng": 77.208888888,
    "source": "http://www.wikidata.org/entity/Q962084"
  },
  {
    "slug": "maharashtra-state-road-transport-corporation",
    "name": "Maharashtra State Road Transport Corporation",
    "website": "http://www.msrtc.gov.in",
    "hq": "Mumbai Central railway station",
    "industry": "company",
    "founded": null,
    "score": 12,
    "city": "Mumbai Central railway station",
    "sector": "Other",
    "lat": 18.970667,
    "lng": 72.819383,
    "source": "http://www.wikidata.org/entity/Q3632293"
  },
  {
    "slug": "cesc-limited",
    "name": "CESC Limited",
    "website": "http://cesc.co.in/",
    "hq": "Kolkata",
    "industry": "company",
    "founded": null,
    "score": 12,
    "city": "Kolkata",
    "sector": "Other",
    "lat": 22.5675,
    "lng": 88.37,
    "source": "http://www.wikidata.org/entity/Q3348734"
  },
  {
    "slug": "food-corporation-of-india",
    "name": "Food Corporation of India",
    "website": "http://www.fci.gov.in/",
    "hq": "New Delhi",
    "industry": "company",
    "founded": null,
    "score": 12,
    "city": "New Delhi",
    "sector": "Other",
    "lat": 28.613888888,
    "lng": 77.208888888,
    "source": "http://www.wikidata.org/entity/Q3530263"
  },
  {
    "slug": "andhra-pradesh-housing-board",
    "name": "Andhra Pradesh Housing Board",
    "website": "http://www.aphb.gov.in",
    "hq": "Hyderabad",
    "industry": "company",
    "founded": null,
    "score": 12,
    "city": "Hyderabad",
    "sector": "Other",
    "lat": 17.361666666,
    "lng": 78.474722222,
    "source": "http://www.wikidata.org/entity/Q4754365"
  },
  {
    "slug": "apollo-hospitals",
    "name": "Apollo Hospitals",
    "website": "http://www.apollohospitals.com/",
    "hq": "Chennai",
    "industry": "company",
    "founded": null,
    "score": 12,
    "city": "Chennai",
    "sector": "Other",
    "lat": 13.0825,
    "lng": 80.275,
    "source": "http://www.wikidata.org/entity/Q4780321"
  },
  {
    "slug": "sahara-india-pariwar",
    "name": "Sahara India Pariwar",
    "website": "http://www.sahara.in/",
    "hq": "Samastipur",
    "industry": "company",
    "founded": null,
    "score": 12,
    "city": "Samastipur",
    "sector": "Other",
    "lat": 25.85,
    "lng": 85.766666666,
    "source": "http://www.wikidata.org/entity/Q1637622"
  },
  {
    "slug": "moser-baer",
    "name": "Moser Baer",
    "website": "http://moserbaer.com",
    "hq": "New Delhi",
    "industry": "company",
    "founded": null,
    "score": 12,
    "city": "New Delhi",
    "sector": "Other",
    "lat": 28.613888888,
    "lng": 77.208888888,
    "source": "http://www.wikidata.org/entity/Q474249"
  },
  {
    "slug": "bangalore-stock-exchange-ltd",
    "name": "Bangalore Stock Exchange Ltd",
    "website": "https://www.bgse.co.in",
    "hq": "Bengaluru",
    "industry": "company",
    "founded": null,
    "score": 12,
    "city": "Bengaluru",
    "sector": "Other",
    "lat": 12.9791198,
    "lng": 77.5912997,
    "source": "http://www.wikidata.org/entity/Q4077204"
  },
  {
    "slug": "reynolds-pens-india-pvt-ltd",
    "name": "Reynolds Pens India Pvt. Ltd.",
    "website": "https://www.reynolds-pens.com/",
    "hq": "Andheri",
    "industry": "company",
    "founded": null,
    "score": 12,
    "city": "Andheri",
    "sector": "Other",
    "lat": 19.119166666,
    "lng": 72.846944444,
    "source": "http://www.wikidata.org/entity/Q3428911"
  },
  {
    "slug": "kirloskar-group",
    "name": "Kirloskar Group",
    "website": "http://www.kirloskar.com",
    "hq": "Pune",
    "industry": "company",
    "founded": null,
    "score": 12,
    "city": "Pune",
    "sector": "Other",
    "lat": 18.521111111,
    "lng": 73.855277777,
    "source": "http://www.wikidata.org/entity/Q3634279"
  },
  {
    "slug": "bpl-group",
    "name": "BPL Group",
    "website": "http://www.bpl.in",
    "hq": "Bengaluru",
    "industry": "company",
    "founded": null,
    "score": 12,
    "city": "Bengaluru",
    "sector": "Other",
    "lat": 12.9791198,
    "lng": 77.5912997,
    "source": "http://www.wikidata.org/entity/Q1130521"
  },
  {
    "slug": "virgin-mobile-india",
    "name": "Virgin Mobile India",
    "website": "http://www.virginmobile.in/",
    "hq": "New Delhi",
    "industry": "company",
    "founded": null,
    "score": 12,
    "city": "New Delhi",
    "sector": "Other",
    "lat": 28.613888888,
    "lng": 77.208888888,
    "source": "http://www.wikidata.org/entity/Q3537762"
  },
  {
    "slug": "hindustan-shipyard",
    "name": "Hindustan Shipyard",
    "website": "https://www.hslvizag.in/",
    "hq": "Visakhapatnam",
    "industry": "company",
    "founded": null,
    "score": 12,
    "city": "Visakhapatnam",
    "sector": "Other",
    "lat": 17.693888888,
    "lng": 83.292222222,
    "source": "http://www.wikidata.org/entity/Q3523533"
  },
  {
    "slug": "the-walt-disney-company-india",
    "name": "The Walt Disney Company India",
    "website": "http://www.disney.in/",
    "hq": "Mumbai",
    "industry": "company",
    "founded": null,
    "score": 12,
    "city": "Mumbai",
    "sector": "Other",
    "lat": 19.075833333,
    "lng": 72.8775,
    "source": "http://www.wikidata.org/entity/Q3523273"
  },
  {
    "slug": "indian-railway-catering-and-tourism-corporation",
    "name": "Indian Railway Catering and Tourism Corporation",
    "website": "http://www.irctc.com/",
    "hq": "New Delhi",
    "industry": "company",
    "founded": null,
    "score": 12,
    "city": "New Delhi",
    "sector": "Other",
    "lat": 28.613888888,
    "lng": 77.208888888,
    "source": "http://www.wikidata.org/entity/Q2721464"
  },
  {
    "slug": "tata-chemicals",
    "name": "Tata Chemicals",
    "website": "https://www.tatachemicals.com/",
    "hq": "Mumbai",
    "industry": "company",
    "founded": null,
    "score": 12,
    "city": "Mumbai",
    "sector": "Other",
    "lat": 19.075833333,
    "lng": 72.8775,
    "source": "http://www.wikidata.org/entity/Q2331365"
  },
  {
    "slug": "vizag-steel",
    "name": "Vizag Steel",
    "website": "http://www.vizagsteel.com/",
    "hq": "Visakhapatnam",
    "industry": "company",
    "founded": null,
    "score": 12,
    "city": "Visakhapatnam",
    "sector": "Other",
    "lat": 17.693888888,
    "lng": 83.292222222,
    "source": "http://www.wikidata.org/entity/Q3633022"
  },
  {
    "slug": "loop-mobile",
    "name": "Loop Mobile",
    "website": "http://www.loopmobile.in/",
    "hq": "Mumbai",
    "industry": "company",
    "founded": null,
    "score": 12,
    "city": "Mumbai",
    "sector": "Other",
    "lat": 19.075833333,
    "lng": 72.8775,
    "source": "http://www.wikidata.org/entity/Q2328981"
  },
  {
    "slug": "singareni-collieries-company",
    "name": "Singareni Collieries Company",
    "website": "http://scclmines.com/",
    "hq": "Kothagudem",
    "industry": "company",
    "founded": null,
    "score": 12,
    "city": "Kothagudem",
    "sector": "Other",
    "lat": 17.55,
    "lng": 80.63,
    "source": "http://www.wikidata.org/entity/Q1144362"
  },
  {
    "slug": "tata-teleservices",
    "name": "Tata Teleservices",
    "website": "http://www.tataindicom.com",
    "hq": "Mumbai",
    "industry": "company",
    "founded": null,
    "score": 12,
    "city": "Mumbai",
    "sector": "Other",
    "lat": 19.075833333,
    "lng": 72.8775,
    "source": "http://www.wikidata.org/entity/Q2151534"
  },
  {
    "slug": "aircel",
    "name": "Aircel",
    "website": "http://www.aircel.com/",
    "hq": "Chennai",
    "industry": "company",
    "founded": null,
    "score": 12,
    "city": "Chennai",
    "sector": "Other",
    "lat": 13.0825,
    "lng": 80.275,
    "source": "http://www.wikidata.org/entity/Q3533647"
  },
  {
    "slug": "ntpc-limited",
    "name": "NTPC Limited",
    "website": "http://www.ntpc.co.in/",
    "hq": "New Delhi",
    "industry": "company",
    "founded": null,
    "score": 12,
    "city": "New Delhi",
    "sector": "Other",
    "lat": 28.613888888,
    "lng": 77.208888888,
    "source": "http://www.wikidata.org/entity/Q1967805"
  },
  {
    "slug": "godrej-group",
    "name": "Godrej Group",
    "website": "http://www.godrej.com/",
    "hq": "Mumbai",
    "industry": "company",
    "founded": null,
    "score": 12,
    "city": "Mumbai",
    "sector": "Other",
    "lat": 19.075833333,
    "lng": 72.8775,
    "source": "http://www.wikidata.org/entity/Q3764225"
  },
  {
    "slug": "trent-limited",
    "name": "Trent Limited",
    "website": "https://trentlimited.com/",
    "hq": "Mumbai",
    "industry": "company",
    "founded": null,
    "score": 12,
    "city": "Mumbai",
    "sector": "Other",
    "lat": 19.075833333,
    "lng": 72.8775,
    "source": "http://www.wikidata.org/entity/Q2336948"
  },
  {
    "slug": "tips-industries",
    "name": "Tips Industries",
    "website": "https://www.tips.in/",
    "hq": "Mumbai",
    "industry": "company",
    "founded": null,
    "score": 12,
    "city": "Mumbai",
    "sector": "Other",
    "lat": 19.075833333,
    "lng": 72.8775,
    "source": "http://www.wikidata.org/entity/Q3529282"
  },
  {
    "slug": "red-chillies-entertainment",
    "name": "Red Chillies Entertainment",
    "website": "https://www.redchillies.com/",
    "hq": "Mumbai",
    "industry": "company",
    "founded": null,
    "score": 12,
    "city": "Mumbai",
    "sector": "Other",
    "lat": 19.075833333,
    "lng": 72.8775,
    "source": "http://www.wikidata.org/entity/Q3349794"
  },
  {
    "slug": "beml-limited",
    "name": "BEML Limited",
    "website": "http://www.bemlindia.com/",
    "hq": "Bengaluru",
    "industry": "company",
    "founded": null,
    "score": 12,
    "city": "Bengaluru",
    "sector": "Other",
    "lat": 12.9791198,
    "lng": 77.5912997,
    "source": "http://www.wikidata.org/entity/Q2920445"
  },
  {
    "slug": "nippon-paint",
    "name": "Nippon Paint",
    "website": "http://www.nipponpaint-holdings.com/",
    "hq": "Chennai",
    "industry": "company",
    "founded": null,
    "score": 12,
    "city": "Chennai",
    "sector": "Other",
    "lat": 13.0825,
    "lng": 80.275,
    "source": "http://www.wikidata.org/entity/Q3661655"
  },
  {
    "slug": "tamilnad-mercantile-bank-limited",
    "name": "Tamilnad Mercantile Bank Limited",
    "website": "https://www.tmb.bank.in/",
    "hq": "Thoothukudi",
    "industry": "company",
    "founded": null,
    "score": 12,
    "city": "Thoothukudi",
    "sector": "Other",
    "lat": 8.783333333,
    "lng": 78.133333333,
    "source": "http://www.wikidata.org/entity/Q2044991"
  },
  {
    "slug": "raymond-group",
    "name": "Raymond Group",
    "website": "http://www.raymond.in/",
    "hq": "Mumbai",
    "industry": "company",
    "founded": null,
    "score": 12,
    "city": "Mumbai",
    "sector": "Other",
    "lat": 19.075833333,
    "lng": 72.8775,
    "source": "http://www.wikidata.org/entity/Q3537018"
  },
  {
    "slug": "aptech-ltd",
    "name": "Aptech Ltd",
    "website": "https://www.aptech-worldwide.com/",
    "hq": "Mumbai",
    "industry": "company",
    "founded": null,
    "score": 12,
    "city": "Mumbai",
    "sector": "Other",
    "lat": 19.075833333,
    "lng": 72.8775,
    "source": "http://www.wikidata.org/entity/Q4782213"
  },
  {
    "slug": "amigos-creations",
    "name": "Amigos Creations",
    "website": "http://www.amigoscreations.com/",
    "hq": "Hyderabad",
    "industry": "company",
    "founded": null,
    "score": 12,
    "city": "Hyderabad",
    "sector": "Other",
    "lat": 17.361666666,
    "lng": 78.474722222,
    "source": "http://www.wikidata.org/entity/Q4746239"
  },
  {
    "slug": "national-aluminium-company",
    "name": "National Aluminium Company",
    "website": "http://www.nalcoindia.com/home.html",
    "hq": "Bhubaneswar",
    "industry": "company",
    "founded": null,
    "score": 12,
    "city": "Bhubaneswar",
    "sector": "Other",
    "lat": 20.295,
    "lng": 85.825,
    "source": "http://www.wikidata.org/entity/Q3635746"
  },
  {
    "slug": "telenor-india",
    "name": "Telenor India",
    "website": "http://www.uninor.in",
    "hq": "Gurgaon",
    "industry": "company",
    "founded": null,
    "score": 12,
    "city": "Gurgaon",
    "sector": "Other",
    "lat": 28.466666666,
    "lng": 77.033333333,
    "source": "http://www.wikidata.org/entity/Q3358931"
  },
  {
    "slug": "iyogi",
    "name": "iYogi",
    "website": "http://www.iyogi.com/",
    "hq": "Gurgaon",
    "industry": "company",
    "founded": null,
    "score": 12,
    "city": "Gurgaon",
    "sector": "Other",
    "lat": 28.466666666,
    "lng": 77.033333333,
    "source": "http://www.wikidata.org/entity/Q1050649"
  },
  {
    "slug": "shapoorji-pallonji-group",
    "name": "Shapoorji Pallonji Group",
    "website": "http://www.shapoorjipallonji.com/",
    "hq": "Mumbai",
    "industry": "company",
    "founded": null,
    "score": 12,
    "city": "Mumbai",
    "sector": "Other",
    "lat": 19.075833333,
    "lng": 72.8775,
    "source": "http://www.wikidata.org/entity/Q2117643"
  },
  {
    "slug": "reliance-anil-dhirubhai-ambani-group",
    "name": "Reliance Anil Dhirubhai Ambani Group",
    "website": "https://www.reliancegroupindia.com",
    "hq": "Navi Mumbai",
    "industry": "company",
    "founded": null,
    "score": 12,
    "city": "Navi Mumbai",
    "sector": "Other",
    "lat": 19.03,
    "lng": 73.01,
    "source": "http://www.wikidata.org/entity/Q935150"
  },
  {
    "slug": "delhi-transport-corporation",
    "name": "Delhi Transport Corporation",
    "website": "https://dtc.delhi.gov.in/",
    "hq": "Delhi",
    "industry": "company",
    "founded": null,
    "score": 12,
    "city": "Delhi",
    "sector": "Other",
    "lat": 28.666666666,
    "lng": 77.216666666,
    "source": "http://www.wikidata.org/entity/Q3595653"
  },
  {
    "slug": "harris-mycfo",
    "name": "Harris myCFO",
    "website": "http://mycfo.in/",
    "hq": "Mumbai",
    "industry": "company",
    "founded": null,
    "score": 12,
    "city": "Mumbai",
    "sector": "Other",
    "lat": 19.075833333,
    "lng": 72.8775,
    "source": "http://www.wikidata.org/entity/Q4044681"
  },
  {
    "slug": "serum-institute-of-india",
    "name": "Serum Institute of India",
    "website": "http://www.seruminstitute.com/",
    "hq": "Pune",
    "industry": "company",
    "founded": null,
    "score": 12,
    "city": "Pune",
    "sector": "Other",
    "lat": 18.521111111,
    "lng": 73.855277777,
    "source": "http://www.wikidata.org/entity/Q3480001"
  },
  {
    "slug": "mazagon-dock-shipbuilders",
    "name": "Mazagon Dock Shipbuilders",
    "website": "http://www.mazagondock.gov.in/",
    "hq": "Mumbai",
    "industry": "company",
    "founded": null,
    "score": 12,
    "city": "Mumbai",
    "sector": "Other",
    "lat": 19.075833333,
    "lng": 72.8775,
    "source": "http://www.wikidata.org/entity/Q2956390"
  },
  {
    "slug": "den-networks",
    "name": "DEN Networks",
    "website": "https://dennetworks.com",
    "hq": "New Delhi",
    "industry": "company",
    "founded": null,
    "score": 12,
    "city": "New Delhi",
    "sector": "Other",
    "lat": 28.613888888,
    "lng": 77.208888888,
    "source": "http://www.wikidata.org/entity/Q4166322"
  },
  {
    "slug": "karnataka-state-road-transport-corporation",
    "name": "Karnataka State Road Transport Corporation",
    "website": "http://www.ksrtc.in/",
    "hq": "Bengaluru",
    "industry": "company",
    "founded": null,
    "score": 12,
    "city": "Bengaluru",
    "sector": "Other",
    "lat": 12.9791198,
    "lng": 77.5912997,
    "source": "http://www.wikidata.org/entity/Q3139469"
  },
  {
    "slug": "tikona-digital-networks",
    "name": "Tikona Digital Networks",
    "website": "http://tikona.in/",
    "hq": "Mumbai",
    "industry": "company",
    "founded": null,
    "score": 12,
    "city": "Mumbai",
    "sector": "Other",
    "lat": 19.075833333,
    "lng": 72.8775,
    "source": "http://www.wikidata.org/entity/Q4122006"
  },
  {
    "slug": "aditya-birla-group",
    "name": "Aditya Birla Group",
    "website": "http://www.adityabirla.com",
    "hq": "Mumbai",
    "industry": "company",
    "founded": null,
    "score": 12,
    "city": "Mumbai",
    "sector": "Other",
    "lat": 19.075833333,
    "lng": 72.8775,
    "source": "http://www.wikidata.org/entity/Q357600"
  },
  {
    "slug": "tata-starbucks",
    "name": "Tata Starbucks",
    "website": "https://gcspatiala.co.in/wp/best-cafes-in-patiala/",
    "hq": "Mumbai",
    "industry": "company",
    "founded": null,
    "score": 12,
    "city": "Mumbai",
    "sector": "Other",
    "lat": 19.075833333,
    "lng": 72.8775,
    "source": "http://www.wikidata.org/entity/Q765398"
  },
  {
    "slug": "tata-docomo",
    "name": "Tata DoCoMo",
    "website": "https://www.airtel.in",
    "hq": "New Delhi",
    "industry": "company",
    "founded": null,
    "score": 12,
    "city": "New Delhi",
    "sector": "Other",
    "lat": 28.613888888,
    "lng": 77.208888888,
    "source": "http://www.wikidata.org/entity/Q3518849"
  },
  {
    "slug": "bharat-sanchar-nigam-limited",
    "name": "Bharat Sanchar Nigam Limited",
    "website": "https://www.bsnl.co.in",
    "hq": "New Delhi",
    "industry": "company",
    "founded": null,
    "score": 12,
    "city": "New Delhi",
    "sector": "Other",
    "lat": 28.613888888,
    "lng": 77.208888888,
    "source": "http://www.wikidata.org/entity/Q278834"
  },
  {
    "slug": "tata-play",
    "name": "Tata Play",
    "website": "https://www.tataplay.com/",
    "hq": "New Delhi",
    "industry": "company",
    "founded": null,
    "score": 12,
    "city": "New Delhi",
    "sector": "Other",
    "lat": 28.613888888,
    "lng": 77.208888888,
    "source": "http://www.wikidata.org/entity/Q3518953"
  },
  {
    "slug": "aamir-khan-productions",
    "name": "Aamir Khan Productions",
    "website": "http://www.akpfilms.com/",
    "hq": "Mumbai",
    "industry": "company",
    "founded": null,
    "score": 12,
    "city": "Mumbai",
    "sector": "Other",
    "lat": 19.075833333,
    "lng": 72.8775,
    "source": "http://www.wikidata.org/entity/Q2820005"
  },
  {
    "slug": "essel-group",
    "name": "Essel Group",
    "website": "http://www.esselgroup.com/",
    "hq": "Mumbai",
    "industry": "company",
    "founded": null,
    "score": 12,
    "city": "Mumbai",
    "sector": "Other",
    "lat": 19.075833333,
    "lng": 72.8775,
    "source": "http://www.wikidata.org/entity/Q5399429"
  },
  {
    "slug": "cox-kings",
    "name": "Cox & Kings",
    "website": "http://www.coxandkings.com/",
    "hq": "Mumbai",
    "industry": "company",
    "founded": null,
    "score": 12,
    "city": "Mumbai",
    "sector": "Other",
    "lat": 19.075833333,
    "lng": 72.8775,
    "source": "http://www.wikidata.org/entity/Q5179871"
  },
  {
    "slug": "coromandel-international",
    "name": "Coromandel International",
    "website": "http://www.coromandel.biz",
    "hq": "Andhra Pradesh",
    "industry": "company",
    "founded": null,
    "score": 12,
    "city": "Andhra Pradesh",
    "sector": "Other",
    "lat": 16.85,
    "lng": 80.866666666,
    "source": "http://www.wikidata.org/entity/Q5172098"
  },
  {
    "slug": "centre-for-excellence-in-telecom-technology-and-management",
    "name": "Centre for Excellence in Telecom Technology and Management",
    "website": "http://cettm.mtnl.in/",
    "hq": "Powai",
    "industry": "company",
    "founded": null,
    "score": 12,
    "city": "Powai",
    "sector": "Other",
    "lat": 19.1176,
    "lng": 72.906,
    "source": "http://www.wikidata.org/entity/Q5062440"
  },
  {
    "slug": "nayara-energy",
    "name": "Nayara Energy",
    "website": "https://www.nayaraenergy.com",
    "hq": "Mumbai",
    "industry": "company",
    "founded": null,
    "score": 12,
    "city": "Mumbai",
    "sector": "Other",
    "lat": 19.075833333,
    "lng": 72.8775,
    "source": "http://www.wikidata.org/entity/Q5399377"
  },
  {
    "slug": "ideal-ice-cream",
    "name": "Ideal Ice Cream",
    "website": "http://www.idealicecream.in/",
    "hq": "Mangaluru",
    "industry": "company",
    "founded": null,
    "score": 12,
    "city": "Mangaluru",
    "sector": "Other",
    "lat": 12.871666666,
    "lng": 74.8425,
    "source": "http://www.wikidata.org/entity/Q5987957"
  },
  {
    "slug": "ballarpur-industries-limited",
    "name": "Ballarpur Industries Limited",
    "website": "https://biltpaper.in/",
    "hq": "Gurgaon",
    "industry": "company",
    "founded": null,
    "score": 12,
    "city": "Gurgaon",
    "sector": "Other",
    "lat": 28.466666666,
    "lng": 77.033333333,
    "source": "http://www.wikidata.org/entity/Q4851529"
  },
  {
    "slug": "jsw-group",
    "name": "JSW Group",
    "website": "http://www.jsw.in/",
    "hq": "Mumbai",
    "industry": "company",
    "founded": null,
    "score": 12,
    "city": "Mumbai",
    "sector": "Other",
    "lat": 19.075833333,
    "lng": 72.8775,
    "source": "http://www.wikidata.org/entity/Q6108973"
  },
  {
    "slug": "infibeam",
    "name": "Infibeam",
    "website": "http://www.infibeam.com/index.html",
    "hq": "Ahmedabad",
    "industry": "company",
    "founded": null,
    "score": 12,
    "city": "Ahmedabad",
    "sector": "Other",
    "lat": 23.021944444,
    "lng": 72.579722222,
    "source": "http://www.wikidata.org/entity/Q6029591"
  },
  {
    "slug": "green-pigeon-movies",
    "name": "Green Pigeon Movies",
    "website": "http://www.greenpigeonmoviesproduction.com/",
    "hq": "Kolkata",
    "industry": "company",
    "founded": null,
    "score": 12,
    "city": "Kolkata",
    "sector": "Other",
    "lat": 22.5675,
    "lng": 88.37,
    "source": "http://www.wikidata.org/entity/Q5603067"
  },
  {
    "slug": "jiostar",
    "name": "JioStar",
    "website": "https://www.startv.com/",
    "hq": "Mumbai",
    "industry": "company",
    "founded": null,
    "score": 12,
    "city": "Mumbai",
    "sector": "Other",
    "lat": 19.075833333,
    "lng": 72.8775,
    "source": "http://www.wikidata.org/entity/Q5919785"
  },
  {
    "slug": "heavy-alloy-penetrator-project",
    "name": "Heavy Alloy Penetrator Project",
    "website": "http://ofb.gov.in/",
    "hq": "Tiruchirappalli",
    "industry": "company",
    "founded": null,
    "score": 12,
    "city": "Tiruchirappalli",
    "sector": "Other",
    "lat": 10.826944444,
    "lng": 78.692777777,
    "source": "http://www.wikidata.org/entity/Q5695010"
  },
  {
    "slug": "mcx-stock-exchange",
    "name": "MCX Stock Exchange",
    "website": "https://www.nmce.com",
    "hq": "Ahmedabad",
    "industry": "company",
    "founded": null,
    "score": 12,
    "city": "Ahmedabad",
    "sector": "Other",
    "lat": 23.021944444,
    "lng": 72.579722222,
    "source": "http://www.wikidata.org/entity/Q6715038"
  },
  {
    "slug": "mavalli-tiffin-room",
    "name": "Mavalli Tiffin Room",
    "website": "http://www.mavallitiffinrooms.com",
    "hq": "Bengaluru",
    "industry": "company",
    "founded": null,
    "score": 12,
    "city": "Bengaluru",
    "sector": "Other",
    "lat": 12.9791198,
    "lng": 77.5912997,
    "source": "http://www.wikidata.org/entity/Q6794121"
  },
  {
    "slug": "comat-technologies",
    "name": "Comat Technologies",
    "website": "http://www.comat.com/",
    "hq": "Bengaluru",
    "industry": "company",
    "founded": null,
    "score": 12,
    "city": "Bengaluru",
    "sector": "Other",
    "lat": 12.9791198,
    "lng": 77.5912997,
    "source": "http://www.wikidata.org/entity/Q5150571"
  },
  {
    "slug": "ibm-india-private-limited",
    "name": "IBM India Private Limited",
    "website": "http://www.ibm.com/in/",
    "hq": "Bengaluru",
    "industry": "company",
    "founded": null,
    "score": 12,
    "city": "Bengaluru",
    "sector": "Other",
    "lat": 12.9791198,
    "lng": 77.5912997,
    "source": "http://www.wikidata.org/entity/Q5968851"
  },
  {
    "slug": "bmw-india",
    "name": "BMW India",
    "website": "http://www.bmw.in",
    "hq": "Gurgaon",
    "industry": "company",
    "founded": null,
    "score": 12,
    "city": "Gurgaon",
    "sector": "Other",
    "lat": 28.466666666,
    "lng": 77.033333333,
    "source": "http://www.wikidata.org/entity/Q4836047"
  },
  {
    "slug": "english-indian-clays",
    "name": "English Indian Clays",
    "website": "http://www.eicl.in/",
    "hq": "New Delhi",
    "industry": "company",
    "founded": null,
    "score": 12,
    "city": "New Delhi",
    "sector": "Other",
    "lat": 28.613888888,
    "lng": 77.208888888,
    "source": "http://www.wikidata.org/entity/Q5378292"
  },
  {
    "slug": "indian-drugs-and-pharmaceuticals",
    "name": "Indian Drugs and Pharmaceuticals",
    "website": "http://www.idpl.gov.in/home.html",
    "hq": "New Delhi",
    "industry": "company",
    "founded": null,
    "score": 12,
    "city": "New Delhi",
    "sector": "Other",
    "lat": 28.613888888,
    "lng": 77.208888888,
    "source": "http://www.wikidata.org/entity/Q6020244"
  },
  {
    "slug": "gleneagles-global-hospitals",
    "name": "Gleneagles Global Hospitals",
    "website": "https://www.gleneaglesglobalhospitals.com/",
    "hq": "Hyderabad",
    "industry": "company",
    "founded": null,
    "score": 12,
    "city": "Hyderabad",
    "sector": "Other",
    "lat": 17.361666666,
    "lng": 78.474722222,
    "source": "http://www.wikidata.org/entity/Q5570383"
  },
  {
    "slug": "bigflix",
    "name": "BIGFlix",
    "website": "http://www.bigflix.com",
    "hq": "Mumbai",
    "industry": "company",
    "founded": null,
    "score": 12,
    "city": "Mumbai",
    "sector": "Other",
    "lat": 19.075833333,
    "lng": 72.8775,
    "source": "http://www.wikidata.org/entity/Q4835663"
  },
  {
    "slug": "ferro-alloys-corporation",
    "name": "Ferro Alloys Corporation",
    "website": "http://www.facorgroup.in/",
    "hq": "Nagpur",
    "industry": "company",
    "founded": null,
    "score": 12,
    "city": "Nagpur",
    "sector": "Other",
    "lat": 21.149722222,
    "lng": 79.080555555,
    "source": "http://www.wikidata.org/entity/Q5445392"
  },
  {
    "slug": "brahma-vision-private-limited",
    "name": "Brahma Vision Private Limited",
    "website": "http://www.brahmavision.com",
    "hq": "Mumbai",
    "industry": "company",
    "founded": null,
    "score": 12,
    "city": "Mumbai",
    "sector": "Other",
    "lat": 19.075833333,
    "lng": 72.8775,
    "source": "http://www.wikidata.org/entity/Q4955509"
  },
  {
    "slug": "jabong-com",
    "name": "Jabong.com",
    "website": "http://www.jabong.com/",
    "hq": "Gurgaon",
    "industry": "company",
    "founded": null,
    "score": 12,
    "city": "Gurgaon",
    "sector": "Other",
    "lat": 28.466666666,
    "lng": 77.033333333,
    "source": "http://www.wikidata.org/entity/Q6110251"
  },
  {
    "slug": "central-organisation-for-railway-electrification",
    "name": "Central Organisation for Railway Electrification",
    "website": "http://www.core.indianrailways.gov.in/",
    "hq": "Prayagraj",
    "industry": "company",
    "founded": null,
    "score": 12,
    "city": "Prayagraj",
    "sector": "Other",
    "lat": 25.45,
    "lng": 81.85,
    "source": "http://www.wikidata.org/entity/Q4504133"
  },
  {
    "slug": "general-insurance-corporation-of-india",
    "name": "General Insurance Corporation of India",
    "website": "https://www.gicofindia.com/en",
    "hq": "Mumbai",
    "industry": "company",
    "founded": null,
    "score": 12,
    "city": "Mumbai",
    "sector": "Other",
    "lat": 19.075833333,
    "lng": 72.8775,
    "source": "http://www.wikidata.org/entity/Q5531960"
  },
  {
    "slug": "geometric-limited",
    "name": "Geometric Limited",
    "website": "http://www.geometricglobal.com/",
    "hq": "Mumbai",
    "industry": "company",
    "founded": null,
    "score": 12,
    "city": "Mumbai",
    "sector": "Other",
    "lat": 19.075833333,
    "lng": 72.8775,
    "source": "http://www.wikidata.org/entity/Q5535470"
  },
  {
    "slug": "imimobile",
    "name": "IMImobile",
    "website": "http://www.imimobile.com/",
    "hq": "Hyderabad",
    "industry": "company",
    "founded": null,
    "score": 12,
    "city": "Hyderabad",
    "sector": "Other",
    "lat": 17.361666666,
    "lng": 78.474722222,
    "source": "http://www.wikidata.org/entity/Q5972029"
  },
  {
    "slug": "durgapur-steel-plant",
    "name": "Durgapur Steel Plant",
    "website": "https://sail.co.in/en/plants/about-durgapur-steel-plant",
    "hq": "Durgapur",
    "industry": "company",
    "founded": null,
    "score": 12,
    "city": "Durgapur",
    "sector": "Other",
    "lat": 23.55,
    "lng": 87.32,
    "source": "http://www.wikidata.org/entity/Q5316422"
  },
  {
    "slug": "designtech-systems",
    "name": "DesignTech Systems",
    "website": "http://www.designtechsys.com/",
    "hq": "Pune",
    "industry": "company",
    "founded": null,
    "score": 12,
    "city": "Pune",
    "sector": "Other",
    "lat": 18.521111111,
    "lng": 73.855277777,
    "source": "http://www.wikidata.org/entity/Q5264246"
  },
  {
    "slug": "haryana-roadways",
    "name": "Haryana Roadways",
    "website": "http://hartrans.gov.in",
    "hq": "Chandigarh",
    "industry": "company",
    "founded": null,
    "score": 12,
    "city": "Chandigarh",
    "sector": "Other",
    "lat": 30.736388888,
    "lng": 76.788333333,
    "source": "http://www.wikidata.org/entity/Q5677960"
  },
  {
    "slug": "dhamra-port",
    "name": "Dhamra Port",
    "website": "https://www.adaniports.com/Ports-and-Terminals/dhamra-port",
    "hq": "Bhubaneswar",
    "industry": "company",
    "founded": null,
    "score": 12,
    "city": "Bhubaneswar",
    "sector": "Other",
    "lat": 20.295,
    "lng": 85.825,
    "source": "http://www.wikidata.org/entity/Q4886995"
  },
  {
    "slug": "hamdard-laboratories-india",
    "name": "Hamdard Laboratories (India)",
    "website": "http://www.hamdard.com",
    "hq": "New Delhi",
    "industry": "company",
    "founded": null,
    "score": 12,
    "city": "New Delhi",
    "sector": "Other",
    "lat": 28.613888888,
    "lng": 77.208888888,
    "source": "http://www.wikidata.org/entity/Q5644379"
  },
  {
    "slug": "gujarat-energy-transmission-corporation-limited",
    "name": "Gujarat Energy Transmission Corporation Limited",
    "website": "https://www.getcogujarat.com",
    "hq": "Vadodara",
    "industry": "company",
    "founded": null,
    "score": 12,
    "city": "Vadodara",
    "sector": "Other",
    "lat": 22.3,
    "lng": 73.2,
    "source": "http://www.wikidata.org/entity/Q5616984"
  },
  {
    "slug": "bharat-aluminium-company",
    "name": "Bharat Aluminium Company",
    "website": "http://www.balcoindia.com/",
    "hq": "New Delhi",
    "industry": "company",
    "founded": null,
    "score": 12,
    "city": "New Delhi",
    "sector": "Other",
    "lat": 28.613888888,
    "lng": 77.208888888,
    "source": "http://www.wikidata.org/entity/Q4901098"
  },
  {
    "slug": "63-moons-technologies",
    "name": "63 Moons Technologies",
    "website": "https://www.63moons.com/",
    "hq": "Chennai",
    "industry": "company",
    "founded": null,
    "score": 12,
    "city": "Chennai",
    "sector": "Other",
    "lat": 13.0825,
    "lng": 80.275,
    "source": "http://www.wikidata.org/entity/Q5449675"
  },
  {
    "slug": "melstar-information-technologies",
    "name": "Melstar Information Technologies",
    "website": "http://www.melstar.com/",
    "hq": "Mumbai",
    "industry": "company",
    "founded": null,
    "score": 12,
    "city": "Mumbai",
    "sector": "Other",
    "lat": 19.075833333,
    "lng": 72.8775,
    "source": "http://www.wikidata.org/entity/Q6813706"
  },
  {
    "slug": "kerala-tourism-development-corporation",
    "name": "Kerala Tourism Development Corporation",
    "website": "https://www.ktdc.com/",
    "hq": "Thiruvananthapuram",
    "industry": "company",
    "founded": null,
    "score": 12,
    "city": "Thiruvananthapuram",
    "sector": "Other",
    "lat": 8.4875,
    "lng": 76.9525,
    "source": "http://www.wikidata.org/entity/Q5015142"
  },
  {
    "slug": "cafe-coffee-day",
    "name": "Café Coffee Day",
    "website": "https://www.cafecoffeeday.com",
    "hq": "Bengaluru",
    "industry": "company",
    "founded": null,
    "score": 12,
    "city": "Bengaluru",
    "sector": "Other",
    "lat": 12.9791198,
    "lng": 77.5912997,
    "source": "http://www.wikidata.org/entity/Q5017235"
  },
  {
    "slug": "getvidya",
    "name": "GetVidya",
    "website": "http://www.getvidya.com",
    "hq": "Bengaluru",
    "industry": "company",
    "founded": null,
    "score": 12,
    "city": "Bengaluru",
    "sector": "Other",
    "lat": 12.9791198,
    "lng": 77.5912997,
    "source": "http://www.wikidata.org/entity/Q5553777"
  },
  {
    "slug": "avesthagen",
    "name": "Avesthagen",
    "website": "http://www.avesthagen.com/",
    "hq": "Bengaluru",
    "industry": "company",
    "founded": null,
    "score": 12,
    "city": "Bengaluru",
    "sector": "Other",
    "lat": 12.9791198,
    "lng": 77.5912997,
    "source": "http://www.wikidata.org/entity/Q4828428"
  },
  {
    "slug": "mullenlowe-lintas-group",
    "name": "MullenLowe Lintas Group",
    "website": "http://www.mullenlowelintas.in",
    "hq": "Mumbai",
    "industry": "company",
    "founded": null,
    "score": 12,
    "city": "Mumbai",
    "sector": "Other",
    "lat": 19.075833333,
    "lng": 72.8775,
    "source": "http://www.wikidata.org/entity/Q6693132"
  },
  {
    "slug": "electronics-corporation-of-tamil-nadu",
    "name": "Electronics Corporation of Tamil Nadu",
    "website": "http://www.elcot.in",
    "hq": "Chennai",
    "industry": "company",
    "founded": null,
    "score": 12,
    "city": "Chennai",
    "sector": "Other",
    "lat": 13.0825,
    "lng": 80.275,
    "source": "http://www.wikidata.org/entity/Q5358474"
  },
  {
    "slug": "icici-lombard",
    "name": "ICICI Lombard",
    "website": "https://www.icicilombard.com/",
    "hq": "Mumbai",
    "industry": "company",
    "founded": null,
    "score": 12,
    "city": "Mumbai",
    "sector": "Other",
    "lat": 19.075833333,
    "lng": 72.8775,
    "source": "http://www.wikidata.org/entity/Q5969591"
  },
  {
    "slug": "chinkara-motors",
    "name": "Chinkara Motors",
    "website": "http://www.chinkara.co.in/",
    "hq": "Mumbai",
    "industry": "company",
    "founded": null,
    "score": 12,
    "city": "Mumbai",
    "sector": "Other",
    "lat": 19.075833333,
    "lng": 72.8775,
    "source": "http://www.wikidata.org/entity/Q5101089"
  },
  {
    "slug": "delhi-university-community-radio",
    "name": "Delhi University Community Radio",
    "website": "http://ducr.du.ac.in/",
    "hq": "New Delhi",
    "industry": "company",
    "founded": null,
    "score": 12,
    "city": "New Delhi",
    "sector": "Other",
    "lat": 28.613888888,
    "lng": 77.208888888,
    "source": "http://www.wikidata.org/entity/Q5253832"
  },
  {
    "slug": "heavy-vehicles-factory",
    "name": "Heavy Vehicles Factory",
    "website": "http://ofb.gov.in/",
    "hq": "Chennai",
    "industry": "company",
    "founded": null,
    "score": 12,
    "city": "Chennai",
    "sector": "Other",
    "lat": 13.0825,
    "lng": 80.275,
    "source": "http://www.wikidata.org/entity/Q5695213"
  },
  {
    "slug": "driptech",
    "name": "Driptech",
    "website": "http://www.driptech.com/",
    "hq": "Pune",
    "industry": "company",
    "founded": null,
    "score": 12,
    "city": "Pune",
    "sector": "Other",
    "lat": 18.521111111,
    "lng": 73.855277777,
    "source": "http://www.wikidata.org/entity/Q5307789"
  },
  {
    "slug": "j-k-organisation",
    "name": "J. K. Organisation",
    "website": "http://jkorg.in/index.php",
    "hq": "New Delhi",
    "industry": "company",
    "founded": null,
    "score": 12,
    "city": "New Delhi",
    "sector": "Other",
    "lat": 28.613888888,
    "lng": 77.208888888,
    "source": "http://www.wikidata.org/entity/Q6106200"
  },
  {
    "slug": "crisil",
    "name": "CRISIL",
    "website": "http://www.crisil.com",
    "hq": "Mumbai",
    "industry": "company",
    "founded": null,
    "score": 12,
    "city": "Mumbai",
    "sector": "Other",
    "lat": 19.075833333,
    "lng": 72.8775,
    "source": "http://www.wikidata.org/entity/Q5013889"
  },
  {
    "slug": "liberty-shoes",
    "name": "Liberty Shoes",
    "website": "http://www.libertyshoes.com/",
    "hq": "Karnal",
    "industry": "company",
    "founded": null,
    "score": 12,
    "city": "Karnal",
    "sector": "Other",
    "lat": 29.69,
    "lng": 76.988333333,
    "source": "http://www.wikidata.org/entity/Q6541947"
  },
  {
    "slug": "bharatmatrimony",
    "name": "BharatMatrimony",
    "website": "http://www.bharatmatrimony.com",
    "hq": "Chennai",
    "industry": "company",
    "founded": null,
    "score": 12,
    "city": "Chennai",
    "sector": "Other",
    "lat": 13.0825,
    "lng": 80.275,
    "source": "http://www.wikidata.org/entity/Q4901092"
  },
  {
    "slug": "finolex-group",
    "name": "Finolex Group",
    "website": "http://www.finolex.com/",
    "hq": "Pune",
    "industry": "company",
    "founded": null,
    "score": 12,
    "city": "Pune",
    "sector": "Other",
    "lat": 18.521111111,
    "lng": 73.855277777,
    "source": "http://www.wikidata.org/entity/Q5450911"
  },
  {
    "slug": "bajaj-hindusthan-limited",
    "name": "Bajaj Hindusthan Limited",
    "website": "http://www.bajajhindusthan.com",
    "hq": "Mumbai",
    "industry": "company",
    "founded": null,
    "score": 12,
    "city": "Mumbai",
    "sector": "Other",
    "lat": 19.075833333,
    "lng": 72.8775,
    "source": "http://www.wikidata.org/entity/Q4848826"
  },
  {
    "slug": "gini-jony",
    "name": "Gini & Jony",
    "website": "http://www.giniandjony.com/",
    "hq": "Mumbai",
    "industry": "company",
    "founded": null,
    "score": 12,
    "city": "Mumbai",
    "sector": "Other",
    "lat": 19.075833333,
    "lng": 72.8775,
    "source": "http://www.wikidata.org/entity/Q5563120"
  },
  {
    "slug": "ixigo-com",
    "name": "IXiGO.com",
    "website": "http://www.ixigo.com",
    "hq": "Gurgaon",
    "industry": "company",
    "founded": null,
    "score": 12,
    "city": "Gurgaon",
    "sector": "Other",
    "lat": 28.466666666,
    "lng": 77.033333333,
    "source": "http://www.wikidata.org/entity/Q5975736"
  },
  {
    "slug": "carwale",
    "name": "CarWale",
    "website": "http://www.carwale.com",
    "hq": "Mumbai",
    "industry": "company",
    "founded": null,
    "score": 12,
    "city": "Mumbai",
    "sector": "Other",
    "lat": 19.075833333,
    "lng": 72.8775,
    "source": "http://www.wikidata.org/entity/Q5037195"
  },
  {
    "slug": "hll-lifecare-limited",
    "name": "HLL Lifecare Limited",
    "website": "http://www.lifecarehll.com/",
    "hq": "Thiruvananthapuram",
    "industry": "company",
    "founded": null,
    "score": 12,
    "city": "Thiruvananthapuram",
    "sector": "Other",
    "lat": 8.4875,
    "lng": 76.9525,
    "source": "http://www.wikidata.org/entity/Q5630211"
  },
  {
    "slug": "husk-power-systems",
    "name": "Husk Power Systems",
    "website": "http://www.huskpowersystems.com",
    "hq": "Patna",
    "industry": "company",
    "founded": null,
    "score": 12,
    "city": "Patna",
    "sector": "Other",
    "lat": 25.61,
    "lng": 85.141388888,
    "source": "http://www.wikidata.org/entity/Q5949332"
  },
  {
    "slug": "escorts-group",
    "name": "Escorts Group",
    "website": "http://www.escortsgroup.com/",
    "hq": "Faridabad",
    "industry": "company",
    "founded": null,
    "score": 12,
    "city": "Faridabad",
    "sector": "Other",
    "lat": 28.41124,
    "lng": 77.31316,
    "source": "http://www.wikidata.org/entity/Q5397409"
  },
  {
    "slug": "classmate-stationery",
    "name": "Classmate Stationery",
    "website": "http://www.classmatestationery.com",
    "hq": "Kolkata",
    "industry": "company",
    "founded": null,
    "score": 12,
    "city": "Kolkata",
    "sector": "Other",
    "lat": 22.5675,
    "lng": 88.37,
    "source": "http://www.wikidata.org/entity/Q5128448"
  },
  {
    "slug": "malabar-institute-of-medical-sciences",
    "name": "Malabar Institute of Medical Sciences",
    "website": "http://www.mimsindia.com/",
    "hq": "Kozhikode",
    "industry": "company",
    "founded": null,
    "score": 12,
    "city": "Kozhikode",
    "sector": "Other",
    "lat": 11.247777777,
    "lng": 75.780277777,
    "source": "http://www.wikidata.org/entity/Q6740744"
  },
  {
    "slug": "alok-industries",
    "name": "Alok Industries",
    "website": "http://www.alokind.com/",
    "hq": "Mumbai",
    "industry": "company",
    "founded": null,
    "score": 12,
    "city": "Mumbai",
    "sector": "Other",
    "lat": 19.075833333,
    "lng": 72.8775,
    "source": "http://www.wikidata.org/entity/Q4734296"
  },
  {
    "slug": "bsnl-mobile",
    "name": "BSNL Mobile",
    "website": "http://www.bsnl.co.in/opencms/bsnl/BSNL/services/mobile/index.html",
    "hq": "New Delhi",
    "industry": "company",
    "founded": null,
    "score": 12,
    "city": "New Delhi",
    "sector": "Other",
    "lat": 28.613888888,
    "lng": 77.208888888,
    "source": "http://www.wikidata.org/entity/Q4982025"
  }
] as const;
