export const directoryCompanies6 = [
  {
    "slug": "ishan-technologies",
    "name": "Ishan Technologies",
    "website": "https://ishantechnologies.com",
    "hq": "Ahmedabad",
    "industry": "information technology",
    "founded": null,
    "score": 15,
    "city": "Ahmedabad",
    "sector": "Software & IT",
    "lat": 23.021944444,
    "lng": 72.579722222,
    "source": "http://www.wikidata.org/entity/Q131938401"
  },
  {
    "slug": "pisignage",
    "name": "PiSignage",
    "website": "https://pisignage.com",
    "hq": "Bengaluru",
    "industry": "information technology",
    "founded": null,
    "score": 15,
    "city": "Bengaluru",
    "sector": "Software & IT",
    "lat": 12.9791198,
    "lng": 77.5912997,
    "source": "http://www.wikidata.org/entity/Q136645390"
  },
  {
    "slug": "webdail",
    "name": "Webdail",
    "website": "https://www.webdail.com",
    "hq": "Delhi",
    "industry": "information technology",
    "founded": null,
    "score": 15,
    "city": "Delhi",
    "sector": "Software & IT",
    "lat": 28.666666666,
    "lng": 77.216666666,
    "source": "http://www.wikidata.org/entity/Q135983802"
  },
  {
    "slug": "ops-singularity",
    "name": "Ops Singularity",
    "website": "https://www.opssingularity.com",
    "hq": "Indore",
    "industry": "information technology",
    "founded": null,
    "score": 15,
    "city": "Indore",
    "sector": "Software & IT",
    "lat": 22.718611111,
    "lng": 75.855,
    "source": "http://www.wikidata.org/entity/Q139964699"
  },
  {
    "slug": "team-computers",
    "name": "Team Computers",
    "website": "https://teamcomputers.com/",
    "hq": "New Delhi",
    "industry": "information technology",
    "founded": null,
    "score": 15,
    "city": "New Delhi",
    "sector": "Software & IT",
    "lat": 28.613888888,
    "lng": 77.208888888,
    "source": "http://www.wikidata.org/entity/Q141062025"
  },
  {
    "slug": "mythvortex-technologies-llp",
    "name": "MythVortex Technologies LLP",
    "website": "https://mythvortex.com",
    "hq": "Greater Noida",
    "industry": "information technology",
    "founded": null,
    "score": 15,
    "city": "Greater Noida",
    "sector": "Software & IT",
    "lat": 28.496152777,
    "lng": 77.536011111,
    "source": "http://www.wikidata.org/entity/Q140451428"
  },
  {
    "slug": "ziniosedge",
    "name": "ZiniosEdge",
    "website": "https://www.ziniosedge.com/",
    "hq": "Bengaluru",
    "industry": "information technology",
    "founded": null,
    "score": 15,
    "city": "Bengaluru",
    "sector": "Software & IT",
    "lat": 12.9791198,
    "lng": 77.5912997,
    "source": "http://www.wikidata.org/entity/Q139022686"
  },
  {
    "slug": "papasiddhi-technologies",
    "name": "PapaSiddhi Technologies",
    "website": "https://www.papasiddhi.com/",
    "hq": "Udaipur",
    "industry": "information technology",
    "founded": null,
    "score": 15,
    "city": "Udaipur",
    "sector": "Software & IT",
    "lat": 24.583333333,
    "lng": 73.683333333,
    "source": "http://www.wikidata.org/entity/Q140393335"
  },
  {
    "slug": "skyrhrg-technologies-systems",
    "name": "SKYRHRG Technologies Systems",
    "website": "https://skyrhrgts.com/",
    "hq": "Sagarpara",
    "industry": "information technology",
    "founded": null,
    "score": 15,
    "city": "Sagarpara",
    "sector": "Software & IT",
    "lat": 24.2386,
    "lng": 88.69779,
    "source": "http://www.wikidata.org/entity/Q139669788"
  },
  {
    "slug": "rategain",
    "name": "RateGain",
    "website": "https://rategain.com/",
    "hq": "Noida",
    "industry": "information technology",
    "founded": null,
    "score": 15,
    "city": "Noida",
    "sector": "Software & IT",
    "lat": 28.57,
    "lng": 77.32,
    "source": "http://www.wikidata.org/entity/Q79605259"
  },
  {
    "slug": "nextologic-solutions",
    "name": "Nextologic Solutions",
    "website": "https://nextologic.com",
    "hq": "Coimbatore",
    "industry": "information technology",
    "founded": null,
    "score": 15,
    "city": "Coimbatore",
    "sector": "Software & IT",
    "lat": 11.000833333,
    "lng": 76.963333333,
    "source": "http://www.wikidata.org/entity/Q134081030"
  },
  {
    "slug": "rinuzmart",
    "name": "RinuzMart",
    "website": "https://rinuzmart.in",
    "hq": "Samdari",
    "industry": "information technology",
    "founded": null,
    "score": 15,
    "city": "Samdari",
    "sector": "Software & IT",
    "lat": 25.816666666,
    "lng": 72.583055555,
    "source": "http://www.wikidata.org/entity/Q135117282"
  },
  {
    "slug": "mindstix-software-labs",
    "name": "Mindstix Software Labs",
    "website": "https://www.mindstix.com/",
    "hq": "Pune",
    "industry": "information technology",
    "founded": null,
    "score": 15,
    "city": "Pune",
    "sector": "Software & IT",
    "lat": 18.521111111,
    "lng": 73.855277777,
    "source": "http://www.wikidata.org/entity/Q137637998"
  },
  {
    "slug": "godigi-infotech",
    "name": "GoDigi InfoTech",
    "website": "https://www.godigiinfotech.com",
    "hq": "Pune",
    "industry": "information technology",
    "founded": null,
    "score": 15,
    "city": "Pune",
    "sector": "Software & IT",
    "lat": 18.521111111,
    "lng": 73.855277777,
    "source": "http://www.wikidata.org/entity/Q134611470"
  },
  {
    "slug": "mastek",
    "name": "Mastek",
    "website": "http://www.mastek.com",
    "hq": "Mumbai",
    "industry": "information technology",
    "founded": null,
    "score": 15,
    "city": "Mumbai",
    "sector": "Software & IT",
    "lat": 19.075833333,
    "lng": 72.8775,
    "source": "http://www.wikidata.org/entity/Q17068495"
  },
  {
    "slug": "classic-network-and-computers",
    "name": "Classic Network and Computers",
    "website": "https://www.cnc-system.com/",
    "hq": "West Patel Nagar",
    "industry": "information technology",
    "founded": null,
    "score": 15,
    "city": "West Patel Nagar",
    "sector": "Software & IT",
    "lat": 28.6505,
    "lng": 77.1691,
    "source": "http://www.wikidata.org/entity/Q140312582"
  },
  {
    "slug": "zucol-services-private-limited",
    "name": "Zucol Services Private Limited",
    "website": "https://zucol.in/",
    "hq": "Gurgaon",
    "industry": "information technology",
    "founded": null,
    "score": 15,
    "city": "Gurgaon",
    "sector": "Software & IT",
    "lat": 28.466666666,
    "lng": 77.033333333,
    "source": "http://www.wikidata.org/entity/Q137298883"
  },
  {
    "slug": "microland",
    "name": "Microland",
    "website": "http://www.microland.com",
    "hq": "Bengaluru",
    "industry": "information technology",
    "founded": null,
    "score": 15,
    "city": "Bengaluru",
    "sector": "Software & IT",
    "lat": 12.9791198,
    "lng": 77.5912997,
    "source": "http://www.wikidata.org/entity/Q6839605"
  },
  {
    "slug": "fluentgrid",
    "name": "Fluentgrid",
    "website": "https://www.fluentgrid.com/",
    "hq": "Visakhapatnam",
    "industry": "information technology",
    "founded": null,
    "score": 15,
    "city": "Visakhapatnam",
    "sector": "Software & IT",
    "lat": 17.693888888,
    "lng": 83.292222222,
    "source": "http://www.wikidata.org/entity/Q115815868"
  },
  {
    "slug": "webvillee-technology-private-limited",
    "name": "Webvillee Technology Private Limited",
    "website": "https://webvillee.com/",
    "hq": "Indore",
    "industry": "information technology",
    "founded": null,
    "score": 15,
    "city": "Indore",
    "sector": "Software & IT",
    "lat": 22.718611111,
    "lng": 75.855,
    "source": "http://www.wikidata.org/entity/Q141125354"
  },
  {
    "slug": "digi-friction",
    "name": "Digi Friction",
    "website": "https://digifriction.com",
    "hq": "Bareilly",
    "industry": "information technology",
    "founded": null,
    "score": 15,
    "city": "Bareilly",
    "sector": "Software & IT",
    "lat": 28.364,
    "lng": 79.415,
    "source": "http://www.wikidata.org/entity/Q121140209"
  },
  {
    "slug": "hidden-brains-infotech-pvt-ltd",
    "name": "Hidden Brains Infotech Pvt. Ltd.",
    "website": "https://www.hiddenbrains.com",
    "hq": "Ahmedabad",
    "industry": "information technology",
    "founded": null,
    "score": 15,
    "city": "Ahmedabad",
    "sector": "Software & IT",
    "lat": 23.021944444,
    "lng": 72.579722222,
    "source": "http://www.wikidata.org/entity/Q138598171"
  },
  {
    "slug": "caerulean-bytechains-private-limited",
    "name": "Caerulean Bytechains Private Limited",
    "website": "https://cerulea.io",
    "hq": "Hyderabad",
    "industry": "information technology",
    "founded": null,
    "score": 15,
    "city": "Hyderabad",
    "sector": "Software & IT",
    "lat": 17.361666666,
    "lng": 78.474722222,
    "source": "http://www.wikidata.org/entity/Q140522504"
  },
  {
    "slug": "mind-it-systems",
    "name": "Mind IT Systems",
    "website": "https://minditsystems.com/",
    "hq": "New Delhi",
    "industry": "information technology",
    "founded": null,
    "score": 15,
    "city": "New Delhi",
    "sector": "Software & IT",
    "lat": 28.613888888,
    "lng": 77.208888888,
    "source": "http://www.wikidata.org/entity/Q140420262"
  },
  {
    "slug": "ventron",
    "name": "Ventron",
    "website": "https://ventron.in",
    "hq": "Hisar",
    "industry": "software industry",
    "founded": null,
    "score": 15,
    "city": "Hisar",
    "sector": "Software & IT",
    "lat": 29.148888888,
    "lng": 75.736666666,
    "source": "http://www.wikidata.org/entity/Q140739193"
  },
  {
    "slug": "skilwi",
    "name": "SKILWI",
    "website": "https://skilwi.ai",
    "hq": "Bengaluru",
    "industry": "software industry",
    "founded": null,
    "score": 15,
    "city": "Bengaluru",
    "sector": "Software & IT",
    "lat": 12.9791198,
    "lng": 77.5912997,
    "source": "http://www.wikidata.org/entity/Q140072850"
  },
  {
    "slug": "agdira",
    "name": "AGDIRA",
    "website": "https://www.agdira.com",
    "hq": "Erode",
    "industry": "software industry",
    "founded": null,
    "score": 15,
    "city": "Erode",
    "sector": "Software & IT",
    "lat": 11.3428,
    "lng": 77.72741,
    "source": "http://www.wikidata.org/entity/Q140361744"
  },
  {
    "slug": "haemologix",
    "name": "Haemologix",
    "website": "https://www.haemologix.in/",
    "hq": "Howrah",
    "industry": "software industry",
    "founded": null,
    "score": 15,
    "city": "Howrah",
    "sector": "Software & IT",
    "lat": 22.58,
    "lng": 88.329444444,
    "source": "http://www.wikidata.org/entity/Q141102668"
  },
  {
    "slug": "image2any",
    "name": "Image2Any",
    "website": "https://image2any.com",
    "hq": "Kolkata",
    "industry": "software industry",
    "founded": null,
    "score": 15,
    "city": "Kolkata",
    "sector": "Software & IT",
    "lat": 22.5675,
    "lng": 88.37,
    "source": "http://www.wikidata.org/entity/Q138412806"
  },
  {
    "slug": "novynix-technologies",
    "name": "Novynix Technologies",
    "website": "https://novynix.com",
    "hq": "Chennai",
    "industry": "software industry",
    "founded": null,
    "score": 15,
    "city": "Chennai",
    "sector": "Software & IT",
    "lat": 13.0825,
    "lng": 80.275,
    "source": "http://www.wikidata.org/entity/Q140346310"
  },
  {
    "slug": "opsenova",
    "name": "Opsenova",
    "website": "https://opsenova.com",
    "hq": "Guwahati",
    "industry": "software industry",
    "founded": null,
    "score": 15,
    "city": "Guwahati",
    "sector": "Software & IT",
    "lat": 26.1805876,
    "lng": 91.750238,
    "source": "http://www.wikidata.org/entity/Q140770859"
  },
  {
    "slug": "recruitkar",
    "name": "RecruitKar",
    "website": "https://recruitkar.com",
    "hq": "Indore district",
    "industry": "software industry",
    "founded": null,
    "score": 15,
    "city": "Indore district",
    "sector": "Software & IT",
    "lat": 22.666666666,
    "lng": 75.75,
    "source": "http://www.wikidata.org/entity/Q140360354"
  },
  {
    "slug": "tech-serve-solutions",
    "name": "Tech Serve Solutions",
    "website": "https://www.techservesolutions.in",
    "hq": "Ahmedabad",
    "industry": "software development",
    "founded": null,
    "score": 15,
    "city": "Ahmedabad",
    "sector": "Software & IT",
    "lat": 23.021944444,
    "lng": 72.579722222,
    "source": "http://www.wikidata.org/entity/Q140157557"
  },
  {
    "slug": "clinikpe",
    "name": "ClinikPe",
    "website": "https://www.clinikpe.com",
    "hq": "Kolkata",
    "industry": "software industry",
    "founded": null,
    "score": 15,
    "city": "Kolkata",
    "sector": "Software & IT",
    "lat": 22.5675,
    "lng": 88.37,
    "source": "http://www.wikidata.org/entity/Q139801637"
  },
  {
    "slug": "strand-life-sciences",
    "name": "Strand Life Sciences",
    "website": "http://www.strandls.com/",
    "hq": "Bengaluru",
    "industry": "software industry",
    "founded": null,
    "score": 15,
    "city": "Bengaluru",
    "sector": "Software & IT",
    "lat": 12.9791198,
    "lng": 77.5912997,
    "source": "http://www.wikidata.org/entity/Q7621233"
  },
  {
    "slug": "setups-works",
    "name": "Setups Works",
    "website": "https://setups.works",
    "hq": "Elavur",
    "industry": "software industry",
    "founded": null,
    "score": 15,
    "city": "Elavur",
    "sector": "Software & IT",
    "lat": 13.4628135,
    "lng": 80.1191296,
    "source": "http://www.wikidata.org/entity/Q140500419"
  },
  {
    "slug": "studiokrew",
    "name": "StudioKrew",
    "website": "https://studiokrew.com",
    "hq": "Delhi",
    "industry": "software development",
    "founded": null,
    "score": 15,
    "city": "Delhi",
    "sector": "Software & IT",
    "lat": 28.666666666,
    "lng": 77.216666666,
    "source": "http://www.wikidata.org/entity/Q138748890"
  },
  {
    "slug": "foren-exports",
    "name": "Foren Exports",
    "website": "https://www.forenexport.com",
    "hq": "Malda",
    "industry": "software industry",
    "founded": null,
    "score": 15,
    "city": "Malda",
    "sector": "Software & IT",
    "lat": 25.004444444,
    "lng": 88.145833333,
    "source": "http://www.wikidata.org/entity/Q109308636"
  },
  {
    "slug": "cybrosys-technologies",
    "name": "Cybrosys Technologies",
    "website": "https://www.cybrosys.com",
    "hq": "Kozhikode",
    "industry": "software industry",
    "founded": null,
    "score": 15,
    "city": "Kozhikode",
    "sector": "Software & IT",
    "lat": 11.247777777,
    "lng": 75.780277777,
    "source": "http://www.wikidata.org/entity/Q140376710"
  },
  {
    "slug": "innblockchain-pvt-ltd",
    "name": "Innblockchain Pvt Ltd",
    "website": "https://www.innblockchain.com/",
    "hq": "Madurai",
    "industry": "software industry",
    "founded": null,
    "score": 15,
    "city": "Madurai",
    "sector": "Software & IT",
    "lat": 9.919661111,
    "lng": 78.119394444,
    "source": "http://www.wikidata.org/entity/Q140996551"
  },
  {
    "slug": "zartek-technologies",
    "name": "Zartek Technologies",
    "website": "https://www.zartek.in/",
    "hq": "Kochi",
    "industry": "software development",
    "founded": null,
    "score": 15,
    "city": "Kochi",
    "sector": "Software & IT",
    "lat": 9.966666666,
    "lng": 76.283333333,
    "source": "http://www.wikidata.org/entity/Q138846726"
  },
  {
    "slug": "chaitanya-digital-solutions",
    "name": "Chaitanya Digital Solutions",
    "website": "https://chaitanyadigitalsolutions.com/",
    "hq": "Badlapur",
    "industry": "software development",
    "founded": null,
    "score": 15,
    "city": "Badlapur",
    "sector": "Software & IT",
    "lat": 19.15,
    "lng": 73.262,
    "source": "http://www.wikidata.org/entity/Q138846024"
  },
  {
    "slug": "trioangle-technologies",
    "name": "Trioangle Technologies",
    "website": "https://www.trioangle.com/",
    "hq": "Madurai",
    "industry": "software industry",
    "founded": null,
    "score": 15,
    "city": "Madurai",
    "sector": "Software & IT",
    "lat": 9.919661111,
    "lng": 78.119394444,
    "source": "http://www.wikidata.org/entity/Q140995870"
  },
  {
    "slug": "adios",
    "name": "AdiOS",
    "website": "https://www.adiosplat.io",
    "hq": "Hyderabad",
    "industry": "software industry",
    "founded": null,
    "score": 15,
    "city": "Hyderabad",
    "sector": "Software & IT",
    "lat": 17.361666666,
    "lng": 78.474722222,
    "source": "http://www.wikidata.org/entity/Q139501266"
  },
  {
    "slug": "rebillion",
    "name": "ReBillion",
    "website": "https://rebillion.ai/",
    "hq": "Bengaluru",
    "industry": "software industry",
    "founded": null,
    "score": 15,
    "city": "Bengaluru",
    "sector": "Software & IT",
    "lat": 12.9791198,
    "lng": 77.5912997,
    "source": "http://www.wikidata.org/entity/Q141038552"
  },
  {
    "slug": "veeruby-technologies",
    "name": "VeeRuby Technologies",
    "website": "https://veeruby.com",
    "hq": "Mysuru district",
    "industry": "software industry",
    "founded": null,
    "score": 15,
    "city": "Mysuru district",
    "sector": "Software & IT",
    "lat": 12.21,
    "lng": 76.49,
    "source": "http://www.wikidata.org/entity/Q139827707"
  },
  {
    "slug": "sendmsg-io",
    "name": "sendmsg.io",
    "website": "https://sendmsg.io",
    "hq": "Mumbai",
    "industry": "software industry",
    "founded": null,
    "score": 15,
    "city": "Mumbai",
    "sector": "Software & IT",
    "lat": 19.075833333,
    "lng": 72.8775,
    "source": "http://www.wikidata.org/entity/Q140043722"
  },
  {
    "slug": "groovy-web",
    "name": "Groovy Web",
    "website": "https://www.groovyweb.co",
    "hq": "Nadiad",
    "industry": "software development",
    "founded": null,
    "score": 15,
    "city": "Nadiad",
    "sector": "Software & IT",
    "lat": 22.7,
    "lng": 72.87,
    "source": "http://www.wikidata.org/entity/Q139548295"
  },
  {
    "slug": "ansi-bytecode-llp",
    "name": "Ansi ByteCode LLP",
    "website": "https://ansibytecode.com/",
    "hq": "Ahmedabad",
    "industry": "software development",
    "founded": null,
    "score": 15,
    "city": "Ahmedabad",
    "sector": "Software & IT",
    "lat": 23.021944444,
    "lng": 72.579722222,
    "source": "http://www.wikidata.org/entity/Q140642526"
  },
  {
    "slug": "sivaro-softwares-llp",
    "name": "SIVARO SOFTWARES LLP",
    "website": "https://sivaro.in",
    "hq": "Delhi",
    "industry": "software industry",
    "founded": null,
    "score": 15,
    "city": "Delhi",
    "sector": "Software & IT",
    "lat": 28.666666666,
    "lng": 77.216666666,
    "source": "http://www.wikidata.org/entity/Q139780694"
  },
  {
    "slug": "hiqbyte",
    "name": "HiQByte",
    "website": "https://www.hiqbyte.in/",
    "hq": "New Delhi",
    "industry": "software industry",
    "founded": null,
    "score": 15,
    "city": "New Delhi",
    "sector": "Software & IT",
    "lat": 28.613888888,
    "lng": 77.208888888,
    "source": "http://www.wikidata.org/entity/Q140446659"
  },
  {
    "slug": "perk-payroll",
    "name": "Perk Payroll",
    "website": "https://www.perkpayroll.com/",
    "hq": "Hyderabad",
    "industry": "software industry",
    "founded": null,
    "score": 15,
    "city": "Hyderabad",
    "sector": "Software & IT",
    "lat": 17.361666666,
    "lng": 78.474722222,
    "source": "http://www.wikidata.org/entity/Q44677928"
  },
  {
    "slug": "dynamisch-inc",
    "name": "Dynamisch Inc",
    "website": "https://dynamisch.co/",
    "hq": "Pune",
    "industry": "software development",
    "founded": null,
    "score": 15,
    "city": "Pune",
    "sector": "Software & IT",
    "lat": 18.521111111,
    "lng": 73.855277777,
    "source": "http://www.wikidata.org/entity/Q139709756"
  },
  {
    "slug": "mindlyft",
    "name": "Mindlyft",
    "website": "https://mindlyft.in",
    "hq": "Bengaluru",
    "industry": "software industry",
    "founded": null,
    "score": 15,
    "city": "Bengaluru",
    "sector": "Software & IT",
    "lat": 12.9791198,
    "lng": 77.5912997,
    "source": "http://www.wikidata.org/entity/Q141133821"
  },
  {
    "slug": "brio-technologies",
    "name": "Brio Technologies",
    "website": "https://www.brio.co.in",
    "hq": "Hyderabad",
    "industry": "software industry",
    "founded": null,
    "score": 15,
    "city": "Hyderabad",
    "sector": "Software & IT",
    "lat": 17.361666666,
    "lng": 78.474722222,
    "source": "http://www.wikidata.org/entity/Q44686004"
  },
  {
    "slug": "ecorpit",
    "name": "eCorpIT",
    "website": "https://ecorpit.com",
    "hq": "Gurgaon",
    "industry": "software development",
    "founded": null,
    "score": 15,
    "city": "Gurgaon",
    "sector": "Software & IT",
    "lat": 28.466666666,
    "lng": 77.033333333,
    "source": "http://www.wikidata.org/entity/Q140068951"
  },
  {
    "slug": "sourcebae",
    "name": "Sourcebae",
    "website": "https://sourcebae.com",
    "hq": "Indore",
    "industry": "software industry",
    "founded": null,
    "score": 15,
    "city": "Indore",
    "sector": "Software & IT",
    "lat": 22.718611111,
    "lng": 75.855,
    "source": "http://www.wikidata.org/entity/Q138682178"
  },
  {
    "slug": "erp24k",
    "name": "ERP24K",
    "website": "https://www.erp24k.com/",
    "hq": "Hyderabad",
    "industry": "software industry",
    "founded": null,
    "score": 15,
    "city": "Hyderabad",
    "sector": "Software & IT",
    "lat": 17.361666666,
    "lng": 78.474722222,
    "source": "http://www.wikidata.org/entity/Q139801126"
  },
  {
    "slug": "kissflow",
    "name": "Kissflow",
    "website": "https://kissflow.com",
    "hq": "Chennai",
    "industry": "software industry",
    "founded": null,
    "score": 15,
    "city": "Chennai",
    "sector": "Software & IT",
    "lat": 13.0825,
    "lng": 80.275,
    "source": "http://www.wikidata.org/entity/Q30525109"
  },
  {
    "slug": "claarifai",
    "name": "ClaarifAI",
    "website": "https://claarifai.com",
    "hq": "Mumbai",
    "industry": "software industry",
    "founded": null,
    "score": 15,
    "city": "Mumbai",
    "sector": "Software & IT",
    "lat": 19.075833333,
    "lng": 72.8775,
    "source": "http://www.wikidata.org/entity/Q139893043"
  },
  {
    "slug": "sanu-builds",
    "name": "Sanu Builds",
    "website": "https://sanubuilds.com",
    "hq": "Fatehpur district",
    "industry": "software development",
    "founded": null,
    "score": 15,
    "city": "Fatehpur district",
    "sector": "Software & IT",
    "lat": 25.9333,
    "lng": 80.8,
    "source": "http://www.wikidata.org/entity/Q140611445"
  },
  {
    "slug": "baaz",
    "name": "baaz",
    "website": "https://www.baaz.pro",
    "hq": "Bengaluru",
    "industry": "software industry",
    "founded": null,
    "score": 15,
    "city": "Bengaluru",
    "sector": "Software & IT",
    "lat": 12.9791198,
    "lng": 77.5912997,
    "source": "http://www.wikidata.org/entity/Q138465565"
  }
] as const;
