export const directoryCompanies7 = [
  {
    "slug": "eris-lifesciences",
    "name": "Eris Lifesciences",
    "website": "https://eris.co.in/",
    "hq": "Ahmedabad",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Ahmedabad",
    "sector": "Other",
    "lat": 23.021944444,
    "lng": 72.579722222,
    "source": "http://www.wikidata.org/entity/Q138166820"
  },
  {
    "slug": "gateway-technolabs",
    "name": "Gateway TechnoLabs",
    "website": "http://www.gatewaytechnolabs.com/",
    "hq": "Ahmedabad",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Ahmedabad",
    "sector": "Other",
    "lat": 23.021944444,
    "lng": 72.579722222,
    "source": "http://www.wikidata.org/entity/Q123456558"
  },
  {
    "slug": "baidyanath-group",
    "name": "Baidyanath group",
    "website": "https://baidyanath.net.in/",
    "hq": "Kolkata",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Kolkata",
    "sector": "Other",
    "lat": 22.5675,
    "lng": 88.37,
    "source": "http://www.wikidata.org/entity/Q4843196"
  },
  {
    "slug": "lambda-therapeutic-research-india",
    "name": "Lambda Therapeutic Research (India)",
    "website": "http://www.lambda-cro.com/",
    "hq": "Ahmedabad",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Ahmedabad",
    "sector": "Other",
    "lat": 23.021944444,
    "lng": 72.579722222,
    "source": "http://www.wikidata.org/entity/Q50039661"
  },
  {
    "slug": "nettech",
    "name": "Nettech",
    "website": "http://www.nettech.in/",
    "hq": "Kolkata",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Kolkata",
    "sector": "Other",
    "lat": 22.5675,
    "lng": 88.37,
    "source": "http://www.wikidata.org/entity/Q7000471"
  },
  {
    "slug": "mcleod-russel",
    "name": "McLeod Russel",
    "website": "http://www.mcleodrussel.com/",
    "hq": "Kolkata",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Kolkata",
    "sector": "Other",
    "lat": 22.5675,
    "lng": 88.37,
    "source": "http://www.wikidata.org/entity/Q18127937"
  },
  {
    "slug": "sinclairs-hotels-limited",
    "name": "Sinclairs Hotels Limited",
    "website": "https://www.sinclairshotels.com/",
    "hq": "Kolkata",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Kolkata",
    "sector": "Other",
    "lat": 22.5675,
    "lng": 88.37,
    "source": "http://www.wikidata.org/entity/Q7522073"
  },
  {
    "slug": "amri-hospitals",
    "name": "AMRI Hospitals",
    "website": "https://www.amrihospitals.in/",
    "hq": "Kolkata",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Kolkata",
    "sector": "Other",
    "lat": 22.5675,
    "lng": 88.37,
    "source": "http://www.wikidata.org/entity/Q4652706"
  },
  {
    "slug": "nlc-india-limited",
    "name": "NLC India Limited",
    "website": "https://www.nlcindia.in",
    "hq": "Chennai",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Chennai",
    "sector": "Other",
    "lat": 13.0825,
    "lng": 80.275,
    "source": "http://www.wikidata.org/entity/Q3530370"
  },
  {
    "slug": "intas-biopharmaceuticals",
    "name": "Intas Biopharmaceuticals",
    "website": "https://www.intaspharma.com/",
    "hq": "Ahmedabad",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Ahmedabad",
    "sector": "Other",
    "lat": 23.021944444,
    "lng": 72.579722222,
    "source": "http://www.wikidata.org/entity/Q16848935"
  },
  {
    "slug": "the-park-hotels",
    "name": "The Park Hotels",
    "website": "https://www.theparkhotels.com/",
    "hq": "Kolkata",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Kolkata",
    "sector": "Other",
    "lat": 22.5675,
    "lng": 88.37,
    "source": "http://www.wikidata.org/entity/Q7756138"
  },
  {
    "slug": "sun-direct",
    "name": "Sun Direct",
    "website": "http://www.sundirect.in",
    "hq": "Chennai",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Chennai",
    "sector": "Other",
    "lat": 13.0825,
    "lng": 80.275,
    "source": "http://www.wikidata.org/entity/Q3523702"
  },
  {
    "slug": "west-bengal-state-coop-bank",
    "name": "West Bengal State Coop Bank",
    "website": "http://www.wbscb.com/",
    "hq": "Kolkata",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Kolkata",
    "sector": "Other",
    "lat": 22.5675,
    "lng": 88.37,
    "source": "http://www.wikidata.org/entity/Q19604617"
  },
  {
    "slug": "j-thomas-co-pvt-ltd",
    "name": "J Thomas & Co. Pvt. Ltd.",
    "website": "http://www.jthomasindia.com/",
    "hq": "Kolkata",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Kolkata",
    "sector": "Other",
    "lat": 22.5675,
    "lng": 88.37,
    "source": "http://www.wikidata.org/entity/Q18352781"
  },
  {
    "slug": "tasmac",
    "name": "TASMAC",
    "website": "http://tasmac.tn.gov.in/",
    "hq": "Chennai",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Chennai",
    "sector": "Other",
    "lat": 13.0825,
    "lng": 80.275,
    "source": "http://www.wikidata.org/entity/Q1971258"
  },
  {
    "slug": "sadbhav-engineering-limited",
    "name": "Sadbhav Engineering Limited",
    "website": "http://www.sadbhaveng.com",
    "hq": "Ahmedabad",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Ahmedabad",
    "sector": "Other",
    "lat": 23.021944444,
    "lng": 72.579722222,
    "source": "http://www.wikidata.org/entity/Q7397638"
  },
  {
    "slug": "association-for-social-and-environmental-development",
    "name": "Association for Social and Environmental Development",
    "website": "http://www.asedkol.org/",
    "hq": "Kolkata",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Kolkata",
    "sector": "Other",
    "lat": 22.5675,
    "lng": 88.37,
    "source": "http://www.wikidata.org/entity/Q30639656"
  },
  {
    "slug": "hsbc-glt-india",
    "name": "HSBC GLT India",
    "website": "http://www.hsbc.com/careers/explore-our-business/working-in-hsbc-operations-services-and-technology",
    "hq": "Kolkata",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Kolkata",
    "sector": "Other",
    "lat": 22.5675,
    "lng": 88.37,
    "source": "http://www.wikidata.org/entity/Q5635876"
  },
  {
    "slug": "gkb-opticals",
    "name": "GKB Opticals",
    "website": "http://www.gkboptical.com/",
    "hq": "Kolkata",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Kolkata",
    "sector": "Other",
    "lat": 22.5675,
    "lng": 88.37,
    "source": "http://www.wikidata.org/entity/Q5513570"
  },
  {
    "slug": "jai-balaji-group",
    "name": "Jai Balaji group",
    "website": "http://www.jaibalajigroup.com/",
    "hq": "Kolkata",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Kolkata",
    "sector": "Other",
    "lat": 22.5675,
    "lng": 88.37,
    "source": "http://www.wikidata.org/entity/Q6123349"
  },
  {
    "slug": "peerless-group",
    "name": "Peerless Group",
    "website": "http://www.peerless.co.in",
    "hq": "Kolkata",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Kolkata",
    "sector": "Other",
    "lat": 22.5675,
    "lng": 88.37,
    "source": "http://www.wikidata.org/entity/Q7160448"
  },
  {
    "slug": "vadilal",
    "name": "Vadilal",
    "website": "http://www.vadilalicecreams.com/",
    "hq": "Ahmedabad",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Ahmedabad",
    "sector": "Other",
    "lat": 23.021944444,
    "lng": 72.579722222,
    "source": "http://www.wikidata.org/entity/Q7908223"
  },
  {
    "slug": "tamil-nadu-housing-board",
    "name": "Tamil Nadu Housing Board",
    "website": "http://www.tnhb.gov.in/",
    "hq": "Chennai",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Chennai",
    "sector": "Other",
    "lat": 13.0825,
    "lng": 80.275,
    "source": "http://www.wikidata.org/entity/Q281513"
  },
  {
    "slug": "korix",
    "name": "KORIX",
    "website": "https://korixinc.com",
    "hq": "Ahmedabad",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Ahmedabad",
    "sector": "Other",
    "lat": 23.021944444,
    "lng": 72.579722222,
    "source": "http://www.wikidata.org/entity/Q138877358"
  },
  {
    "slug": "exide-industries",
    "name": "Exide Industries",
    "website": "https://www.exideindustries.com",
    "hq": "Kolkata",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Kolkata",
    "sector": "Other",
    "lat": 22.5675,
    "lng": 88.37,
    "source": "http://www.wikidata.org/entity/Q5420252"
  },
  {
    "slug": "torrent-cables",
    "name": "Torrent Cables",
    "website": "http://www.torrentcables.com/",
    "hq": "Ahmedabad",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Ahmedabad",
    "sector": "Other",
    "lat": 23.021944444,
    "lng": 72.579722222,
    "source": "http://www.wikidata.org/entity/Q7827041"
  },
  {
    "slug": "gtpl-hathway-limited",
    "name": "GTPL Hathway Limited",
    "website": "https://www.gtpl.net",
    "hq": "Ahmedabad",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Ahmedabad",
    "sector": "Other",
    "lat": 23.021944444,
    "lng": 72.579722222,
    "source": "http://www.wikidata.org/entity/Q106351547"
  },
  {
    "slug": "torrent-power",
    "name": "Torrent Power",
    "website": "http://www.torrentpower.com/",
    "hq": "Ahmedabad",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Ahmedabad",
    "sector": "Other",
    "lat": 23.021944444,
    "lng": 72.579722222,
    "source": "http://www.wikidata.org/entity/Q7827044"
  },
  {
    "slug": "spencer-s",
    "name": "Spencer's",
    "website": "http://www.spencersretail.com",
    "hq": "Kolkata",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Kolkata",
    "sector": "Other",
    "lat": 22.5675,
    "lng": 88.37,
    "source": "http://www.wikidata.org/entity/Q7575959"
  },
  {
    "slug": "intas-pharmaceuticals",
    "name": "Intas Pharmaceuticals",
    "website": "https://www.intaspharma.com/",
    "hq": "Ahmedabad",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Ahmedabad",
    "sector": "Other",
    "lat": 23.021944444,
    "lng": 72.579722222,
    "source": "http://www.wikidata.org/entity/Q108782794"
  },
  {
    "slug": "national-institute-of-personnel-management",
    "name": "National Institute of Personnel Management",
    "website": "http://www.nipm.in/",
    "hq": "Kolkata",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Kolkata",
    "sector": "Other",
    "lat": 22.5675,
    "lng": 88.37,
    "source": "http://www.wikidata.org/entity/Q18379519"
  },
  {
    "slug": "veeda-clinical-research-india",
    "name": "Veeda Clinical Research (India)",
    "website": "https://veedacr.com/",
    "hq": "Ahmedabad",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Ahmedabad",
    "sector": "Other",
    "lat": 23.021944444,
    "lng": 72.579722222,
    "source": "http://www.wikidata.org/entity/Q50037157"
  },
  {
    "slug": "shree-venkatesh-films",
    "name": "Shree Venkatesh Films",
    "website": "http://venkateshfilms.com",
    "hq": "Kolkata",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Kolkata",
    "sector": "Other",
    "lat": 22.5675,
    "lng": 88.37,
    "source": "http://www.wikidata.org/entity/Q7503531"
  },
  {
    "slug": "tcg-lifesciences-india",
    "name": "TCG Lifesciences (India)",
    "website": "http://www.tcgls.com/",
    "hq": "Kolkata",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Kolkata",
    "sector": "Other",
    "lat": 22.5675,
    "lng": 88.37,
    "source": "http://www.wikidata.org/entity/Q30263061"
  },
  {
    "slug": "west-bengal-green-energy-development-corporation-india",
    "name": "West Bengal Green Energy Development Corporation (India)",
    "website": "http://www.wbgedcl.in/",
    "hq": "Kolkata",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Kolkata",
    "sector": "Other",
    "lat": 22.5675,
    "lng": 88.37,
    "source": "http://www.wikidata.org/entity/Q30263052"
  },
  {
    "slug": "abhikram-india",
    "name": "Abhikram (India)",
    "website": "http://www.abhikram.com/home.php",
    "hq": "Ahmedabad",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Ahmedabad",
    "sector": "Other",
    "lat": 23.021944444,
    "lng": 72.579722222,
    "source": "http://www.wikidata.org/entity/Q30262865"
  },
  {
    "slug": "usha-martin-india",
    "name": "Usha Martin (India)",
    "website": "http://www.ushamartin.com/en/",
    "hq": "Kolkata",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Kolkata",
    "sector": "Other",
    "lat": 22.5675,
    "lng": 88.37,
    "source": "http://www.wikidata.org/entity/Q30263065"
  },
  {
    "slug": "workoscope",
    "name": "Workoscope",
    "website": "https://www.workoscope.com",
    "hq": "Ahmedabad",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Ahmedabad",
    "sector": "Other",
    "lat": 23.021944444,
    "lng": 72.579722222,
    "source": "http://www.wikidata.org/entity/Q97119123"
  },
  {
    "slug": "shree-cement",
    "name": "Shree Cement",
    "website": "https://www.shreecement.com",
    "hq": "Kolkata",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Kolkata",
    "sector": "Other",
    "lat": 22.5675,
    "lng": 88.37,
    "source": "http://www.wikidata.org/entity/Q7503476"
  },
  {
    "slug": "adani-airport-holdings",
    "name": "Adani Airport Holdings",
    "website": "https://www.adaniairports.com",
    "hq": "Ahmedabad",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Ahmedabad",
    "sector": "Other",
    "lat": 23.021944444,
    "lng": 72.579722222,
    "source": "http://www.wikidata.org/entity/Q134474338"
  },
  {
    "slug": "saravanaa-bhavan",
    "name": "Saravanaa Bhavan",
    "website": "https://saravanabhavan.com",
    "hq": "Chennai",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Chennai",
    "sector": "Other",
    "lat": 13.0825,
    "lng": 80.275,
    "source": "http://www.wikidata.org/entity/Q3528082"
  },
  {
    "slug": "prayag-film-city",
    "name": "Prayag Film City",
    "website": "http://prayagfilmcity.net/",
    "hq": "Kolkata",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Kolkata",
    "sector": "Other",
    "lat": 22.5675,
    "lng": 88.37,
    "source": "http://www.wikidata.org/entity/Q7238987"
  },
  {
    "slug": "nirma",
    "name": "Nirma",
    "website": "http://www.nirma.co.in",
    "hq": "Ahmedabad",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Ahmedabad",
    "sector": "Other",
    "lat": 23.021944444,
    "lng": 72.579722222,
    "source": "http://www.wikidata.org/entity/Q12435810"
  },
  {
    "slug": "va-tech-wabag",
    "name": "VA Tech Wabag",
    "website": "http://www.wabag.com/de/",
    "hq": "Chennai",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Chennai",
    "sector": "Other",
    "lat": 13.0825,
    "lng": 80.275,
    "source": "http://www.wikidata.org/entity/Q2536827"
  },
  {
    "slug": "greenply",
    "name": "Greenply",
    "website": "http://www.greenply.com",
    "hq": "Kolkata",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Kolkata",
    "sector": "Other",
    "lat": 22.5675,
    "lng": 88.37,
    "source": "http://www.wikidata.org/entity/Q17054016"
  },
  {
    "slug": "hardik-fintrade-india",
    "name": "Hardik Fintrade (India)",
    "website": "http://hardikgroup.com/",
    "hq": "Ahmedabad",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Ahmedabad",
    "sector": "Other",
    "lat": 23.021944444,
    "lng": 72.579722222,
    "source": "http://www.wikidata.org/entity/Q30262931"
  },
  {
    "slug": "landbitt",
    "name": "Landbitt",
    "website": "https://landbitt.com",
    "hq": "Ahmedabad",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Ahmedabad",
    "sector": "Other",
    "lat": 23.021944444,
    "lng": 72.579722222,
    "source": "http://www.wikidata.org/entity/Q140388220"
  },
  {
    "slug": "sterling-hospitals",
    "name": "Sterling Hospitals",
    "website": "http://www.sterlinghospitals.com",
    "hq": "Ahmedabad",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Ahmedabad",
    "sector": "Other",
    "lat": 23.021944444,
    "lng": 72.579722222,
    "source": "http://www.wikidata.org/entity/Q7611428"
  },
  {
    "slug": "ajanta-group",
    "name": "Ajanta Group",
    "website": "http://www.shoporeva.com",
    "hq": "Ahmedabad",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Ahmedabad",
    "sector": "Other",
    "lat": 23.021944444,
    "lng": 72.579722222,
    "source": "http://www.wikidata.org/entity/Q4699545"
  },
  {
    "slug": "shaw-wallace",
    "name": "Shaw Wallace",
    "website": "http://www.shawwallace.com/",
    "hq": "Kolkata",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Kolkata",
    "sector": "Other",
    "lat": 22.5675,
    "lng": 88.37,
    "source": "http://www.wikidata.org/entity/Q7491216"
  },
  {
    "slug": "havmor-ice-cream",
    "name": "Havmor Ice Cream",
    "website": "https://www.havmor.com",
    "hq": "Ahmedabad",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Ahmedabad",
    "sector": "Other",
    "lat": 23.021944444,
    "lng": 72.579722222,
    "source": "http://www.wikidata.org/entity/Q108739835"
  },
  {
    "slug": "cadila-pharmaceuticals",
    "name": "Cadila Pharmaceuticals",
    "website": "http://www.cadilapharma.com/",
    "hq": "Ahmedabad",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Ahmedabad",
    "sector": "Other",
    "lat": 23.021944444,
    "lng": 72.579722222,
    "source": "http://www.wikidata.org/entity/Q18379736"
  },
  {
    "slug": "educational-initiatives",
    "name": "Educational Initiatives",
    "website": "http://www.ei-india.com/",
    "hq": "Ahmedabad",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Ahmedabad",
    "sector": "Other",
    "lat": 23.021944444,
    "lng": 72.579722222,
    "source": "http://www.wikidata.org/entity/Q5341239"
  },
  {
    "slug": "chandrani-pearls",
    "name": "Chandrani Pearls",
    "website": "http://www.chandranipearls.net/front/",
    "hq": "Kolkata",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Kolkata",
    "sector": "Other",
    "lat": 22.5675,
    "lng": 88.37,
    "source": "http://www.wikidata.org/entity/Q5071425"
  },
  {
    "slug": "firepowersfx",
    "name": "FirepowerSFX",
    "website": "https://firepowersfx.com",
    "hq": "Ahmedabad",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Ahmedabad",
    "sector": "Other",
    "lat": 23.021944444,
    "lng": 72.579722222,
    "source": "http://www.wikidata.org/entity/Q139497543"
  },
  {
    "slug": "fusioncharts",
    "name": "FusionCharts",
    "website": "http://fusioncharts.com",
    "hq": "Kolkata",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Kolkata",
    "sector": "Other",
    "lat": 22.5675,
    "lng": 88.37,
    "source": "http://www.wikidata.org/entity/Q5510245"
  },
  {
    "slug": "sun-cable-vision",
    "name": "Sun Cable Vision",
    "website": "http://www.scv.co.in",
    "hq": "Chennai",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Chennai",
    "sector": "Other",
    "lat": 13.0825,
    "lng": 80.275,
    "source": "http://www.wikidata.org/entity/Q3194669"
  },
  {
    "slug": "care-institute-of-medical-sciences",
    "name": "Care Institute of Medical Sciences",
    "website": "http://www.cims.org",
    "hq": "Ahmedabad",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Ahmedabad",
    "sector": "Other",
    "lat": 23.021944444,
    "lng": 72.579722222,
    "source": "http://www.wikidata.org/entity/Q25212579"
  },
  {
    "slug": "d-bebe-kids-private-limited",
    "name": "D'bebe Kids Private Limited",
    "website": "https://www.dbebe.in",
    "hq": "Ahmedabad",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Ahmedabad",
    "sector": "Other",
    "lat": 23.021944444,
    "lng": 72.579722222,
    "source": "http://www.wikidata.org/entity/Q139574420"
  },
  {
    "slug": "bengal-chemicals-and-pharmaceuticals",
    "name": "Bengal Chemicals and Pharmaceuticals",
    "website": "http://www.bengalchemicals.gov.in/",
    "hq": "Kolkata",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Kolkata",
    "sector": "Other",
    "lat": 22.5675,
    "lng": 88.37,
    "source": "http://www.wikidata.org/entity/Q4887610"
  },
  {
    "slug": "vedacreatives",
    "name": "VedaCreatives",
    "website": "https://vedacreatives.com",
    "hq": "Ahmedabad",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Ahmedabad",
    "sector": "Other",
    "lat": 23.021944444,
    "lng": 72.579722222,
    "source": "http://www.wikidata.org/entity/Q139830328"
  },
  {
    "slug": "simulations-pr",
    "name": "Simulations PR",
    "website": "http://www.simulationsindia.com/",
    "hq": "Ahmedabad",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Ahmedabad",
    "sector": "Other",
    "lat": 23.021944444,
    "lng": 72.579722222,
    "source": "http://www.wikidata.org/entity/Q64858998"
  },
  {
    "slug": "ubiome",
    "name": "UBiome",
    "website": "https://ubiome.in/",
    "hq": "Kolkata",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Kolkata",
    "sector": "Other",
    "lat": 22.5675,
    "lng": 88.37,
    "source": "http://www.wikidata.org/entity/Q17087863"
  },
  {
    "slug": "skigle-technologies-llp",
    "name": "Skigle Technologies LLP",
    "website": "http://www.skigle.com",
    "hq": "Ahmedabad",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Ahmedabad",
    "sector": "Other",
    "lat": 23.021944444,
    "lng": 72.579722222,
    "source": "http://www.wikidata.org/entity/Q30148344"
  },
  {
    "slug": "dms-retail",
    "name": "DMS Retail",
    "website": "https://dmsretail.in",
    "hq": "Ahmedabad",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Ahmedabad",
    "sector": "Other",
    "lat": 23.021944444,
    "lng": 72.579722222,
    "source": "http://www.wikidata.org/entity/Q139915624"
  },
  {
    "slug": "gurully",
    "name": "Gurully",
    "website": "https://www.gurully.com/",
    "hq": "Ahmedabad",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Ahmedabad",
    "sector": "Other",
    "lat": 23.021944444,
    "lng": 72.579722222,
    "source": "http://www.wikidata.org/entity/Q134469604"
  },
  {
    "slug": "bharat-bhari-udyog-nigam",
    "name": "Bharat Bhari Udyog Nigam",
    "website": "http://www.bbunl.com/",
    "hq": "Kolkata",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Kolkata",
    "sector": "Other",
    "lat": 22.5675,
    "lng": 88.37,
    "source": "http://www.wikidata.org/entity/Q4901099"
  },
  {
    "slug": "cliantha-india",
    "name": "Cliantha (India)",
    "website": "http://www.cliantha.in/",
    "hq": "Ahmedabad",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Ahmedabad",
    "sector": "Other",
    "lat": 23.021944444,
    "lng": 72.579722222,
    "source": "http://www.wikidata.org/entity/Q50039466"
  },
  {
    "slug": "dhudiya-entertainment",
    "name": "Dhudiya Entertainment",
    "website": "https://dhudiya.com",
    "hq": "Ahmedabad",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Ahmedabad",
    "sector": "Other",
    "lat": 23.021944444,
    "lng": 72.579722222,
    "source": "http://www.wikidata.org/entity/Q68154124"
  },
  {
    "slug": "symphony-limited",
    "name": "Symphony Limited",
    "website": "https://www.symphonylimited.com/",
    "hq": "Ahmedabad",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Ahmedabad",
    "sector": "Other",
    "lat": 23.021944444,
    "lng": 72.579722222,
    "source": "http://www.wikidata.org/entity/Q7661472"
  },
  {
    "slug": "jio-bp",
    "name": "Jio-BP",
    "website": "https://www.jiobp.com/",
    "hq": "Ahmedabad",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Ahmedabad",
    "sector": "Other",
    "lat": 23.021944444,
    "lng": 72.579722222,
    "source": "http://www.wikidata.org/entity/Q7311026"
  },
  {
    "slug": "garden-reach-shipbuilders-engineers",
    "name": "Garden Reach Shipbuilders & Engineers",
    "website": "https://grse.in",
    "hq": "Kolkata",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Kolkata",
    "sector": "Other",
    "lat": 22.5675,
    "lng": 88.37,
    "source": "http://www.wikidata.org/entity/Q5522292"
  },
  {
    "slug": "stormforz",
    "name": "stormforz",
    "website": "https://stormforz.com",
    "hq": "Ahmedabad",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Ahmedabad",
    "sector": "Other",
    "lat": 23.021944444,
    "lng": 72.579722222,
    "source": "http://www.wikidata.org/entity/Q113925748"
  },
  {
    "slug": "visa-steel",
    "name": "VISA Steel",
    "website": "http://www.visasteel.com/",
    "hq": "Kolkata",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Kolkata",
    "sector": "Other",
    "lat": 22.5675,
    "lng": 88.37,
    "source": "http://www.wikidata.org/entity/Q7907069"
  },
  {
    "slug": "emami",
    "name": "Emami",
    "website": "http://www.emamiltd.in/",
    "hq": "Kolkata",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Kolkata",
    "sector": "Other",
    "lat": 22.5675,
    "lng": 88.37,
    "source": "http://www.wikidata.org/entity/Q5368876"
  },
  {
    "slug": "linc-pen-plastics-limited",
    "name": "Linc Pen & Plastics Limited",
    "website": "http://www.lincpen.com/",
    "hq": "Kolkata",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Kolkata",
    "sector": "Other",
    "lat": 22.5675,
    "lng": 88.37,
    "source": "http://www.wikidata.org/entity/Q38253695"
  },
  {
    "slug": "madras-rubber-factory",
    "name": "Madras Rubber Factory",
    "website": "http://www.mrftyres.com/",
    "hq": "Chennai",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Chennai",
    "sector": "Other",
    "lat": 13.0825,
    "lng": 80.275,
    "source": "http://www.wikidata.org/entity/Q1789944"
  },
  {
    "slug": "birla-tyres",
    "name": "Birla Tyres",
    "website": "http://www.birlatyre.com",
    "hq": "Kolkata",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Kolkata",
    "sector": "Other",
    "lat": 22.5675,
    "lng": 88.37,
    "source": "http://www.wikidata.org/entity/Q4916542"
  },
  {
    "slug": "aspire-systems",
    "name": "Aspire Systems",
    "website": "http://www.aspiresys.com/",
    "hq": "Chennai",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Chennai",
    "sector": "Other",
    "lat": 13.0825,
    "lng": 80.275,
    "source": "http://www.wikidata.org/entity/Q4808091"
  },
  {
    "slug": "qube-cinema-technologies",
    "name": "Qube Cinema Technologies",
    "website": "http://www.realimage.com",
    "hq": "Chennai",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Chennai",
    "sector": "Other",
    "lat": 13.0825,
    "lng": 80.275,
    "source": "http://www.wikidata.org/entity/Q7300944"
  },
  {
    "slug": "consultivo",
    "name": "Consultivo",
    "website": "https://consultivo.in",
    "hq": "Kolkata",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Kolkata",
    "sector": "Other",
    "lat": 22.5675,
    "lng": 88.37,
    "source": "http://www.wikidata.org/entity/Q138598588"
  },
  {
    "slug": "zikhoya-jewellery",
    "name": "Zikhoya Jewellery",
    "website": "https://zikhoya.com",
    "hq": "Kolkata",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Kolkata",
    "sector": "Other",
    "lat": 22.5675,
    "lng": 88.37,
    "source": "http://www.wikidata.org/entity/Q138645874"
  },
  {
    "slug": "bgr-energy-systems-ltd",
    "name": "BGR Energy Systems Ltd",
    "website": "https://www.bgrcorp.com/",
    "hq": "Chennai",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Chennai",
    "sector": "Other",
    "lat": 13.0825,
    "lng": 80.275,
    "source": "http://www.wikidata.org/entity/Q4835562"
  },
  {
    "slug": "vivimed-labs-limited",
    "name": "Vivimed Labs Limited",
    "website": "http://www.vivimedlabs.com",
    "hq": "Hyderabad",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Hyderabad",
    "sector": "Other",
    "lat": 17.361666666,
    "lng": 78.474722222,
    "source": "http://www.wikidata.org/entity/Q7937906"
  },
  {
    "slug": "studio-green",
    "name": "Studio Green",
    "website": "http://www.studiogreen.in/",
    "hq": "Chennai",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Chennai",
    "sector": "Other",
    "lat": 13.0825,
    "lng": 80.275,
    "source": "http://www.wikidata.org/entity/Q7628187"
  },
  {
    "slug": "watchdoq",
    "name": "Watchdoq",
    "website": "https://watchdoq.com",
    "hq": "Kolkata",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Kolkata",
    "sector": "Other",
    "lat": 22.5675,
    "lng": 88.37,
    "source": "http://www.wikidata.org/entity/Q138835451"
  },
  {
    "slug": "pressmart",
    "name": "Pressmart",
    "website": "http://www.pressmart.com",
    "hq": "Hyderabad",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Hyderabad",
    "sector": "Other",
    "lat": 17.361666666,
    "lng": 78.474722222,
    "source": "http://www.wikidata.org/entity/Q7241670"
  },
  {
    "slug": "sri-venkateswara-creations",
    "name": "Sri Venkateswara Creations",
    "website": "http://www.dilraju.com",
    "hq": "Hyderabad",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Hyderabad",
    "sector": "Other",
    "lat": 17.361666666,
    "lng": 78.474722222,
    "source": "http://www.wikidata.org/entity/Q7586324"
  },
  {
    "slug": "hatsun-agro-product",
    "name": "Hatsun Agro Product",
    "website": "http://www.hatsun.com/",
    "hq": "Chennai",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Chennai",
    "sector": "Other",
    "lat": 13.0825,
    "lng": 80.275,
    "source": "http://www.wikidata.org/entity/Q16259165"
  },
  {
    "slug": "tube-products-of-india",
    "name": "Tube Products of India",
    "website": "https://www.tubeproductsindia.com/",
    "hq": "Chennai",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Chennai",
    "sector": "Other",
    "lat": 13.0825,
    "lng": 80.275,
    "source": "http://www.wikidata.org/entity/Q7850775"
  },
  {
    "slug": "kwitts",
    "name": "Kwitts",
    "website": "https://www.kwitts.in",
    "hq": "Chennai",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Chennai",
    "sector": "Other",
    "lat": 13.0825,
    "lng": 80.275,
    "source": "http://www.wikidata.org/entity/Q67429889"
  },
  {
    "slug": "orchid-chemicals-pharmaceuticals-limited",
    "name": "Orchid Chemicals & Pharmaceuticals Limited",
    "website": "http://www.orchidpharma.com/",
    "hq": "Chennai",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Chennai",
    "sector": "Other",
    "lat": 13.0825,
    "lng": 80.275,
    "source": "http://www.wikidata.org/entity/Q7100279"
  },
  {
    "slug": "job-recruitment",
    "name": "Job Recruitment",
    "website": "https://jobrecruitment.in",
    "hq": "Ahmedabad",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Ahmedabad",
    "sector": "Other",
    "lat": 23.021944444,
    "lng": 72.579722222,
    "source": "http://www.wikidata.org/entity/Q140932312"
  },
  {
    "slug": "tafe-tractors",
    "name": "TAFE Tractors",
    "website": "http://www.tafe.com/",
    "hq": "Chennai",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Chennai",
    "sector": "Other",
    "lat": 13.0825,
    "lng": 80.275,
    "source": "http://www.wikidata.org/entity/Q7669254"
  },
  {
    "slug": "aavin",
    "name": "Aavin",
    "website": "http://www.aavinmilk.com/",
    "hq": "Chennai",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Chennai",
    "sector": "Other",
    "lat": 13.0825,
    "lng": 80.275,
    "source": "http://www.wikidata.org/entity/Q4662814"
  },
  {
    "slug": "cholamandalam-ms-general-insurance",
    "name": "Cholamandalam MS General Insurance",
    "website": "http://www.cholainsurance.com",
    "hq": "Chennai",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Chennai",
    "sector": "Other",
    "lat": 13.0825,
    "lng": 80.275,
    "source": "http://www.wikidata.org/entity/Q5104279"
  },
  {
    "slug": "mio-amore",
    "name": "Mio Amore",
    "website": "https://mioamoreshop.com/",
    "hq": "Kolkata",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Kolkata",
    "sector": "Other",
    "lat": 22.5675,
    "lng": 88.37,
    "source": "http://www.wikidata.org/entity/Q130534919"
  },
  {
    "slug": "gyan-data-pvt-ltd",
    "name": "Gyan Data Pvt Ltd",
    "website": "http://gyandata.com/",
    "hq": "Chennai",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Chennai",
    "sector": "Other",
    "lat": 13.0825,
    "lng": 80.275,
    "source": "http://www.wikidata.org/entity/Q55775864"
  },
  {
    "slug": "vortex-engineering",
    "name": "Vortex Engineering",
    "website": "https://www.vortexindia.co.in/",
    "hq": "Chennai",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Chennai",
    "sector": "Other",
    "lat": 13.0825,
    "lng": 80.275,
    "source": "http://www.wikidata.org/entity/Q7941915"
  },
  {
    "slug": "anabond",
    "name": "Anabond",
    "website": "http://www.anabond.com",
    "hq": "Chennai",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Chennai",
    "sector": "Other",
    "lat": 13.0825,
    "lng": 80.275,
    "source": "http://www.wikidata.org/entity/Q4750603"
  },
  {
    "slug": "spic",
    "name": "SPIC",
    "website": "http://spic.in/",
    "hq": "Chennai",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Chennai",
    "sector": "Other",
    "lat": 13.0825,
    "lng": 80.275,
    "source": "http://www.wikidata.org/entity/Q7392557"
  },
  {
    "slug": "accel-animation-studios",
    "name": "Accel Animation Studios",
    "website": "http://accelanimation.com",
    "hq": "Chennai",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Chennai",
    "sector": "Other",
    "lat": 13.0825,
    "lng": 80.275,
    "source": "http://www.wikidata.org/entity/Q4672259"
  },
  {
    "slug": "aban-offshore",
    "name": "Aban Offshore",
    "website": "http://www.abanoffshore.com/",
    "hq": "Chennai",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Chennai",
    "sector": "Other",
    "lat": 13.0825,
    "lng": 80.275,
    "source": "http://www.wikidata.org/entity/Q4663338"
  },
  {
    "slug": "inside-chennai",
    "name": "Inside Chennai",
    "website": "https://www.insidechennai.com",
    "hq": "Chennai",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Chennai",
    "sector": "Other",
    "lat": 13.0825,
    "lng": 80.275,
    "source": "http://www.wikidata.org/entity/Q59180982"
  },
  {
    "slug": "tamil-nadu-electricity-board",
    "name": "Tamil Nadu Electricity Board",
    "website": "http://www.tangedco.gov.in",
    "hq": "Chennai",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Chennai",
    "sector": "Other",
    "lat": 13.0825,
    "lng": 80.275,
    "source": "http://www.wikidata.org/entity/Q7670848"
  },
  {
    "slug": "isuzu-motors-india",
    "name": "Isuzu Motors India",
    "website": "http://www.isuzu.in",
    "hq": "Chennai",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Chennai",
    "sector": "Other",
    "lat": 13.0825,
    "lng": 80.275,
    "source": "http://www.wikidata.org/entity/Q58047909"
  },
  {
    "slug": "basics-life",
    "name": "Basics Life",
    "website": "https://basicslife.com/",
    "hq": "Chennai",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Chennai",
    "sector": "Other",
    "lat": 13.0825,
    "lng": 80.275,
    "source": "http://www.wikidata.org/entity/Q128711197"
  },
  {
    "slug": "hinduja-foundries",
    "name": "Hinduja Foundries",
    "website": "http://www.hindujafoundries.in",
    "hq": "Chennai",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Chennai",
    "sector": "Other",
    "lat": 13.0825,
    "lng": 80.275,
    "source": "http://www.wikidata.org/entity/Q17029865"
  },
  {
    "slug": "chennai-metro-rail-limited",
    "name": "Chennai Metro Rail Limited",
    "website": "https://chennaimetrorail.org/",
    "hq": "Chennai",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Chennai",
    "sector": "Other",
    "lat": 13.0825,
    "lng": 80.275,
    "source": "http://www.wikidata.org/entity/Q126616138"
  },
  {
    "slug": "sterling-holiday-resorts",
    "name": "Sterling Holiday Resorts",
    "website": "https://www.sterlingholidays.com/",
    "hq": "Chennai",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Chennai",
    "sector": "Other",
    "lat": 13.0825,
    "lng": 80.275,
    "source": "http://www.wikidata.org/entity/Q7611426"
  },
  {
    "slug": "sql-star",
    "name": "SQL Star",
    "website": "http://www.sqlstar.com/",
    "hq": "Hyderabad",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Hyderabad",
    "sector": "Other",
    "lat": 17.361666666,
    "lng": 78.474722222,
    "source": "http://www.wikidata.org/entity/Q7392742"
  },
  {
    "slug": "vaartha",
    "name": "Vaartha",
    "website": "http://www.vaartha.com/",
    "hq": "Hyderabad",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Hyderabad",
    "sector": "Other",
    "lat": 17.361666666,
    "lng": 78.474722222,
    "source": "http://www.wikidata.org/entity/Q7907837"
  },
  {
    "slug": "arcvision-technologies",
    "name": "ArcVision Technologies",
    "website": "https://www.arcvisions.com/",
    "hq": "Kolkata",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Kolkata",
    "sector": "Other",
    "lat": 22.5675,
    "lng": 88.37,
    "source": "http://www.wikidata.org/entity/Q119982318"
  },
  {
    "slug": "takraf-india-pvt-ltd",
    "name": "Takraf India Pvt. Ltd.",
    "website": "http://www.takraf.co.in/",
    "hq": "Chennai",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Chennai",
    "sector": "Other",
    "lat": 13.0825,
    "lng": 80.275,
    "source": "http://www.wikidata.org/entity/Q7678498"
  },
  {
    "slug": "nexus-consultants",
    "name": "Nexus Consultants",
    "website": "https://www.nexusconsultants.co.in",
    "hq": "Ahmedabad",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Ahmedabad",
    "sector": "Other",
    "lat": 23.021944444,
    "lng": 72.579722222,
    "source": "http://www.wikidata.org/entity/Q140690995"
  },
  {
    "slug": "johnson-lifts",
    "name": "Johnson Lifts",
    "website": "https://www.johnsonliftsltd.com/",
    "hq": "Chennai",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Chennai",
    "sector": "Other",
    "lat": 13.0825,
    "lng": 80.275,
    "source": "http://www.wikidata.org/entity/Q119149986"
  },
  {
    "slug": "west-bengal-state-electricity-board",
    "name": "West Bengal State Electricity Board",
    "website": "http://www.wbseb.in",
    "hq": "Kolkata",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Kolkata",
    "sector": "Other",
    "lat": 22.5675,
    "lng": 88.37,
    "source": "http://www.wikidata.org/entity/Q3348795"
  },
  {
    "slug": "brightcom-group",
    "name": "Brightcom Group",
    "website": "http://brightcomgroup.com",
    "hq": "Hyderabad",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Hyderabad",
    "sector": "Other",
    "lat": 17.361666666,
    "lng": 78.474722222,
    "source": "http://www.wikidata.org/entity/Q8050699"
  },
  {
    "slug": "ashok-leyland-defence-systems",
    "name": "Ashok Leyland Defence Systems",
    "website": "http://defence.ashokleyland.com/",
    "hq": "Chennai",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Chennai",
    "sector": "Other",
    "lat": 13.0825,
    "lng": 80.275,
    "source": "http://www.wikidata.org/entity/Q4805761"
  },
  {
    "slug": "tata-advanced-systems",
    "name": "Tata Advanced Systems",
    "website": "http://www.tataadvancedsystems.com/",
    "hq": "Hyderabad",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Hyderabad",
    "sector": "Other",
    "lat": 17.361666666,
    "lng": 78.474722222,
    "source": "http://www.wikidata.org/entity/Q7687789"
  },
  {
    "slug": "desi-machines",
    "name": "Desi Machines",
    "website": "https://desimachines.com/",
    "hq": "Kolkata",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Kolkata",
    "sector": "Other",
    "lat": 22.5675,
    "lng": 88.37,
    "source": "http://www.wikidata.org/entity/Q140425089"
  },
  {
    "slug": "penda",
    "name": "Penda",
    "website": "https://penda.in/",
    "hq": "Chennai",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Chennai",
    "sector": "Other",
    "lat": 13.0825,
    "lng": 80.275,
    "source": "http://www.wikidata.org/entity/Q130027333"
  },
  {
    "slug": "rapid-bevtech-pvt-ltd",
    "name": "Rapid BevTech Pvt. Ltd.",
    "website": "https://www.rapidbevtech.com/",
    "hq": "Ahmedabad",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Ahmedabad",
    "sector": "Other",
    "lat": 23.021944444,
    "lng": 72.579722222,
    "source": "http://www.wikidata.org/entity/Q140393346"
  },
  {
    "slug": "sun-group",
    "name": "Sun Group",
    "website": "http://www.sun.in/",
    "hq": "Chennai",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Chennai",
    "sector": "Other",
    "lat": 13.0825,
    "lng": 80.275,
    "source": "http://www.wikidata.org/entity/Q7638314"
  },
  {
    "slug": "ford-india-private-limited",
    "name": "Ford India Private Limited",
    "website": "http://www.india.ford.com",
    "hq": "Chennai",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Chennai",
    "sector": "Other",
    "lat": 13.0825,
    "lng": 80.275,
    "source": "http://www.wikidata.org/entity/Q3537079"
  },
  {
    "slug": "tvs-electronics",
    "name": "TVS Electronics",
    "website": "http://www.tvs-e.in/",
    "hq": "Chennai",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Chennai",
    "sector": "Other",
    "lat": 13.0825,
    "lng": 80.275,
    "source": "http://www.wikidata.org/entity/Q7672250"
  },
  {
    "slug": "madras-export-processing-zone",
    "name": "Madras Export Processing Zone",
    "website": "http://www.mepz.gov.in/home.asp",
    "hq": "Chennai",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Chennai",
    "sector": "Other",
    "lat": 13.0825,
    "lng": 80.275,
    "source": "http://www.wikidata.org/entity/Q15243520"
  },
  {
    "slug": "assetplus",
    "name": "assetplus",
    "website": "https://www.partners.assetplus.in/",
    "hq": "Chennai",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Chennai",
    "sector": "Other",
    "lat": 13.0825,
    "lng": 80.275,
    "source": "http://www.wikidata.org/entity/Q135438297"
  },
  {
    "slug": "rp-sanjiv-goenka-group",
    "name": "RP-Sanjiv Goenka Group",
    "website": "https://www.rpsg.in",
    "hq": "Kolkata",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Kolkata",
    "sector": "Other",
    "lat": 22.5675,
    "lng": 88.37,
    "source": "http://www.wikidata.org/entity/Q96400900"
  },
  {
    "slug": "randstad-india",
    "name": "Randstad India",
    "website": "https://www.randstad.in/",
    "hq": "Chennai",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Chennai",
    "sector": "Other",
    "lat": 13.0825,
    "lng": 80.275,
    "source": "http://www.wikidata.org/entity/Q7292031"
  },
  {
    "slug": "jilla-ventures",
    "name": "Jilla Ventures",
    "website": "https://jillaventures.in",
    "hq": "Chennai",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Chennai",
    "sector": "Other",
    "lat": 13.0825,
    "lng": 80.275,
    "source": "http://www.wikidata.org/entity/Q138744525"
  },
  {
    "slug": "eid-parry",
    "name": "EID Parry",
    "website": "http://www.eidparry.com/",
    "hq": "Chennai",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Chennai",
    "sector": "Other",
    "lat": 13.0825,
    "lng": 80.275,
    "source": "http://www.wikidata.org/entity/Q5323127"
  },
  {
    "slug": "sun-news",
    "name": "Sun News",
    "website": "http://sunnetwork.in/tv-channel-details.aspx?Channelid=10&channelname=SUN%20NEWS",
    "hq": "Chennai",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Chennai",
    "sector": "Other",
    "lat": 13.0825,
    "lng": 80.275,
    "source": "http://www.wikidata.org/entity/Q7638419"
  },
  {
    "slug": "electric-ji",
    "name": "Electric Ji",
    "website": "https://electricji.com",
    "hq": "Kolkata",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Kolkata",
    "sector": "Other",
    "lat": 22.5675,
    "lng": 88.37,
    "source": "http://www.wikidata.org/entity/Q140036847"
  },
  {
    "slug": "tamil-nadu-state-agricultural-marketing-board",
    "name": "Tamil Nadu State Agricultural Marketing Board",
    "website": "http://www.tnsamb.gov.in/",
    "hq": "Chennai",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Chennai",
    "sector": "Other",
    "lat": 13.0825,
    "lng": 80.275,
    "source": "http://www.wikidata.org/entity/Q12973153"
  },
  {
    "slug": "geo-trends",
    "name": "Geo Trends",
    "website": "https://geotrends.in",
    "hq": "Kolkata",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Kolkata",
    "sector": "Other",
    "lat": 22.5675,
    "lng": 88.37,
    "source": "http://www.wikidata.org/entity/Q140310145"
  },
  {
    "slug": "ideal-eyes-interior",
    "name": "Ideal Eyes Interior",
    "website": "https://idealeyesinterior.com/",
    "hq": "Kolkata",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Kolkata",
    "sector": "Other",
    "lat": 22.5675,
    "lng": 88.37,
    "source": "http://www.wikidata.org/entity/Q137996495"
  },
  {
    "slug": "photon-factory-films",
    "name": "Photon factory films",
    "website": "http://www.photonfactoryfilms.com",
    "hq": "Chennai",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Chennai",
    "sector": "Other",
    "lat": 13.0825,
    "lng": 80.275,
    "source": "http://www.wikidata.org/entity/Q7187852"
  },
  {
    "slug": "zylog-systems-limited",
    "name": "Zylog Systems Limited",
    "website": "http://www.zsl.com/",
    "hq": "Chennai",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Chennai",
    "sector": "Other",
    "lat": 13.0825,
    "lng": 80.275,
    "source": "http://www.wikidata.org/entity/Q8075918"
  },
  {
    "slug": "gemini-film-circuit",
    "name": "Gemini Film Circuit",
    "website": "http://www.gemini360.in/",
    "hq": "Chennai",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Chennai",
    "sector": "Other",
    "lat": 13.0825,
    "lng": 80.275,
    "source": "http://www.wikidata.org/entity/Q5530647"
  },
  {
    "slug": "hdr-play-pictures",
    "name": "HDR Play Pictures",
    "website": "https://hdrplay.com/",
    "hq": "Kolkata",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Kolkata",
    "sector": "Other",
    "lat": 22.5675,
    "lng": 88.37,
    "source": "http://www.wikidata.org/entity/Q64711297"
  },
  {
    "slug": "signature-24-productions",
    "name": "Signature 24 Productions",
    "website": "https://signature24.in",
    "hq": "Kolkata",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Kolkata",
    "sector": "Other",
    "lat": 22.5675,
    "lng": 88.37,
    "source": "http://www.wikidata.org/entity/Q106599405"
  },
  {
    "slug": "suresh-productions",
    "name": "Suresh Productions",
    "website": "http://www.sureshproductions.com/",
    "hq": "Hyderabad",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Hyderabad",
    "sector": "Other",
    "lat": 17.361666666,
    "lng": 78.474722222,
    "source": "http://www.wikidata.org/entity/Q7645776"
  },
  {
    "slug": "event-1o1",
    "name": "Event 1O1",
    "website": "https://www.event1o1.com",
    "hq": "Ahmedabad",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Ahmedabad",
    "sector": "Other",
    "lat": 23.021944444,
    "lng": 72.579722222,
    "source": "http://www.wikidata.org/entity/Q140694985"
  },
  {
    "slug": "society-for-elimination-of-rural-poverty",
    "name": "Society for Elimination of Rural Poverty",
    "website": "http://www.serp.ap.gov.in",
    "hq": "Hyderabad",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Hyderabad",
    "sector": "Other",
    "lat": 17.361666666,
    "lng": 78.474722222,
    "source": "http://www.wikidata.org/entity/Q7552113"
  },
  {
    "slug": "damodar-valley-corporation",
    "name": "Damodar Valley Corporation",
    "website": "https://www.dvc.gov.in",
    "hq": "Kolkata",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Kolkata",
    "sector": "Other",
    "lat": 22.5675,
    "lng": 88.37,
    "source": "http://www.wikidata.org/entity/Q3346347"
  },
  {
    "slug": "arambagh-foodmart",
    "name": "Arambagh Foodmart",
    "website": "https://arambaghfoodmart.com/",
    "hq": "Kolkata",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Kolkata",
    "sector": "Other",
    "lat": 22.5675,
    "lng": 88.37,
    "source": "http://www.wikidata.org/entity/Q130550508"
  },
  {
    "slug": "nx-studios",
    "name": "NX Studios",
    "website": "https://www.nxstudios.tk",
    "hq": "Kolkata",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Kolkata",
    "sector": "Other",
    "lat": 22.5675,
    "lng": 88.37,
    "source": "http://www.wikidata.org/entity/Q74386272"
  },
  {
    "slug": "uco-bank",
    "name": "UCO Bank",
    "website": "https://www.uco.bank.in/",
    "hq": "Kolkata",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Kolkata",
    "sector": "Other",
    "lat": 22.5675,
    "lng": 88.37,
    "source": "http://www.wikidata.org/entity/Q2005310"
  },
  {
    "slug": "sri-lakshmi-prasanna-pictures",
    "name": "Sri Lakshmi Prasanna Pictures",
    "website": "http://www.slppictures.com/",
    "hq": "Hyderabad",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Hyderabad",
    "sector": "Other",
    "lat": 17.361666666,
    "lng": 78.474722222,
    "source": "http://www.wikidata.org/entity/Q7585881"
  },
  {
    "slug": "the-sugarr-and-spice",
    "name": "The Sugarr And Spice",
    "website": "https://thesugarrandspice.com/",
    "hq": "Kolkata",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Kolkata",
    "sector": "Other",
    "lat": 22.5675,
    "lng": 88.37,
    "source": "http://www.wikidata.org/entity/Q130550402"
  },
  {
    "slug": "neuland-laboratories",
    "name": "Neuland Laboratories",
    "website": "https://www.neulandlabs.com/en",
    "hq": "Hyderabad",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Hyderabad",
    "sector": "Other",
    "lat": 17.361666666,
    "lng": 78.474722222,
    "source": "http://www.wikidata.org/entity/Q135489874"
  },
  {
    "slug": "reporeserve",
    "name": "RepoReserve",
    "website": "https://reporeserve.com/",
    "hq": "Hyderabad",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Hyderabad",
    "sector": "Other",
    "lat": 17.361666666,
    "lng": 78.474722222,
    "source": "http://www.wikidata.org/entity/Q138667214"
  },
  {
    "slug": "novalead-pharma-india",
    "name": "NovaLead Pharma (India)",
    "website": "http://www.novaleadpharma.com/#about",
    "hq": "Pune",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Pune",
    "sector": "Other",
    "lat": 18.521111111,
    "lng": 73.855277777,
    "source": "http://www.wikidata.org/entity/Q30263044"
  },
  {
    "slug": "suncon-engineers-india",
    "name": "Suncon Engineers (India)",
    "website": "http://www.sunconengineers.com/",
    "hq": "Pune",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Pune",
    "sector": "Other",
    "lat": 18.521111111,
    "lng": 73.855277777,
    "source": "http://www.wikidata.org/entity/Q30263035"
  },
  {
    "slug": "praj",
    "name": "Praj",
    "website": "http://www.praj.net/",
    "hq": "Pune",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Pune",
    "sector": "Other",
    "lat": 18.521111111,
    "lng": 73.855277777,
    "source": "http://www.wikidata.org/entity/Q25303288"
  },
  {
    "slug": "omni-hospitals",
    "name": "Omni Hospitals",
    "website": "https://omnihospitals.in/our-hospitals/",
    "hq": "Hyderabad",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Hyderabad",
    "sector": "Other",
    "lat": 17.361666666,
    "lng": 78.474722222,
    "source": "http://www.wikidata.org/entity/Q107621390"
  },
  {
    "slug": "navayuga-group",
    "name": "Navayuga Group",
    "website": "http://www.navayuga.com",
    "hq": "Hyderabad",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Hyderabad",
    "sector": "Other",
    "lat": 17.361666666,
    "lng": 78.474722222,
    "source": "http://www.wikidata.org/entity/Q24907131"
  },
  {
    "slug": "hello-curry",
    "name": "Hello Curry",
    "website": "http://www.hellocurry.com/index.php",
    "hq": "Hyderabad",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Hyderabad",
    "sector": "Other",
    "lat": 17.361666666,
    "lng": 78.474722222,
    "source": "http://www.wikidata.org/entity/Q29026056"
  },
  {
    "slug": "telangana-state-road-transport-corporation",
    "name": "Telangana State Road Transport Corporation",
    "website": "https://www.tsrtc.telangana.gov.in",
    "hq": "Hyderabad",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Hyderabad",
    "sector": "Other",
    "lat": 17.361666666,
    "lng": 78.474722222,
    "source": "http://www.wikidata.org/entity/Q19898600"
  },
  {
    "slug": "yb-juris",
    "name": "YB Juris",
    "website": "https://ybjuris.com/",
    "hq": "Hyderabad",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Hyderabad",
    "sector": "Other",
    "lat": 17.361666666,
    "lng": 78.474722222,
    "source": "http://www.wikidata.org/entity/Q138795674"
  },
  {
    "slug": "mold-tek-packaging",
    "name": "Mold-Tek Packaging",
    "website": "https://www.moldtekpackaging.com/",
    "hq": "Hyderabad",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Hyderabad",
    "sector": "Other",
    "lat": 17.361666666,
    "lng": 78.474722222,
    "source": "http://www.wikidata.org/entity/Q125523105"
  },
  {
    "slug": "bioaxis-dna-research-centre-india",
    "name": "BioAxis DNA Research Centre (India)",
    "website": "http://dnares.in/",
    "hq": "Hyderabad",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Hyderabad",
    "sector": "Other",
    "lat": 17.361666666,
    "lng": 78.474722222,
    "source": "http://www.wikidata.org/entity/Q30266958"
  },
  {
    "slug": "wemakescholars",
    "name": "WeMakeScholars",
    "website": "https://www.wemakescholars.com/",
    "hq": "Hyderabad",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Hyderabad",
    "sector": "Other",
    "lat": 17.361666666,
    "lng": 78.474722222,
    "source": "http://www.wikidata.org/entity/Q136374017"
  },
  {
    "slug": "uv-creations",
    "name": "UV Creations",
    "website": "http://www.uvcreations.com",
    "hq": "Hyderabad",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Hyderabad",
    "sector": "Other",
    "lat": 17.361666666,
    "lng": 78.474722222,
    "source": "http://www.wikidata.org/entity/Q19899107"
  },
  {
    "slug": "faasos",
    "name": "Faasos",
    "website": "https://www.faasos.com/",
    "hq": "Pune",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Pune",
    "sector": "Other",
    "lat": 18.521111111,
    "lng": 73.855277777,
    "source": "http://www.wikidata.org/entity/Q21008866"
  },
  {
    "slug": "mythri-movie-makers",
    "name": "Mythri Movie Makers",
    "website": "https://mythrimoviemakers.com",
    "hq": "Hyderabad",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Hyderabad",
    "sector": "Other",
    "lat": 17.361666666,
    "lng": 78.474722222,
    "source": "http://www.wikidata.org/entity/Q21190867"
  },
  {
    "slug": "modular-infotech-pvt-ltd",
    "name": "Modular Infotech Pvt. Ltd.",
    "website": "http://www.modular-infotech.com/",
    "hq": "Pune",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Pune",
    "sector": "Other",
    "lat": 18.521111111,
    "lng": 73.855277777,
    "source": "http://www.wikidata.org/entity/Q20726207"
  },
  {
    "slug": "telangana-state-industrial-infrastructure-corporation",
    "name": "Telangana State Industrial Infrastructure Corporation",
    "website": "http://tsiic.telangana.gov.in",
    "hq": "Hyderabad",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Hyderabad",
    "sector": "Other",
    "lat": 17.361666666,
    "lng": 78.474722222,
    "source": "http://www.wikidata.org/entity/Q19605133"
  },
  {
    "slug": "aegis-protocol",
    "name": "Aegis Protocol",
    "website": "https://aegisprotocol.in",
    "hq": "Hyderabad",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Hyderabad",
    "sector": "Other",
    "lat": 17.361666666,
    "lng": 78.474722222,
    "source": "http://www.wikidata.org/entity/Q138783462"
  },
  {
    "slug": "hoho-goa",
    "name": "HOHO Goa",
    "website": "http://hohogoa.com/",
    "hq": "Pune",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Pune",
    "sector": "Other",
    "lat": 18.521111111,
    "lng": 73.855277777,
    "source": "http://www.wikidata.org/entity/Q30227653"
  },
  {
    "slug": "hetero-labs",
    "name": "Hetero Labs",
    "website": "http://www.heterodrugs.com",
    "hq": "Hyderabad",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Hyderabad",
    "sector": "Other",
    "lat": 17.361666666,
    "lng": 78.474722222,
    "source": "http://www.wikidata.org/entity/Q17054856"
  },
  {
    "slug": "telangana-state-power-generation-corporation-limited",
    "name": "Telangana State Power Generation Corporation Limited",
    "website": "http://tsgenco.telangana.gov.in/",
    "hq": "Hyderabad",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Hyderabad",
    "sector": "Other",
    "lat": 17.361666666,
    "lng": 78.474722222,
    "source": "http://www.wikidata.org/entity/Q18388424"
  },
  {
    "slug": "jk-agri-genetics-india",
    "name": "JK Agri Genetics (India)",
    "website": "http://www.jkseeds.net/jk/index.php",
    "hq": "Hyderabad",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Hyderabad",
    "sector": "Other",
    "lat": 17.361666666,
    "lng": 78.474722222,
    "source": "http://www.wikidata.org/entity/Q30262939"
  },
  {
    "slug": "abhishek-agarwal-arts",
    "name": "Abhishek Agarwal Arts",
    "website": "https://www.abhishekagarwalarts.com/",
    "hq": "Hyderabad",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Hyderabad",
    "sector": "Other",
    "lat": 17.361666666,
    "lng": 78.474722222,
    "source": "http://www.wikidata.org/entity/Q111262042"
  },
  {
    "slug": "sks-microfinance",
    "name": "SKS Microfinance",
    "website": "http://www.bfil.co.in/",
    "hq": "Hyderabad",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Hyderabad",
    "sector": "Other",
    "lat": 17.361666666,
    "lng": 78.474722222,
    "source": "http://www.wikidata.org/entity/Q17081137"
  },
  {
    "slug": "sipra-labs-india",
    "name": "Sipra Labs (India)",
    "website": "http://www.sipralabs.com/",
    "hq": "Hyderabad",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Hyderabad",
    "sector": "Other",
    "lat": 17.361666666,
    "lng": 78.474722222,
    "source": "http://www.wikidata.org/entity/Q30263008"
  },
  {
    "slug": "growell-india",
    "name": "Growell india",
    "website": "http://www.growell.com/",
    "hq": "Pune",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Pune",
    "sector": "Other",
    "lat": 18.521111111,
    "lng": 73.855277777,
    "source": "http://www.wikidata.org/entity/Q25245682"
  },
  {
    "slug": "primove-infrastructure-development-consultants-india",
    "name": "PriMove Infrastructure Development Consultants (India)",
    "website": "http://www.primoveindia.com/",
    "hq": "Pune",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Pune",
    "sector": "Other",
    "lat": 18.521111111,
    "lng": 73.855277777,
    "source": "http://www.wikidata.org/entity/Q30260648"
  },
  {
    "slug": "suven-life-sciences-india",
    "name": "Suven Life Sciences (India)",
    "website": "http://www.suven.com/",
    "hq": "Hyderabad",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Hyderabad",
    "sector": "Other",
    "lat": 17.361666666,
    "lng": 78.474722222,
    "source": "http://www.wikidata.org/entity/Q30263038"
  },
  {
    "slug": "crivly",
    "name": "Crivly",
    "website": "https://crivly.com/",
    "hq": "Hyderabad",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Hyderabad",
    "sector": "Other",
    "lat": 17.361666666,
    "lng": 78.474722222,
    "source": "http://www.wikidata.org/entity/Q114152032"
  },
  {
    "slug": "amazon-in",
    "name": "Amazon.in",
    "website": "http://amazon.in",
    "hq": "Hyderabad",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Hyderabad",
    "sector": "Other",
    "lat": 17.361666666,
    "lng": 78.474722222,
    "source": "http://www.wikidata.org/entity/Q123036952"
  },
  {
    "slug": "rainbow-hospitals",
    "name": "Rainbow Hospitals",
    "website": "http://www.rainbowhospitals.in/",
    "hq": "Hyderabad",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Hyderabad",
    "sector": "Other",
    "lat": 17.361666666,
    "lng": 78.474722222,
    "source": "http://www.wikidata.org/entity/Q19895624"
  },
  {
    "slug": "prosquad-consulting",
    "name": "ProSquad Consulting",
    "website": "https://prosquad.consulting",
    "hq": "Hyderabad",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Hyderabad",
    "sector": "Other",
    "lat": 17.361666666,
    "lng": 78.474722222,
    "source": "http://www.wikidata.org/entity/Q138412857"
  },
  {
    "slug": "mahindra-satyam",
    "name": "Mahindra Satyam",
    "website": "http://www.mahindrasatyam.com/",
    "hq": "Hyderabad",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Hyderabad",
    "sector": "Other",
    "lat": 17.361666666,
    "lng": 78.474722222,
    "source": "http://www.wikidata.org/entity/Q1405782"
  },
  {
    "slug": "ctrls",
    "name": "CtrlS",
    "website": "http://www.ctrls.in/",
    "hq": "Hyderabad",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Hyderabad",
    "sector": "Other",
    "lat": 17.361666666,
    "lng": 78.474722222,
    "source": "http://www.wikidata.org/entity/Q18712873"
  },
  {
    "slug": "sasha-skin-clinic",
    "name": "Sasha Skin Clinic",
    "website": "https://sashaclinics.com/",
    "hq": "Hyderabad",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Hyderabad",
    "sector": "Other",
    "lat": 17.361666666,
    "lng": 78.474722222,
    "source": "http://www.wikidata.org/entity/Q120483861"
  },
  {
    "slug": "garudavega",
    "name": "GarudaVega",
    "website": "https://www.garudavega.com/",
    "hq": "Hyderabad",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Hyderabad",
    "sector": "Other",
    "lat": 17.361666666,
    "lng": 78.474722222,
    "source": "http://www.wikidata.org/entity/Q129971655"
  },
  {
    "slug": "nanohealth",
    "name": "NanoHealth",
    "website": "http://www.nanohealth.in",
    "hq": "Hyderabad",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Hyderabad",
    "sector": "Other",
    "lat": 17.361666666,
    "lng": 78.474722222,
    "source": "http://www.wikidata.org/entity/Q19836941"
  },
  {
    "slug": "qulabs-software-india",
    "name": "Qulabs Software India",
    "website": "https://qulabs.ai/",
    "hq": "Hyderabad",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Hyderabad",
    "sector": "Other",
    "lat": 17.361666666,
    "lng": 78.474722222,
    "source": "http://www.wikidata.org/entity/Q126898463"
  },
  {
    "slug": "telangana-housing-board",
    "name": "Telangana Housing Board",
    "website": "http://hb.telangana.gov.in/",
    "hq": "Hyderabad",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Hyderabad",
    "sector": "Other",
    "lat": 17.361666666,
    "lng": 78.474722222,
    "source": "http://www.wikidata.org/entity/Q18636637"
  },
  {
    "slug": "amaron",
    "name": "Amaron",
    "website": "https://www.amaron.com/",
    "hq": "Hyderabad",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Hyderabad",
    "sector": "Other",
    "lat": 17.361666666,
    "lng": 78.474722222,
    "source": "http://www.wikidata.org/entity/Q127756841"
  },
  {
    "slug": "telangana-state-southern-power-distribution-company-limited",
    "name": "Telangana State Southern Power Distribution Company Limited",
    "website": "https://www.tssouthernpower.com/",
    "hq": "Hyderabad",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Hyderabad",
    "sector": "Other",
    "lat": 17.361666666,
    "lng": 78.474722222,
    "source": "http://www.wikidata.org/entity/Q18636641"
  },
  {
    "slug": "biogenex-india",
    "name": "BioGenex (India)",
    "website": "http://biogenex.com/",
    "hq": "Hyderabad",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Hyderabad",
    "sector": "Other",
    "lat": 17.361666666,
    "lng": 78.474722222,
    "source": "http://www.wikidata.org/entity/Q30260305"
  },
  {
    "slug": "instadwell",
    "name": "InstaDwell",
    "website": "https://instadwell.com/",
    "hq": "Hyderabad",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Hyderabad",
    "sector": "Other",
    "lat": 17.361666666,
    "lng": 78.474722222,
    "source": "http://www.wikidata.org/entity/Q134719493"
  },
  {
    "slug": "national-mineral-development-corporation",
    "name": "National Mineral Development Corporation",
    "website": "http://www.nmdc.co.in",
    "hq": "Hyderabad",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Hyderabad",
    "sector": "Other",
    "lat": 17.361666666,
    "lng": 78.474722222,
    "source": "http://www.wikidata.org/entity/Q952281"
  },
  {
    "slug": "kheyti",
    "name": "Kheyti",
    "website": "https://www.kheyti.com/",
    "hq": "Hyderabad",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Hyderabad",
    "sector": "Other",
    "lat": 17.361666666,
    "lng": 78.474722222,
    "source": "http://www.wikidata.org/entity/Q112133464"
  },
  {
    "slug": "24-frames-factory",
    "name": "24 Frames Factory",
    "website": "http://www.24framesfactory.com/",
    "hq": "Hyderabad",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Hyderabad",
    "sector": "Other",
    "lat": 17.361666666,
    "lng": 78.474722222,
    "source": "http://www.wikidata.org/entity/Q18205083"
  },
  {
    "slug": "pulla-reddy-sweets",
    "name": "Pulla Reddy Sweets",
    "website": "http://www.gpullareddysweets.com/",
    "hq": "Hyderabad",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Hyderabad",
    "sector": "Other",
    "lat": 17.361666666,
    "lng": 78.474722222,
    "source": "http://www.wikidata.org/entity/Q18340437"
  },
  {
    "slug": "indus-health-plus",
    "name": "Indus Health Plus",
    "website": "http://www.indushealthplus.com",
    "hq": "Pune",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Pune",
    "sector": "Other",
    "lat": 18.521111111,
    "lng": 73.855277777,
    "source": "http://www.wikidata.org/entity/Q24887785"
  },
  {
    "slug": "kaavios",
    "name": "Kaavios",
    "website": "https://www.kaavios.com/",
    "hq": "Pune",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Pune",
    "sector": "Other",
    "lat": 18.521111111,
    "lng": 73.855277777,
    "source": "http://www.wikidata.org/entity/Q134869821"
  },
  {
    "slug": "hindustan-antibiotics",
    "name": "Hindustan Antibiotics",
    "website": "http://www.hindantibiotics.gov.in",
    "hq": "Pune",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Pune",
    "sector": "Other",
    "lat": 18.521111111,
    "lng": 73.855277777,
    "source": "http://www.wikidata.org/entity/Q2723198"
  },
  {
    "slug": "persistent-systems",
    "name": "Persistent Systems",
    "website": "http://www.persistent.com/",
    "hq": "Pune",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Pune",
    "sector": "Other",
    "lat": 18.521111111,
    "lng": 73.855277777,
    "source": "http://www.wikidata.org/entity/Q7170401"
  },
  {
    "slug": "cyrus-poonawalla-group",
    "name": "Cyrus Poonawalla Group",
    "website": "https://www.cyruspoonawallagroup.com/",
    "hq": "Pune",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Pune",
    "sector": "Other",
    "lat": 18.521111111,
    "lng": 73.855277777,
    "source": "http://www.wikidata.org/entity/Q97498127"
  },
  {
    "slug": "automotive-research-association-of-india",
    "name": "Automotive Research Association of India",
    "website": "https://www.araiindia.com/",
    "hq": "Pune",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Pune",
    "sector": "Other",
    "lat": 18.521111111,
    "lng": 73.855277777,
    "source": "http://www.wikidata.org/entity/Q4826715"
  },
  {
    "slug": "maclab",
    "name": "MacLab",
    "website": "https://maclab.co.in",
    "hq": "Pune",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Pune",
    "sector": "Other",
    "lat": 18.521111111,
    "lng": 73.855277777,
    "source": "http://www.wikidata.org/entity/Q140051802"
  },
  {
    "slug": "vizabyte-llp",
    "name": "Vizabyte LLP",
    "website": "http://www.vizabyte.com",
    "hq": "Pune",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Pune",
    "sector": "Other",
    "lat": 18.521111111,
    "lng": 73.855277777,
    "source": "http://www.wikidata.org/entity/Q39137040"
  },
  {
    "slug": "kumar-properties",
    "name": "Kumar Properties",
    "website": "https://www.kumarworld.com/",
    "hq": "Pune",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Pune",
    "sector": "Other",
    "lat": 18.521111111,
    "lng": 73.855277777,
    "source": "http://www.wikidata.org/entity/Q106572473"
  },
  {
    "slug": "tata-research-development-and-design-centre",
    "name": "Tata Research Development and Design Centre",
    "website": "http://www.tcs-trddc.com",
    "hq": "Pune",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Pune",
    "sector": "Other",
    "lat": 18.521111111,
    "lng": 73.855277777,
    "source": "http://www.wikidata.org/entity/Q7687824"
  },
  {
    "slug": "tata-technologies",
    "name": "Tata Technologies",
    "website": "http://www.tatatechnologies.com",
    "hq": "Pune",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Pune",
    "sector": "Other",
    "lat": 18.521111111,
    "lng": 73.855277777,
    "source": "http://www.wikidata.org/entity/Q7687835"
  },
  {
    "slug": "harbinger-knowledge-products",
    "name": "Harbinger Knowledge Products",
    "website": "http://www.harbingerknowledge.com/",
    "hq": "Pune",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Pune",
    "sector": "Other",
    "lat": 18.521111111,
    "lng": 73.855277777,
    "source": "http://www.wikidata.org/entity/Q5654492"
  },
  {
    "slug": "sterlite-technologies",
    "name": "Sterlite Technologies",
    "website": "http://www.sterlitetechnologies.com",
    "hq": "Pune",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Pune",
    "sector": "Other",
    "lat": 18.521111111,
    "lng": 73.855277777,
    "source": "http://www.wikidata.org/entity/Q7611502"
  },
  {
    "slug": "maharashtra-knowledge-corporation-limited",
    "name": "Maharashtra Knowledge Corporation Limited",
    "website": "http://www.mkcl.org/",
    "hq": "Pune",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Pune",
    "sector": "Other",
    "lat": 18.521111111,
    "lng": 73.855277777,
    "source": "http://www.wikidata.org/entity/Q6733342"
  },
  {
    "slug": "ubisoft-pune",
    "name": "Ubisoft Pune",
    "website": "https://www.ubisoft.com/en-US/studio/pune.aspx",
    "hq": "Pune",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Pune",
    "sector": "Other",
    "lat": 18.521111111,
    "lng": 73.855277777,
    "source": "http://www.wikidata.org/entity/Q15635619"
  },
  {
    "slug": "football-synergy",
    "name": "Football Synergy",
    "website": "http://www.footballsynergy.com",
    "hq": "Pune",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Pune",
    "sector": "Other",
    "lat": 18.521111111,
    "lng": 73.855277777,
    "source": "http://www.wikidata.org/entity/Q56761114"
  },
  {
    "slug": "kirloskar-brothers-ltd",
    "name": "Kirloskar Brothers Ltd",
    "website": "http://www.kirloskarpumps.com/",
    "hq": "Pune",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Pune",
    "sector": "Other",
    "lat": 18.521111111,
    "lng": 73.855277777,
    "source": "http://www.wikidata.org/entity/Q6415912"
  },
  {
    "slug": "satmat-group",
    "name": "Satmat Group",
    "website": "https://satmatgroup.com",
    "hq": "Pune",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Pune",
    "sector": "Other",
    "lat": 18.521111111,
    "lng": 73.855277777,
    "source": "http://www.wikidata.org/entity/Q116783628"
  },
  {
    "slug": "bajaj-group",
    "name": "Bajaj Group",
    "website": "http://www.bajajgroup.org/",
    "hq": "Pune",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Pune",
    "sector": "Other",
    "lat": 18.521111111,
    "lng": 73.855277777,
    "source": "http://www.wikidata.org/entity/Q4848823"
  },
  {
    "slug": "bajaj-finserv",
    "name": "Bajaj Finserv",
    "website": "http://www.bajajfinserv.in/",
    "hq": "Pune",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Pune",
    "sector": "Other",
    "lat": 18.521111111,
    "lng": 73.855277777,
    "source": "http://www.wikidata.org/entity/Q18636352"
  },
  {
    "slug": "kalyani-group",
    "name": "Kalyani Group",
    "website": "http://www.kalyanigroup.com/",
    "hq": "Pune",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Pune",
    "sector": "Other",
    "lat": 18.521111111,
    "lng": 73.855277777,
    "source": "http://www.wikidata.org/entity/Q6354966"
  },
  {
    "slug": "sgurrenergy",
    "name": "SgurrEnergy",
    "website": "https://www.sgurrenergy.com/",
    "hq": "Pune",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Pune",
    "sector": "Other",
    "lat": 18.521111111,
    "lng": 73.855277777,
    "source": "http://www.wikidata.org/entity/Q7459798"
  },
  {
    "slug": "zensar-technologies",
    "name": "Zensar Technologies",
    "website": "http://www.zensar.com/",
    "hq": "Pune",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Pune",
    "sector": "Other",
    "lat": 18.521111111,
    "lng": 73.855277777,
    "source": "http://www.wikidata.org/entity/Q8069225"
  },
  {
    "slug": "attron-automotive",
    "name": "Attron automotive",
    "website": "https://www.attronautomotive.com/",
    "hq": "Pune",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Pune",
    "sector": "Other",
    "lat": 18.521111111,
    "lng": 73.855277777,
    "source": "http://www.wikidata.org/entity/Q136717764"
  },
  {
    "slug": "the-shamrao-vithal-co-operative-bank-ltd",
    "name": "The Shamrao Vithal Co-operative Bank Ltd.",
    "website": "http://www.svcbank.com",
    "hq": "Pune",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Pune",
    "sector": "Other",
    "lat": 18.521111111,
    "lng": 73.855277777,
    "source": "http://www.wikidata.org/entity/Q17137309"
  },
  {
    "slug": "pioneer-industrial-instruments",
    "name": "Pioneer Industrial Instruments",
    "website": "https://www.pioneercabletrays.com",
    "hq": "Pune",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Pune",
    "sector": "Other",
    "lat": 18.521111111,
    "lng": 73.855277777,
    "source": "http://www.wikidata.org/entity/Q141003543"
  },
  {
    "slug": "venky-s",
    "name": "Venky's",
    "website": "http://www.venkys.com/archive/chicken/index.html",
    "hq": "Pune",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Pune",
    "sector": "Other",
    "lat": 18.521111111,
    "lng": 73.855277777,
    "source": "http://www.wikidata.org/entity/Q7920111"
  },
  {
    "slug": "thermax",
    "name": "Thermax",
    "website": "http://www.thermaxglobal.com",
    "hq": "Pune",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Pune",
    "sector": "Other",
    "lat": 18.521111111,
    "lng": 73.855277777,
    "source": "http://www.wikidata.org/entity/Q7783088"
  },
  {
    "slug": "softdel-systems",
    "name": "SoftDEL Systems",
    "website": "http://www.softdel.com/jp/default.asp",
    "hq": "Pune",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Pune",
    "sector": "Other",
    "lat": 18.521111111,
    "lng": 73.855277777,
    "source": "http://www.wikidata.org/entity/Q7553834"
  },
  {
    "slug": "cybage",
    "name": "Cybage",
    "website": "http://www.cybage.com/",
    "hq": "Pune",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Pune",
    "sector": "Other",
    "lat": 18.521111111,
    "lng": 73.855277777,
    "source": "http://www.wikidata.org/entity/Q5197649"
  },
  {
    "slug": "bonn-weiss-group",
    "name": "Bonn-Weiss Group",
    "website": "https://bwg.life/",
    "hq": "Pune",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Pune",
    "sector": "Other",
    "lat": 18.521111111,
    "lng": 73.855277777,
    "source": "http://www.wikidata.org/entity/Q140252557"
  },
  {
    "slug": "mylab-discovery-solutions",
    "name": "Mylab Discovery Solutions",
    "website": "https://mylabdiscoverysolutions.com/",
    "hq": "Pune",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Pune",
    "sector": "Other",
    "lat": 18.521111111,
    "lng": 73.855277777,
    "source": "http://www.wikidata.org/entity/Q88868798"
  },
  {
    "slug": "bank-of-maharashtra",
    "name": "Bank of Maharashtra",
    "website": "https://bankofmaharashtra.bank.in/",
    "hq": "Pune",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Pune",
    "sector": "Other",
    "lat": 18.521111111,
    "lng": 73.855277777,
    "source": "http://www.wikidata.org/entity/Q2004304"
  },
  {
    "slug": "volkswagen-india",
    "name": "Volkswagen India",
    "website": "http://www.volkswagen.co.in",
    "hq": "Pune",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Pune",
    "sector": "Other",
    "lat": 18.521111111,
    "lng": 73.855277777,
    "source": "http://www.wikidata.org/entity/Q7940325"
  },
  {
    "slug": "skoda-auto-volkswagen-india",
    "name": "Skoda Auto Volkswagen India",
    "website": "https://skoda-vw.co.in/",
    "hq": "Pune",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Pune",
    "sector": "Other",
    "lat": 18.521111111,
    "lng": 73.855277777,
    "source": "http://www.wikidata.org/entity/Q7940322"
  },
  {
    "slug": "indiacom",
    "name": "Indiacom",
    "website": "http://www.Indiacom.com",
    "hq": "Pune",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Pune",
    "sector": "Other",
    "lat": 18.521111111,
    "lng": 73.855277777,
    "source": "http://www.wikidata.org/entity/Q17056008"
  },
  {
    "slug": "computational-research-laboratories",
    "name": "Computational Research Laboratories",
    "website": "http://www.crlindia.com",
    "hq": "Pune",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Pune",
    "sector": "Other",
    "lat": 18.521111111,
    "lng": 73.855277777,
    "source": "http://www.wikidata.org/entity/Q5157291"
  },
  {
    "slug": "seagull-biosolutions-india",
    "name": "Seagull BioSolutions (India)",
    "website": "http://www.seagullbiosolutions.in/",
    "hq": "Pune",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Pune",
    "sector": "Other",
    "lat": 18.521111111,
    "lng": 73.855277777,
    "source": "http://www.wikidata.org/entity/Q30271869"
  },
  {
    "slug": "dynalec-controls-pvt-ltd",
    "name": "Dynalec Controls Pvt. Ltd.",
    "website": "http://dynaleccontrols.com/",
    "hq": "Pune",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Pune",
    "sector": "Other",
    "lat": 18.521111111,
    "lng": 73.855277777,
    "source": "http://www.wikidata.org/entity/Q106485505"
  },
  {
    "slug": "sg-analytics",
    "name": "SG Analytics",
    "website": "https://www.sganalytics.com/",
    "hq": "Pune",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Pune",
    "sector": "Other",
    "lat": 18.521111111,
    "lng": 73.855277777,
    "source": "http://www.wikidata.org/entity/Q140287891"
  },
  {
    "slug": "vitaminhaat",
    "name": "VitaminHaat",
    "website": "https://www.vitaminhaat.com",
    "hq": "Pune",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Pune",
    "sector": "Other",
    "lat": 18.521111111,
    "lng": 73.855277777,
    "source": "http://www.wikidata.org/entity/Q98143697"
  },
  {
    "slug": "v-h-group",
    "name": "V H Group",
    "website": "http://www.venkys.com",
    "hq": "Pune",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Pune",
    "sector": "Other",
    "lat": 18.521111111,
    "lng": 73.855277777,
    "source": "http://www.wikidata.org/entity/Q7907735"
  },
  {
    "slug": "faber-india",
    "name": "Faber India",
    "website": "https://dealers.faberindia.com/",
    "hq": "Pune",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Pune",
    "sector": "Other",
    "lat": 18.521111111,
    "lng": 73.855277777,
    "source": "http://www.wikidata.org/entity/Q127864696"
  },
  {
    "slug": "bajaj-life-insurance",
    "name": "Bajaj Life Insurance",
    "website": "https://www.bajajlifeinsurance.com/",
    "hq": "Pune",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Pune",
    "sector": "Other",
    "lat": 18.521111111,
    "lng": 73.855277777,
    "source": "http://www.wikidata.org/entity/Q4848816"
  },
  {
    "slug": "entryking",
    "name": "EntryKing",
    "website": "https://www.entryking.com/",
    "hq": "Pune",
    "industry": "company",
    "founded": null,
    "score": 14,
    "city": "Pune",
    "sector": "Other",
    "lat": 18.521111111,
    "lng": 73.855277777,
    "source": "http://www.wikidata.org/entity/Q113663140"
  }
] as const;
