export const directoryCompanies2 = [
  {
    "slug": "terraflock",
    "name": "Terraflock",
    "website": "https://terraflock.com",
    "hq": "Bihar",
    "industry": "Deep tech",
    "founded": 2025,
    "score": 11,
    "city": "India",
    "sector": "Deep Tech",
    "lat": 20.572699999999998,
    "lng": 78.9349
  },
  {
    "slug": "house-of-falguni",
    "name": "House of Falguni",
    "website": "https://www.houseoffalguni.com",
    "hq": "Ahmedabad",
    "industry": "fashion",
    "founded": 2025,
    "score": 11,
    "city": "Ahmedabad",
    "sector": "Fashion",
    "lat": 23.005000000000003,
    "lng": 72.5469
  },
  {
    "slug": "nyvo",
    "name": "NYVO",
    "website": "https://www.nyvo.money",
    "hq": "Bengaluru",
    "industry": "financial services",
    "founded": 2025,
    "score": 11,
    "city": "Bengaluru",
    "sector": "Financials",
    "lat": 12.957600000000001,
    "lng": 77.5736
  },
  {
    "slug": "syntaai",
    "name": "SyntaAI",
    "website": "https://syntaai.com",
    "hq": "Bengaluru",
    "industry": "computer security",
    "founded": 2025,
    "score": 11,
    "city": "Bengaluru",
    "sector": "Computer Security",
    "lat": 12.9611,
    "lng": 77.5771
  },
  {
    "slug": "nature-plates",
    "name": "Nature Plates",
    "website": "https://www.natureplates.in",
    "hq": "Morbi",
    "industry": "tableware",
    "founded": 2025,
    "score": 11,
    "city": "India",
    "sector": "Tableware",
    "lat": 20.586699999999997,
    "lng": 78.94890000000001
  },
  {
    "slug": "aestros",
    "name": "Aestros",
    "website": "https://aestros.com",
    "hq": "Gurgaon",
    "industry": "information technology consulting",
    "founded": 2025,
    "score": 11,
    "city": "Delhi NCR",
    "sector": "Information Technology Consulting",
    "lat": 28.456,
    "lng": 77.01610000000001
  },
  {
    "slug": "sweet-duet",
    "name": "Sweet Duet",
    "website": "https://www.sweetduet.in",
    "hq": "Hyderabad district",
    "industry": "human food",
    "founded": 2025,
    "score": 11,
    "city": "Hyderabad",
    "sector": "Human Food",
    "lat": 17.385,
    "lng": 78.4797
  },
  {
    "slug": "sa-fab",
    "name": "SA Fab",
    "website": "https://handblockprintsbagru.com/",
    "hq": "Bagru",
    "industry": "textile industry",
    "founded": 2024,
    "score": 11,
    "city": "India",
    "sector": "Textile",
    "lat": 20.597199999999997,
    "lng": 78.9594
  },
  {
    "slug": "devpunya",
    "name": "DevPunya",
    "website": "https://devpunya.com",
    "hq": "Rajasthan",
    "industry": "e-commerce",
    "founded": 2024,
    "score": 11,
    "city": "India",
    "sector": "E-Commerce",
    "lat": 20.6007,
    "lng": 78.9629
  },
  {
    "slug": "lumio",
    "name": "Lumio",
    "website": "https://lumio.co.in",
    "hq": "Bengaluru",
    "industry": "consumer electronics industry",
    "founded": 2024,
    "score": 11,
    "city": "Bengaluru",
    "sector": "Consumer Electronics",
    "lat": 12.9821,
    "lng": 77.5981
  },
  {
    "slug": "lendingleaf",
    "name": "LendingLeaf",
    "website": "https://lendingleaf.in",
    "hq": "Noida",
    "industry": "financial services",
    "founded": 2024,
    "score": 11,
    "city": "Delhi NCR",
    "sector": "Financials",
    "lat": 28.473499999999998,
    "lng": 77.0336
  },
  {
    "slug": "walonium-textile-llp",
    "name": "Walonium Textile LLP",
    "website": "https://www.waloniumtextile.com",
    "hq": "Morbi",
    "industry": "textile industry in India",
    "founded": 2023,
    "score": 11,
    "city": "India",
    "sector": "Textile In India",
    "lat": 20.611199999999997,
    "lng": 78.9734
  },
  {
    "slug": "draconic",
    "name": "Draconic",
    "website": "https://draconic.ai",
    "hq": "Bengaluru",
    "industry": "fintech",
    "founded": 2023,
    "score": 11,
    "city": "Bengaluru",
    "sector": "Fintech",
    "lat": 12.992600000000001,
    "lng": 77.6086
  },
  {
    "slug": "goldhartz",
    "name": "GoldHartz",
    "website": "https://goldhartz.co",
    "hq": "Jaipur district",
    "industry": "jewelry",
    "founded": 2022,
    "score": 11,
    "city": "Jaipur",
    "sector": "Jewelry",
    "lat": 26.8914,
    "lng": 75.8048
  },
  {
    "slug": "9ai",
    "name": "9AI",
    "website": "https://9ai.in/",
    "hq": "Udaipur",
    "industry": "artificial intelligence",
    "founded": 2022,
    "score": 11,
    "city": "India",
    "sector": "Artificial Intelligence",
    "lat": 20.5762,
    "lng": 78.9839
  },
  {
    "slug": "cvefy",
    "name": "CVefy",
    "website": "https://cvefy.com",
    "hq": "Pune",
    "industry": "career counseling",
    "founded": 2021,
    "score": 11,
    "city": "Pune",
    "sector": "Career Counseling",
    "lat": 18.5064,
    "lng": 73.8812
  },
  {
    "slug": "point-of-care-microfluidics",
    "name": "Point-of-Care Microfluidics",
    "website": "https://www.pointofcaremicrofluidics.com/",
    "hq": "Vellore",
    "industry": "biotechnology",
    "founded": 2021,
    "score": 11,
    "city": "India",
    "sector": "Biotechnology",
    "lat": 20.583199999999998,
    "lng": 78.99090000000001
  },
  {
    "slug": "bullalo",
    "name": "Bullalo",
    "website": "https://www.bullalo.com/",
    "hq": "Hyderabad",
    "industry": "technology company",
    "founded": 2021,
    "score": 11,
    "city": "Hyderabad",
    "sector": "Technology",
    "lat": 17.378,
    "lng": 78.4587
  },
  {
    "slug": "raykam-alloys-llp",
    "name": "Raykam Alloys LLP",
    "website": "https://raykamalloys.com/",
    "hq": "Mumbai",
    "industry": "iron and steel industry",
    "founded": 2021,
    "score": 11,
    "city": "Mumbai",
    "sector": "Iron And Steel",
    "lat": 19.0725,
    "lng": 72.8532
  },
  {
    "slug": "masarrati-it-studio",
    "name": "Masarrati IT Studio",
    "website": "https://masarrati.com",
    "hq": "Hyderabad",
    "industry": "software engineering",
    "founded": 2021,
    "score": 11,
    "city": "Hyderabad",
    "sector": "Software Engineering",
    "lat": 17.385,
    "lng": 78.4657
  },
  {
    "slug": "next-skills-360-edtech-private-limited",
    "name": "Next Skills 360 EdTech Private Limited",
    "website": "https://www.nextskills360.in",
    "hq": "Hyderabad",
    "industry": "educational technology",
    "founded": 2020,
    "score": 11,
    "city": "Hyderabad",
    "sector": "Educational Technology",
    "lat": 17.3885,
    "lng": 78.4692
  },
  {
    "slug": "ecofy",
    "name": "Ecofy",
    "website": "https://ecofy.io",
    "hq": "Aurangabad",
    "industry": "packaging industry",
    "founded": 2020,
    "score": 11,
    "city": "India",
    "sector": "Packaging",
    "lat": 20.6007,
    "lng": 78.94890000000001
  },
  {
    "slug": "jb-polypack-pvt-ltd",
    "name": "JB Polypack Pvt. Ltd.",
    "website": "https://www.jbpolypack.com/",
    "hq": "Mangrol (Surat) Taluka",
    "industry": "plastics industry",
    "founded": 2020,
    "score": 11,
    "city": "Ahmedabad",
    "sector": "Plastics",
    "lat": 23.033,
    "lng": 72.5609
  },
  {
    "slug": "benaka-gold-company",
    "name": "Benaka Gold Company",
    "website": "https://www.benakagoldcompany.com",
    "hq": "Bengaluru",
    "industry": "gold industry",
    "founded": 2020,
    "score": 11,
    "city": "Bengaluru",
    "sector": "Gold",
    "lat": 12.9856,
    "lng": 77.5876
  },
  {
    "slug": "jhaji-store",
    "name": "JhaJi Store",
    "website": "https://www.jhajistore.com",
    "hq": "Darbhanga",
    "industry": "food",
    "founded": 2020,
    "score": 11,
    "city": "India",
    "sector": "Food",
    "lat": 20.611199999999997,
    "lng": 78.9594
  },
  {
    "slug": "petrichor-investments",
    "name": "Petrichor Investments",
    "website": "https://www.petrichorinvestments.in/",
    "hq": "Hyderabad",
    "industry": "investment",
    "founded": 2020,
    "score": 11,
    "city": "Hyderabad",
    "sector": "Investment",
    "lat": 17.406000000000002,
    "lng": 78.4867
  },
  {
    "slug": "rkecom-services",
    "name": "RKeCom Services",
    "website": "https://rkecom.in",
    "hq": "Mumbai",
    "industry": "business intelligence",
    "founded": 2020,
    "score": 11,
    "city": "Mumbai",
    "sector": "Business Intelligence",
    "lat": 19.055,
    "lng": 72.8812
  },
  {
    "slug": "sciencefather",
    "name": "Sciencefather",
    "website": "https://sciencefather.com/",
    "hq": "Chennai",
    "industry": "academic publishing",
    "founded": 2019,
    "score": 11,
    "city": "Chennai",
    "sector": "Academic Publishing",
    "lat": 13.0652,
    "lng": 80.27770000000001
  },
  {
    "slug": "namya-press",
    "name": "Namya Press",
    "website": "https://namyapress.com/",
    "hq": "Delhi",
    "industry": "publishing",
    "founded": 2019,
    "score": 11,
    "city": "Delhi NCR",
    "sector": "Publishing",
    "lat": 28.4455,
    "lng": 77.0371
  },
  {
    "slug": "riticare-online-solutions-private-limited",
    "name": "Riticare Online Solutions Private Limited",
    "website": "https://ritikart.com",
    "hq": "Bhubaneswar",
    "industry": "technology",
    "founded": 2019,
    "score": 11,
    "city": "Bhubaneswar",
    "sector": "Technology",
    "lat": 20.2856,
    "lng": 85.8385
  },
  {
    "slug": "duradoor",
    "name": "Duradoor",
    "website": "https://www.duradoor.in",
    "hq": "Hyderabad",
    "industry": "industrial manufacturing",
    "founded": 2019,
    "score": 11,
    "city": "Hyderabad",
    "sector": "Industrial Manufacturing",
    "lat": 17.378,
    "lng": 78.5042
  },
  {
    "slug": "india-ipo",
    "name": "India IPO",
    "website": "https://www.indiaipo.in/",
    "hq": "Delhi",
    "industry": "Pinnacle Financial Solutions Ltd",
    "founded": 2018,
    "score": 11,
    "city": "Delhi NCR",
    "sector": "Pinnacle Financial Solutions Ltd",
    "lat": 28.456,
    "lng": 77.0476
  },
  {
    "slug": "enveu",
    "name": "Enveu",
    "website": "https://www.enveu.com",
    "hq": "Noida",
    "industry": "streaming media",
    "founded": 2017,
    "score": 11,
    "city": "Delhi NCR",
    "sector": "Streaming Media",
    "lat": 28.4595,
    "lng": 77.0511
  },
  {
    "slug": "esaf-small-finance-bank",
    "name": "ESAF Small Finance Bank",
    "website": "https://www.esaf.bank.in/",
    "hq": "Thrissur",
    "industry": "bank",
    "founded": 2017,
    "score": 11,
    "city": "India",
    "sector": "Bank",
    "lat": 20.597199999999997,
    "lng": 78.99090000000001
  },
  {
    "slug": "kansoft-solutions",
    "name": "Kansoft Solutions",
    "website": "https://kansoftware.com",
    "hq": "Udaipur",
    "industry": "software development process",
    "founded": 2017,
    "score": 11,
    "city": "India",
    "sector": "Software Development Process",
    "lat": 20.6007,
    "lng": 78.9349
  },
  {
    "slug": "gcosol-platforms-inc",
    "name": "Gcosol Platforms, Inc.",
    "website": "https://gcosol.com",
    "hq": "Hyderabad",
    "industry": "conglomerate",
    "founded": 2017,
    "score": 11,
    "city": "Hyderabad",
    "sector": "Conglomerate",
    "lat": 17.395500000000002,
    "lng": 78.4622
  },
  {
    "slug": "bellatrix-aerospace",
    "name": "Bellatrix Aerospace",
    "website": "https://www.bellatrix.aero/",
    "hq": "Bengaluru",
    "industry": "space industry",
    "founded": 2015,
    "score": 11,
    "city": "Bengaluru",
    "sector": "Space",
    "lat": 12.9856,
    "lng": 77.5736
  },
  {
    "slug": "madrasmindworks",
    "name": "MadrasMindWorks",
    "website": "https://madrasmindworks.com",
    "hq": "Chennai",
    "industry": "virtual reality",
    "founded": 2015,
    "score": 11,
    "city": "Chennai",
    "sector": "Virtual Reality",
    "lat": 13.100200000000001,
    "lng": 80.2532
  },
  {
    "slug": "sylvi",
    "name": "Sylvi",
    "website": "https://sylvi.in",
    "hq": "Surat",
    "industry": "watchmaking",
    "founded": 2015,
    "score": 11,
    "city": "Ahmedabad",
    "sector": "Watchmaking",
    "lat": 23.0435,
    "lng": 72.5574
  },
  {
    "slug": "lendbox",
    "name": "Lendbox",
    "website": "https://www.lendbox.in",
    "hq": "New Delhi",
    "industry": "fintech",
    "founded": 2015,
    "score": 11,
    "city": "Delhi NCR",
    "sector": "Fintech",
    "lat": 28.438499999999998,
    "lng": 77.01610000000001
  },
  {
    "slug": "velvex",
    "name": "Velvex",
    "website": "https://www.velvex.in/",
    "hq": "Mumbai",
    "industry": "diesel exhaust fluid",
    "founded": 2015,
    "score": 11,
    "city": "Mumbai",
    "sector": "Diesel Exhaust Fluid",
    "lat": 19.058500000000002,
    "lng": 72.8707
  },
  {
    "slug": "anemoi",
    "name": "Anemoi",
    "website": "https://www.anemoi.in",
    "hq": "Haryana",
    "industry": "personal protective equipment",
    "founded": 2015,
    "score": 11,
    "city": "India",
    "sector": "Personal Protective Equipment",
    "lat": 20.5797,
    "lng": 78.9594
  },
  {
    "slug": "adani-energy-solutions",
    "name": "Adani Energy Solutions",
    "website": "https://www.adanienergysolutions.com/",
    "hq": "Ahmedabad",
    "industry": "electricity supply company",
    "founded": 2013,
    "score": 11,
    "city": "Ahmedabad",
    "sector": "Electricity Supply",
    "lat": 23.012,
    "lng": 72.5714
  },
  {
    "slug": "elan-group",
    "name": "Elan Group",
    "website": "https://www.elanlimited.com/",
    "hq": "Gurgaon",
    "industry": "real estate development",
    "founded": 2013,
    "score": 11,
    "city": "Delhi NCR",
    "sector": "Real Estate Development",
    "lat": 28.452499999999997,
    "lng": 77.0301
  },
  {
    "slug": "bloomsbury-india",
    "name": "Bloomsbury India",
    "website": "https://www.bloomsbury.com/in/",
    "hq": "New Delhi",
    "industry": "publishing",
    "founded": 2012,
    "score": 11,
    "city": "Delhi NCR",
    "sector": "Publishing",
    "lat": 28.456,
    "lng": 77.0336
  },
  {
    "slug": "vertoz-limited",
    "name": "Vertoz Limited",
    "website": "https://vertoz.com",
    "hq": "India",
    "industry": "digital advertising",
    "founded": 2012,
    "score": 11,
    "city": "India",
    "sector": "Digital Advertising",
    "lat": 20.5937,
    "lng": 78.9734
  },
  {
    "slug": "hotelivate",
    "name": "Hotelivate",
    "website": "https://www.hotelivate.com/",
    "hq": "Gurgaon",
    "industry": "management consulting industry",
    "founded": 2011,
    "score": 11,
    "city": "Delhi NCR",
    "sector": "Management Consulting",
    "lat": 28.462999999999997,
    "lng": 77.0406
  },
  {
    "slug": "carnival-cinemas",
    "name": "Carnival Cinemas",
    "website": "https://www.carnivalcinemas.com",
    "hq": "Malad",
    "industry": "entertainment",
    "founded": 2010,
    "score": 11,
    "city": "India",
    "sector": "Entertainment",
    "lat": 20.6007,
    "lng": 78.9804
  },
  {
    "slug": "shri-chakradhar-publication",
    "name": "Shri Chakradhar Publication",
    "website": "https://ignouproject.com",
    "hq": "New Delhi",
    "industry": "education",
    "founded": 2010,
    "score": 11,
    "city": "Delhi NCR",
    "sector": "Education",
    "lat": 28.47,
    "lng": 77.0476
  },
  {
    "slug": "wonder-cement",
    "name": "Wonder cement",
    "website": "https://www.wondercement.com/",
    "hq": "Udaipur",
    "industry": "cement industry",
    "founded": 2010,
    "score": 11,
    "city": "India",
    "sector": "Cement",
    "lat": 20.607699999999998,
    "lng": 78.98740000000001
  },
  {
    "slug": "archer-infotech",
    "name": "Archer Infotech",
    "website": "https://archerinfotech.in",
    "hq": "Pune",
    "industry": "information technology",
    "founded": 2009,
    "score": 11,
    "city": "Pune",
    "sector": "Information Technology",
    "lat": 18.537899999999997,
    "lng": 73.88470000000001
  },
  {
    "slug": "q3259819",
    "name": "Q3259819",
    "website": "https://www.d2h.com/",
    "hq": "Mumbai",
    "industry": "subscription television",
    "founded": 2009,
    "score": 11,
    "city": "Mumbai",
    "sector": "Subscription Television",
    "lat": 19.097,
    "lng": 72.8497
  },
  {
    "slug": "aaron-impex",
    "name": "Aaron Impex",
    "website": "https://www.aaronimpex.com",
    "hq": "Moradabad",
    "industry": "cutlery",
    "founded": 2009,
    "score": 11,
    "city": "India",
    "sector": "Cutlery",
    "lat": 20.572699999999998,
    "lng": 78.9384
  },
  {
    "slug": "megaplast-india-pvt-ltd",
    "name": "Megaplast India Pvt. Ltd.",
    "website": "https://megaplast.in/",
    "hq": "Mumbai",
    "industry": "plastics industry",
    "founded": 2007,
    "score": 11,
    "city": "Mumbai",
    "sector": "Plastics",
    "lat": 19.058500000000002,
    "lng": 72.8567
  },
  {
    "slug": "kanaka-management-services",
    "name": "Kanaka Management Services",
    "website": "https://kms-group.com",
    "hq": "Bengaluru",
    "industry": "consulting",
    "founded": 2007,
    "score": 11,
    "city": "Bengaluru",
    "sector": "Consulting",
    "lat": 12.957600000000001,
    "lng": 77.5771
  },
  {
    "slug": "hg-walls-india-pvt-ltd",
    "name": "HG Walls India Pvt Ltd",
    "website": "https://www.hgwalls.in",
    "hq": "Chennai",
    "industry": "Facade engineering",
    "founded": 2007,
    "score": 11,
    "city": "Chennai",
    "sector": "Facade Engineering",
    "lat": 13.0722,
    "lng": 80.25670000000001
  },
  {
    "slug": "texture-clothing-company",
    "name": "Texture Clothing Company",
    "website": "https://textureclothingcompany.com/",
    "hq": "Tiruppur",
    "industry": "clothing industry",
    "founded": 2006,
    "score": 11,
    "city": "India",
    "sector": "Clothing",
    "lat": 20.586699999999997,
    "lng": 78.95240000000001
  },
  {
    "slug": "texture-clothing-company",
    "name": "Texture Clothing Company",
    "website": "https://textureclothing.in",
    "hq": "Tiruppur",
    "industry": "clothing industry",
    "founded": 2006,
    "score": 11,
    "city": "India",
    "sector": "Clothing",
    "lat": 20.5902,
    "lng": 78.9559
  },
  {
    "slug": "jivial-industries-limited",
    "name": "Jivial Industries Limited",
    "website": "https://www.jivialrailings.com",
    "hq": "Rajkot district",
    "industry": "industrial manufacturing",
    "founded": 2006,
    "score": 11,
    "city": "India",
    "sector": "Industrial Manufacturing",
    "lat": 20.5937,
    "lng": 78.9594
  },
  {
    "slug": "assam-gramin-bank",
    "name": "Assam Gramin Bank",
    "website": "https://agvb.bank.in/",
    "hq": "Guwahati",
    "industry": "financial services",
    "founded": 2006,
    "score": 11,
    "city": "Guwahati",
    "sector": "Financials",
    "lat": 26.148,
    "lng": 91.7362
  },
  {
    "slug": "balaji-enterprise",
    "name": "Balaji Enterprise",
    "website": "https://www.balajilabels.com",
    "hq": "Ahmedabad",
    "industry": "printing",
    "founded": 2006,
    "score": 11,
    "city": "Ahmedabad",
    "sector": "Printing",
    "lat": 23.029500000000002,
    "lng": 72.5749
  },
  {
    "slug": "fun-cinemas",
    "name": "Fun Cinemas",
    "website": "https://www.funcinemas.com/",
    "hq": "Jaipur",
    "industry": "entertainment",
    "founded": 2003,
    "score": 11,
    "city": "Jaipur",
    "sector": "Entertainment",
    "lat": 26.922900000000002,
    "lng": 75.7943
  },
  {
    "slug": "yes-bank",
    "name": "Yes Bank",
    "website": "https://www.yes.bank.in/",
    "hq": "Mumbai",
    "industry": "financial sector",
    "founded": 2003,
    "score": 11,
    "city": "Mumbai",
    "sector": "Financial Sector",
    "lat": 19.09,
    "lng": 72.8882
  },
  {
    "slug": "giiava-group",
    "name": "GIIAVA Group",
    "website": "https://giiava.com/",
    "hq": "Pune",
    "industry": "agriculture",
    "founded": 2003,
    "score": 11,
    "city": "Pune",
    "sector": "Agriculture",
    "lat": 18.537899999999997,
    "lng": 73.8707
  },
  {
    "slug": "springer-india",
    "name": "Springer India",
    "website": "https://www.springer.com/in",
    "hq": "Delhi",
    "industry": "academic publishing",
    "founded": 2002,
    "score": 11,
    "city": "Delhi NCR",
    "sector": "Academic Publishing",
    "lat": 28.4805,
    "lng": 77.0441
  },
  {
    "slug": "anand-rathi-wealth-limited",
    "name": "Anand Rathi Wealth Limited",
    "website": "https://www.anandrathiwealth.in/",
    "hq": "Mumbai",
    "industry": "financial services",
    "founded": 2002,
    "score": 11,
    "city": "Mumbai",
    "sector": "Financials",
    "lat": 19.055,
    "lng": 72.8987
  },
  {
    "slug": "adiance-technologies",
    "name": "Adiance Technologies",
    "website": "https://www.adiance.com/",
    "hq": "Ahmedabad",
    "industry": "closed-circuit television",
    "founded": 2002,
    "score": 11,
    "city": "Ahmedabad",
    "sector": "Closed-Circuit Television",
    "lat": 23.005000000000003,
    "lng": 72.5959
  },
  {
    "slug": "bandhan-bank",
    "name": "Bandhan Bank",
    "website": "https://www.bandhan.bank.in/",
    "hq": "Kolkata",
    "industry": "financial sector",
    "founded": 2001,
    "score": 11,
    "city": "Kolkata",
    "sector": "Financial Sector",
    "lat": 22.558600000000002,
    "lng": 88.3919
  },
  {
    "slug": "sbi-life-insurance-company-limited",
    "name": "SBI Life Insurance Company Limited",
    "website": "https://branches.sbilife.co.in/",
    "hq": "Mumbai",
    "industry": "insurance",
    "founded": 2001,
    "score": 11,
    "city": "Mumbai",
    "sector": "Insurance",
    "lat": 19.0655,
    "lng": 72.8497
  },
  {
    "slug": "sarvatra-technologies",
    "name": "Sarvatra Technologies",
    "website": "https://sarvatra.tech/",
    "hq": "Pune",
    "industry": "fintech",
    "founded": 2000,
    "score": 11,
    "city": "Pune",
    "sector": "Fintech",
    "lat": 18.513399999999997,
    "lng": 73.8322
  },
  {
    "slug": "mphasis",
    "name": "Mphasis",
    "website": "https://www.mphasis.com/",
    "hq": "Bengaluru",
    "industry": "IT service management",
    "founded": 2000,
    "score": 11,
    "city": "Bengaluru",
    "sector": "IT Management",
    "lat": 12.9681,
    "lng": 77.5736
  },
  {
    "slug": "infobeans-technologies-limited",
    "name": "InfoBeans Technologies Limited",
    "website": "https://www.infobeans.com/",
    "hq": "Indore",
    "industry": "information technology",
    "founded": 2000,
    "score": 11,
    "city": "Indore",
    "sector": "Information Technology",
    "lat": 22.7196,
    "lng": 75.8402
  },
  {
    "slug": "pace-iit-medical",
    "name": "PACE IIT & Medical",
    "website": "https://iitianspace.com/",
    "hq": "Andheri",
    "industry": "Colleges, Universities, and Professional Schools",
    "founded": 1999,
    "score": 11,
    "city": "India",
    "sector": "Colleges, Universities, And Professional",
    "lat": 20.597199999999997,
    "lng": 78.94890000000001
  },
  {
    "slug": "surveymonkey",
    "name": "SurveyMonkey",
    "website": "https://jp.surveymonkey.com/",
    "hq": "San Mateo",
    "industry": "online survey service",
    "founded": 1999,
    "score": 11,
    "city": "India",
    "sector": "Online Survey",
    "lat": 20.6007,
    "lng": 78.95240000000001
  },
  {
    "slug": "surveymonkey",
    "name": "SurveyMonkey",
    "website": "https://www.surveymonkey.com/",
    "hq": "San Mateo",
    "industry": "online survey service",
    "founded": 1999,
    "score": 11,
    "city": "India",
    "sector": "Online Survey",
    "lat": 20.6042,
    "lng": 78.9559
  },
  {
    "slug": "surveymonkey",
    "name": "SurveyMonkey",
    "website": "https://it.surveymonkey.com/",
    "hq": "San Mateo",
    "industry": "online survey service",
    "founded": 1999,
    "score": 11,
    "city": "India",
    "sector": "Online Survey",
    "lat": 20.607699999999998,
    "lng": 78.9594
  },
  {
    "slug": "surveymonkey",
    "name": "SurveyMonkey",
    "website": "https://da.surveymonkey.com/",
    "hq": "San Mateo",
    "industry": "online survey service",
    "founded": 1999,
    "score": 11,
    "city": "India",
    "sector": "Online Survey",
    "lat": 20.611199999999997,
    "lng": 78.9629
  },
  {
    "slug": "surveymonkey",
    "name": "SurveyMonkey",
    "website": "https://sv.surveymonkey.com/",
    "hq": "San Mateo",
    "industry": "online survey service",
    "founded": 1999,
    "score": 11,
    "city": "India",
    "sector": "Online Survey",
    "lat": 20.6147,
    "lng": 78.96640000000001
  },
  {
    "slug": "surveymonkey",
    "name": "SurveyMonkey",
    "website": "https://no.surveymonkey.com/",
    "hq": "San Mateo",
    "industry": "online survey service",
    "founded": 1999,
    "score": 11,
    "city": "India",
    "sector": "Online Survey",
    "lat": 20.572699999999998,
    "lng": 78.96990000000001
  },
  {
    "slug": "surveymonkey",
    "name": "SurveyMonkey",
    "website": "https://fi.surveymonkey.com/",
    "hq": "San Mateo",
    "industry": "online survey service",
    "founded": 1999,
    "score": 11,
    "city": "India",
    "sector": "Online Survey",
    "lat": 20.5762,
    "lng": 78.9734
  },
  {
    "slug": "surveymonkey",
    "name": "SurveyMonkey",
    "website": "https://ko.surveymonkey.com/",
    "hq": "San Mateo",
    "industry": "online survey service",
    "founded": 1999,
    "score": 11,
    "city": "India",
    "sector": "Online Survey",
    "lat": 20.5797,
    "lng": 78.9769
  },
  {
    "slug": "surveymonkey",
    "name": "SurveyMonkey",
    "website": "https://tr.surveymonkey.com/",
    "hq": "San Mateo",
    "industry": "online survey service",
    "founded": 1999,
    "score": 11,
    "city": "India",
    "sector": "Online Survey",
    "lat": 20.583199999999998,
    "lng": 78.9804
  },
  {
    "slug": "surveymonkey",
    "name": "SurveyMonkey",
    "website": "https://zh.surveymonkey.com/",
    "hq": "San Mateo",
    "industry": "online survey service",
    "founded": 1999,
    "score": 11,
    "city": "India",
    "sector": "Online Survey",
    "lat": 20.586699999999997,
    "lng": 78.9839
  },
  {
    "slug": "surveymonkey",
    "name": "SurveyMonkey",
    "website": "https://ru.surveymonkey.com/",
    "hq": "San Mateo",
    "industry": "online survey service",
    "founded": 1999,
    "score": 11,
    "city": "India",
    "sector": "Online Survey",
    "lat": 20.5902,
    "lng": 78.98740000000001
  },
  {
    "slug": "mindtree",
    "name": "Mindtree",
    "website": "https://www.mindtree.com/",
    "hq": "Bengaluru",
    "industry": "IT service management",
    "founded": 1999,
    "score": 11,
    "city": "Bengaluru",
    "sector": "IT Management",
    "lat": 12.9716,
    "lng": 77.6226
  },
  {
    "slug": "adani-wilmar",
    "name": "Adani Wilmar",
    "website": "https://www.awl.in",
    "hq": "Ahmedabad",
    "industry": "food processing",
    "founded": 1999,
    "score": 11,
    "city": "Ahmedabad",
    "sector": "Food Processing",
    "lat": 23.026,
    "lng": 72.54339999999999
  },
  {
    "slug": "moschip-technologies-limited",
    "name": "MosChip Technologies Limited",
    "website": "https://moschip.com/",
    "hq": "India",
    "industry": "artificial intelligence",
    "founded": 1999,
    "score": 11,
    "city": "India",
    "sector": "Artificial Intelligence",
    "lat": 20.6007,
    "lng": 78.9384
  },
  {
    "slug": "ahmad-web-solutions",
    "name": "Ahmad Web Solutions",
    "website": "https://www.ahmadwebsolutions.com/about-us.html",
    "hq": "New Delhi",
    "industry": "web development",
    "founded": 1999,
    "score": 11,
    "city": "Delhi NCR",
    "sector": "Web Development",
    "lat": 28.47,
    "lng": 77.0056
  },
  {
    "slug": "adani-ports-sez",
    "name": "Adani Ports & SEZ",
    "website": "https://www.adaniports.com/",
    "hq": "Ahmedabad",
    "industry": "port",
    "founded": 1998,
    "score": 11,
    "city": "Ahmedabad",
    "sector": "Port",
    "lat": 23.0365,
    "lng": 72.5539
  },
  {
    "slug": "astral",
    "name": "Astral",
    "website": "https://astralltd.com/",
    "hq": "Ahmedabad",
    "industry": "architecture",
    "founded": 1996,
    "score": 11,
    "city": "Ahmedabad",
    "sector": "Architecture",
    "lat": 23.04,
    "lng": 72.5574
  },
  {
    "slug": "astral",
    "name": "Astral",
    "website": "https://www.astralpipes.com/",
    "hq": "Ahmedabad",
    "industry": "architecture",
    "founded": 1996,
    "score": 11,
    "city": "Ahmedabad",
    "sector": "Architecture",
    "lat": 23.0435,
    "lng": 72.5609
  },
  {
    "slug": "india-infoline",
    "name": "India Infoline",
    "website": "https://www.iifl.com/",
    "hq": "Mumbai",
    "industry": "financial services",
    "founded": 1995,
    "score": 11,
    "city": "Mumbai",
    "sector": "Financials",
    "lat": 19.055,
    "lng": 72.8707
  },
  {
    "slug": "hdfc-bank",
    "name": "HDFC Bank",
    "website": "https://hdfc.bank.in/",
    "hq": "Mumbai",
    "industry": "economics of banking",
    "founded": 1994,
    "score": 11,
    "city": "Mumbai",
    "sector": "Economics Of Banking",
    "lat": 19.058500000000002,
    "lng": 72.8742
  },
  {
    "slug": "icici-bank",
    "name": "ICICI Bank",
    "website": "https://www.icici.bank.in/",
    "hq": "Mumbai City district",
    "industry": "financial sector",
    "founded": 1994,
    "score": 11,
    "city": "Mumbai",
    "sector": "Financial Sector",
    "lat": 19.062,
    "lng": 72.8777
  },
  {
    "slug": "indusind-bank",
    "name": "IndusInd Bank",
    "website": "https://www.indusind.bank.in/",
    "hq": "Mumbai",
    "industry": "financial sector",
    "founded": 1994,
    "score": 11,
    "city": "Mumbai",
    "sector": "Financial Sector",
    "lat": 19.0655,
    "lng": 72.8812
  },
  {
    "slug": "real-value-portfolio-management-marketing",
    "name": "Real Value Portfolio Management & Marketing",
    "website": "https://www.realvalueportfolio.com/",
    "hq": "Bharuch",
    "industry": "financial services",
    "founded": 1994,
    "score": 11,
    "city": "India",
    "sector": "Financials",
    "lat": 20.586699999999997,
    "lng": 78.96990000000001
  },
  {
    "slug": "showoffff",
    "name": "Showoffff",
    "website": "https://www.showoffff.in",
    "hq": "Bengaluru",
    "industry": "e-commerce",
    "founded": 1994,
    "score": 11,
    "city": "Bengaluru",
    "sector": "E-Commerce",
    "lat": 12.9681,
    "lng": 77.6051
  },
  {
    "slug": "elsevier",
    "name": "Elsevier",
    "website": "https://www.elsevier.com/",
    "hq": "Amsterdam",
    "industry": "publishing",
    "founded": 1993,
    "score": 11,
    "city": "India",
    "sector": "Publishing",
    "lat": 20.5937,
    "lng": 78.9769
  },
  {
    "slug": "vinay-enterprises",
    "name": "Vinay Enterprises",
    "website": "https://vinayenterprises.co.in",
    "hq": "Ahmedabad",
    "industry": "information technology",
    "founded": 1993,
    "score": 11,
    "city": "Ahmedabad",
    "sector": "Information Technology",
    "lat": 23.026,
    "lng": 72.5889
  },
  {
    "slug": "dixon-technologies",
    "name": "Dixon Technologies",
    "website": "https://www.dixoninfo.com",
    "hq": "Noida",
    "industry": "electronics manufacturing services",
    "founded": 1993,
    "score": 11,
    "city": "Delhi NCR",
    "sector": "Electronics Manufacturings",
    "lat": 28.4665,
    "lng": 77.0476
  },
  {
    "slug": "dialog",
    "name": "Dialog",
    "website": "https://www.dialog.lk/",
    "hq": "Colombo",
    "industry": "telecommunications industry",
    "founded": 1993,
    "score": 11,
    "city": "India",
    "sector": "Telecommunications",
    "lat": 20.6042,
    "lng": 78.98740000000001
  },
  {
    "slug": "harpercollins-publishers-india",
    "name": "HarperCollins Publishers India",
    "website": "https://harpercollins.co.in/",
    "hq": "Noida",
    "industry": "publishing",
    "founded": 1992,
    "score": 11,
    "city": "Delhi NCR",
    "sector": "Publishing",
    "lat": 28.473499999999998,
    "lng": 77.05460000000001
  },
  {
    "slug": "harish-puri-co",
    "name": "Harish Puri & Co.",
    "website": "https://sportsos.co.in",
    "hq": "Bengaluru",
    "industry": "sport management",
    "founded": 1992,
    "score": 11,
    "city": "Bengaluru",
    "sector": "Sport Management",
    "lat": 12.9891,
    "lng": 77.5666
  },
  {
    "slug": "heritage-foods",
    "name": "Heritage Foods",
    "website": "https://www.heritagefoods.in/",
    "hq": "Hyderabad",
    "industry": "agribusiness",
    "founded": 1992,
    "score": 11,
    "city": "Hyderabad",
    "sector": "Agribusiness",
    "lat": 17.406000000000002,
    "lng": 78.4622
  },
  {
    "slug": "vodafonein",
    "name": "VodafoneIN",
    "website": "https://www.vodafone.in/",
    "hq": "Mumbai",
    "industry": "telecommunications industry",
    "founded": 1992,
    "score": 11,
    "city": "Mumbai",
    "sector": "Telecommunications",
    "lat": 19.055,
    "lng": 72.8567
  },
  {
    "slug": "ajax-engineering",
    "name": "AJAX Engineering",
    "website": "https://www.ajax-engg.com/",
    "hq": "Peenya Industrial Area",
    "industry": "construction",
    "founded": 1992,
    "score": 11,
    "city": "India",
    "sector": "Construction",
    "lat": 20.5762,
    "lng": 78.9454
  },
  {
    "slug": "crossword-bookstores",
    "name": "Crossword Bookstores",
    "website": "https://www.crossword.in/",
    "hq": "Mumbai",
    "industry": "retail",
    "founded": 1992,
    "score": 11,
    "city": "Mumbai",
    "sector": "Retail",
    "lat": 19.062,
    "lng": 72.86370000000001
  },
  {
    "slug": "hcl-technologies",
    "name": "HCL Technologies",
    "website": "https://www.hcltech.com",
    "hq": "Noida",
    "industry": "information technology",
    "founded": 1991,
    "score": 11,
    "city": "Delhi NCR",
    "sector": "Information Technology",
    "lat": 28.448999999999998,
    "lng": 77.01610000000001
  },
  {
    "slug": "q137015469",
    "name": "Q137015469",
    "website": "https://www.biome-solutions.com/",
    "hq": "Bengaluru",
    "industry": "architecture",
    "founded": 1991,
    "score": 11,
    "city": "Bengaluru",
    "sector": "Architecture",
    "lat": 12.9646,
    "lng": 77.5876
  },
  {
    "slug": "axis-bank",
    "name": "Axis Bank",
    "website": "https://www.axis.bank.in/",
    "hq": "Mumbai",
    "industry": "financial sector",
    "founded": 1990,
    "score": 11,
    "city": "Mumbai",
    "sector": "Financial Sector",
    "lat": 19.0725,
    "lng": 72.8742
  },
  {
    "slug": "kpit-technologies",
    "name": "KPIT Technologies",
    "website": "https://www.kpit.com/",
    "hq": "Hyderabad",
    "industry": "IT service management",
    "founded": 1990,
    "score": 11,
    "city": "Hyderabad",
    "sector": "IT Management",
    "lat": 17.385,
    "lng": 78.4867
  },
  {
    "slug": "bharti-airtel",
    "name": "Bharti Airtel",
    "website": "https://www.airtel.com",
    "hq": "New Delhi",
    "industry": "telecommunications industry",
    "founded": 1990,
    "score": 11,
    "city": "Delhi NCR",
    "sector": "Telecommunications",
    "lat": 28.462999999999997,
    "lng": 77.0301
  },
  {
    "slug": "tempsens",
    "name": "Tempsens",
    "website": "https://tempsens.com/",
    "hq": "Udaipur",
    "industry": "industrial manufacturing",
    "founded": 1990,
    "score": 11,
    "city": "India",
    "sector": "Industrial Manufacturing",
    "lat": 20.6007,
    "lng": 78.96990000000001
  },
  {
    "slug": "londe-jewellers-gold-diamonds",
    "name": "Londe Jewellers Gold & Diamonds",
    "website": "https://londejewellers.com",
    "hq": "Nagpur",
    "industry": "jewelry",
    "founded": 1989,
    "score": 11,
    "city": "India",
    "sector": "Jewelry",
    "lat": 20.6042,
    "lng": 78.9734
  },
  {
    "slug": "ankit-pulps-boards-pvt-ltd",
    "name": "Ankit Pulps & Boards Pvt. Ltd.",
    "website": "https://www.celluloseankit.com/",
    "hq": "Nagpur",
    "industry": "pharmaceutical industry",
    "founded": 1988,
    "score": 11,
    "city": "India",
    "sector": "Pharmaceutical",
    "lat": 20.607699999999998,
    "lng": 78.9769
  },
  {
    "slug": "ndtv",
    "name": "NDTV",
    "website": "https://ndtv.in",
    "hq": "New Delhi",
    "industry": "mass media",
    "founded": 1988,
    "score": 11,
    "city": "Delhi NCR",
    "sector": "Mass Media",
    "lat": 28.476999999999997,
    "lng": 77.0441
  },
  {
    "slug": "ndtv",
    "name": "NDTV",
    "website": "https://www.ndtv.com",
    "hq": "New Delhi",
    "industry": "mass media",
    "founded": 1988,
    "score": 11,
    "city": "Delhi NCR",
    "sector": "Mass Media",
    "lat": 28.4805,
    "lng": 77.0476
  },
  {
    "slug": "adani-group",
    "name": "Adani Group",
    "website": "https://www.adani.com/",
    "hq": "Ahmedabad",
    "industry": "conglomerate",
    "founded": 1988,
    "score": 11,
    "city": "Ahmedabad",
    "sector": "Conglomerate",
    "lat": 23.0015,
    "lng": 72.5959
  },
  {
    "slug": "cottonworld",
    "name": "Cottonworld",
    "website": "https://cottonworld.net/",
    "hq": "Mumbai",
    "industry": "clothing industry",
    "founded": 1987,
    "score": 11,
    "city": "Mumbai",
    "sector": "Clothing",
    "lat": 19.058500000000002,
    "lng": 72.90570000000001
  },
  {
    "slug": "raj-comics",
    "name": "Raj Comics",
    "website": "https://www.rajcomics.net",
    "hq": "New Delhi",
    "industry": "comics industry",
    "founded": 1986,
    "score": 11,
    "city": "Delhi NCR",
    "sector": "Comics",
    "lat": 28.4455,
    "lng": 76.9986
  },
  {
    "slug": "buldana-urban-cooperative-credit-society",
    "name": "Buldana Urban Cooperative Credit Society",
    "website": "https://buldanaurban.in",
    "hq": "Buldhana",
    "industry": "financial sector",
    "founded": 1986,
    "score": 11,
    "city": "India",
    "sector": "Financial Sector",
    "lat": 20.583199999999998,
    "lng": 78.9384
  },
  {
    "slug": "tech-mahindra-india",
    "name": "Tech Mahindra India",
    "website": "https://www.techmahindra.com/en-in/",
    "hq": "Mumbai",
    "industry": "consulting industry",
    "founded": 1986,
    "score": 11,
    "city": "Mumbai",
    "sector": "Consulting",
    "lat": 19.069,
    "lng": 72.8567
  },
  {
    "slug": "gruh-finance",
    "name": "GRUH Finance",
    "website": "https://www.gruh.com/",
    "hq": "Ahmedabad",
    "industry": "economics of banking",
    "founded": 1986,
    "score": 11,
    "city": "Ahmedabad",
    "sector": "Economics Of Banking",
    "lat": 23.019000000000002,
    "lng": 72.5539
  },
  {
    "slug": "penguin-india",
    "name": "Penguin India",
    "website": "https://penguin.co.in/",
    "hq": "Noida",
    "industry": "publishing",
    "founded": 1985,
    "score": 11,
    "city": "Delhi NCR",
    "sector": "Publishing",
    "lat": 28.4595,
    "lng": 77.0126
  },
  {
    "slug": "kotak-mahindra-bank",
    "name": "Kotak Mahindra Bank",
    "website": "https://www.kotak.bank.in/",
    "hq": "Mumbai",
    "industry": "financial sector",
    "founded": 1985,
    "score": 11,
    "city": "Mumbai",
    "sector": "Financial Sector",
    "lat": 19.0795,
    "lng": 72.86720000000001
  },
  {
    "slug": "navbharat-water-pvt-ltd",
    "name": "Navbharat Water Pvt Ltd",
    "website": "https://navbharatwater.biz",
    "hq": "Andheri",
    "industry": "water treatment",
    "founded": 1984,
    "score": 11,
    "city": "India",
    "sector": "Water Treatment",
    "lat": 20.6007,
    "lng": 78.9559
  },
  {
    "slug": "hero-motocorp",
    "name": "Hero MotoCorp",
    "website": "https://www.heromotocorp.com/",
    "hq": "New Delhi",
    "industry": "automotive industry",
    "founded": 1984,
    "score": 11,
    "city": "Delhi NCR",
    "sector": "Automotive",
    "lat": 28.47,
    "lng": 77.0231
  },
  {
    "slug": "natco-pharma",
    "name": "Natco Pharma",
    "website": "https://natcopharma.site/",
    "hq": "Hyderabad",
    "industry": "pharmaceutical company",
    "founded": 1981,
    "score": 11,
    "city": "Hyderabad",
    "sector": "Pharmaceutical",
    "lat": 17.399,
    "lng": 78.4867
  },
  {
    "slug": "infosys-limited",
    "name": "Infosys limited",
    "website": "https://www.infosys.com/",
    "hq": "Bengaluru",
    "industry": "IT service management",
    "founded": 1981,
    "score": 11,
    "city": "Bengaluru",
    "sector": "IT Management",
    "lat": 12.9891,
    "lng": 77.5981
  },
  {
    "slug": "maruti-suzuki",
    "name": "Maruti Suzuki",
    "website": "https://www.marutisuzuki.com/",
    "hq": "New Delhi",
    "industry": "automotive industry",
    "founded": 1981,
    "score": 11,
    "city": "Delhi NCR",
    "sector": "Automotive",
    "lat": 28.4805,
    "lng": 77.0336
  },
  {
    "slug": "shanker-agencies-private-limited",
    "name": "Shanker Agencies Private Limited",
    "website": "https://www.shankeragencies.com/",
    "hq": "Shahdara",
    "industry": "refractory",
    "founded": 1980,
    "score": 11,
    "city": "India",
    "sector": "Refractory",
    "lat": 20.572699999999998,
    "lng": 78.9734
  },
  {
    "slug": "hyderabad-book-trust",
    "name": "Hyderabad Book Trust",
    "website": "https://hyderabadbooktrust.com",
    "hq": "Hyderabad",
    "industry": "publishing",
    "founded": 1980,
    "score": 11,
    "city": "Hyderabad",
    "sector": "Publishing",
    "lat": 17.367500000000003,
    "lng": 78.5007
  },
  {
    "slug": "gujarat-gas-limited",
    "name": "Gujarat Gas Limited",
    "website": "https://www.gujaratgas.com",
    "hq": "Ahmedabad",
    "industry": "petroleum industry",
    "founded": 1980,
    "score": 11,
    "city": "Ahmedabad",
    "sector": "Petroleum",
    "lat": 23.0085,
    "lng": 72.5889
  },
  {
    "slug": "tira",
    "name": "Tira",
    "website": "http://www.tirabeauty.com",
    "hq": "Mumbai",
    "industry": "cosmetics industry",
    "founded": 2023,
    "score": 10,
    "city": "Mumbai",
    "sector": "Cosmetics",
    "lat": 19.0655,
    "lng": 72.8987
  },
  {
    "slug": "odisha-coal-and-power-limited",
    "name": "Odisha Coal and Power Limited",
    "website": "http://www.ocpl.org.in/",
    "hq": "Bhubaneswar",
    "industry": "mining of coal",
    "founded": 2015,
    "score": 10,
    "city": "Bhubaneswar",
    "sector": "Mining Of Coal",
    "lat": 20.289099999999998,
    "lng": 85.849
  },
  {
    "slug": "dsm-fresh-foods-pvt-ltd",
    "name": "DSM Fresh Foods Pvt Ltd",
    "website": "http://www.zappfresh.com/",
    "hq": "Delhi",
    "industry": "retail",
    "founded": 2015,
    "score": 10,
    "city": "Delhi NCR",
    "sector": "Retail",
    "lat": 28.456,
    "lng": 77.05460000000001
  },
  {
    "slug": "mypoolin",
    "name": "MyPoolin",
    "website": "http://mypoolin.com/",
    "hq": "Dwarka",
    "industry": "mobile payment",
    "founded": 2014,
    "score": 10,
    "city": "India",
    "sector": "Mobile Payment",
    "lat": 20.5937,
    "lng": 78.9349
  },
  {
    "slug": "creo",
    "name": "CREO",
    "website": "http://www.creosense.com",
    "hq": "Bengaluru",
    "industry": "consumer electronics industry",
    "founded": 2013,
    "score": 10,
    "city": "Bengaluru",
    "sector": "Consumer Electronics",
    "lat": 12.975100000000001,
    "lng": 77.5701
  },
  {
    "slug": "bhartiya-mahila-bank",
    "name": "Bhartiya Mahila Bank",
    "website": "http://www.bhartiyamahilabank.com/",
    "hq": "New Delhi",
    "industry": "financial sector",
    "founded": 2013,
    "score": 10,
    "city": "Delhi NCR",
    "sector": "Financial Sector",
    "lat": 28.4665,
    "lng": 77.0056
  },
  {
    "slug": "bhartiya-mahila-bank",
    "name": "Bhartiya Mahila Bank",
    "website": "http://www.bmb.co.in/",
    "hq": "New Delhi",
    "industry": "financial sector",
    "founded": 2013,
    "score": 10,
    "city": "Delhi NCR",
    "sector": "Financial Sector",
    "lat": 28.47,
    "lng": 77.0091
  },
  {
    "slug": "dhruva-space",
    "name": "Dhruva Space",
    "website": "http://www.dhruvaspace.com/",
    "hq": "Hyderabad",
    "industry": "space industry",
    "founded": 2012,
    "score": 10,
    "city": "Hyderabad",
    "sector": "Space",
    "lat": 17.399,
    "lng": 78.4727
  },
  {
    "slug": "vishal-film-factory",
    "name": "Vishal Film Factory",
    "website": "http://vishalfilmfactory.com/",
    "hq": "Chennai",
    "industry": "entertainment",
    "founded": 2012,
    "score": 10,
    "city": "Chennai",
    "sector": "Entertainment",
    "lat": 13.100200000000001,
    "lng": 80.26020000000001
  },
  {
    "slug": "mukta-a2-cinemas",
    "name": "Mukta A2 Cinemas",
    "website": "http://www.muktaa2cinemas.com",
    "hq": "Mumbai",
    "industry": "entertainment",
    "founded": 2011,
    "score": 10,
    "city": "Mumbai",
    "sector": "Entertainment",
    "lat": 19.097,
    "lng": 72.8707
  },
  {
    "slug": "sufi-comics",
    "name": "Sufi Comics",
    "website": "http://www.suficomics.com",
    "hq": "Bengaluru",
    "industry": "publishing",
    "founded": 2009,
    "score": 10,
    "city": "Bengaluru",
    "sector": "Publishing",
    "lat": 12.9506,
    "lng": 77.5911
  },
  {
    "slug": "milk-mantra",
    "name": "Milk Mantra",
    "website": "http://www.milkmantra.com/",
    "hq": "Odisha",
    "industry": "food industry",
    "founded": 2009,
    "score": 10,
    "city": "India",
    "sector": "Food",
    "lat": 20.5762,
    "lng": 78.9629
  },
  {
    "slug": "uniphore",
    "name": "Uniphore",
    "website": "http://www.uniphore.com/",
    "hq": "Tharamani",
    "industry": "software industry",
    "founded": 2008,
    "score": 10,
    "city": "India",
    "sector": "Software",
    "lat": 20.5797,
    "lng": 78.96640000000001
  },
  {
    "slug": "renault-india-private-limited",
    "name": "Renault India Private Limited",
    "website": "http://www.renault.co.in",
    "hq": "Chennai",
    "industry": "automotive industry",
    "founded": 2005,
    "score": 10,
    "city": "Chennai",
    "sector": "Automotive",
    "lat": 13.0722,
    "lng": 80.27770000000001
  },
  {
    "slug": "haier-india",
    "name": "Haier India",
    "website": "http://www.haier.com/in",
    "hq": "New Delhi",
    "industry": "home appliance industry",
    "founded": 2004,
    "score": 10,
    "city": "Delhi NCR",
    "sector": "Home Appliance",
    "lat": 28.452499999999997,
    "lng": 77.0371
  },
  {
    "slug": "images-bazaar",
    "name": "Images Bazaar",
    "website": "http://www.imagesbazaar.com",
    "hq": "New Delhi",
    "industry": "stock footage",
    "founded": 2003,
    "score": 10,
    "city": "Delhi NCR",
    "sector": "Stock Footage",
    "lat": 28.456,
    "lng": 77.0406
  },
  {
    "slug": "sbi-life-insurance-company-limited",
    "name": "SBI Life Insurance Company Limited",
    "website": "http://sbilife.co.in",
    "hq": "Mumbai",
    "industry": "insurance",
    "founded": 2001,
    "score": 10,
    "city": "Mumbai",
    "sector": "Insurance",
    "lat": 19.076,
    "lng": 72.8952
  },
  {
    "slug": "gvk",
    "name": "GVK",
    "website": "http://www.gvk.com/",
    "hq": "Hyderabad",
    "industry": "Conglomerate",
    "founded": 2000,
    "score": 10,
    "city": "Hyderabad",
    "sector": "Conglomerate",
    "lat": 17.3885,
    "lng": 78.5077
  },
  {
    "slug": "gvk",
    "name": "GVK",
    "website": "http://www.gvkbio.com/",
    "hq": "Hyderabad",
    "industry": "Conglomerate",
    "founded": 2000,
    "score": 10,
    "city": "Hyderabad",
    "sector": "Conglomerate",
    "lat": 17.392000000000003,
    "lng": 78.5112
  },
  {
    "slug": "surveymonkey",
    "name": "SurveyMonkey",
    "website": "http://fr.surveymonkey.com/",
    "hq": "San Mateo",
    "industry": "online survey service",
    "founded": 1999,
    "score": 10,
    "city": "India",
    "sector": "Online Survey",
    "lat": 20.6042,
    "lng": 78.99090000000001
  },
  {
    "slug": "surveymonkey",
    "name": "SurveyMonkey",
    "website": "http://nl.surveymonkey.com/",
    "hq": "San Mateo",
    "industry": "online survey service",
    "founded": 1999,
    "score": 10,
    "city": "India",
    "sector": "Online Survey",
    "lat": 20.607699999999998,
    "lng": 78.9349
  },
  {
    "slug": "surveymonkey",
    "name": "SurveyMonkey",
    "website": "http://es.surveymonkey.com/",
    "hq": "San Mateo",
    "industry": "online survey service",
    "founded": 1999,
    "score": 10,
    "city": "India",
    "sector": "Online Survey",
    "lat": 20.611199999999997,
    "lng": 78.9384
  },
  {
    "slug": "surveymonkey",
    "name": "SurveyMonkey",
    "website": "http://pt.surveymonkey.com/",
    "hq": "San Mateo",
    "industry": "online survey service",
    "founded": 1999,
    "score": 10,
    "city": "India",
    "sector": "Online Survey",
    "lat": 20.6147,
    "lng": 78.9419
  },
  {
    "slug": "surveymonkey",
    "name": "SurveyMonkey",
    "website": "http://de.surveymonkey.com",
    "hq": "San Mateo",
    "industry": "online survey service",
    "founded": 1999,
    "score": 10,
    "city": "India",
    "sector": "Online Survey",
    "lat": 20.572699999999998,
    "lng": 78.9454
  },
  {
    "slug": "tv-today-network",
    "name": "TV Today Network",
    "website": "http://www.indiatodaygroup.com/new-site/television.html",
    "hq": "Delhi",
    "industry": "broadcasting",
    "founded": 1999,
    "score": 10,
    "city": "Delhi NCR",
    "sector": "Broadcasting",
    "lat": 28.442,
    "lng": 77.0126
  },
  {
    "slug": "tanla",
    "name": "TANLA",
    "website": "http://www.tanla.com",
    "hq": "Hyderabad",
    "industry": "telecommunications",
    "founded": 1999,
    "score": 10,
    "city": "Hyderabad",
    "sector": "Telecommunications",
    "lat": 17.371000000000002,
    "lng": 78.4762
  },
  {
    "slug": "bharat-biotech-international",
    "name": "Bharat Biotech International",
    "website": "http://www.bharatbiotech.com/",
    "hq": "Hyderabad",
    "industry": "biotechnology",
    "founded": 1996,
    "score": 10,
    "city": "Hyderabad",
    "sector": "Biotechnology",
    "lat": 17.3745,
    "lng": 78.4797
  },
  {
    "slug": "reliance-power",
    "name": "Reliance Power",
    "website": "http://www.reliancepower.co.in/home.htm",
    "hq": "Navi Mumbai",
    "industry": "electricity supply company",
    "founded": 1995,
    "score": 10,
    "city": "Mumbai",
    "sector": "Electricity Supply",
    "lat": 19.069,
    "lng": 72.8742
  },
  {
    "slug": "sify",
    "name": "Sify",
    "website": "http://corporate.sify.com/",
    "hq": "Tharamani",
    "industry": "Internet",
    "founded": 1995,
    "score": 10,
    "city": "India",
    "sector": "Internet",
    "lat": 20.5902,
    "lng": 78.9629
  },
  {
    "slug": "ht-media",
    "name": "HT Media",
    "website": "http://www.htmedia.in",
    "hq": "Delhi",
    "industry": "mass media",
    "founded": 1993,
    "score": 10,
    "city": "Delhi NCR",
    "sector": "Mass Media",
    "lat": 28.4595,
    "lng": 77.0301
  },
  {
    "slug": "quick-heal",
    "name": "Quick Heal",
    "website": "http://www.quickheal.co.in/",
    "hq": "Pune",
    "industry": "software industry",
    "founded": 1993,
    "score": 10,
    "city": "Pune",
    "sector": "Software",
    "lat": 18.523899999999998,
    "lng": 73.86370000000001
  },
  {
    "slug": "coca-cola-india",
    "name": "Coca-Cola India",
    "website": "http://www.coca-colaindia.com",
    "hq": "Atlanta",
    "industry": "fast-moving consumer goods",
    "founded": 1992,
    "score": 10,
    "city": "India",
    "sector": "Fast-Moving Consumer Goods",
    "lat": 20.6007,
    "lng": 78.9734
  },
  {
    "slug": "ramco-systems",
    "name": "Ramco Systems",
    "website": "http://www.ramco.com/",
    "hq": "Chennai",
    "industry": "enterprise software",
    "founded": 1992,
    "score": 10,
    "city": "Chennai",
    "sector": "Enterprise Software",
    "lat": 13.093200000000001,
    "lng": 80.2847
  },
  {
    "slug": "divi-s-laboratories",
    "name": "Divi's Laboratories",
    "website": "http://www.divislabs.com/",
    "hq": "Hyderabad",
    "industry": "pharmaceutical industry",
    "founded": 1990,
    "score": 10,
    "city": "Hyderabad",
    "sector": "Pharmaceutical",
    "lat": 17.399,
    "lng": 78.5042
  },
  {
    "slug": "jain-irrigation-systems-limited",
    "name": "Jain Irrigation Systems Limited",
    "website": "http://www.jains.com/",
    "hq": "Jalgaon",
    "industry": "agriculture",
    "founded": 1989,
    "score": 10,
    "city": "India",
    "sector": "Agriculture",
    "lat": 20.611199999999997,
    "lng": 78.9839
  },
  {
    "slug": "irh-press",
    "name": "IRH Press",
    "website": "http://www.irhpress.co.jp/",
    "hq": "Hiratsuka",
    "industry": "digital rights management",
    "founded": 1987,
    "score": 10,
    "city": "India",
    "sector": "Digital Rights Management",
    "lat": 20.6147,
    "lng": 78.98740000000001
  },
  {
    "slug": "balkrishna-industries",
    "name": "Balkrishna Industries",
    "website": "http://www.bkt-tires.com",
    "hq": "Mumbai",
    "industry": "tire",
    "founded": 1987,
    "score": 10,
    "city": "Mumbai",
    "sector": "Tire",
    "lat": 19.055,
    "lng": 72.90570000000001
  },
  {
    "slug": "pen-india-limited",
    "name": "Pen India Limited",
    "website": "http://penindia.in/",
    "hq": "Mumbai",
    "industry": "entertainment",
    "founded": 1987,
    "score": 10,
    "city": "Mumbai",
    "sector": "Entertainment",
    "lat": 19.058500000000002,
    "lng": 72.8497
  },
  {
    "slug": "samvardhana-motherson",
    "name": "Samvardhana Motherson",
    "website": "http://www.motherson.com/",
    "hq": "Bötzingen",
    "industry": "automotive industry",
    "founded": 1986,
    "score": 10,
    "city": "India",
    "sector": "Automotive",
    "lat": 20.5797,
    "lng": 78.9384
  },
  {
    "slug": "samvardhana-motherson",
    "name": "Samvardhana Motherson",
    "website": "http://www.smp-automotive.com/index.html",
    "hq": "Bötzingen",
    "industry": "automotive industry",
    "founded": 1986,
    "score": 10,
    "city": "India",
    "sector": "Automotive",
    "lat": 20.583199999999998,
    "lng": 78.9419
  },
  {
    "slug": "aurobindo-pharma",
    "name": "Aurobindo Pharma",
    "website": "http://www.aurobindo.com",
    "hq": "Hyderabad",
    "industry": "pharmaceutical industry",
    "founded": 1986,
    "score": 10,
    "city": "Hyderabad",
    "sector": "Pharmaceutical",
    "lat": 17.378,
    "lng": 78.4692
  },
  {
    "slug": "mahanagar-telephone-nigam",
    "name": "Mahanagar Telephone Nigam",
    "website": "http://www.mtnl.net.in/",
    "hq": "New Delhi",
    "industry": "telecommunications industry",
    "founded": 1986,
    "score": 10,
    "city": "Delhi NCR",
    "sector": "Telecommunications",
    "lat": 28.456,
    "lng": 77.0126
  },
  {
    "slug": "delta-corp-limited",
    "name": "Delta Corp Limited",
    "website": "http://www.deltacorp.in/",
    "hq": "Mumbai",
    "industry": "conglomerate",
    "founded": 1985,
    "score": 10,
    "city": "Mumbai",
    "sector": "Conglomerate",
    "lat": 19.076,
    "lng": 72.86720000000001
  },
  {
    "slug": "panacea-biotec",
    "name": "Panacea Biotec",
    "website": "http://www.panacea-biotec.com",
    "hq": "New Delhi",
    "industry": "pharmaceutical industry",
    "founded": 1984,
    "score": 10,
    "city": "Delhi NCR",
    "sector": "Pharmaceutical",
    "lat": 28.462999999999997,
    "lng": 77.0196
  },
  {
    "slug": "dr-reddy-s-laboratories",
    "name": "Dr. Reddy's Laboratories",
    "website": "http://www.drreddys.com/",
    "hq": "Hyderabad",
    "industry": "pharmaceutical industry",
    "founded": 1984,
    "score": 10,
    "city": "Hyderabad",
    "sector": "Pharmaceutical",
    "lat": 17.392000000000003,
    "lng": 78.4832
  },
  {
    "slug": "sun-pharmaceutical",
    "name": "Sun Pharmaceutical",
    "website": "http://www.sunpharma.com",
    "hq": "Mumbai",
    "industry": "pharmaceutical industry",
    "founded": 1983,
    "score": 10,
    "city": "Mumbai",
    "sector": "Pharmaceutical",
    "lat": 19.0865,
    "lng": 72.8777
  },
  {
    "slug": "blue-dart-express",
    "name": "Blue Dart Express",
    "website": "http://www.bluedart.com/",
    "hq": "Mumbai",
    "industry": "logistics",
    "founded": 1983,
    "score": 10,
    "city": "Mumbai",
    "sector": "Logistics",
    "lat": 19.09,
    "lng": 72.8812
  },
  {
    "slug": "accel",
    "name": "Accel",
    "website": "http://www.accel.com/",
    "hq": "Palo Alto",
    "industry": "venture capital",
    "founded": 1983,
    "score": 10,
    "city": "India",
    "sector": "Venture Capital",
    "lat": 20.611199999999997,
    "lng": 78.96990000000001
  },
  {
    "slug": "ratna-sagar-p-ltd",
    "name": "Ratna Sagar P.Ltd",
    "website": "http://ratnasagar.com/",
    "hq": "Mukherjee Nagar",
    "industry": "publishing",
    "founded": 1982,
    "score": 10,
    "city": "India",
    "sector": "Publishing",
    "lat": 20.6147,
    "lng": 78.9734
  },
  {
    "slug": "exim-bank-india",
    "name": "EXIM Bank India",
    "website": "http://www.eximbankindia.in/",
    "hq": "Mumbai",
    "industry": "economics of banking",
    "founded": 1982,
    "score": 10,
    "city": "Mumbai",
    "sector": "Economics Of Banking",
    "lat": 19.055,
    "lng": 72.8917
  },
  {
    "slug": "jsw-steel-ltd",
    "name": "JSW Steel Ltd",
    "website": "http://www.jsw.in/",
    "hq": "Mumbai",
    "industry": "iron and steel industry",
    "founded": 1982,
    "score": 10,
    "city": "Mumbai",
    "sector": "Iron And Steel",
    "lat": 19.058500000000002,
    "lng": 72.8952
  },
  {
    "slug": "niit",
    "name": "NIIT",
    "website": "http://www.niit.com/",
    "hq": "New Delhi",
    "industry": "higher education",
    "founded": 1981,
    "score": 10,
    "city": "Delhi NCR",
    "sector": "Higher Education",
    "lat": 28.4455,
    "lng": 77.0476
  },
  {
    "slug": "pnv-nuts-private-limited",
    "name": "PNV Nuts Private Limited",
    "website": "https://pnvnuts.com",
    "hq": "Jammu & Kashmir",
    "industry": "Retail trade",
    "founded": null,
    "score": 9,
    "city": "India",
    "sector": "Retail Trade",
    "lat": 20.583199999999998,
    "lng": 78.98740000000001
  },
  {
    "slug": "functional-foods-pvt-ltd",
    "name": "Functional Foods Pvt Ltd",
    "website": "https://www.glp1supportplus.com",
    "hq": "Chennai",
    "industry": "nutraceutical",
    "founded": null,
    "score": 9,
    "city": "Chennai",
    "sector": "Nutraceutical",
    "lat": 13.075700000000001,
    "lng": 80.29870000000001
  },
  {
    "slug": "net-access-internet-india-pvt-ltd",
    "name": "Net Access Internet India Pvt. Ltd.",
    "website": "https://netaccessinternet.com/",
    "hq": "Pune",
    "industry": "telecommunications",
    "founded": null,
    "score": 9,
    "city": "Pune",
    "sector": "Telecommunications",
    "lat": 18.5169,
    "lng": 73.8287
  },
  {
    "slug": "jana-small-finance-bank",
    "name": "Jana Small Finance Bank",
    "website": "https://www.jana.bank.in/",
    "hq": "Bengaluru",
    "industry": "small finance bank",
    "founded": null,
    "score": 9,
    "city": "Bengaluru",
    "sector": "Small Finance Bank",
    "lat": 12.9716,
    "lng": 77.5701
  },
  {
    "slug": "centreal-bazaar",
    "name": "Centreal Bazaar",
    "website": "https://www.centrealbazaar.com",
    "hq": "Kizhakkambalam",
    "industry": "retail",
    "founded": null,
    "score": 9,
    "city": "India",
    "sector": "Retail",
    "lat": 20.597199999999997,
    "lng": 78.9419
  },
  {
    "slug": "klm-infra-projects",
    "name": "KLM Infra Projects",
    "website": "https://klmprojects.in/",
    "hq": "Hyderabad",
    "industry": "real estate services",
    "founded": null,
    "score": 9,
    "city": "Hyderabad",
    "sector": "Real Estates",
    "lat": 17.392000000000003,
    "lng": 78.4692
  },
  {
    "slug": "fly-it-solution",
    "name": "Fly IT Solution",
    "website": "https://flyitsolution.com",
    "hq": "Mohali",
    "industry": "software industry",
    "founded": null,
    "score": 9,
    "city": "Chandigarh",
    "sector": "Software",
    "lat": 30.7438,
    "lng": 76.7654
  },
  {
    "slug": "paliram-carpets",
    "name": "Paliram Carpets",
    "website": "https://paliramcarpets.com/",
    "hq": "Mirzapur district",
    "industry": "rug making",
    "founded": null,
    "score": 9,
    "city": "India",
    "sector": "Rug Making",
    "lat": 20.607699999999998,
    "lng": 78.95240000000001
  },
  {
    "slug": "mohit-road-carriers",
    "name": "Mohit Road Carriers",
    "website": "https://mohitroadcarriers.com",
    "hq": "Ahmedabad",
    "industry": "transport industry",
    "founded": null,
    "score": 9,
    "city": "Ahmedabad",
    "sector": "Transport",
    "lat": 23.04,
    "lng": 72.56439999999999
  },
  {
    "slug": "dhani",
    "name": "Dhani",
    "website": "https://www.dhani.com/",
    "hq": "New Delhi",
    "industry": "fintech",
    "founded": null,
    "score": 9,
    "city": "Delhi NCR",
    "sector": "Fintech",
    "lat": 28.4805,
    "lng": 77.0231
  },
  {
    "slug": "doubtnut",
    "name": "Doubtnut",
    "website": "https://doubtnut.com/",
    "hq": "Gurgaon",
    "industry": "Internet",
    "founded": null,
    "score": 9,
    "city": "Delhi NCR",
    "sector": "Internet",
    "lat": 28.438499999999998,
    "lng": 77.0266
  },
  {
    "slug": "shubham-epc",
    "name": "Shubham EPC",
    "website": "https://shubham.biz/",
    "hq": "Pune",
    "industry": "construction industry",
    "founded": null,
    "score": 9,
    "city": "Pune",
    "sector": "Construction",
    "lat": 18.5029,
    "lng": 73.8602
  },
  {
    "slug": "hashcodex",
    "name": "Hashcodex",
    "website": "https://www.hashcodex.com/",
    "hq": "Madurai",
    "industry": "software industry",
    "founded": null,
    "score": 9,
    "city": "India",
    "sector": "Software",
    "lat": 20.5797,
    "lng": 78.96990000000001
  },
  {
    "slug": "hdgelabs",
    "name": "HDGElabs",
    "website": "https://hdgelabs.com",
    "hq": "Mumbai",
    "industry": "artificial intelligence",
    "founded": null,
    "score": 9,
    "city": "Mumbai",
    "sector": "Artificial Intelligence",
    "lat": 19.0655,
    "lng": 72.8882
  },
  {
    "slug": "bright-organik",
    "name": "Bright Organik",
    "website": "https://brightorganik.com/",
    "hq": "Pune",
    "industry": "agribusiness",
    "founded": null,
    "score": 9,
    "city": "Pune",
    "sector": "Agribusiness",
    "lat": 18.513399999999997,
    "lng": 73.8707
  }
] as const;

