export const directoryCompanies4 = [
  {
    "slug": "exchmarket",
    "name": "Exchmarket",
    "website": "https://exchmarket.net/",
    "hq": "Curaçao",
    "industry": "betting",
    "founded": 2020,
    "score": 11,
    "city": "India",
    "sector": "Betting",
    "lat": 20.553199999999997,
    "lng": 78.91340000000001
  },
  {
    "slug": "hello-health-group",
    "name": "Hello Health Group",
    "website": "https://hellodoktor.com/",
    "hq": "Singapore",
    "industry": "health",
    "founded": 2015,
    "score": 11,
    "city": "India",
    "sector": "Health",
    "lat": 20.557699999999997,
    "lng": 78.9179
  },
  {
    "slug": "hello-health-group",
    "name": "Hello Health Group",
    "website": "https://hellohealthgroup.com/",
    "hq": "Singapore",
    "industry": "health",
    "founded": 2015,
    "score": 11,
    "city": "India",
    "sector": "Health",
    "lat": 20.562199999999997,
    "lng": 78.92240000000001
  },
  {
    "slug": "hello-health-group",
    "name": "Hello Health Group",
    "website": "https://hellosehat.com/",
    "hq": "Singapore",
    "industry": "health",
    "founded": 2015,
    "score": 11,
    "city": "India",
    "sector": "Health",
    "lat": 20.566699999999997,
    "lng": 78.9269
  },
  {
    "slug": "hello-health-group",
    "name": "Hello Health Group",
    "website": "https://helloyishi.com.tw/",
    "hq": "Singapore",
    "industry": "health",
    "founded": 2015,
    "score": 11,
    "city": "India",
    "sector": "Health",
    "lat": 20.571199999999997,
    "lng": 78.93140000000001
  },
  {
    "slug": "hello-health-group",
    "name": "Hello Health Group",
    "website": "https://hellobacsi.com/",
    "hq": "Singapore",
    "industry": "telemedicine",
    "founded": 2015,
    "score": 11,
    "city": "India",
    "sector": "Telemedicine",
    "lat": 20.575699999999998,
    "lng": 78.9359
  },
  {
    "slug": "hello-health-group",
    "name": "Hello Health Group",
    "website": "https://hellodoctor.com.ph/",
    "hq": "Singapore",
    "industry": "telemedicine",
    "founded": 2015,
    "score": 11,
    "city": "India",
    "sector": "Telemedicine",
    "lat": 20.580199999999998,
    "lng": 78.94040000000001
  },
  {
    "slug": "avanti-cinema",
    "name": "Avanti Cinema",
    "website": "https://www.avanticinema.com",
    "hq": "Banjara Hills",
    "industry": "entertainment",
    "founded": 2013,
    "score": 11,
    "city": "India",
    "sector": "Entertainment",
    "lat": 20.584699999999998,
    "lng": 78.9449
  },
  {
    "slug": "cineman-productions",
    "name": "CineMan Productions",
    "website": "https://cineman.in",
    "hq": "Ahmedabad",
    "industry": "entertainment",
    "founded": 2010,
    "score": 11,
    "city": "Ahmedabad",
    "sector": "Entertainment",
    "lat": 23.018,
    "lng": 72.5579
  },
  {
    "slug": "behindwoods",
    "name": "Behindwoods",
    "website": "https://www.behindwoods.com/",
    "hq": "Chennai",
    "industry": "news media",
    "founded": 2004,
    "score": 11,
    "city": "Chennai",
    "sector": "News Media",
    "lat": 13.0827,
    "lng": 80.2617
  },
  {
    "slug": "network-18",
    "name": "Network 18",
    "website": "https://www.nw18.com/",
    "hq": "Noida",
    "industry": "mass media",
    "founded": 1993,
    "score": 11,
    "city": "Delhi NCR",
    "sector": "Mass Media",
    "lat": 28.464,
    "lng": 77.02210000000001
  },
  {
    "slug": "emcure-pharmaceuticals",
    "name": "Emcure Pharmaceuticals",
    "website": "https://emcure.com",
    "hq": "Hinjawadi",
    "industry": "pharmaceutical industry",
    "founded": 1983,
    "score": 11,
    "city": "India",
    "sector": "Pharmaceutical",
    "lat": 20.6027,
    "lng": 78.9629
  },
  {
    "slug": "metro-shoes",
    "name": "Metro Shoes",
    "website": "https://www.metroshoes.com",
    "hq": "Mumbai",
    "industry": "retail",
    "founded": 1977,
    "score": 11,
    "city": "Mumbai",
    "sector": "Retail",
    "lat": 19.0895,
    "lng": 72.8822
  },
  {
    "slug": "dharma-productions",
    "name": "Dharma Productions",
    "website": "https://www.dharma-production.com/",
    "hq": "Mumbai",
    "industry": "film production",
    "founded": 1976,
    "score": 11,
    "city": "Mumbai",
    "sector": "Film Production",
    "lat": 19.094,
    "lng": 72.8867
  },
  {
    "slug": "lexisnexis",
    "name": "LexisNexis",
    "website": "https://www.lexisnexis.com/en-us/home.page",
    "hq": "New York City",
    "industry": "publishing",
    "founded": 1973,
    "score": 11,
    "city": "India",
    "sector": "Publishing",
    "lat": 20.6162,
    "lng": 78.9764
  },
  {
    "slug": "asian-news-international",
    "name": "Asian News International",
    "website": "https://aninews.in/",
    "hq": "New Delhi",
    "industry": "news media",
    "founded": 1971,
    "score": 11,
    "city": "Delhi NCR",
    "sector": "News Media",
    "lat": 28.4865,
    "lng": 77.0446
  },
  {
    "slug": "konark-films",
    "name": "Konark Films",
    "website": "https://konarkfilms.com",
    "hq": "Mumbai",
    "industry": "entertainment",
    "founded": 1960,
    "score": 11,
    "city": "Mumbai",
    "sector": "Entertainment",
    "lat": 19.1075,
    "lng": 72.9002
  },
  {
    "slug": "uralungal-labour-contract-co-operative-society",
    "name": "Uralungal Labour Contract Co-operative Society",
    "website": "https://ulccsltd.com/",
    "hq": "Vatakara",
    "industry": "construction industry",
    "founded": 1925,
    "score": 11,
    "city": "India",
    "sector": "Construction",
    "lat": 20.6297,
    "lng": 78.9899
  },
  {
    "slug": "royal-enfield",
    "name": "Royal Enfield",
    "website": "https://www.royalenfield.com/uk/en/",
    "hq": "Redditch",
    "industry": "automotive industry",
    "founded": 1901,
    "score": 11,
    "city": "India",
    "sector": "Automotive",
    "lat": 20.6342,
    "lng": 78.9944
  },
  {
    "slug": "dharishah-ayurveda",
    "name": "Dharishah Ayurveda",
    "website": "https://dharishahayurveda.com",
    "hq": "Ambala Cantonment",
    "industry": "Ayurveda",
    "founded": 1889,
    "score": 11,
    "city": "India",
    "sector": "Ayurveda",
    "lat": 20.553199999999997,
    "lng": 78.9989
  },
  {
    "slug": "rrb-energy",
    "name": "RRB Energy",
    "website": "http://www.rrbenergy.com/",
    "hq": "New Delhi",
    "industry": "wind power industry",
    "founded": 1987,
    "score": 10,
    "city": "Delhi NCR",
    "sector": "Wind Power",
    "lat": 28.423499999999997,
    "lng": 77.0671
  },
  {
    "slug": "odisha-power-generation-corporation",
    "name": "Odisha Power Generation Corporation",
    "website": "http://www.opgc.co.in/",
    "hq": "Bhubaneswar",
    "industry": "electric power industry",
    "founded": 1984,
    "score": 10,
    "city": "Bhubaneswar",
    "sector": "Electric Power",
    "lat": 20.264599999999998,
    "lng": 85.8695
  },
  {
    "slug": "t-series",
    "name": "T-Series",
    "website": "http://www.tseries.com/",
    "hq": "Delhi",
    "industry": "show business",
    "founded": 1983,
    "score": 10,
    "city": "Delhi NCR",
    "sector": "Show Business",
    "lat": 28.432499999999997,
    "lng": 77.0761
  },
  {
    "slug": "annapurna-studios",
    "name": "Annapurna Studios",
    "website": "http://annapurnastudios.com/",
    "hq": "Hyderabad",
    "industry": "film industry",
    "founded": 1975,
    "score": 10,
    "city": "Hyderabad",
    "sector": "Film",
    "lat": 17.3625,
    "lng": 78.4372
  },
  {
    "slug": "vyjayanthi-movies",
    "name": "Vyjayanthi Movies",
    "website": "http://www.vyjayanthi.com",
    "hq": "Hyderabad",
    "industry": "entertainment",
    "founded": 1974,
    "score": 10,
    "city": "Hyderabad",
    "sector": "Entertainment",
    "lat": 17.367,
    "lng": 78.4417
  },
  {
    "slug": "nadiadwala-grandson-entertainment",
    "name": "Nadiadwala Grandson Entertainment",
    "website": "http://www.nadiadwalagrandson.com",
    "hq": "Mumbai",
    "industry": "show business",
    "founded": 1970,
    "score": 10,
    "city": "Mumbai",
    "sector": "Show Business",
    "lat": 19.0625,
    "lng": 72.83720000000001
  },
  {
    "slug": "goa-shipyard-limited",
    "name": "Goa Shipyard Limited",
    "website": "http://www.goashipyard.co.in/",
    "hq": "Goa",
    "industry": "shipbuilding",
    "founded": 1957,
    "score": 10,
    "city": "India",
    "sector": "Shipbuilding",
    "lat": 20.584699999999998,
    "lng": 78.9269
  },
  {
    "slug": "amul",
    "name": "Amul",
    "website": "http://www.amul.com/",
    "hq": "Anand",
    "industry": "dairy industry",
    "founded": 1946,
    "score": 10,
    "city": "India",
    "sector": "Dairy",
    "lat": 20.589199999999998,
    "lng": 78.93140000000001
  },
  {
    "slug": "avm-productions",
    "name": "AVM Productions",
    "website": "http://avm.in/",
    "hq": "Vadapalani",
    "industry": "film industry",
    "founded": 1945,
    "score": 10,
    "city": "India",
    "sector": "Film",
    "lat": 20.5937,
    "lng": 78.9359
  },
  {
    "slug": "eros-now",
    "name": "Eros Now",
    "website": "https://erosnow.com/",
    "hq": "Mumbai",
    "industry": "communications media",
    "founded": null,
    "score": 9,
    "city": "Mumbai",
    "sector": "Communications Media",
    "lat": 19.0805,
    "lng": 72.85520000000001
  },
  {
    "slug": "sandesh-productions",
    "name": "Sandesh Productions",
    "website": "https://sandeshproductions.com/",
    "hq": "Bengaluru",
    "industry": "entertainment",
    "founded": null,
    "score": 9,
    "city": "Bengaluru",
    "sector": "Entertainment",
    "lat": 12.9806,
    "lng": 77.5766
  },
  {
    "slug": "meghavi-wellness-spa",
    "name": "Meghavi Wellness Spa",
    "website": "https://meghaviwellness.com",
    "hq": "Hyderabad",
    "industry": "health care",
    "founded": null,
    "score": 9,
    "city": "Hyderabad",
    "sector": "Health Care",
    "lat": 17.398500000000002,
    "lng": 78.4732
  },
  {
    "slug": "vidyarthi-studios",
    "name": "Vidyarthi Studios",
    "website": "https://www.vidyarthistudios.com/",
    "hq": "Mumbai",
    "industry": "film industry",
    "founded": null,
    "score": 9,
    "city": "Mumbai",
    "sector": "Film",
    "lat": 19.094,
    "lng": 72.8687
  },
  {
    "slug": "jiomart",
    "name": "JioMart",
    "website": "https://www.jiomart.com/",
    "hq": "Navi Mumbai",
    "industry": "e-commerce",
    "founded": null,
    "score": 9,
    "city": "Mumbai",
    "sector": "E-Commerce",
    "lat": 19.0985,
    "lng": 72.87320000000001
  },
  {
    "slug": "applause-entertainment",
    "name": "Applause Entertainment",
    "website": "http://applauseentertainment.in",
    "hq": "Mumbai",
    "industry": "film production",
    "founded": null,
    "score": 8,
    "city": "Mumbai",
    "sector": "Film Production",
    "lat": 19.103,
    "lng": 72.8777
  },
  {
    "slug": "reflection-pictures-studio",
    "name": "Reflection Pictures Studio",
    "website": "https://reflectionpicturesstudio.com",
    "hq": "Mumbai",
    "industry": "",
    "founded": 2023,
    "score": 7,
    "city": "Mumbai",
    "sector": "Other",
    "lat": 19.1075,
    "lng": 72.8822
  },
  {
    "slug": "hilton-garden-inn-pune-hinjawadi",
    "name": "Hilton Garden Inn Pune Hinjawadi",
    "website": "https://www.hilton.com/en/hotels/pnqhpgi-hilton-garden-inn-pune-hinjawadi/",
    "hq": "",
    "industry": "hospitality industry",
    "founded": 2022,
    "score": 7,
    "city": "India",
    "sector": "Hospitality",
    "lat": 20.6297,
    "lng": 78.9719
  },
  {
    "slug": "b62-studios",
    "name": "B62 Studios",
    "website": "https://b62studios.com",
    "hq": "Mumbai",
    "industry": "",
    "founded": 2021,
    "score": 7,
    "city": "Mumbai",
    "sector": "Other",
    "lat": 19.116500000000002,
    "lng": 72.8912
  },
  {
    "slug": "mc-joint",
    "name": "MC Joint",
    "website": "https://www.mcjoint.in",
    "hq": "Hyderabad",
    "industry": "",
    "founded": 2021,
    "score": 7,
    "city": "Hyderabad",
    "sector": "Other",
    "lat": 17.3445,
    "lng": 78.5047
  },
  {
    "slug": "8i-ventures",
    "name": "8i Ventures",
    "website": "https://www.8ivc.com",
    "hq": "Mumbai",
    "industry": "",
    "founded": 2019,
    "score": 7,
    "city": "Mumbai",
    "sector": "Other",
    "lat": 19.04,
    "lng": 72.9002
  },
  {
    "slug": "hoichoi",
    "name": "Hoichoi",
    "website": "https://www.hoichoi.tv/",
    "hq": "West Bengal",
    "industry": "",
    "founded": 2017,
    "score": 7,
    "city": "Kolkata",
    "sector": "Other",
    "lat": 22.5411,
    "lng": 88.3909
  },
  {
    "slug": "talrop",
    "name": "Talrop",
    "website": "https://talrop.com/",
    "hq": "Kochi",
    "industry": "",
    "founded": 2016,
    "score": 7,
    "city": "Kochi",
    "sector": "Other",
    "lat": 9.904200000000001,
    "lng": 76.2988
  },
  {
    "slug": "excitel-broadband",
    "name": "Excitel Broadband",
    "website": "https://www.excitel.com/",
    "hq": "New Delhi",
    "industry": "",
    "founded": 2015,
    "score": 7,
    "city": "Delhi NCR",
    "sector": "Other",
    "lat": 28.436999999999998,
    "lng": 77.0626
  },
  {
    "slug": "eruk-films",
    "name": "Eruk Films",
    "website": "https://www.erukfilms.com",
    "hq": "Agartala",
    "industry": "",
    "founded": 2015,
    "score": 7,
    "city": "India",
    "sector": "Other",
    "lat": 20.575699999999998,
    "lng": 79.0034
  },
  {
    "slug": "sol-brand-solutions-pvt-ltd",
    "name": "SOL Brand Solutions Pvt. Ltd.",
    "website": "https://experiencesol.com/",
    "hq": "Mumbai",
    "industry": "",
    "founded": 2014,
    "score": 7,
    "city": "Mumbai",
    "sector": "Other",
    "lat": 19.0625,
    "lng": 72.9227
  },
  {
    "slug": "nilenso",
    "name": "Nilenso",
    "website": "https://nilenso.com",
    "hq": "",
    "industry": "consulting",
    "founded": 2013,
    "score": 7,
    "city": "India",
    "sector": "Consulting",
    "lat": 20.584699999999998,
    "lng": 79.0124
  },
  {
    "slug": "hombale-films",
    "name": "Hombale Films",
    "website": "https://hombalefilms.com/",
    "hq": "Bengaluru",
    "industry": "",
    "founded": 2012,
    "score": 7,
    "city": "Bengaluru",
    "sector": "Other",
    "lat": 12.9671,
    "lng": 77.5451
  },
  {
    "slug": "swastik-productions",
    "name": "Swastik Productions",
    "website": "https://swastikproductions.com",
    "hq": "Mumbai",
    "industry": "",
    "founded": 2006,
    "score": 7,
    "city": "Mumbai",
    "sector": "Other",
    "lat": 19.076,
    "lng": 72.8327
  },
  {
    "slug": "unipro",
    "name": "Unipro",
    "website": "https://www.unipro.energy/",
    "hq": "Surgut",
    "industry": "",
    "founded": 2005,
    "score": 7,
    "city": "India",
    "sector": "Other",
    "lat": 20.5982,
    "lng": 78.92240000000001
  },
  {
    "slug": "vestige-marketing",
    "name": "Vestige Marketing",
    "website": "https://www.myvestige.com",
    "hq": "New Delhi",
    "industry": "",
    "founded": 2004,
    "score": 7,
    "city": "Delhi NCR",
    "sector": "Other",
    "lat": 28.4685,
    "lng": 76.9906
  },
  {
    "slug": "dq-entertainment",
    "name": "DQ Entertainment",
    "website": "https://www.dqentertainment.com/",
    "hq": "Hyderabad, Uttar Pradesh",
    "industry": "",
    "founded": 2000,
    "score": 7,
    "city": "Hyderabad",
    "sector": "Other",
    "lat": 17.398500000000002,
    "lng": 78.4552
  },
  {
    "slug": "renascent-consultants",
    "name": "Renascent Consultants",
    "website": "https://renascent.co.in/",
    "hq": "New Delhi",
    "industry": "",
    "founded": 1994,
    "score": 7,
    "city": "Delhi NCR",
    "sector": "Other",
    "lat": 28.4775,
    "lng": 76.9996
  },
  {
    "slug": "yash-raj-films",
    "name": "Yash Raj Films",
    "website": "https://www.yashrajfilms.com/",
    "hq": "Mumbai",
    "industry": "",
    "founded": 1970,
    "score": 7,
    "city": "Mumbai",
    "sector": "Other",
    "lat": 19.0985,
    "lng": 72.85520000000001
  },
  {
    "slug": "rajkot-nagarik-sahakari-bank",
    "name": "Rajkot Nagarik Sahakari Bank",
    "website": "https://rnsbindia.com",
    "hq": "Rajkot",
    "industry": "",
    "founded": 1953,
    "score": 7,
    "city": "India",
    "sector": "Other",
    "lat": 20.6207,
    "lng": 78.9449
  },
  {
    "slug": "sanspareils-greenlands",
    "name": "Sanspareils Greenlands",
    "website": "https://shop.teamsg.in/",
    "hq": "Meerut",
    "industry": "",
    "founded": 1950,
    "score": 7,
    "city": "India",
    "sector": "Other",
    "lat": 20.6252,
    "lng": 78.94940000000001
  },
  {
    "slug": "press-trust-of-india",
    "name": "Press Trust of India",
    "website": "https://www.ptinews.com/",
    "hq": "",
    "industry": "news media",
    "founded": 1947,
    "score": 7,
    "city": "India",
    "sector": "News Media",
    "lat": 20.6297,
    "lng": 78.9539
  },
  {
    "slug": "othbrok-production-llp",
    "name": "OthBrok Production LLP",
    "website": "http://othbrokproduction.com",
    "hq": "Kolhapur",
    "industry": "",
    "founded": 2021,
    "score": 6,
    "city": "India",
    "sector": "Other",
    "lat": 20.6342,
    "lng": 78.95840000000001
  },
  {
    "slug": "weekend-blockbusters",
    "name": "Weekend Blockbusters",
    "website": "http://www.weekendblockbusters.com",
    "hq": "",
    "industry": "Malayalam cinema",
    "founded": 2014,
    "score": 6,
    "city": "India",
    "sector": "Malayalam Cinema",
    "lat": 20.553199999999997,
    "lng": 78.9629
  },
  {
    "slug": "ostseeland-verkehr",
    "name": "Ostseeland Verkehr",
    "website": "http://www.ostseelandverkehr.de/",
    "hq": "Schwerin",
    "industry": "",
    "founded": 2010,
    "score": 6,
    "city": "India",
    "sector": "Other",
    "lat": 20.557699999999997,
    "lng": 78.9674
  },
  {
    "slug": "friday-filmworks",
    "name": "Friday Filmworks",
    "website": "http://www.fridayfilmworks.com",
    "hq": "Mumbai",
    "industry": "",
    "founded": 2007,
    "score": 6,
    "city": "Mumbai",
    "sector": "Other",
    "lat": 19.0445,
    "lng": 72.8867
  },
  {
    "slug": "ajay-devgn-films",
    "name": "Ajay Devgn Films",
    "website": "http://www.nyvfxwaala.com/home",
    "hq": "Mumbai",
    "industry": "",
    "founded": 2000,
    "score": 6,
    "city": "Mumbai",
    "sector": "Other",
    "lat": 19.049,
    "lng": 72.8912
  },
  {
    "slug": "pritish-nandy-communications",
    "name": "Pritish Nandy Communications",
    "website": "http://www.pritishnandycom.com",
    "hq": "Mumbai",
    "industry": "",
    "founded": 1993,
    "score": 6,
    "city": "Mumbai",
    "sector": "Other",
    "lat": 19.0535,
    "lng": 72.8957
  },
  {
    "slug": "elephant-strategy-design",
    "name": "Elephant Strategy+Design",
    "website": "http://www.elephantdesign.com/",
    "hq": "Pune",
    "industry": "",
    "founded": 1989,
    "score": 6,
    "city": "Pune",
    "sector": "Other",
    "lat": 18.502399999999998,
    "lng": 73.8792
  },
  {
    "slug": "indo-asian-news-service",
    "name": "Indo-Asian News Service",
    "website": "http://www.ians.in/",
    "hq": "Greater Noida",
    "industry": "",
    "founded": 1986,
    "score": 6,
    "city": "Delhi NCR",
    "sector": "Other",
    "lat": 28.445999999999998,
    "lng": 77.0536
  },
  {
    "slug": "innovision-communications",
    "name": "Innovision Communications",
    "website": "http://innovisionindia.net/",
    "hq": "Mumbai",
    "industry": "",
    "founded": 1981,
    "score": 6,
    "city": "Mumbai",
    "sector": "Other",
    "lat": 19.067,
    "lng": 72.9092
  },
  {
    "slug": "micro-labs",
    "name": "Micro Labs",
    "website": "http://www.microlabsltd.com/",
    "hq": "Bengaluru",
    "industry": "",
    "founded": 1973,
    "score": 6,
    "city": "Bengaluru",
    "sector": "Other",
    "lat": 12.9671,
    "lng": 77.6306
  },
  {
    "slug": "dudhsagar-dairy",
    "name": "Dudhsagar Dairy",
    "website": "http://www.dudhsagardairy.coop/",
    "hq": "Mehsana",
    "industry": "",
    "founded": 1963,
    "score": 6,
    "city": "India",
    "sector": "Other",
    "lat": 20.5937,
    "lng": 79.0034
  },
  {
    "slug": "bbc-news-punjabi",
    "name": "BBC News Punjabi",
    "website": "https://www.bbc.com/punjabi",
    "hq": "Delhi",
    "industry": "",
    "founded": null,
    "score": 5,
    "city": "Delhi NCR",
    "sector": "Other",
    "lat": 28.464,
    "lng": 77.0716
  },
  {
    "slug": "argus-news",
    "name": "Argus News",
    "website": "https://argusnews.in/",
    "hq": "Bhubaneswar",
    "industry": "",
    "founded": null,
    "score": 5,
    "city": "Bhubaneswar",
    "sector": "Other",
    "lat": 20.3051,
    "lng": 85.874
  },
  {
    "slug": "nideas-productions",
    "name": "Nideas Productions",
    "website": "https://www.nideas.in/",
    "hq": "Kolkata",
    "industry": "",
    "founded": null,
    "score": 5,
    "city": "Kolkata",
    "sector": "Other",
    "lat": 22.586100000000002,
    "lng": 88.3144
  },
  {
    "slug": "2d-entertainment",
    "name": "2D Entertainment",
    "website": "https://www.2dentertainment.in",
    "hq": "Chennai",
    "industry": "",
    "founded": null,
    "score": 5,
    "city": "Chennai",
    "sector": "Other",
    "lat": 13.100700000000002,
    "lng": 80.2257
  },
  {
    "slug": "samrat-cinematics",
    "name": "Samrat Cinematics",
    "website": "https://www.samrattv.com/",
    "hq": "Mumbai",
    "industry": "",
    "founded": null,
    "score": 5,
    "city": "Mumbai",
    "sector": "Other",
    "lat": 19.0985,
    "lng": 72.83720000000001
  },
  {
    "slug": "shri-ram-janmabhoomi-teerth-kshetra",
    "name": "Shri Ram Janmabhoomi Teerth Kshetra",
    "website": "https://srjbtkshetra.org",
    "hq": "Ayodhya",
    "industry": "",
    "founded": null,
    "score": 5,
    "city": "India",
    "sector": "Other",
    "lat": 20.6207,
    "lng": 78.9269
  },
  {
    "slug": "pavra-entertainment",
    "name": "Pavra Entertainment",
    "website": "https://pavraentertainment.com",
    "hq": "Ahmedabad",
    "industry": "",
    "founded": null,
    "score": 5,
    "city": "Ahmedabad",
    "sector": "Other",
    "lat": 23.054000000000002,
    "lng": 72.5399
  },
  {
    "slug": "harfanmaula-films",
    "name": "Harfanmaula Films",
    "website": "https://harfanmaulafilms.com",
    "hq": "Ahmedabad",
    "industry": "",
    "founded": null,
    "score": 5,
    "city": "Ahmedabad",
    "sector": "Other",
    "lat": 23.058500000000002,
    "lng": 72.5444
  },
  {
    "slug": "gd-studio",
    "name": "GD Studio",
    "website": "http://gdstudio.info",
    "hq": "",
    "industry": "entertainment",
    "founded": null,
    "score": 4,
    "city": "India",
    "sector": "Entertainment",
    "lat": 20.6342,
    "lng": 78.94040000000001
  },
  {
    "slug": "ksk-energy-ventures-limited",
    "name": "KSK Energy Ventures Limited",
    "website": "http://www.ksk.co.in",
    "hq": "Hyderabad",
    "industry": "",
    "founded": null,
    "score": 4,
    "city": "Hyderabad",
    "sector": "Other",
    "lat": 17.3445,
    "lng": 78.4687
  },
  {
    "slug": "pentamedia-graphics",
    "name": "Pentamedia Graphics",
    "website": "http://penta-media.com",
    "hq": "",
    "industry": "animation",
    "founded": null,
    "score": 4,
    "city": "India",
    "sector": "Animation",
    "lat": 20.557699999999997,
    "lng": 78.94940000000001
  },
  {
    "slug": "merck-india",
    "name": "Merck (India)",
    "website": "http://www.merck.co.in/en/index.html",
    "hq": "Mumbai",
    "industry": "",
    "founded": null,
    "score": 4,
    "city": "Mumbai",
    "sector": "Other",
    "lat": 19.0445,
    "lng": 72.8687
  },
  {
    "slug": "fareeagle",
    "name": "FareEagle",
    "website": "https://www.fareeagle.com/",
    "hq": "",
    "industry": "",
    "founded": 2025,
    "score": 3,
    "city": "India",
    "sector": "Other",
    "lat": 20.566699999999997,
    "lng": 78.95840000000001
  },
  {
    "slug": "the-nikah-corner",
    "name": "The Nikah Corner",
    "website": "https://thenikahcorner.com",
    "hq": "",
    "industry": "",
    "founded": 2025,
    "score": 3,
    "city": "India",
    "sector": "Other",
    "lat": 20.571199999999997,
    "lng": 78.9629
  },
  {
    "slug": "hammerzz-makarena",
    "name": "Hammerzz Makarena",
    "website": "https://hammerzzmakarena.com",
    "hq": "",
    "industry": "",
    "founded": 2025,
    "score": 3,
    "city": "India",
    "sector": "Other",
    "lat": 20.575699999999998,
    "lng": 78.9674
  },
  {
    "slug": "impulse-cine-entertainments",
    "name": "Impulse Cine Entertainments",
    "website": "https://impulsecineentertainments.in",
    "hq": "",
    "industry": "",
    "founded": 2021,
    "score": 3,
    "city": "India",
    "sector": "Other",
    "lat": 20.580199999999998,
    "lng": 78.9719
  },
  {
    "slug": "transmedia-films",
    "name": "Transmedia Films",
    "website": "https://www.transmediafilms.com/",
    "hq": "",
    "industry": "",
    "founded": 2019,
    "score": 3,
    "city": "India",
    "sector": "Other",
    "lat": 20.584699999999998,
    "lng": 78.9764
  },
  {
    "slug": "appu-ghar",
    "name": "Appu Ghar",
    "website": "https://appughargurugram.com/",
    "hq": "",
    "industry": "",
    "founded": 2014,
    "score": 3,
    "city": "India",
    "sector": "Other",
    "lat": 20.589199999999998,
    "lng": 78.9809
  },
  {
    "slug": "emmay-entertainment",
    "name": "Emmay Entertainment",
    "website": "https://emmay.com",
    "hq": "",
    "industry": "",
    "founded": 2011,
    "score": 3,
    "city": "India",
    "sector": "Other",
    "lat": 20.5937,
    "lng": 78.9854
  },
  {
    "slug": "secondshaadi",
    "name": "SecondShaadi",
    "website": "https://www.secondshaadi.com/",
    "hq": "",
    "industry": "",
    "founded": 2006,
    "score": 3,
    "city": "India",
    "sector": "Other",
    "lat": 20.5982,
    "lng": 78.9899
  },
  {
    "slug": "aman-i-khas",
    "name": "Aman-i-Khas",
    "website": "https://www.aman.com/resorts/aman-i-khas",
    "hq": "",
    "industry": "",
    "founded": 2003,
    "score": 3,
    "city": "India",
    "sector": "Other",
    "lat": 20.6027,
    "lng": 78.9944
  },
  {
    "slug": "8mm",
    "name": "8mm",
    "website": "https://8mm.in",
    "hq": "",
    "industry": "",
    "founded": 1990,
    "score": 3,
    "city": "India",
    "sector": "Other",
    "lat": 20.6072,
    "lng": 78.9989
  },
  {
    "slug": "taj-coromandel",
    "name": "Taj Coromandel",
    "website": "https://taj.tajhotels.com/en-in/taj-coromandel-chennai/",
    "hq": "",
    "industry": "",
    "founded": 1974,
    "score": 3,
    "city": "India",
    "sector": "Other",
    "lat": 20.6117,
    "lng": 79.0034
  },
  {
    "slug": "ava-productions",
    "name": "AVA Productions",
    "website": "http://www.ava-productions.com/",
    "hq": "",
    "industry": "",
    "founded": 2012,
    "score": 2,
    "city": "India",
    "sector": "Other",
    "lat": 20.6162,
    "lng": 79.0079
  },
  {
    "slug": "worlds-of-wonder",
    "name": "Worlds of Wonder",
    "website": "http://worldsofwonder.in/",
    "hq": "",
    "industry": "",
    "founded": 2007,
    "score": 2,
    "city": "India",
    "sector": "Other",
    "lat": 20.6207,
    "lng": 79.0124
  },
  {
    "slug": "arka-media-works",
    "name": "Arka Media Works",
    "website": "http://www.arkamediaworks.com",
    "hq": "",
    "industry": "",
    "founded": 2001,
    "score": 2,
    "city": "India",
    "sector": "Other",
    "lat": 20.6252,
    "lng": 78.91340000000001
  },
  {
    "slug": "kazhcha-chalachithra-vedi",
    "name": "Kazhcha Chalachithra Vedi",
    "website": "http://kazhcha.in",
    "hq": "",
    "industry": "",
    "founded": 2001,
    "score": 2,
    "city": "India",
    "sector": "Other",
    "lat": 20.6297,
    "lng": 78.9179
  },
  {
    "slug": "northstar-entertainment",
    "name": "NorthStar Entertainment",
    "website": "http://northstarentertainment.in/",
    "hq": "",
    "industry": "",
    "founded": 2000,
    "score": 2,
    "city": "India",
    "sector": "Other",
    "lat": 20.6342,
    "lng": 78.92240000000001
  },
  {
    "slug": "dash-n-splash",
    "name": "Dash n Splash",
    "website": "http://www.dashnsplash.co.in",
    "hq": "",
    "industry": "",
    "founded": 1995,
    "score": 2,
    "city": "India",
    "sector": "Other",
    "lat": 20.553199999999997,
    "lng": 78.9269
  },
  {
    "slug": "sterling-cineplex",
    "name": "Sterling Cineplex",
    "website": "http://www.sterlingcineplex.in/",
    "hq": "",
    "industry": "",
    "founded": 1969,
    "score": 2,
    "city": "India",
    "sector": "Other",
    "lat": 20.557699999999997,
    "lng": 78.93140000000001
  },
  {
    "slug": "gujarat-state-federation-of-cooperative-sugar-factories-limi",
    "name": "Gujarat State Federation of Cooperative Sugar Factories Limited",
    "website": "http://www.gujsugarfed.com/",
    "hq": "",
    "industry": "",
    "founded": 1960,
    "score": 2,
    "city": "India",
    "sector": "Other",
    "lat": 20.562199999999997,
    "lng": 78.9359
  },
  {
    "slug": "children-s-film-society-india",
    "name": "Children's Film Society, India",
    "website": "http://www.cfsindia.org/",
    "hq": "",
    "industry": "",
    "founded": 1955,
    "score": 2,
    "city": "India",
    "sector": "Other",
    "lat": 20.566699999999997,
    "lng": 78.94040000000001
  },
  {
    "slug": "kesar-da-dhaba",
    "name": "Kesar Da Dhaba",
    "website": "http://www.kesardadhaba.com/",
    "hq": "",
    "industry": "",
    "founded": 1916,
    "score": 2,
    "city": "India",
    "sector": "Other",
    "lat": 20.571199999999997,
    "lng": 78.9449
  },
  {
    "slug": "leopold-cafe",
    "name": "Leopold Cafe",
    "website": "http://www.leopoldcafe.com/",
    "hq": "",
    "industry": "",
    "founded": 1871,
    "score": 2,
    "city": "India",
    "sector": "Other",
    "lat": 20.575699999999998,
    "lng": 78.94940000000001
  },
  {
    "slug": "hotel-aurora-towers",
    "name": "Hotel Aurora Towers",
    "website": "https://www.hotelauroratowers.in/",
    "hq": "",
    "industry": "",
    "founded": null,
    "score": 1,
    "city": "India",
    "sector": "Other",
    "lat": 20.580199999999998,
    "lng": 78.9539
  },
  {
    "slug": "the-taj-exotica-hotel-resort",
    "name": "The Taj Exotica Hotel & Resort",
    "website": "https://www.tajhotels.com/en-in/taj/taj-fort-aguada-goa/",
    "hq": "",
    "industry": "",
    "founded": null,
    "score": 1,
    "city": "India",
    "sector": "Other",
    "lat": 20.584699999999998,
    "lng": 78.95840000000001
  },
  {
    "slug": "namaste-cafe",
    "name": "Namaste Cafe",
    "website": "https://namastegokarna.com/",
    "hq": "",
    "industry": "",
    "founded": null,
    "score": 1,
    "city": "India",
    "sector": "Other",
    "lat": 20.589199999999998,
    "lng": 78.9629
  },
  {
    "slug": "resort-rio",
    "name": "Resort Rio",
    "website": "https://www.resortrio.com",
    "hq": "",
    "industry": "",
    "founded": null,
    "score": 1,
    "city": "India",
    "sector": "Other",
    "lat": 20.5937,
    "lng": 78.9674
  },
  {
    "slug": "great-eastern-hotel",
    "name": "Great Eastern Hotel",
    "website": "https://www.thelalit.com/the-lalit-kolkata/",
    "hq": "",
    "industry": "",
    "founded": null,
    "score": 1,
    "city": "India",
    "sector": "Other",
    "lat": 20.5982,
    "lng": 78.9719
  },
  {
    "slug": "q17053931",
    "name": "Q17053931",
    "website": "https://www.hyatt.com/grand-hyatt/en-US/mumgh-grand-hyatt-mumbai",
    "hq": "",
    "industry": "",
    "founded": null,
    "score": 1,
    "city": "India",
    "sector": "Other",
    "lat": 20.6027,
    "lng": 78.9764
  },
  {
    "slug": "sitara-luxury-hotel",
    "name": "Sitara Luxury Hotel",
    "website": "https://hotels.ramojifilmcity.com/sitara.php",
    "hq": "",
    "industry": "",
    "founded": null,
    "score": 1,
    "city": "India",
    "sector": "Other",
    "lat": 20.6072,
    "lng": 78.9809
  },
  {
    "slug": "roland-hotel-kolkata",
    "name": "Roland Hotel, Kolkata",
    "website": "https://rolandhotel.com",
    "hq": "",
    "industry": "",
    "founded": null,
    "score": 1,
    "city": "India",
    "sector": "Other",
    "lat": 20.6117,
    "lng": 78.9854
  },
  {
    "slug": "regency-lagoon-resort",
    "name": "Regency Lagoon Resort",
    "website": "https://regencylagoonresort.com/",
    "hq": "",
    "industry": "",
    "founded": null,
    "score": 1,
    "city": "India",
    "sector": "Other",
    "lat": 20.6162,
    "lng": 78.9899
  },
  {
    "slug": "the-ritz-carlton-pune",
    "name": "The Ritz-Carlton, Pune",
    "website": "https://www.ritzcarlton.com/en/hotels/pnqrz-the-ritz-carlton-pune/overview/",
    "hq": "",
    "industry": "",
    "founded": null,
    "score": 1,
    "city": "India",
    "sector": "Other",
    "lat": 20.6207,
    "lng": 78.9944
  },
  {
    "slug": "morgan-house",
    "name": "Morgan House",
    "website": "https://www.wbtdcl.com/home/lodge_search?Lodge_id=OA&Lodge_destinationName=Mw",
    "hq": "",
    "industry": "",
    "founded": null,
    "score": 1,
    "city": "India",
    "sector": "Other",
    "lat": 20.6252,
    "lng": 78.9989
  },
  {
    "slug": "national-hotel",
    "name": "National Hotel",
    "website": "https://nationalhotelpune.com/",
    "hq": "",
    "industry": "",
    "founded": null,
    "score": 1,
    "city": "India",
    "sector": "Other",
    "lat": 20.6297,
    "lng": 79.0034
  },
  {
    "slug": "heritage-khirasara-palace",
    "name": "Heritage Khirasara Palace",
    "website": "https://khirasarapalace.in/",
    "hq": "",
    "industry": "",
    "founded": null,
    "score": 1,
    "city": "India",
    "sector": "Other",
    "lat": 20.6342,
    "lng": 79.0079
  },
  {
    "slug": "elgin-fairlawn",
    "name": "Elgin Fairlawn",
    "website": "https://www.elginhotels.com/fairlawn.php",
    "hq": "",
    "industry": "",
    "founded": null,
    "score": 1,
    "city": "India",
    "sector": "Other",
    "lat": 20.553199999999997,
    "lng": 79.0124
  },
  {
    "slug": "lalitha-mahal",
    "name": "Lalitha Mahal",
    "website": "https://www.lalithamahalpalace.co.in/",
    "hq": "",
    "industry": "",
    "founded": null,
    "score": 1,
    "city": "India",
    "sector": "Other",
    "lat": 20.557699999999997,
    "lng": 78.91340000000001
  },
  {
    "slug": "taj-connemara",
    "name": "Taj Connemara",
    "website": "https://vivanta.tajhotels.com/en-in/connemara-chennai/",
    "hq": "",
    "industry": "",
    "founded": null,
    "score": 1,
    "city": "India",
    "sector": "Other",
    "lat": 20.562199999999997,
    "lng": 78.9179
  },
  {
    "slug": "the-leela-palace-chennai",
    "name": "The Leela Palace Chennai",
    "website": "https://www.theleela.com/en_us/hotels-in-chennai/the-leela-palace-hotel-chennai/",
    "hq": "",
    "industry": "",
    "founded": null,
    "score": 1,
    "city": "India",
    "sector": "Other",
    "lat": 20.566699999999997,
    "lng": 78.92240000000001
  },
  {
    "slug": "the-poona-club-ltd",
    "name": "The Poona Club Ltd.",
    "website": "https://poonaclubltd.com/",
    "hq": "",
    "industry": "",
    "founded": null,
    "score": 1,
    "city": "India",
    "sector": "Other",
    "lat": 20.571199999999997,
    "lng": 78.9269
  },
  {
    "slug": "jw-marriot-hotel-kolkata",
    "name": "JW Marriot Hotel Kolkata",
    "website": "https://www.marriott.com/hotels/travel/ccujw-jw-marriott-hotel-kolkata/",
    "hq": "",
    "industry": "",
    "founded": null,
    "score": 1,
    "city": "India",
    "sector": "Other",
    "lat": 20.575699999999998,
    "lng": 78.93140000000001
  },
  {
    "slug": "raichak-on-ganges",
    "name": "Raichak on Ganges",
    "website": "https://raichakonganges.com/",
    "hq": "",
    "industry": "",
    "founded": null,
    "score": 1,
    "city": "India",
    "sector": "Other",
    "lat": 20.580199999999998,
    "lng": 78.9359
  },
  {
    "slug": "bawali-rajbari",
    "name": "Bawali Rajbari",
    "website": "https://www.therajbari.com/",
    "hq": "",
    "industry": "",
    "founded": null,
    "score": 1,
    "city": "India",
    "sector": "Other",
    "lat": 20.584699999999998,
    "lng": 78.94040000000001
  },
  {
    "slug": "amanora-the-fern-hotels-club",
    "name": "Amanora The Fern Hotels & Club",
    "website": "https://www.fernhotels.com/metro-getaway-cities/amanora-the-fern-an-ecotel-hotel-pune",
    "hq": "",
    "industry": "",
    "founded": null,
    "score": 1,
    "city": "India",
    "sector": "Other",
    "lat": 20.589199999999998,
    "lng": 78.9449
  },
  {
    "slug": "st-laurn-koregaon-park-pune",
    "name": "St Laurn Koregaon Park Pune",
    "website": "https://www.stlaurnhotels.com/pune/",
    "hq": "",
    "industry": "",
    "founded": null,
    "score": 1,
    "city": "India",
    "sector": "Other",
    "lat": 20.5937,
    "lng": 78.94940000000001
  },
  {
    "slug": "lemon-tree-hotel-chandigarh",
    "name": "Lemon Tree Hotel, Chandigarh",
    "website": "https://www.lemontreehotels.com/lemon-tree-hotel/chandigarh/hotel-chandigarh",
    "hq": "",
    "industry": "",
    "founded": null,
    "score": 1,
    "city": "India",
    "sector": "Other",
    "lat": 20.5982,
    "lng": 78.9539
  },
  {
    "slug": "the-corinthians-resort-club",
    "name": "The Corinthians Resort & Club",
    "website": "https://www.thecorinthianspune.com/",
    "hq": "",
    "industry": "",
    "founded": null,
    "score": 1,
    "city": "India",
    "sector": "Other",
    "lat": 20.6027,
    "lng": 78.95840000000001
  },
  {
    "slug": "windamere-hotel",
    "name": "Windamere Hotel",
    "website": "https://windamerehotel.com/",
    "hq": "",
    "industry": "",
    "founded": null,
    "score": 1,
    "city": "India",
    "sector": "Other",
    "lat": 20.6072,
    "lng": 78.9629
  },
  {
    "slug": "sadar-manzil-heritage-by-atmosphere",
    "name": "SADAR MANZIL HERITAGE BY ATMOSPHERE",
    "website": "https://sadarmanzil-atmosphere.com/",
    "hq": "",
    "industry": "",
    "founded": null,
    "score": 1,
    "city": "India",
    "sector": "Other",
    "lat": 20.6117,
    "lng": 78.9674
  },
  {
    "slug": "itc-maurya-a-luxury-collection-hotel-new-delhi",
    "name": "ITC Maurya, a Luxury Collection Hotel, New Delhi",
    "website": "https://www.itchotels.com/in/en/itcmaurya-new-delhi",
    "hq": "",
    "industry": "",
    "founded": null,
    "score": 1,
    "city": "India",
    "sector": "Other",
    "lat": 20.6162,
    "lng": 78.9719
  },
  {
    "slug": "the-samilton",
    "name": "The Samilton",
    "website": "https://www.samiltonhotel.com",
    "hq": "",
    "industry": "",
    "founded": null,
    "score": 1,
    "city": "India",
    "sector": "Other",
    "lat": 20.6207,
    "lng": 78.9764
  },
  {
    "slug": "blue-star",
    "name": "Blue Star",
    "website": "https://www.bluestarindia.com",
    "hq": "",
    "industry": "",
    "founded": null,
    "score": 1,
    "city": "India",
    "sector": "Other",
    "lat": 20.6252,
    "lng": 78.9809
  },
  {
    "slug": "apollo-pharmacy",
    "name": "Apollo Pharmacy",
    "website": "https://www.apollopharmacy.in",
    "hq": "",
    "industry": "",
    "founded": null,
    "score": 1,
    "city": "India",
    "sector": "Other",
    "lat": 20.6297,
    "lng": 78.9854
  },
  {
    "slug": "medplus-pharmacy",
    "name": "MedPlus Pharmacy",
    "website": "https://www.medplusindia.com",
    "hq": "",
    "industry": "",
    "founded": null,
    "score": 1,
    "city": "India",
    "sector": "Other",
    "lat": 20.6342,
    "lng": 78.9899
  },
  {
    "slug": "margin-free-market",
    "name": "Margin Free Market",
    "website": "https://mfreem.com",
    "hq": "",
    "industry": "",
    "founded": null,
    "score": 1,
    "city": "India",
    "sector": "Other",
    "lat": 20.553199999999997,
    "lng": 78.9944
  },
  {
    "slug": "q132472558",
    "name": "Q132472558",
    "website": "https://ddsolar.in/",
    "hq": "",
    "industry": "",
    "founded": null,
    "score": 1,
    "city": "India",
    "sector": "Other",
    "lat": 20.557699999999997,
    "lng": 78.9989
  },
  {
    "slug": "q132472595",
    "name": "Q132472595",
    "website": "https://www.pwc.in/",
    "hq": "",
    "industry": "",
    "founded": null,
    "score": 1,
    "city": "India",
    "sector": "Other",
    "lat": 20.562199999999997,
    "lng": 79.0034
  },
  {
    "slug": "q132472633",
    "name": "Q132472633",
    "website": "https://www.ipeglobal.com/",
    "hq": "",
    "industry": "",
    "founded": null,
    "score": 1,
    "city": "India",
    "sector": "Other",
    "lat": 20.566699999999997,
    "lng": 79.0079
  },
  {
    "slug": "kambala-solutions",
    "name": "Kambala Solutions",
    "website": "https://www.kambala.co.in",
    "hq": "",
    "industry": "",
    "founded": null,
    "score": 1,
    "city": "India",
    "sector": "Other",
    "lat": 20.571199999999997,
    "lng": 79.0124
  },
  {
    "slug": "idevsec",
    "name": "IDevSec",
    "website": "https://idevsec.com",
    "hq": "",
    "industry": "",
    "founded": null,
    "score": 1,
    "city": "India",
    "sector": "Other",
    "lat": 20.575699999999998,
    "lng": 78.91340000000001
  },
  {
    "slug": "indraprastha-gas-limited",
    "name": "Indraprastha Gas Limited",
    "website": "https://www.iglonline.net/",
    "hq": "",
    "industry": "",
    "founded": null,
    "score": 1,
    "city": "India",
    "sector": "Other",
    "lat": 20.580199999999998,
    "lng": 78.9179
  },
  {
    "slug": "q116460655",
    "name": "Q116460655",
    "website": "https://www.antaracruises.com/ganga-vilas-2/",
    "hq": "",
    "industry": "",
    "founded": null,
    "score": 1,
    "city": "India",
    "sector": "Other",
    "lat": 20.584699999999998,
    "lng": 78.92240000000001
  },
  {
    "slug": "giani-ice-cream",
    "name": "Giani Ice Cream",
    "website": "https://gianiicecream.in/",
    "hq": "",
    "industry": "",
    "founded": null,
    "score": 1,
    "city": "India",
    "sector": "Other",
    "lat": 20.589199999999998,
    "lng": 78.9269
  },
  {
    "slug": "zudio",
    "name": "Zudio",
    "website": "https://www.zudio.com/",
    "hq": "",
    "industry": "",
    "founded": null,
    "score": 1,
    "city": "India",
    "sector": "Other",
    "lat": 20.5937,
    "lng": 78.93140000000001
  },
  {
    "slug": "easybuy",
    "name": "EasyBuy",
    "website": "https://www.easybuyindia.com/",
    "hq": "",
    "industry": "",
    "founded": null,
    "score": 1,
    "city": "India",
    "sector": "Other",
    "lat": 20.5982,
    "lng": 78.9359
  },
  {
    "slug": "reliance-smart-point",
    "name": "Reliance Smart Point",
    "website": "https://www.relianceretail.com/reliance-smart.html#rilsmtpnt",
    "hq": "",
    "industry": "",
    "founded": null,
    "score": 1,
    "city": "India",
    "sector": "Other",
    "lat": 20.6027,
    "lng": 78.94040000000001
  },
  {
    "slug": "vishal-mega-mart",
    "name": "Vishal Mega Mart",
    "website": "https://www.vishalmegamart.com/",
    "hq": "",
    "industry": "",
    "founded": null,
    "score": 1,
    "city": "India",
    "sector": "Other",
    "lat": 20.6072,
    "lng": 78.9449
  },
  {
    "slug": "reliance-digital-stores",
    "name": "Reliance Digital stores",
    "website": "https://www.reliancedigitalstores.in",
    "hq": "",
    "industry": "",
    "founded": null,
    "score": 1,
    "city": "India",
    "sector": "Other",
    "lat": 20.6117,
    "lng": 78.94940000000001
  },
  {
    "slug": "westside",
    "name": "Westside",
    "website": "https://www.westside.com",
    "hq": "",
    "industry": "",
    "founded": null,
    "score": 1,
    "city": "India",
    "sector": "Other",
    "lat": 20.6162,
    "lng": 78.9539
  },
  {
    "slug": "star-bazaar",
    "name": "Star Bazaar",
    "website": "https://starbazaarindia.com/",
    "hq": "",
    "industry": "",
    "founded": null,
    "score": 1,
    "city": "India",
    "sector": "Other",
    "lat": 20.6207,
    "lng": 78.95840000000001
  },
  {
    "slug": "supplyco-medical-store",
    "name": "Supplyco Medical Store",
    "website": "https://supplycokerala.com/",
    "hq": "",
    "industry": "",
    "founded": null,
    "score": 1,
    "city": "India",
    "sector": "Other",
    "lat": 20.6252,
    "lng": 78.9629
  },
  {
    "slug": "chinita",
    "name": "Chinita",
    "website": "https://www.chinita.in/",
    "hq": "",
    "industry": "",
    "founded": null,
    "score": 1,
    "city": "India",
    "sector": "Other",
    "lat": 20.6297,
    "lng": 78.9674
  },
  {
    "slug": "netmeds",
    "name": "Netmeds",
    "website": "https://www.netmeds.com",
    "hq": "",
    "industry": "",
    "founded": null,
    "score": 1,
    "city": "India",
    "sector": "Other",
    "lat": 20.6342,
    "lng": 78.9719
  },
  {
    "slug": "girish-ch-dey-nakur-ch-nandi",
    "name": "Girish Ch. Dey & Nakur Ch. Nandi",
    "website": "https://girishnakur.com/",
    "hq": "",
    "industry": "",
    "founded": null,
    "score": 1,
    "city": "India",
    "sector": "Other",
    "lat": 20.553199999999997,
    "lng": 78.9764
  },
  {
    "slug": "imagicaa",
    "name": "Imagicaa",
    "website": "https://www.imagicaaworld.com/",
    "hq": "",
    "industry": "",
    "founded": null,
    "score": 1,
    "city": "India",
    "sector": "Other",
    "lat": 20.557699999999997,
    "lng": 78.9809
  },
  {
    "slug": "shivsrushti-pune",
    "name": "Shivsrushti, Pune",
    "website": "https://www.shivsrushti.com/",
    "hq": "",
    "industry": "",
    "founded": null,
    "score": 1,
    "city": "India",
    "sector": "Other",
    "lat": 20.562199999999997,
    "lng": 78.9854
  },
  {
    "slug": "atmos29-restobar-club",
    "name": "Atmos29 RestoBar & Club",
    "website": "https://atmos29.com/",
    "hq": "",
    "industry": "",
    "founded": null,
    "score": 1,
    "city": "India",
    "sector": "Other",
    "lat": 20.566699999999997,
    "lng": 78.9899
  },
  {
    "slug": "apollo-diagnostics",
    "name": "Apollo Diagnostics",
    "website": "https://apollodiagnostics.in",
    "hq": "",
    "industry": "",
    "founded": null,
    "score": 1,
    "city": "India",
    "sector": "Other",
    "lat": 20.571199999999997,
    "lng": 78.9944
  },
  {
    "slug": "carmelagiri-elephant-park",
    "name": "Carmelagiri Elephant Park",
    "website": "https://carmelagirielephantparkmunnar.com/",
    "hq": "",
    "industry": "",
    "founded": null,
    "score": 1,
    "city": "India",
    "sector": "Other",
    "lat": 20.575699999999998,
    "lng": 78.9989
  },
  {
    "slug": "sharbabharatiya-sylheti-forum-trust",
    "name": "Sharbabharatiya Sylheti Forum Trust",
    "website": "https://sbsftrust.com/",
    "hq": "",
    "industry": "",
    "founded": null,
    "score": 1,
    "city": "India",
    "sector": "Other",
    "lat": 20.580199999999998,
    "lng": 79.0034
  },
  {
    "slug": "mahida-and-sons",
    "name": "Mahida and Sons",
    "website": "https://www.mahidaandsons.in/",
    "hq": "",
    "industry": "",
    "founded": null,
    "score": 1,
    "city": "India",
    "sector": "Other",
    "lat": 20.584699999999998,
    "lng": 79.0079
  },
  {
    "slug": "experimenter-gallery",
    "name": "Experimenter Gallery",
    "website": "https://experimenter.in/",
    "hq": "",
    "industry": "",
    "founded": null,
    "score": 1,
    "city": "India",
    "sector": "Other",
    "lat": 20.589199999999998,
    "lng": 79.0124
  },
  {
    "slug": "pune-district-central-co-operative-bank-ltd-budhwer-peth-bra",
    "name": "Pune District Central Co-operative Bank Ltd., Budhwer Peth branch",
    "website": "https://www.pdccbank.co.in/",
    "hq": "",
    "industry": "",
    "founded": null,
    "score": 1,
    "city": "India",
    "sector": "Other",
    "lat": 20.5937,
    "lng": 78.91340000000001
  },
  {
    "slug": "mahindra-home-finance",
    "name": "Mahindra Home Finance",
    "website": "https://mahindrahomefinance.com",
    "hq": "",
    "industry": "",
    "founded": null,
    "score": 1,
    "city": "India",
    "sector": "Other",
    "lat": 20.5982,
    "lng": 78.9179
  },
  {
    "slug": "krup-productions",
    "name": "Krup Productions",
    "website": "https://krupproductions.com/",
    "hq": "",
    "industry": "",
    "founded": null,
    "score": 1,
    "city": "India",
    "sector": "Other",
    "lat": 20.6027,
    "lng": 78.92240000000001
  },
  {
    "slug": "amaazia",
    "name": "Amaazia",
    "website": "https://www.amaazia.com/",
    "hq": "",
    "industry": "",
    "founded": null,
    "score": 1,
    "city": "India",
    "sector": "Other",
    "lat": 20.6072,
    "lng": 78.9269
  },
  {
    "slug": "fundamental-pictures",
    "name": "Fundamental Pictures",
    "website": "https://www.fundamentalpictures.in",
    "hq": "",
    "industry": "",
    "founded": null,
    "score": 1,
    "city": "India",
    "sector": "Other",
    "lat": 20.6117,
    "lng": 78.93140000000001
  },
  {
    "slug": "aquatica",
    "name": "Aquatica",
    "website": "https://www.aquaticaindia.in/",
    "hq": "",
    "industry": "",
    "founded": null,
    "score": 1,
    "city": "India",
    "sector": "Other",
    "lat": 20.6162,
    "lng": 78.9359
  },
  {
    "slug": "all-india-ophthalmological-society",
    "name": "All India Ophthalmological Society",
    "website": "http://www.aios.org/",
    "hq": "",
    "industry": "",
    "founded": null,
    "score": 0,
    "city": "India",
    "sector": "Other",
    "lat": 20.6207,
    "lng": 78.94040000000001
  },
  {
    "slug": "indian-psychiatric-society",
    "name": "Indian Psychiatric Society",
    "website": "http://indianpsychiatricsociety.org",
    "hq": "",
    "industry": "",
    "founded": null,
    "score": 0,
    "city": "India",
    "sector": "Other",
    "lat": 20.6252,
    "lng": 78.9449
  },
  {
    "slug": "arc-parcel-service",
    "name": "ARC Parcel Service",
    "website": "http://arcparcelservice.com",
    "hq": "",
    "industry": "",
    "founded": null,
    "score": 0,
    "city": "India",
    "sector": "Other",
    "lat": 20.6297,
    "lng": 78.94940000000001
  },
  {
    "slug": "air-charter-services",
    "name": "Air Charter Services",
    "website": "http://www.aircharterservices.com/",
    "hq": "",
    "industry": "",
    "founded": null,
    "score": 0,
    "city": "India",
    "sector": "Other",
    "lat": 20.6342,
    "lng": 78.9539
  },
  {
    "slug": "association-of-physicians-of-india",
    "name": "Association of Physicians of India",
    "website": "http://www.apiindia.org/",
    "hq": "",
    "industry": "",
    "founded": null,
    "score": 0,
    "city": "India",
    "sector": "Other",
    "lat": 20.553199999999997,
    "lng": 78.95840000000001
  },
  {
    "slug": "world-research-journals",
    "name": "World Research Journals",
    "website": "http://worldresearchjournals.com/",
    "hq": "",
    "industry": "",
    "founded": null,
    "score": 0,
    "city": "India",
    "sector": "Other",
    "lat": 20.557699999999997,
    "lng": 78.9629
  },
  {
    "slug": "impact-journals",
    "name": "Impact Journals",
    "website": "http://www.impactjournals.us/",
    "hq": "",
    "industry": "",
    "founded": null,
    "score": 0,
    "city": "India",
    "sector": "Other",
    "lat": 20.562199999999997,
    "lng": 78.9674
  },
  {
    "slug": "club-one-air",
    "name": "Club One Air",
    "website": "http://www.cluboneair.com/",
    "hq": "",
    "industry": "",
    "founded": null,
    "score": 0,
    "city": "India",
    "sector": "Other",
    "lat": 20.566699999999997,
    "lng": 78.9719
  },
  {
    "slug": "remedy-publications-llc",
    "name": "Remedy Publications LLC",
    "website": "http://www.remedypublications.com",
    "hq": "",
    "industry": "",
    "founded": null,
    "score": 0,
    "city": "India",
    "sector": "Other",
    "lat": 20.571199999999997,
    "lng": 78.9764
  },
  {
    "slug": "sangri-la-books",
    "name": "Sangri-La Books",
    "website": "http://sangrilabooks.com.np/",
    "hq": "",
    "industry": "",
    "founded": null,
    "score": 0,
    "city": "India",
    "sector": "Other",
    "lat": 20.575699999999998,
    "lng": 78.9809
  },
  {
    "slug": "adyar-ananda-bhavan",
    "name": "Adyar Ananda Bhavan",
    "website": "http://www.adyaranandabhavanny.com/",
    "hq": "",
    "industry": "",
    "founded": null,
    "score": 0,
    "city": "India",
    "sector": "Other",
    "lat": 20.580199999999998,
    "lng": 78.9854
  },
  {
    "slug": "cactus-communications-pvt-ltd",
    "name": "Cactus Communications Pvt. Ltd.",
    "website": "http://www.cactusglobal.com",
    "hq": "",
    "industry": "",
    "founded": null,
    "score": 0,
    "city": "India",
    "sector": "Other",
    "lat": 20.584699999999998,
    "lng": 78.9899
  },
  {
    "slug": "vr-foundries",
    "name": "VR Foundries",
    "website": "http://www.vrfoundries.com/",
    "hq": "",
    "industry": "",
    "founded": null,
    "score": 0,
    "city": "India",
    "sector": "Other",
    "lat": 20.589199999999998,
    "lng": 78.9944
  },
  {
    "slug": "the-kerala-state-co-operative-bank-limited",
    "name": "The Kerala State Co Operative Bank Limited",
    "website": "http://keralacobank.com/",
    "hq": "",
    "industry": "",
    "founded": null,
    "score": 0,
    "city": "India",
    "sector": "Other",
    "lat": 20.5937,
    "lng": 78.9989
  },
  {
    "slug": "ambarnath-jaihind-co-op-bank-ltd-ambarnath",
    "name": "Ambarnath Jaihind Co-Op Bank Ltd Ambarnath",
    "website": "http://jaihindbank.com/profile.php",
    "hq": "",
    "industry": "",
    "founded": null,
    "score": 0,
    "city": "India",
    "sector": "Other",
    "lat": 20.5982,
    "lng": 79.0034
  },
  {
    "slug": "radisson-blu-city-centre",
    "name": "Radisson Blu City Centre",
    "website": "http://www.radissonblu.com/hotel-chennaicitycentre",
    "hq": "",
    "industry": "",
    "founded": null,
    "score": 0,
    "city": "India",
    "sector": "Other",
    "lat": 20.6027,
    "lng": 79.0079
  },
  {
    "slug": "residency-towers-chennai",
    "name": "Residency Towers Chennai",
    "website": "http://www.theresidency.com/residency-tower/chennai-tower.asp",
    "hq": "",
    "industry": "",
    "founded": null,
    "score": 0,
    "city": "India",
    "sector": "Other",
    "lat": 20.6072,
    "lng": 79.0124
  },
  {
    "slug": "savera-hotel",
    "name": "Savera Hotel",
    "website": "http://www.hotelsavera.com/",
    "hq": "",
    "industry": "",
    "founded": null,
    "score": 0,
    "city": "India",
    "sector": "Other",
    "lat": 20.6117,
    "lng": 78.91340000000001
  },
  {
    "slug": "le-royal-meridien-chennai",
    "name": "Le Royal Meridien, Chennai",
    "website": "http://www.starwoodhotels.com/lemeridien/property/overview/index.html?propertyID=1834",
    "hq": "",
    "industry": "",
    "founded": null,
    "score": 0,
    "city": "India",
    "sector": "Other",
    "lat": 20.6162,
    "lng": 78.9179
  },
  {
    "slug": "accord-metropolitan",
    "name": "Accord Metropolitan",
    "website": "http://www.theaccordmetropolitan.com/",
    "hq": "",
    "industry": "",
    "founded": null,
    "score": 0,
    "city": "India",
    "sector": "Other",
    "lat": 20.6207,
    "lng": 78.92240000000001
  },
  {
    "slug": "jhargram-palace",
    "name": "Jhargram Palace",
    "website": "http://www.jhargrampalace.com",
    "hq": "",
    "industry": "",
    "founded": null,
    "score": 0,
    "city": "India",
    "sector": "Other",
    "lat": 20.6252,
    "lng": 78.9269
  },
  {
    "slug": "holiday-inn-new-delhi-mayur-vihar-noida",
    "name": "Holiday Inn New Delhi Mayur Vihar NOIDA",
    "website": "http://holidayinn.hotelsgroup.in/holiday-inn-mayur-vihar.html",
    "hq": "",
    "industry": "",
    "founded": null,
    "score": 0,
    "city": "India",
    "sector": "Other",
    "lat": 20.6297,
    "lng": 78.93140000000001
  },
  {
    "slug": "hyatt-regency-kolkata",
    "name": "Hyatt Regency Kolkata",
    "website": "http://kolkata.regency.hyatt.com/",
    "hq": "",
    "industry": "",
    "founded": null,
    "score": 0,
    "city": "India",
    "sector": "Other",
    "lat": 20.6342,
    "lng": 78.9359
  },
  {
    "slug": "taj-surya-coimbatore",
    "name": "Taj Surya Coimbatore",
    "website": "http://www.vivantabytaj.com/Surya-Coimbatore/Overview.html",
    "hq": "",
    "industry": "",
    "founded": null,
    "score": 0,
    "city": "India",
    "sector": "Other",
    "lat": 20.553199999999997,
    "lng": 78.94040000000001
  },
  {
    "slug": "park-hyatt-hyderabad",
    "name": "Park Hyatt Hyderabad",
    "website": "http://hyderabad.park.hyatt.com/en/hotel/home.html",
    "hq": "",
    "industry": "",
    "founded": null,
    "score": 0,
    "city": "India",
    "sector": "Other",
    "lat": 20.557699999999997,
    "lng": 78.9449
  },
  {
    "slug": "hotel-de-l-orient",
    "name": "Hotel de l'Orient",
    "website": "http://www.neemranahotels.com/pondi/index.html.htm",
    "hq": "",
    "industry": "",
    "founded": null,
    "score": 0,
    "city": "India",
    "sector": "Other",
    "lat": 20.562199999999997,
    "lng": 78.94940000000001
  },
  {
    "slug": "conrad-pune",
    "name": "Conrad Pune",
    "website": "http://conradhotels3.hilton.com/en/hotels/india/conrad-pune-PNQCICI/index.html",
    "hq": "",
    "industry": "",
    "founded": null,
    "score": 0,
    "city": "India",
    "sector": "Other",
    "lat": 20.566699999999997,
    "lng": 78.9539
  },
  {
    "slug": "hotel-homeland",
    "name": "Hotel Homeland",
    "website": "http://www.hotelhomeland.net/",
    "hq": "",
    "industry": "",
    "founded": null,
    "score": 0,
    "city": "India",
    "sector": "Other",
    "lat": 20.571199999999997,
    "lng": 78.95840000000001
  },
  {
    "slug": "the-park-chennai",
    "name": "The Park, Chennai",
    "website": "http://www.theparkhotels.com/chennai-park/chennai-park.html",
    "hq": "",
    "industry": "",
    "founded": null,
    "score": 0,
    "city": "India",
    "sector": "Other",
    "lat": 20.575699999999998,
    "lng": 78.9629
  },
  {
    "slug": "kohinoor-asiana-hotel",
    "name": "Kohinoor Asiana Hotel",
    "website": "http://www.hotelkohinoorasiana.com/",
    "hq": "",
    "industry": "",
    "founded": null,
    "score": 0,
    "city": "India",
    "sector": "Other",
    "lat": 20.580199999999998,
    "lng": 78.9674
  },
  {
    "slug": "hyatt-regency-chennai",
    "name": "Hyatt Regency Chennai",
    "website": "http://chennai.regency.hyatt.com/hyatt/hotels/",
    "hq": "",
    "industry": "",
    "founded": null,
    "score": 0,
    "city": "India",
    "sector": "Other",
    "lat": 20.584699999999998,
    "lng": 78.9719
  },
  {
    "slug": "radha-regent-hotel-chennai",
    "name": "Radha Regent Hotel, Chennai",
    "website": "http://www.radhahotels.com/radha-regent-chennai/index.asp",
    "hq": "",
    "industry": "",
    "founded": null,
    "score": 0,
    "city": "India",
    "sector": "Other",
    "lat": 20.589199999999998,
    "lng": 78.9764
  },
  {
    "slug": "itc-sheraton-park-hotel-towers",
    "name": "ITC Sheraton Park Hotel & Towers",
    "website": "http://www.ihg.com/crowneplaza/hotels/gb/en/chennai/maaca/hoteldetail",
    "hq": "",
    "industry": "",
    "founded": null,
    "score": 0,
    "city": "India",
    "sector": "Other",
    "lat": 20.5937,
    "lng": 78.9809
  }
] as const;

