"use client";
import { useEffect,useMemo,useState } from "react";
import { startups } from "./data";
import StartupMap from "./startup-map";

export default function ExploreClient({city,technology}:{city?:string;technology?:string}){
 const [query,setQuery]=useState(""); const [sector,setSector]=useState("All sectors"); const [hiring,setHiring]=useState(false); const [view,setView]=useState<"grid"|"map">("grid"); const [visibleCount,setVisibleCount]=useState(60);
 useEffect(()=>{const params=new URLSearchParams(window.location.search);setQuery(params.get("q")||"");setSector(params.get("sector")||"All sectors");setHiring(params.get("hiring")==="true");},[]);
 useEffect(()=>{const params=new URLSearchParams();if(query)params.set("q",query);if(sector!=="All sectors")params.set("sector",sector);if(hiring)params.set("hiring","true");const next=`${window.location.pathname}${params.size?`?${params}`:""}`;window.history.replaceState({},"",next);},[query,sector,hiring]);
 useEffect(()=>setVisibleCount(60),[query,sector,hiring,city,technology]);
 const items=useMemo(()=>{const ignored=new Set(["startup","startups","company","companies","using","hiring","in","the","and","with"]);const terms=query.toLowerCase().split(/\s+/).map(x=>x.replace(/[^a-z0-9.+/#-]/g,"")).filter(x=>x.length>1&&!ignored.has(x));return startups.filter(s=>{const haystack=JSON.stringify(s).toLowerCase();return (!city||s.city===city)&&(!technology||s.tech.some(t=>t.toLowerCase()===technology.toLowerCase()))&&(sector==="All sectors"||s.sector===sector)&&(!hiring||s.hiring)&&terms.every(term=>haystack.includes(term));});},[city,technology,sector,hiring,query]);
 const mapItems=items.filter(item=>item.city!=="India");
 return <main><header className="innerNav shell"><a className="brand" href="/"><span className="brandMark">ISM</span><span>India Startup Map</span></a><div className="profileActions"><a href="/remote">Remote companies</a><a href="/location-unverified">Location unverified</a><a href="/submit">+ Add a startup</a></div></header>
 <section className="listingHero shell"><div className="eyebrow">{technology?"TECHNOLOGY INDEX":city?"CITY ECOSYSTEM":"NATIONAL ECOSYSTEM"} / SOURCE-LABELLED RECORDS</div><h2>{technology?<>Companies using <em>{technology}</em>{city?` in ${city}`:" in India"}</>:city?<>Startups in <em>{city}</em></>:<>Companies across <em>India</em></>}</h2><p>{items.length.toLocaleString()} real organizations mapped · Verification level is shown on each profile.</p></section>
 <div className="filterBar shell"><div className="miniSearch">⌕ <input placeholder="Search startups, founders, tech..." value={query} onChange={e=>setQuery(e.target.value)}/></div><select value={sector} onChange={e=>setSector(e.target.value)}><option>All sectors</option>{[...new Set(startups.map(s=>s.sector))].map(x=><option key={x}>{x}</option>)}</select><button className={hiring?"filterOn":""} onClick={()=>setHiring(!hiring)}>● Hiring now</button><div className="viewToggle"><button className={view==="map"?"on":""} onClick={()=>setView("map")}>Map</button><button className={view==="grid"?"on":""} onClick={()=>setView("grid")}>Grid</button></div></div>
 {view==="grid"?<><section className="startupGrid shell">{items.slice(0,visibleCount).map(s=><a href={`/startup/${s.slug}`} className="startupCard" key={s.slug}><div className="cardHead"><span className="logo" style={{background:s.color}}><span>{s.initials}</span><img src={s.logoUrl} alt={`${s.name} logo`}/></span>{"verificationStatus" in s?<b className="demoTag">DIRECTORY SOURCE</b>:s.isDemo?<b className="demoTag">DEMO DATA</b>:s.hiring&&<b className="hiring">● CAREERS PAGE</b>}</div><h3>{s.name}</h3><p>{s.description}</p><div className="meta">{s.neighborhood===s.city?s.city:`${s.city} · ${s.neighborhood}`}<br/>{s.sector} · {s.stage}</div><div className="badges">{s.tech.map(t=><span key={t}>{t}</span>)}</div><div className="cardFoot"><span>{s.roles?"Careers page verified":"No active roles verified"}</span><b>View profile →</b></div></a>)}</section>{visibleCount<items.length&&<div className="loadMore shell"><button onClick={()=>setVisibleCount(x=>Math.min(x+60,items.length))}>Load 60 more <span>{visibleCount} of {items.length.toLocaleString()}</span></button></div>}</>:<section className="mapShell shell"><StartupMap items={mapItems} city={city}/><div className="mapResultCount"><b>{mapItems.length.toLocaleString()}</b> companies with city data shown · {items.length-mapItems.length} withheld</div></section>}
 {items.length===0&&<div className="empty shell">No startups match those filters. Try broadening your search.</div>}</main>
}
