// City-level company records imported from Wikidata on 21 Aug 2026.
// Each record has an official website and a headquarters statement for the named city.
export const multiCityCompanies = [
  {
    "slug": "advenio-tecnosys-india",
    "name": "Advenio TecnoSys (India)",
    "website": "https://www.adveniotecnosys.com/",
    "city": "Chandigarh",
    "industry": "business",
    "sector": "Other",
    "founded": 2010,
    "lat": 30.7333,
    "lng": 76.7794,
    "source": "http://www.wikidata.org/entity/Q30271543"
  },
  {
    "slug": "publication-bureau-punjabi-university",
    "name": "Publication Bureau, Punjabi University",
    "website": "http://www.punjabiuniversity.ac.in/pages/Page.aspx?dsenc=PublicationBureau",
    "city": "Chandigarh",
    "industry": "business",
    "sector": "Other",
    "founded": null,
    "lat": 30.7333,
    "lng": 76.7794,
    "source": "http://www.wikidata.org/entity/Q112671101"
  },
  {
    "slug": "scorpyns-technologies-private-limited",
    "name": "Scorpyns Technologies Private Limited",
    "website": "https://scorpyns.com/",
    "city": "Chandigarh",
    "industry": "business",
    "sector": "Other",
    "founded": 2025,
    "lat": 30.7333,
    "lng": 76.7794,
    "source": "http://www.wikidata.org/entity/Q138034829"
  },
  {
    "slug": "ags-entertainment",
    "name": "AGS Entertainment",
    "website": "http://www.agscinemas.com",
    "city": "Chennai",
    "industry": "entertainment",
    "sector": "Media",
    "founded": 2006,
    "lat": 13.0827,
    "lng": 80.2707,
    "source": "http://www.wikidata.org/entity/Q4651702"
  },
  {
    "slug": "ais-business-corp-private-limited",
    "name": "AIS Business Corp Private Limited",
    "website": "https://aiscorp.ai",
    "city": "Chennai",
    "industry": "information technology consulting",
    "sector": "SaaS",
    "founded": null,
    "lat": 13.0827,
    "lng": 80.2707,
    "source": "http://www.wikidata.org/entity/Q140246945"
  },
  {
    "slug": "alcorone-solutions",
    "name": "AlcorOne Solutions",
    "website": "https://www.alcorone.com",
    "city": "Chennai",
    "industry": "construction",
    "sector": "Other",
    "founded": 2022,
    "lat": 13.0827,
    "lng": 80.2707,
    "source": "http://www.wikidata.org/entity/Q140944131"
  },
  {
    "slug": "athena-infonomics-india",
    "name": "Athena Infonomics (India)",
    "website": "https://www.athenainfonomics.in/",
    "city": "Chennai",
    "industry": "business",
    "sector": "Other",
    "founded": null,
    "lat": 13.0827,
    "lng": 80.2707,
    "source": "http://www.wikidata.org/entity/Q30271513"
  },
  {
    "slug": "cocomera",
    "name": "Cocomera",
    "website": "https://cocomera.in",
    "city": "Chennai",
    "industry": "cosmetics industry",
    "sector": "Other",
    "founded": 2025,
    "lat": 13.0827,
    "lng": 80.2707,
    "source": "http://www.wikidata.org/entity/Q140288056"
  },
  {
    "slug": "escape-artists-motion-pictures",
    "name": "Escape Artists Motion Pictures",
    "website": "https://escapeartistsmotionpictures.blogspot.com/",
    "city": "Chennai",
    "industry": "business",
    "sector": "Other",
    "founded": null,
    "lat": 13.0827,
    "lng": 80.2707,
    "source": "http://www.wikidata.org/entity/Q18712208"
  },
  {
    "slug": "everonn-public-school",
    "name": "Everonn Public School",
    "website": "http://www.everonnpublicschool.com/",
    "city": "Chennai",
    "industry": "business",
    "sector": "Other",
    "founded": null,
    "lat": 13.0827,
    "lng": 80.2707,
    "source": "http://www.wikidata.org/entity/Q17052645"
  },
  {
    "slug": "evolva-india",
    "name": "Evolva (India)",
    "website": "http://www.evolva.com/",
    "city": "Chennai",
    "industry": "business",
    "sector": "Other",
    "founded": null,
    "lat": 13.0827,
    "lng": 80.2707,
    "source": "http://www.wikidata.org/entity/Q30262911"
  },
  {
    "slug": "fives-chennai-s-property-portal",
    "name": "FIVES – Chennai's Property Portal",
    "website": "https://www.fives.co.in",
    "city": "Chennai",
    "industry": "real property",
    "sector": "Other",
    "founded": 2026,
    "lat": 13.0827,
    "lng": 80.2707,
    "source": "http://www.wikidata.org/entity/Q141063993"
  },
  {
    "slug": "flame-tao-knoware-india",
    "name": "FLAME TAO Knoware (India)",
    "website": "http://www.flametaoknoware.com/",
    "city": "Chennai",
    "industry": "business",
    "sector": "Other",
    "founded": null,
    "lat": 13.0827,
    "lng": 80.2707,
    "source": "http://www.wikidata.org/entity/Q30262917"
  },
  {
    "slug": "galvanize-global-education",
    "name": "Galvanize Global Education",
    "website": "https://galvanizetestprep.com/",
    "city": "Chennai",
    "industry": "education",
    "sector": "EdTech",
    "founded": null,
    "lat": 13.0827,
    "lng": 80.2707,
    "source": "http://www.wikidata.org/entity/Q140664599"
  },
  {
    "slug": "hustl",
    "name": "Hustl",
    "website": "https://hustl.today",
    "city": "Chennai",
    "industry": "gig economy",
    "sector": "Other",
    "founded": 2026,
    "lat": 13.0827,
    "lng": 80.2707,
    "source": "http://www.wikidata.org/entity/Q140365927"
  },
  {
    "slug": "india-home-health-care",
    "name": "India Home Health Care",
    "website": "http://www.indiahomehealthcare.com/",
    "city": "Chennai",
    "industry": "business",
    "sector": "Other",
    "founded": 2009,
    "lat": 13.0827,
    "lng": 80.2707,
    "source": "http://www.wikidata.org/entity/Q18125923"
  },
  {
    "slug": "infrastructure-development-finance-company",
    "name": "Infrastructure Development Finance Company",
    "website": "http://www.idfc.com/",
    "city": "Chennai",
    "industry": "business",
    "sector": "Other",
    "founded": null,
    "lat": 13.0827,
    "lng": 80.2707,
    "source": "http://www.wikidata.org/entity/Q6031537"
  },
  {
    "slug": "irevna",
    "name": "Irevna",
    "website": "http://www.crisil.com/gra",
    "city": "Chennai",
    "industry": "business",
    "sector": "Other",
    "founded": 2001,
    "lat": 13.0827,
    "lng": 80.2707,
    "source": "http://www.wikidata.org/entity/Q6069420"
  },
  {
    "slug": "jsk-film-corporation",
    "name": "JSK Film Corporation",
    "website": "http://www.jskfilmcorporation.com",
    "city": "Chennai",
    "industry": "business",
    "sector": "Other",
    "founded": 2006,
    "lat": 13.0827,
    "lng": 80.2707,
    "source": "http://www.wikidata.org/entity/Q19892253"
  },
  {
    "slug": "karadi-tales",
    "name": "Karadi Tales",
    "website": "http://www.karaditales.com",
    "city": "Chennai",
    "industry": "publishing",
    "sector": "Other",
    "founded": 2008,
    "lat": 13.0827,
    "lng": 80.2707,
    "source": "http://www.wikidata.org/entity/Q6367839"
  },
  {
    "slug": "khazana-jewellery",
    "name": "Khazana jewellery",
    "website": "http://www.khazanajewellery.com/",
    "city": "Chennai",
    "industry": "jewelry",
    "sector": "Other",
    "founded": null,
    "lat": 13.0827,
    "lng": 80.2707,
    "source": "http://www.wikidata.org/entity/Q24907129"
  },
  {
    "slug": "landmark-bookstores",
    "name": "Landmark Bookstores",
    "website": "http://www.landmarkonthenet.com/",
    "city": "Chennai",
    "industry": "retail",
    "sector": "E-commerce",
    "founded": null,
    "lat": 13.0827,
    "lng": 80.2707,
    "source": "http://www.wikidata.org/entity/Q17063997"
  },
  {
    "slug": "lebrands-space",
    "name": "LeBrands.Space",
    "website": "https://lebrands.space",
    "city": "Chennai",
    "industry": "e-commerce",
    "sector": "E-commerce",
    "founded": 2025,
    "lat": 13.0827,
    "lng": 80.2707,
    "source": "http://www.wikidata.org/entity/Q139831952"
  },
  {
    "slug": "ma-foi-strategic-consultants",
    "name": "Ma Foi Strategic Consultants",
    "website": "http://mafoistrategy.com",
    "city": "Chennai",
    "industry": "business and other management consultancy activities",
    "sector": "Other",
    "founded": 2012,
    "lat": 13.0827,
    "lng": 80.2707,
    "source": "http://www.wikidata.org/entity/Q6720726"
  },
  {
    "slug": "medindia",
    "name": "Medindia",
    "website": "http://www.medindia.net/",
    "city": "Chennai",
    "industry": "business",
    "sector": "Other",
    "founded": null,
    "lat": 13.0827,
    "lng": 80.2707,
    "source": "http://www.wikidata.org/entity/Q17068778"
  },
  {
    "slug": "mednext-academy",
    "name": "MedNext Academy",
    "website": "https://mednext.academy",
    "city": "Chennai",
    "industry": "educational technology",
    "sector": "SaaS",
    "founded": 2021,
    "lat": 13.0827,
    "lng": 80.2707,
    "source": "http://www.wikidata.org/entity/Q141131559"
  },
  {
    "slug": "mgm-group-of-companies",
    "name": "MGM Group of Companies",
    "website": "http://www.mgm-india.com/",
    "city": "Chennai",
    "industry": "business",
    "sector": "Other",
    "founded": null,
    "lat": 13.0827,
    "lng": 80.2707,
    "source": "http://www.wikidata.org/entity/Q6715743"
  },
  {
    "slug": "millennial-labs",
    "name": "Millennial Labs",
    "website": "https://millenniallabs.in",
    "city": "Chennai",
    "industry": "business",
    "sector": "Other",
    "founded": null,
    "lat": 13.0827,
    "lng": 80.2707,
    "source": "http://www.wikidata.org/entity/Q140166010"
  },
  {
    "slug": "nissan-motor-india-private-limited",
    "name": "Nissan Motor India Private Limited",
    "website": "http://www.nissan.in",
    "city": "Chennai",
    "industry": "automotive industry",
    "sector": "Other",
    "founded": 2005,
    "lat": 13.0827,
    "lng": 80.2707,
    "source": "http://www.wikidata.org/entity/Q7041008"
  },
  {
    "slug": "notion-press",
    "name": "Notion Press",
    "website": "http://www.notionpress.com/",
    "city": "Chennai",
    "industry": "self-publishing",
    "sector": "Other",
    "founded": 2012,
    "lat": 13.0827,
    "lng": 80.2707,
    "source": "http://www.wikidata.org/entity/Q17145804"
  },
  {
    "slug": "photon-kathaas",
    "name": "Photon Kathaas",
    "website": "http://www.photonkathaas.com",
    "city": "Chennai",
    "industry": "business",
    "sector": "Other",
    "founded": 2010,
    "lat": 13.0827,
    "lng": 80.2707,
    "source": "http://www.wikidata.org/entity/Q7187842"
  },
  {
    "slug": "propertism-realty-advisors",
    "name": "Propertism Realty Advisors",
    "website": "https://www.propertism.in/",
    "city": "Chennai",
    "industry": "property management",
    "sector": "Other",
    "founded": 2017,
    "lat": 13.0827,
    "lng": 80.2707,
    "source": "http://www.wikidata.org/entity/Q140361493"
  },
  {
    "slug": "radiance-realty",
    "name": "Radiance Realty",
    "website": "http://radiancerealty.in/",
    "city": "Chennai",
    "industry": "business",
    "sector": "Other",
    "founded": 2012,
    "lat": 13.0827,
    "lng": 80.2707,
    "source": "http://www.wikidata.org/entity/Q17073435"
  },
  {
    "slug": "renault-nissan-automotive-india-private-limited",
    "name": "Renault Nissan Automotive India Private Limited",
    "website": "http://www.nissan.in",
    "city": "Chennai",
    "industry": "automotive industry",
    "sector": "Other",
    "founded": 2005,
    "lat": 13.0827,
    "lng": 80.2707,
    "source": "http://www.wikidata.org/entity/Q2143731"
  },
  {
    "slug": "royal-sundaram-general-insurance",
    "name": "Royal Sundaram General Insurance",
    "website": "http://www.royalsundaram.in/",
    "city": "Chennai",
    "industry": "insurance",
    "sector": "FinTech",
    "founded": 2001,
    "lat": 13.0827,
    "lng": 80.2707,
    "source": "http://www.wikidata.org/entity/Q18636403"
  },
  {
    "slug": "rpp-film-factory",
    "name": "RPP Film Factory",
    "website": "http://rppfilmfactory.blogspot.in",
    "city": "Chennai",
    "industry": "business",
    "sector": "Other",
    "founded": 2013,
    "lat": 13.0827,
    "lng": 80.2707,
    "source": "http://www.wikidata.org/entity/Q19895913"
  },
  {
    "slug": "sea6-energy",
    "name": "Sea6 Energy",
    "website": "http://www.sea6energy.com/",
    "city": "Chennai",
    "industry": "biofuel",
    "sector": "Other",
    "founded": null,
    "lat": 13.0827,
    "lng": 80.2707,
    "source": "http://www.wikidata.org/entity/Q17074141"
  },
  {
    "slug": "shriram-finance-limited",
    "name": "Shriram Finance Limited",
    "website": "https://www.shriramfinance.in/",
    "city": "Chennai",
    "industry": "business",
    "sector": "Other",
    "founded": null,
    "lat": 13.0827,
    "lng": 80.2707,
    "source": "http://www.wikidata.org/entity/Q17074288"
  },
  {
    "slug": "sun-pictures",
    "name": "Sun Pictures",
    "website": "http://sunpictures.in/index.html",
    "city": "Chennai",
    "industry": "business",
    "sector": "Other",
    "founded": 2008,
    "lat": 13.0827,
    "lng": 80.2707,
    "source": "http://www.wikidata.org/entity/Q7638437"
  },
  {
    "slug": "sundaram-clayton-limited",
    "name": "Sundaram - Clayton Limited",
    "website": "http://www.sundaram-clayton.com",
    "city": "Chennai",
    "industry": "business",
    "sector": "Other",
    "founded": null,
    "lat": 13.0827,
    "lng": 80.2707,
    "source": "http://www.wikidata.org/entity/Q17125821"
  },
  {
    "slug": "tamil-nadu-horticulture-development-agency",
    "name": "Tamil Nadu Horticulture Development Agency",
    "website": "http://www.tanhoda.gov.in/",
    "city": "Chennai",
    "industry": "agriculture",
    "sector": "Other",
    "founded": 2004,
    "lat": 13.0827,
    "lng": 80.2707,
    "source": "http://www.wikidata.org/entity/Q7681285"
  },
  {
    "slug": "tamil-nadu-transmission-corporation",
    "name": "Tamil Nadu Transmission Corporation",
    "website": "http://www.tantransco.gov.in",
    "city": "Chennai",
    "industry": "electricity supply company",
    "sector": "Other",
    "founded": 2010,
    "lat": 13.0827,
    "lng": 80.2707,
    "source": "http://www.wikidata.org/entity/Q17074936"
  },
  {
    "slug": "thadam-media",
    "name": "Thadam Media",
    "website": "https://thadammedia.in",
    "city": "Chennai",
    "industry": "business",
    "sector": "Other",
    "founded": 2026,
    "lat": 13.0827,
    "lng": 80.2707,
    "source": "http://www.wikidata.org/entity/Q140274616"
  },
  {
    "slug": "the-chennai-angels",
    "name": "The Chennai Angels",
    "website": "http://www.thechennaiangels.com/",
    "city": "Chennai",
    "industry": "business",
    "sector": "Other",
    "founded": 2007,
    "lat": 13.0827,
    "lng": 80.2707,
    "source": "http://www.wikidata.org/entity/Q24913040"
  },
  {
    "slug": "the-eplane-company",
    "name": "The ePlane Company",
    "website": "https://www.eplane.ai/",
    "city": "Chennai",
    "industry": "business",
    "sector": "Other",
    "founded": null,
    "lat": 13.0827,
    "lng": 80.2707,
    "source": "http://www.wikidata.org/entity/Q140356705"
  },
  {
    "slug": "thuyonx",
    "name": "Thuyonx",
    "website": "https://thuyonx.in",
    "city": "Chennai",
    "industry": "artificial intelligence",
    "sector": "Other",
    "founded": 2024,
    "lat": 13.0827,
    "lng": 80.2707,
    "source": "http://www.wikidata.org/entity/Q140323351"
  },
  {
    "slug": "united-india-insurance-company-limited",
    "name": "United India Insurance Company Limited",
    "website": "http://www.uiic.co.in/",
    "city": "Chennai",
    "industry": "business",
    "sector": "Other",
    "founded": null,
    "lat": 13.0827,
    "lng": 80.2707,
    "source": "http://www.wikidata.org/entity/Q7887870"
  },
  {
    "slug": "vansan-movies",
    "name": "Vansan Movies",
    "website": "http://www.vansanmovies.com",
    "city": "Chennai",
    "industry": "business",
    "sector": "Other",
    "founded": 2015,
    "lat": 13.0827,
    "lng": 80.2707,
    "source": "http://www.wikidata.org/entity/Q28961492"
  },
  {
    "slug": "vendhar-movies",
    "name": "Vendhar Movies",
    "website": "http://vendharmovies.org/",
    "city": "Chennai",
    "industry": "business",
    "sector": "Other",
    "founded": 2011,
    "lat": 13.0827,
    "lng": 80.2707,
    "source": "http://www.wikidata.org/entity/Q18395294"
  },
  {
    "slug": "bakeys",
    "name": "Bakeys",
    "website": "http://www.bakeys.com",
    "city": "Hyderabad",
    "industry": "food industry",
    "sector": "Other",
    "founded": 2010,
    "lat": 17.385,
    "lng": 78.4867,
    "source": "http://www.wikidata.org/entity/Q24915902"
  },
  {
    "slug": "blaksyd",
    "name": "Blaksyd",
    "website": "https://blaksyd.com",
    "city": "Hyderabad",
    "industry": "artificial intelligence",
    "sector": "Other",
    "founded": 2026,
    "lat": 17.385,
    "lng": 78.4867,
    "source": "http://www.wikidata.org/entity/Q140068113"
  },
  {
    "slug": "byrraju-foundation",
    "name": "Byrraju Foundation",
    "website": "http://byrrajufoundation.org",
    "city": "Hyderabad",
    "industry": "business",
    "sector": "Other",
    "founded": 2001,
    "lat": 17.385,
    "lng": 78.4867,
    "source": "http://www.wikidata.org/entity/Q5004504"
  },
  {
    "slug": "centre-for-sustainable-agriculture",
    "name": "Centre for Sustainable Agriculture",
    "website": "http://www.csa-india.org/",
    "city": "Hyderabad",
    "industry": "business",
    "sector": "Other",
    "founded": null,
    "lat": 17.385,
    "lng": 78.4867,
    "source": "http://www.wikidata.org/entity/Q5062596"
  },
  {
    "slug": "drunken-monkey",
    "name": "Drunken Monkey",
    "website": "http://thedrunkenmonkey.in/",
    "city": "Hyderabad",
    "industry": "business",
    "sector": "Other",
    "founded": null,
    "lat": 17.385,
    "lng": 78.4867,
    "source": "http://www.wikidata.org/entity/Q60761767"
  },
  {
    "slug": "gadget-rebirth",
    "name": "Gadget Rebirth",
    "website": "https://www.gadgetrebirth.com",
    "city": "Hyderabad",
    "industry": "refurbishing",
    "sector": "Other",
    "founded": 2024,
    "lat": 17.385,
    "lng": 78.4867,
    "source": "http://www.wikidata.org/entity/Q139720495"
  },
  {
    "slug": "gcosol-platforms",
    "name": "Gcosol Platforms",
    "website": "https://gcosol.com",
    "city": "Hyderabad",
    "industry": "conglomerate",
    "sector": "Other",
    "founded": 2017,
    "lat": 17.385,
    "lng": 78.4867,
    "source": "http://www.wikidata.org/entity/Q140518247"
  },
  {
    "slug": "homefleet",
    "name": "Homefleet",
    "website": "https://www.homefleet.in/",
    "city": "Hyderabad",
    "industry": "Real Estate",
    "sector": "Other",
    "founded": 2023,
    "lat": 17.385,
    "lng": 78.4867,
    "source": "http://www.wikidata.org/entity/Q140447034"
  },
  {
    "slug": "icube-logics",
    "name": "iCube Logics",
    "website": "https://www.icubelogics.com/",
    "city": "Hyderabad",
    "industry": "Engineering Services",
    "sector": "Other",
    "founded": 2008,
    "lat": 17.385,
    "lng": 78.4867,
    "source": "http://www.wikidata.org/entity/Q139373019"
  },
  {
    "slug": "kad-movies",
    "name": "Kad movies",
    "website": "http://www.kaddvd.com",
    "city": "Hyderabad",
    "industry": "entertainment",
    "sector": "Media",
    "founded": 2000,
    "lat": 17.385,
    "lng": 78.4867,
    "source": "http://www.wikidata.org/entity/Q6344919"
  },
  {
    "slug": "keka-hr",
    "name": "Keka HR",
    "website": "https://www.keka.com",
    "city": "Hyderabad",
    "industry": "business",
    "sector": "Other",
    "founded": null,
    "lat": 17.385,
    "lng": 78.4867,
    "source": "http://www.wikidata.org/entity/Q96577145"
  },
  {
    "slug": "kraionyx-ai",
    "name": "Kraionyx AI",
    "website": "https://www.kraionyx.com",
    "city": "Hyderabad",
    "industry": "artificial intelligence",
    "sector": "Other",
    "founded": 2025,
    "lat": 17.385,
    "lng": 78.4867,
    "source": "http://www.wikidata.org/entity/Q140632977"
  },
  {
    "slug": "latestone",
    "name": "LatestOne",
    "website": "http://www.latestone.com",
    "city": "Hyderabad",
    "industry": "retail",
    "sector": "E-commerce",
    "founded": 2014,
    "lat": 17.385,
    "lng": 78.4867,
    "source": "http://www.wikidata.org/entity/Q30644840"
  },
  {
    "slug": "laurus-labs",
    "name": "Laurus Labs",
    "website": "http://lauruslabs.com/",
    "city": "Hyderabad",
    "industry": "biotechnology",
    "sector": "SaaS",
    "founded": 2005,
    "lat": 17.385,
    "lng": 78.4867,
    "source": "http://www.wikidata.org/entity/Q96387060"
  },
  {
    "slug": "lifespring-hospitals",
    "name": "LifeSpring Hospitals",
    "website": "http://www.lifespring.in",
    "city": "Hyderabad",
    "industry": "business",
    "sector": "Other",
    "founded": 2005,
    "lat": 17.385,
    "lng": 78.4867,
    "source": "http://www.wikidata.org/entity/Q6544636"
  },
  {
    "slug": "moksha-media",
    "name": "Moksha Media",
    "website": "https://www.mokshamedia.co.in",
    "city": "Hyderabad",
    "industry": "marketing",
    "sector": "Other",
    "founded": 2002,
    "lat": 17.385,
    "lng": 78.4867,
    "source": "http://www.wikidata.org/entity/Q140772682"
  },
  {
    "slug": "neumeal",
    "name": "NeuMeal",
    "website": "https://www.neumeal.in",
    "city": "Hyderabad",
    "industry": "e-commerce",
    "sector": "E-commerce",
    "founded": 2025,
    "lat": 17.385,
    "lng": 78.4867,
    "source": "http://www.wikidata.org/entity/Q139594276"
  },
  {
    "slug": "ots-advertising",
    "name": "OTS Advertising",
    "website": "http://ots.net.in",
    "city": "Hyderabad",
    "industry": "business",
    "sector": "Other",
    "founded": null,
    "lat": 17.385,
    "lng": 78.4867,
    "source": "http://www.wikidata.org/entity/Q64767743"
  },
  {
    "slug": "quadato",
    "name": "Quadato",
    "website": "https://quadato.com/",
    "city": "Hyderabad",
    "industry": "business",
    "sector": "Other",
    "founded": 2021,
    "lat": 17.385,
    "lng": 78.4867,
    "source": "http://www.wikidata.org/entity/Q106902613"
  },
  {
    "slug": "rdp-technologies-limited",
    "name": "RDP Technologies Limited",
    "website": "https://www.rdp.in",
    "city": "Hyderabad",
    "industry": "computer hardware industry",
    "sector": "Other",
    "founded": 2012,
    "lat": 17.385,
    "lng": 78.4867,
    "source": "http://www.wikidata.org/entity/Q139831559"
  },
  {
    "slug": "t-hub",
    "name": "T-Hub",
    "website": "http://www.t-hub.co/",
    "city": "Hyderabad",
    "industry": "business",
    "sector": "Other",
    "founded": 2015,
    "lat": 17.385,
    "lng": 78.4867,
    "source": "http://www.wikidata.org/entity/Q21503632"
  },
  {
    "slug": "t-hub-2",
    "name": "T-Hub 2",
    "website": "http://www.t-hub.co/",
    "city": "Hyderabad",
    "industry": "business",
    "sector": "Other",
    "founded": 2022,
    "lat": 17.385,
    "lng": 78.4867,
    "source": "http://www.wikidata.org/entity/Q113302763"
  },
  {
    "slug": "tax-garden",
    "name": "Tax Garden",
    "website": "https://www.taxgarden.in",
    "city": "Hyderabad",
    "industry": "business",
    "sector": "Other",
    "founded": 2026,
    "lat": 17.385,
    "lng": 78.4867,
    "source": "http://www.wikidata.org/entity/Q139708857"
  },
  {
    "slug": "ths-impex",
    "name": "THS Impex",
    "website": "https://www.thsimpex.com/",
    "city": "Hyderabad",
    "industry": "herb",
    "sector": "Other",
    "founded": 2020,
    "lat": 17.385,
    "lng": 78.4867,
    "source": "http://www.wikidata.org/entity/Q140358478"
  },
  {
    "slug": "yeshveda",
    "name": "Yeshveda",
    "website": "https://yeshveda.com/",
    "city": "Hyderabad",
    "industry": "cosmetics industry",
    "sector": "Other",
    "founded": 2019,
    "lat": 17.385,
    "lng": 78.4867,
    "source": "http://www.wikidata.org/entity/Q140442418"
  },
  {
    "slug": "baecars",
    "name": "BaeCars",
    "website": "https://baecars.com/",
    "city": "Jaipur",
    "industry": "peer-to-peer carsharing",
    "sector": "Other",
    "founded": 2019,
    "lat": 26.9124,
    "lng": 75.7873,
    "source": "http://www.wikidata.org/entity/Q140693137"
  },
  {
    "slug": "bludip-industries-private-limited",
    "name": "Bludip Industries Private Limited",
    "website": "https://BLUDIPBRUSH.COM",
    "city": "Jaipur",
    "industry": "paint tool accessory",
    "sector": "Other",
    "founded": 2026,
    "lat": 26.9124,
    "lng": 75.7873,
    "source": "http://www.wikidata.org/entity/Q140982891"
  },
  {
    "slug": "canrim-pharma",
    "name": "Canrim Pharma",
    "website": "https://canrimpharma.com",
    "city": "Jaipur",
    "industry": "pharmaceutical industry",
    "sector": "HealthTech",
    "founded": 2026,
    "lat": 26.9124,
    "lng": 75.7873,
    "source": "http://www.wikidata.org/entity/Q139905717"
  },
  {
    "slug": "desal",
    "name": "deSal",
    "website": "https://desal.in",
    "city": "Jaipur",
    "industry": "cosmetics industry",
    "sector": "Other",
    "founded": 2026,
    "lat": 26.9124,
    "lng": 75.7873,
    "source": "http://www.wikidata.org/entity/Q140753676"
  },
  {
    "slug": "devicecure",
    "name": "Devicecure",
    "website": "https://www.devicecure.in/",
    "city": "Jaipur",
    "industry": "repair of computers and communication equipment",
    "sector": "Other",
    "founded": 2019,
    "lat": 26.9124,
    "lng": 75.7873,
    "source": "http://www.wikidata.org/entity/Q141100262"
  },
  {
    "slug": "heylin-spark",
    "name": "Heylin Spark",
    "website": "https://www.heylinspark.com/",
    "city": "Jaipur",
    "industry": "advertising",
    "sector": "Other",
    "founded": 2021,
    "lat": 26.9124,
    "lng": 75.7873,
    "source": "http://www.wikidata.org/entity/Q131833633"
  },
  {
    "slug": "india-magica-tours",
    "name": "India Magica Tours",
    "website": "https://indiamagicatours.it/",
    "city": "Jaipur",
    "industry": "tourism",
    "sector": "Other",
    "founded": null,
    "lat": 26.9124,
    "lng": 75.7873,
    "source": "http://www.wikidata.org/entity/Q140192228"
  },
  {
    "slug": "movozen-private-limited",
    "name": "Movozen Private Limited",
    "website": "https://www.mobosafe.in",
    "city": "Jaipur",
    "industry": "telematics",
    "sector": "Other",
    "founded": 2026,
    "lat": 26.9124,
    "lng": 75.7873,
    "source": "http://www.wikidata.org/entity/Q140753344"
  },
  {
    "slug": "nimara-ventures",
    "name": "Nimara Ventures",
    "website": "https://www.nimaraventures.com/",
    "city": "Jaipur",
    "industry": "artificial intelligence",
    "sector": "Other",
    "founded": 2025,
    "lat": 26.9124,
    "lng": 75.7873,
    "source": "http://www.wikidata.org/entity/Q141127975"
  },
  {
    "slug": "planet-arts",
    "name": "Planet Arts",
    "website": "https://www.planetarts.in",
    "city": "Jaipur",
    "industry": "rug",
    "sector": "Other",
    "founded": 2004,
    "lat": 26.9124,
    "lng": 75.7873,
    "source": "http://www.wikidata.org/entity/Q139946142"
  },
  {
    "slug": "rajasthan-rajya-vidyut-utpadan-nigam",
    "name": "Rajasthan Rajya Vidyut Utpadan Nigam",
    "website": "http://rvunl.com/",
    "city": "Jaipur",
    "industry": "electricity generation",
    "sector": "Other",
    "founded": 2002,
    "lat": 26.9124,
    "lng": 75.7873,
    "source": "http://www.wikidata.org/entity/Q7285839"
  },
  {
    "slug": "rajasthan-state-road-transport-corporation",
    "name": "Rajasthan State Road Transport Corporation",
    "website": "http://www.rsrtc.rajasthan.gov.in",
    "city": "Jaipur",
    "industry": "business",
    "sector": "Other",
    "founded": null,
    "lat": 26.9124,
    "lng": 75.7873,
    "source": "http://www.wikidata.org/entity/Q7285846"
  },
  {
    "slug": "sangri-internet",
    "name": "Sangri Internet",
    "website": "https://www.sangriinternet.in/",
    "city": "Jaipur",
    "industry": "news media",
    "sector": "Media",
    "founded": 2018,
    "lat": 26.9124,
    "lng": 75.7873,
    "source": "http://www.wikidata.org/entity/Q126095944"
  },
  {
    "slug": "scnwire",
    "name": "SCNWire",
    "website": "https://www.scnwire.com/",
    "city": "Jaipur",
    "industry": "business",
    "sector": "Other",
    "founded": 2024,
    "lat": 26.9124,
    "lng": 75.7873,
    "source": "http://www.wikidata.org/entity/Q138643838"
  },
  {
    "slug": "shriram-general-insurance",
    "name": "Shriram General Insurance",
    "website": "https://www.shriramgi.com",
    "city": "Jaipur",
    "industry": "general insurance",
    "sector": "FinTech",
    "founded": 2008,
    "lat": 26.9124,
    "lng": 75.7873,
    "source": "http://www.wikidata.org/entity/Q106309795"
  },
  {
    "slug": "tatwansh-digital-private-limited",
    "name": "Tatwansh Digital Private Limited",
    "website": "https://tatwansh.com",
    "city": "Jaipur",
    "industry": "visualization",
    "sector": "Other",
    "founded": 2023,
    "lat": 26.9124,
    "lng": 75.7873,
    "source": "http://www.wikidata.org/entity/Q139545937"
  },
  {
    "slug": "texaura",
    "name": "Texaura",
    "website": "https://texaura.com",
    "city": "Jaipur",
    "industry": "e-commerce",
    "sector": "E-commerce",
    "founded": 2024,
    "lat": 26.9124,
    "lng": 75.7873,
    "source": "http://www.wikidata.org/entity/Q134426430"
  },
  {
    "slug": "the-rajasthan-state-cooperative-bank-limited",
    "name": "The Rajasthan State Cooperative Bank Limited",
    "website": "http://www.rscb.org.in/",
    "city": "Jaipur",
    "industry": "business",
    "sector": "Other",
    "founded": null,
    "lat": 26.9124,
    "lng": 75.7873,
    "source": "http://www.wikidata.org/entity/Q74488270"
  },
  {
    "slug": "aashirvad-cinemas",
    "name": "Aashirvad Cinemas",
    "website": "http://aashirvadcinemas.com",
    "city": "Kochi",
    "industry": "business",
    "sector": "Other",
    "founded": 2000,
    "lat": 9.9312,
    "lng": 76.2673,
    "source": "http://www.wikidata.org/entity/Q4662716"
  },
  {
    "slug": "amrita-learning",
    "name": "Amrita Learning",
    "website": "http://www.amritalearning.com/",
    "city": "Kochi",
    "industry": "Internet",
    "sector": "SaaS",
    "founded": 2005,
    "lat": 9.9312,
    "lng": 76.2673,
    "source": "http://www.wikidata.org/entity/Q4748674"
  },
  {
    "slug": "dotnot",
    "name": "Dotnot",
    "website": "https://dotnot.solutions",
    "city": "Kochi",
    "industry": "business and other management consultancy activities",
    "sector": "Other",
    "founded": 2023,
    "lat": 9.9312,
    "lng": 76.2673,
    "source": "http://www.wikidata.org/entity/Q140312156"
  },
  {
    "slug": "geojit-technologies-pvt-ltd",
    "name": "Geojit Technologies Pvt Ltd",
    "website": "https://www.branch.geojit.com",
    "city": "Kochi",
    "industry": "financial services",
    "sector": "FinTech",
    "founded": 2000,
    "lat": 9.9312,
    "lng": 76.2673,
    "source": "http://www.wikidata.org/entity/Q5535285"
  },
  {
    "slug": "greater-cochin-development-authority",
    "name": "Greater Cochin Development Authority",
    "website": "http://www.gcdaonline.com/",
    "city": "Kochi",
    "industry": "business",
    "sector": "Other",
    "founded": null,
    "lat": 9.9312,
    "lng": 76.2673,
    "source": "http://www.wikidata.org/entity/Q5600511"
  },
  {
    "slug": "infopark",
    "name": "InfoPark",
    "website": "https://infopark.in/",
    "city": "Kochi",
    "industry": "information technology",
    "sector": "SaaS",
    "founded": 2004,
    "lat": 9.9312,
    "lng": 76.2673,
    "source": "http://www.wikidata.org/entity/Q2003162"
  },
  {
    "slug": "joyalukkas",
    "name": "Joyalukkas",
    "website": "https://www.joyalukkas.com",
    "city": "Kochi",
    "industry": "jewelry",
    "sector": "Other",
    "founded": 2009,
    "lat": 9.9312,
    "lng": 76.2673,
    "source": "http://www.wikidata.org/entity/Q6297357"
  },
  {
    "slug": "kerala-urban-road-transport-corporation",
    "name": "Kerala Urban Road Transport Corporation",
    "website": "http://www.kurtc.in/",
    "city": "Kochi",
    "industry": "business",
    "sector": "Other",
    "founded": 2014,
    "lat": 9.9312,
    "lng": 76.2673,
    "source": "http://www.wikidata.org/entity/Q19892654"
  },
  {
    "slug": "kochi-metro-rail-limited",
    "name": "Kochi Metro Rail Limited",
    "website": "https://kochimetro.org",
    "city": "Kochi",
    "industry": "public transport",
    "sector": "Logistics",
    "founded": 2011,
    "lat": 9.9312,
    "lng": 76.2673,
    "source": "http://www.wikidata.org/entity/Q50375387"
  },
  {
    "slug": "kochi-water-metro-limited",
    "name": "Kochi Water Metro Limited",
    "website": "https://watermetro.co.in",
    "city": "Kochi",
    "industry": "public transport",
    "sector": "Logistics",
    "founded": 2021,
    "lat": 9.9312,
    "lng": 76.2673,
    "source": "http://www.wikidata.org/entity/Q117856926"
  },
  {
    "slug": "marikar-films",
    "name": "Marikar Films",
    "website": "http://www.marikargroup.in/content.aspx?code=films;",
    "city": "Kochi",
    "industry": "business",
    "sector": "Other",
    "founded": 2007,
    "lat": 9.9312,
    "lng": 76.2673,
    "source": "http://www.wikidata.org/entity/Q6763424"
  },
  {
    "slug": "plant-lipids",
    "name": "Plant Lipids",
    "website": "http://plantlipids.com/",
    "city": "Kochi",
    "industry": "business",
    "sector": "Other",
    "founded": null,
    "lat": 9.9312,
    "lng": 76.2673,
    "source": "http://www.wikidata.org/entity/Q28171821"
  },
  {
    "slug": "satyam-audios",
    "name": "Satyam Audios",
    "website": "http://satyamaudios.com",
    "city": "Kochi",
    "industry": "business",
    "sector": "Other",
    "founded": null,
    "lat": 9.9312,
    "lng": 76.2673,
    "source": "http://www.wikidata.org/entity/Q23309817"
  },
  {
    "slug": "scigenom-labs",
    "name": "SciGenom Labs",
    "website": "http://www.scigenom.com/",
    "city": "Kochi",
    "industry": "business",
    "sector": "Other",
    "founded": 2009,
    "lat": 9.9312,
    "lng": 76.2673,
    "source": "http://www.wikidata.org/entity/Q18378083"
  },
  {
    "slug": "bharat-road-network-limited",
    "name": "Bharat Road Network Limited",
    "website": "http://www.brnl.in/",
    "city": "Kolkata",
    "industry": "infrastructure",
    "sector": "Other",
    "founded": 2006,
    "lat": 22.5726,
    "lng": 88.3639,
    "source": "http://www.wikidata.org/entity/Q30592551"
  },
  {
    "slug": "bisk-farm",
    "name": "Bisk Farm",
    "website": "http://www.biskfarm.com/",
    "city": "Kolkata",
    "industry": "industrial manufacturing",
    "sector": "Other",
    "founded": 2000,
    "lat": 22.5726,
    "lng": 88.3639,
    "source": "http://www.wikidata.org/entity/Q16241925"
  },
  {
    "slug": "promotedge",
    "name": "PromotEdge",
    "website": "https://promotedge.com/",
    "city": "Kolkata",
    "industry": "marketing",
    "sector": "Other",
    "founded": 2015,
    "lat": 22.5726,
    "lng": 88.3639,
    "source": "http://www.wikidata.org/entity/Q139832210"
  },
  {
    "slug": "square",
    "name": "Square",
    "website": "https://www.squareconsultancyservices.com/",
    "city": "Kolkata",
    "industry": "business",
    "sector": "Other",
    "founded": null,
    "lat": 22.5726,
    "lng": 88.3639,
    "source": "http://www.wikidata.org/entity/Q140770732"
  },
  {
    "slug": "vikram-solar-pvt-ltd",
    "name": "Vikram Solar Pvt. Ltd",
    "website": "http://www.vikramsolar.com/",
    "city": "Kolkata",
    "industry": "business",
    "sector": "Other",
    "founded": 2006,
    "lat": 22.5726,
    "lng": 88.3639,
    "source": "http://www.wikidata.org/entity/Q24949477"
  },
  {
    "slug": "92-7-big-fm",
    "name": "92.7 Big FM",
    "website": "https://bigfmindia.com/",
    "city": "Mumbai",
    "industry": "business",
    "sector": "Other",
    "founded": null,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q3763950"
  },
  {
    "slug": "abof",
    "name": "Abof",
    "website": "http://www.abof.com/",
    "city": "Mumbai",
    "industry": "business",
    "sector": "Other",
    "founded": 2015,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q24590037"
  },
  {
    "slug": "aditya-birla-science-and-technology-company-private-limited",
    "name": "Aditya Birla Science and Technology Company Private Limited",
    "website": "http://www.adityabirla.com/innovation/abstcpl",
    "city": "Mumbai",
    "industry": "business",
    "sector": "Other",
    "founded": null,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q47526526"
  },
  {
    "slug": "aerpace",
    "name": "aerpace",
    "website": "https://www.aerpace.com/",
    "city": "Mumbai",
    "industry": "business",
    "sector": "Other",
    "founded": null,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q140985579"
  },
  {
    "slug": "air-india-limited",
    "name": "Air India Limited",
    "website": "http://www.airindia.com/",
    "city": "Mumbai",
    "industry": "aviation",
    "sector": "Other",
    "founded": 2007,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q4698035"
  },
  {
    "slug": "apex-infosys-india",
    "name": "Apex Infosys India",
    "website": "https://www.apexinfosys.in",
    "city": "Mumbai",
    "industry": "business",
    "sector": "Other",
    "founded": 2017,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q96760080"
  },
  {
    "slug": "asa-productions-and-enterprises",
    "name": "ASA Productions and Enterprises",
    "website": "http://www.asaproductions.in/",
    "city": "Mumbai",
    "industry": "business",
    "sector": "Other",
    "founded": 2006,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q4654061"
  },
  {
    "slug": "atom-technologies",
    "name": "Atom Technologies",
    "website": "http://www.atomtech.in",
    "city": "Mumbai",
    "industry": "business",
    "sector": "Other",
    "founded": 2006,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q4817227"
  },
  {
    "slug": "audi-india",
    "name": "Audi India",
    "website": "http://www.audi.in",
    "city": "Mumbai",
    "industry": "automotive industry",
    "sector": "Other",
    "founded": 2004,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q4819702"
  },
  {
    "slug": "bajaj-nomarks",
    "name": "Bajaj Nomarks",
    "website": "http://www.bajajnomarks.com",
    "city": "Mumbai",
    "industry": "skin care",
    "sector": "Other",
    "founded": 2001,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q51031692"
  },
  {
    "slug": "balaji-motion-pictures",
    "name": "Balaji Motion Pictures",
    "website": "http://www.balajitelefilms.com",
    "city": "Mumbai",
    "industry": "business",
    "sector": "Other",
    "founded": 2002,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q4849846"
  },
  {
    "slug": "big-cinemas",
    "name": "Big Cinemas",
    "website": "http://www.bigcinemas.com/",
    "city": "Mumbai",
    "industry": "entertainment",
    "sector": "Media",
    "founded": 2001,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q4905449"
  },
  {
    "slug": "brandforge-ai",
    "name": "BrandForge AI",
    "website": "https://brandforge.me",
    "city": "Mumbai",
    "industry": "artificial intelligence",
    "sector": "Other",
    "founded": 2025,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q140225401"
  },
  {
    "slug": "capital-first-ltd",
    "name": "Capital First Ltd.",
    "website": "https://www.capitalfirst.com",
    "city": "Mumbai",
    "industry": "non-banking financial company",
    "sector": "FinTech",
    "founded": 2012,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q39054559"
  },
  {
    "slug": "cartrade-com",
    "name": "CarTrade.com",
    "website": "http://www.cartrade.com/",
    "city": "Mumbai",
    "industry": "automotive industry",
    "sector": "Other",
    "founded": 2010,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q21190428"
  },
  {
    "slug": "cell-18",
    "name": "Cell 18",
    "website": "http://www.cell18.in",
    "city": "Mumbai",
    "industry": "business",
    "sector": "Other",
    "founded": 2003,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q5058140"
  },
  {
    "slug": "cinex-asia",
    "name": "Cinex Asia",
    "website": "http://www.cinexasia.com/",
    "city": "Mumbai",
    "industry": "business",
    "sector": "Other",
    "founded": null,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q5120905"
  },
  {
    "slug": "closr",
    "name": "Closr",
    "website": "https://closr.in",
    "city": "Mumbai",
    "industry": "executive search",
    "sector": "Other",
    "founded": 2025,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q140832509"
  },
  {
    "slug": "covestro-india",
    "name": "Covestro (India)",
    "website": "https://www.covestro.in/en",
    "city": "Mumbai",
    "industry": "business",
    "sector": "Other",
    "founded": null,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q68462598"
  },
  {
    "slug": "craftsvilla",
    "name": "Craftsvilla",
    "website": "http://www.craftsvilla.com",
    "city": "Mumbai",
    "industry": "business",
    "sector": "Other",
    "founded": 2011,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q24914808"
  },
  {
    "slug": "creative-eye-limited",
    "name": "Creative Eye Limited",
    "website": "http://www.creativeeye.com/",
    "city": "Mumbai",
    "industry": "media conglomerate",
    "sector": "Media",
    "founded": null,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q5183518"
  },
  {
    "slug": "croma",
    "name": "Cromā",
    "website": "https://www.croma.com/",
    "city": "Mumbai",
    "industry": "retail",
    "sector": "E-commerce",
    "founded": 2006,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q5187683"
  },
  {
    "slug": "d-badami",
    "name": "D BADAMI",
    "website": "https://www.dbadami.com/",
    "city": "Mumbai",
    "industry": "textile industry",
    "sector": "Other",
    "founded": 2018,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q140250356"
  },
  {
    "slug": "d-damas",
    "name": "D'damas",
    "website": "http://www.ddamas.co.in/",
    "city": "Mumbai",
    "industry": "business",
    "sector": "Other",
    "founded": 2003,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q5203200"
  },
  {
    "slug": "dar-motion-pictures",
    "name": "DAR motion pictures",
    "website": "http://www.darworld.com",
    "city": "Mumbai",
    "industry": "film production",
    "sector": "Other",
    "founded": 2009,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q5204317"
  },
  {
    "slug": "delhi-art-gallery",
    "name": "Delhi Art Gallery",
    "website": "https://dagworld.com/",
    "city": "Mumbai",
    "industry": "business",
    "sector": "Other",
    "founded": null,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q120849591"
  },
  {
    "slug": "director-s-kut-productions",
    "name": "Director's Kut Productions",
    "website": "http://www.directorskutproduction.com/",
    "city": "Mumbai",
    "industry": "business",
    "sector": "Other",
    "founded": 2007,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q5280497"
  },
  {
    "slug": "directorate-general-of-shipping",
    "name": "Directorate General of Shipping",
    "website": "http://www.dgshipping.com/",
    "city": "Mumbai",
    "industry": "Maritime",
    "sector": "Other",
    "founded": null,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q5280626"
  },
  {
    "slug": "dmart",
    "name": "DMart",
    "website": "https://www.dmartindia.com",
    "city": "Mumbai",
    "industry": "retail",
    "sector": "E-commerce",
    "founded": 2005,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q5203271"
  },
  {
    "slug": "dolphin-films-pvt-ltd",
    "name": "Dolphin Films Pvt. Ltd",
    "website": "http://www.dolphinfilmsindia.com/",
    "city": "Mumbai",
    "industry": "film production",
    "sector": "Other",
    "founded": null,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q5289625"
  },
  {
    "slug": "drona-mobile",
    "name": "DRONA Mobile",
    "website": "http://www.dronahq.com/",
    "city": "Mumbai",
    "industry": "information technology",
    "sector": "SaaS",
    "founded": 2007,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q5206068"
  },
  {
    "slug": "dukaan",
    "name": "Dukaan",
    "website": "https://mydukaan.io/",
    "city": "Mumbai",
    "industry": "e-commerce",
    "sector": "E-commerce",
    "founded": 2019,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q105071140"
  },
  {
    "slug": "ecobot",
    "name": "Ecobot",
    "website": "https://www.ecobot.co.in/",
    "city": "Mumbai",
    "industry": "Waste Management",
    "sector": "Other",
    "founded": 2017,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q137553926"
  },
  {
    "slug": "edelweiss-broking-limited",
    "name": "Edelweiss Broking Limited",
    "website": "https://www.edelweissfin.com",
    "city": "Mumbai",
    "industry": "business",
    "sector": "Other",
    "founded": 2008,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q29025132"
  },
  {
    "slug": "edupristine",
    "name": "EduPristine",
    "website": "http://www.edupristine.com/",
    "city": "Mumbai",
    "industry": "business",
    "sector": "Other",
    "founded": 2007,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q25245667"
  },
  {
    "slug": "ek-type",
    "name": "Ek Type",
    "website": "https://ektype.in",
    "city": "Mumbai",
    "industry": "business",
    "sector": "Other",
    "founded": null,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q89462001"
  },
  {
    "slug": "emerge-digital",
    "name": "Emerge Digital",
    "website": "https://emergedigital.co/",
    "city": "Mumbai",
    "industry": "web design",
    "sector": "Other",
    "founded": 2018,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q139586331"
  },
  {
    "slug": "essar-hypermart",
    "name": "Essar Hypermart",
    "website": "http://www.essarhypermart.in",
    "city": "Mumbai",
    "industry": "retail",
    "sector": "E-commerce",
    "founded": 2006,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q5399374"
  },
  {
    "slug": "f21-properties",
    "name": "F21 Properties",
    "website": "https://f21properties.com",
    "city": "Mumbai",
    "industry": "real estate business",
    "sector": "Other",
    "founded": null,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q140937043"
  },
  {
    "slug": "fairbridge-capital",
    "name": "Fairbridge Capital",
    "website": "http://www.fairbridgecapital.com/",
    "city": "Mumbai",
    "industry": "business",
    "sector": "Other",
    "founded": null,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q23010917"
  },
  {
    "slug": "film-farm-india",
    "name": "Film Farm India",
    "website": "http://www.filmfarmindia.com/our-portfolio.html",
    "city": "Mumbai",
    "industry": "business",
    "sector": "Other",
    "founded": 2004,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q5448937"
  },
  {
    "slug": "filmymantra",
    "name": "Filmymantra",
    "website": "https://filmymantra.com",
    "city": "Mumbai",
    "industry": "media industry",
    "sector": "Media",
    "founded": 2014,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q124563219"
  },
  {
    "slug": "firstsource",
    "name": "Firstsource",
    "website": "http://www.firstsource.com",
    "city": "Mumbai",
    "industry": "business process management",
    "sector": "Other",
    "founded": 2000,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q5454288"
  },
  {
    "slug": "fried-water-films-and-entertainment",
    "name": "Fried Water Films and Entertainment",
    "website": "http://www.friedwaterfilms.com",
    "city": "Mumbai",
    "industry": "business",
    "sector": "Other",
    "founded": 2013,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q24930002"
  },
  {
    "slug": "future-group",
    "name": "Future Group",
    "website": "http://www.futuregroup.in",
    "city": "Mumbai",
    "industry": "retail",
    "sector": "E-commerce",
    "founded": null,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q5510683"
  },
  {
    "slug": "gameeon",
    "name": "GameEon",
    "website": "http://www.gameeon.in/",
    "city": "Mumbai",
    "industry": "video game industry",
    "sector": "Other",
    "founded": 2011,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q16251010"
  },
  {
    "slug": "global-vectra-helicorp-limited",
    "name": "Global Vectra Helicorp Limited",
    "website": "http://www.globalhelicorp.com/index.asp",
    "city": "Mumbai",
    "industry": "aviation",
    "sector": "Other",
    "founded": null,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q5570752"
  },
  {
    "slug": "godrej-consumer-products-limited",
    "name": "Godrej Consumer Products Limited",
    "website": "http://godrejcp.com/",
    "city": "Mumbai",
    "industry": "fast-moving consumer goods",
    "sector": "Other",
    "founded": 2001,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q5576809"
  },
  {
    "slug": "godrej-properties-limited",
    "name": "Godrej Properties Limited",
    "website": "http://www.godrejproperties.com/",
    "city": "Mumbai",
    "industry": "business",
    "sector": "Other",
    "founded": null,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q5576812"
  },
  {
    "slug": "hats-off-productions",
    "name": "Hats Off Productions",
    "website": "http://hatsoffproduction.com/",
    "city": "Mumbai",
    "industry": "business",
    "sector": "Other",
    "founded": 2003,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q5681794"
  },
  {
    "slug": "hdfc-ergo-general-insurance-company",
    "name": "HDFC ERGO General Insurance Company",
    "website": "https://www.hdfcergo.com/",
    "city": "Mumbai",
    "industry": "insurance",
    "sector": "FinTech",
    "founded": null,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q5629187"
  },
  {
    "slug": "hdfc-securities",
    "name": "HDFC securities",
    "website": "http://www.hdfcsec.com/",
    "city": "Mumbai",
    "industry": "financial services",
    "sector": "FinTech",
    "founded": 2000,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q19891703"
  },
  {
    "slug": "high-mark-credit-information-services",
    "name": "High Mark Credit Information Services",
    "website": "http://www.highmark.in/",
    "city": "Mumbai",
    "industry": "financial services",
    "sector": "FinTech",
    "founded": 2005,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q5755905"
  },
  {
    "slug": "himanshu-kushwaha",
    "name": "Himanshu Kushwaha",
    "website": "http://www.vutvs.com/",
    "city": "Mumbai",
    "industry": "business",
    "sector": "Other",
    "founded": 2006,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q30643898"
  },
  {
    "slug": "housing-com",
    "name": "Housing.com",
    "website": "https://housing.com/",
    "city": "Mumbai",
    "industry": "business",
    "sector": "Other",
    "founded": 2012,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q18125739"
  },
  {
    "slug": "hurix-systems",
    "name": "Hurix Systems",
    "website": "https://hurix.com/",
    "city": "Mumbai",
    "industry": "business",
    "sector": "Other",
    "founded": 2000,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q5946556"
  },
  {
    "slug": "iball",
    "name": "iBall",
    "website": "http://www.iball.co.in",
    "city": "Mumbai",
    "industry": "consumer electronics industry",
    "sector": "Other",
    "founded": 2001,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q5969268"
  },
  {
    "slug": "icici-prudential",
    "name": "ICICI Prudential",
    "website": "http://www.iciciprulife.com/",
    "city": "Mumbai",
    "industry": "insurance industry",
    "sector": "FinTech",
    "founded": 2000,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q5969602"
  },
  {
    "slug": "idfc-project-equity",
    "name": "IDFC Project Equity",
    "website": "http://www.idfcprojectequity.com/",
    "city": "Mumbai",
    "industry": "business",
    "sector": "Other",
    "founded": null,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q5970010"
  },
  {
    "slug": "image-media-vision",
    "name": "Image Media Vision",
    "website": "http://www.imagemediavision.org/",
    "city": "Mumbai",
    "industry": "business",
    "sector": "Other",
    "founded": 2012,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q18125884"
  },
  {
    "slug": "impact-guru",
    "name": "Impact Guru",
    "website": "https://www.impactguru.com/",
    "city": "Mumbai",
    "industry": "crowdfunding",
    "sector": "Other",
    "founded": 2014,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q30589043"
  },
  {
    "slug": "indiabulls",
    "name": "Indiabulls",
    "website": "http://www.indiabulls.com",
    "city": "Mumbai",
    "industry": "financial services",
    "sector": "FinTech",
    "founded": 2000,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q6019738"
  },
  {
    "slug": "indiafirst-life-insurance-company",
    "name": "IndiaFirst Life Insurance Company",
    "website": "http://www.indiafirstlife.com",
    "city": "Mumbai",
    "industry": "life insurance",
    "sector": "FinTech",
    "founded": 2009,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q6019231"
  },
  {
    "slug": "indusind-securities",
    "name": "IndusInd Securities",
    "website": "https://www.reliancesmartmoney.com/",
    "city": "Mumbai",
    "industry": "business",
    "sector": "Other",
    "founded": null,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q12508385"
  },
  {
    "slug": "inkfruit",
    "name": "Inkfruit",
    "website": "http://www.inkfruit.com",
    "city": "Mumbai",
    "industry": "business",
    "sector": "Other",
    "founded": 2007,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q16251019"
  },
  {
    "slug": "intelenet-global-services",
    "name": "Intelenet Global Services",
    "website": "http://www.intelenetglobal.com",
    "city": "Mumbai",
    "industry": "business",
    "sector": "Other",
    "founded": 2000,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q6043596"
  },
  {
    "slug": "internet-and-mobile-association-of-india",
    "name": "Internet and Mobile Association of India",
    "website": "http://www.iamai.in/",
    "city": "Mumbai",
    "industry": "business",
    "sector": "Other",
    "founded": 2004,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q6055734"
  },
  {
    "slug": "jar-pictures",
    "name": "Jar Pictures",
    "website": "http://www.jarpictures.com/",
    "city": "Mumbai",
    "industry": "business",
    "sector": "Other",
    "founded": 2011,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q16249595"
  },
  {
    "slug": "jay-production",
    "name": "Jay Production",
    "website": "http://www.jayproduction.co.in/",
    "city": "Mumbai",
    "industry": "business",
    "sector": "Other",
    "founded": null,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q6167059"
  },
  {
    "slug": "jsw-cement",
    "name": "JSW Cement",
    "website": "http://www.jsw.in/organization/jsw_cement.shtml",
    "city": "Mumbai",
    "industry": "cement",
    "sector": "Other",
    "founded": null,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q6108969"
  },
  {
    "slug": "jsw-infrastructure",
    "name": "JSW Infrastructure",
    "website": "http://www.jsw.in/",
    "city": "Mumbai",
    "industry": "business",
    "sector": "Other",
    "founded": 2006,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q6108976"
  },
  {
    "slug": "jugaad-motion-pictures",
    "name": "Jugaad Motion Pictures",
    "website": "https://www.jugaadmotionpictures.in/",
    "city": "Mumbai",
    "industry": "business",
    "sector": "Other",
    "founded": 2016,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q117217758"
  },
  {
    "slug": "k-sera-sera",
    "name": "K. Sera Sera",
    "website": "http://www.kserasera.com",
    "city": "Mumbai",
    "industry": "business",
    "sector": "Other",
    "founded": null,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q6324000"
  },
  {
    "slug": "kalpanik-films",
    "name": "Kalpanik Films",
    "website": "https://www.kalpanikfilms.com/",
    "city": "Mumbai",
    "industry": "business",
    "sector": "Other",
    "founded": 2013,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q63959358"
  },
  {
    "slug": "kapotex-industries",
    "name": "Kapotex industries",
    "website": "http://www.kapotex.com/",
    "city": "Mumbai",
    "industry": "textile industry",
    "sector": "Other",
    "founded": 2008,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q17106622"
  },
  {
    "slug": "kaya-limited",
    "name": "Kaya Limited",
    "website": "http://www.kaya.in/",
    "city": "Mumbai",
    "industry": "business",
    "sector": "Other",
    "founded": 2003,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q23306016"
  },
  {
    "slug": "kingfisher-xpress",
    "name": "Kingfisher Xpress",
    "website": "http://kingfisherxpress.com",
    "city": "Mumbai",
    "industry": "business",
    "sector": "Other",
    "founded": 2010,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q6412754"
  },
  {
    "slug": "kumite-1-league",
    "name": "Kumite 1 League",
    "website": "https://kumite1league.in/",
    "city": "Mumbai",
    "industry": "business",
    "sector": "Other",
    "founded": 2017,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q65049930"
  },
  {
    "slug": "level10-comics",
    "name": "Level10 Comics",
    "website": "http://www.level10comics.com/",
    "city": "Mumbai",
    "industry": "business",
    "sector": "Other",
    "founded": 2009,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q6534989"
  },
  {
    "slug": "liberty-videocon-general-insurance",
    "name": "Liberty Videocon General Insurance",
    "website": "http://www.libertyvideocon.com",
    "city": "Mumbai",
    "industry": "insurance",
    "sector": "FinTech",
    "founded": 2013,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q18127220"
  },
  {
    "slug": "lyf",
    "name": "LYF",
    "website": "http://www.mylyf.com",
    "city": "Mumbai",
    "industry": "consumer electronics industry",
    "sector": "Other",
    "founded": 2015,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q24589909"
  },
  {
    "slug": "maharashtra-state-road-development-corporation",
    "name": "Maharashtra State Road Development Corporation",
    "website": "http://www.msrdc.org",
    "city": "Mumbai",
    "industry": "construction",
    "sector": "Other",
    "founded": null,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q2722424"
  },
  {
    "slug": "mahindra-aerospace",
    "name": "Mahindra Aerospace",
    "website": "http://www.mahindraaerospace.com",
    "city": "Mumbai",
    "industry": "aerospace industry",
    "sector": "Other",
    "founded": 2003,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q6734037"
  },
  {
    "slug": "mahindra-epc",
    "name": "Mahindra EPC",
    "website": "http://www.mahindraepc.in/",
    "city": "Mumbai",
    "industry": "business",
    "sector": "Other",
    "founded": 2010,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q17071166"
  },
  {
    "slug": "mahindra-navistar",
    "name": "Mahindra Navistar",
    "website": "http://www.mahindratruckandbus.com/",
    "city": "Mumbai",
    "industry": "automotive industry",
    "sector": "Other",
    "founded": null,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q6734057"
  },
  {
    "slug": "meru-cabs",
    "name": "Meru Cabs",
    "website": "http://www.merucabs.com",
    "city": "Mumbai",
    "industry": "transport",
    "sector": "Logistics",
    "founded": 2007,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q19893970"
  },
  {
    "slug": "moshe-s",
    "name": "Moshe's",
    "website": "http://moshes.in/",
    "city": "Mumbai",
    "industry": "restaurant",
    "sector": "Other",
    "founded": 2004,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q16953551"
  },
  {
    "slug": "multi-commodity-exchange-of-india-ltd",
    "name": "Multi Commodity Exchange Of India Ltd.",
    "website": "https://www.mcxindia.com",
    "city": "Mumbai",
    "industry": "service",
    "sector": "Other",
    "founded": 2003,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q6934544"
  },
  {
    "slug": "mumbai-refinery",
    "name": "Mumbai Refinery",
    "website": "https://www.hindustanpetroleum.com/hp-refineries",
    "city": "Mumbai",
    "industry": "petroleum industry",
    "sector": "Other",
    "founded": null,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q6935319"
  },
  {
    "slug": "mx-player",
    "name": "MX Player",
    "website": "http://mx.j2inter.com",
    "city": "Mumbai",
    "industry": "business",
    "sector": "Other",
    "founded": null,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q25389797"
  },
  {
    "slug": "nakshatra-jewellery",
    "name": "Nakshatra Jewellery",
    "website": "http://www.nakshatradiamonds.in",
    "city": "Mumbai",
    "industry": "business",
    "sector": "Other",
    "founded": 2000,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q6960712"
  },
  {
    "slug": "narotam-sekhsaria-foundation",
    "name": "Narotam sekhsaria foundation",
    "website": "https://nsfoundation.co.in",
    "city": "Mumbai",
    "industry": "business",
    "sector": "Other",
    "founded": 2002,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q6966133"
  },
  {
    "slug": "narsi-interior",
    "name": "Narsi Interior",
    "website": "https://narsi.in",
    "city": "Mumbai",
    "industry": "business",
    "sector": "Other",
    "founded": 2008,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q136373803"
  },
  {
    "slug": "national-bulk-handling-corporation",
    "name": "National Bulk Handling Corporation",
    "website": "http://www.nbhcindia.com",
    "city": "Mumbai",
    "industry": "business",
    "sector": "Other",
    "founded": 2003,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q6971147"
  },
  {
    "slug": "national-commodity-and-derivatives-exchange",
    "name": "National Commodity and Derivatives Exchange",
    "website": "http://www.ncdex.com/",
    "city": "Mumbai",
    "industry": "service",
    "sector": "Other",
    "founded": 2003,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q6971712"
  },
  {
    "slug": "national-spot-exchange",
    "name": "National Spot Exchange",
    "website": "http://www.nationalspotexchange.com/",
    "city": "Mumbai",
    "industry": "service",
    "sector": "Other",
    "founded": 2005,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q6978661"
  },
  {
    "slug": "newj",
    "name": "Newj",
    "website": "https://thenewj.com/",
    "city": "Mumbai",
    "industry": "business",
    "sector": "Other",
    "founded": null,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q107648742"
  },
  {
    "slug": "only-much-louder",
    "name": "Only Much Louder",
    "website": "http://oml.in/about/",
    "city": "Mumbai",
    "industry": "business",
    "sector": "Other",
    "founded": 2002,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q7094222"
  },
  {
    "slug": "optimystix-entertainment",
    "name": "Optimystix Entertainment",
    "website": "http://www.optimystix.tv",
    "city": "Mumbai",
    "industry": "television",
    "sector": "Other",
    "founded": 2000,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q7098995"
  },
  {
    "slug": "oxemberg",
    "name": "Oxemberg",
    "website": "http://www.oxemberg.com",
    "city": "Mumbai",
    "industry": "fashion",
    "sector": "Other",
    "founded": null,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q19899307"
  },
  {
    "slug": "pagalguy",
    "name": "PaGaLGuY",
    "website": "http://www.pagalguy.com",
    "city": "Mumbai",
    "industry": "business",
    "sector": "Other",
    "founded": null,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q19895008"
  },
  {
    "slug": "palador-pictures",
    "name": "Palador Pictures",
    "website": "http://www.mypalador.com",
    "city": "Mumbai",
    "industry": "entertainment",
    "sector": "Media",
    "founded": 2005,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q7126374"
  },
  {
    "slug": "panorama-studios",
    "name": "Panorama Studios",
    "website": "http://panoramastudios.in/",
    "city": "Mumbai",
    "industry": "entertainment",
    "sector": "Media",
    "founded": 2005,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q19895072"
  },
  {
    "slug": "paymate",
    "name": "PayMate",
    "website": "http://www.gopaymate.com/",
    "city": "Mumbai",
    "industry": "financial services",
    "sector": "FinTech",
    "founded": 2006,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q7156552"
  },
  {
    "slug": "pepperfry-com",
    "name": "Pepperfry.com",
    "website": "http://www.pepperfry.com",
    "city": "Mumbai",
    "industry": "business",
    "sector": "Other",
    "founded": 2011,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q7166413"
  },
  {
    "slug": "piramal-realty",
    "name": "Piramal Realty",
    "website": "https://www.piramalrealty.com",
    "city": "Mumbai",
    "industry": "real estate development",
    "sector": "Other",
    "founded": 2012,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q114000903"
  },
  {
    "slug": "planet41",
    "name": "Planet41",
    "website": "http://planet41.com/",
    "city": "Mumbai",
    "industry": "business",
    "sector": "Other",
    "founded": 2006,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q7201041"
  },
  {
    "slug": "porsche-india",
    "name": "Porsche India",
    "website": "http://www.porsche.in",
    "city": "Mumbai",
    "industry": "automotive industry",
    "sector": "Other",
    "founded": 2004,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q7230400"
  },
  {
    "slug": "q21660492",
    "name": "Q21660492",
    "website": "http://www.miraklecouriers.com/",
    "city": "Mumbai",
    "industry": "business",
    "sector": "Other",
    "founded": 2009,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q21660492"
  },
  {
    "slug": "quikr",
    "name": "Quikr",
    "website": "http://www.quikr.com/",
    "city": "Mumbai",
    "industry": "media & entertainment industry",
    "sector": "Media",
    "founded": 2008,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q7271957"
  },
  {
    "slug": "rajshri-media",
    "name": "Rajshri Media",
    "website": "http://www.rajshri.com/",
    "city": "Mumbai",
    "industry": "digital entertainment",
    "sector": "Media",
    "founded": 2006,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q7286441"
  },
  {
    "slug": "reliance-broadcast-network",
    "name": "Reliance Broadcast Network",
    "website": "http://www.reliancebroadcast.com/",
    "city": "Mumbai",
    "industry": "business",
    "sector": "Other",
    "founded": 2005,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q7311010"
  },
  {
    "slug": "reliance-digital",
    "name": "Reliance Digital",
    "website": "https://www.reliancedigital.in/",
    "city": "Mumbai",
    "industry": "retail",
    "sector": "E-commerce",
    "founded": 2007,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q7311012"
  },
  {
    "slug": "reliance-entertainment",
    "name": "Reliance Entertainment",
    "website": "http://www.rbe.co.in/",
    "city": "Mumbai",
    "industry": "mass media",
    "sector": "Media",
    "founded": 2005,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q3634702"
  },
  {
    "slug": "reliance-fresh",
    "name": "Reliance Fresh",
    "website": "https://relianceretail.com/reliance-fresh.html",
    "city": "Mumbai",
    "industry": "retail",
    "sector": "E-commerce",
    "founded": 2006,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q7311014"
  },
  {
    "slug": "reliance-general-insurance",
    "name": "Reliance General Insurance",
    "website": "https://www.reliancegeneral.co.in/insurance/home.aspx",
    "city": "Mumbai",
    "industry": "general insurance",
    "sector": "FinTech",
    "founded": 2001,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q7311015"
  },
  {
    "slug": "reliance-natural-resources-limited",
    "name": "Reliance Natural Resources Limited",
    "website": "http://www.rnrl.in/",
    "city": "Mumbai",
    "industry": "petroleum industry",
    "sector": "Other",
    "founded": 2000,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q7311025"
  },
  {
    "slug": "reliance-retail",
    "name": "Reliance Retail",
    "website": "https://relianceretail.com",
    "city": "Mumbai",
    "industry": "retail",
    "sector": "E-commerce",
    "founded": null,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q7311028"
  },
  {
    "slug": "rentmacha",
    "name": "RentMacha",
    "website": "https://www.rentmacha.com",
    "city": "Mumbai",
    "industry": "leasing service",
    "sector": "Other",
    "founded": 2016,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q134884966"
  },
  {
    "slug": "rupesh-paul-productions-limited",
    "name": "Rupesh Paul Productions Limited",
    "website": "http://www.rpplmovies.com",
    "city": "Mumbai",
    "industry": "business",
    "sector": "Other",
    "founded": 2012,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q17152137"
  },
  {
    "slug": "s-kumars",
    "name": "S. Kumars",
    "website": "http://www.sknl.co.in/",
    "city": "Mumbai",
    "industry": "business",
    "sector": "Other",
    "founded": 2000,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q7387626"
  },
  {
    "slug": "samco-securities",
    "name": "SAMCO Securities",
    "website": "http://www.samco.in/",
    "city": "Mumbai",
    "industry": "business",
    "sector": "Other",
    "founded": null,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q24949375"
  },
  {
    "slug": "satellize",
    "name": "Satellize",
    "website": "http://satellize.com/",
    "city": "Mumbai",
    "industry": "space industry",
    "sector": "Other",
    "founded": null,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q104849207"
  },
  {
    "slug": "scienceabc",
    "name": "ScienceABC",
    "website": "https://www.scienceabc.com",
    "city": "Mumbai",
    "industry": "business",
    "sector": "Other",
    "founded": 2015,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q126810523"
  },
  {
    "slug": "semsons-tech",
    "name": "Semsons Tech",
    "website": "https://www.semsonstech.com/",
    "city": "Mumbai",
    "industry": "jewelry industry",
    "sector": "Other",
    "founded": null,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q141104757"
  },
  {
    "slug": "shakuntalam-telefilms",
    "name": "Shakuntalam Telefilms",
    "website": "http://www.shakuntalamtelefilms.com",
    "city": "Mumbai",
    "industry": "entertainment",
    "sector": "Media",
    "founded": 2004,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q7487103"
  },
  {
    "slug": "shirpur-gold-refinery",
    "name": "Shirpur Gold Refinery",
    "website": "http://www.shirpurgold.net/",
    "city": "Mumbai",
    "industry": "business",
    "sector": "Other",
    "founded": 2001,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q7498971"
  },
  {
    "slug": "shree-ashtavinayak-cine-vision-ltd",
    "name": "Shree Ashtavinayak Cine Vision Ltd",
    "website": "http://www.ashtavinayakindia.com/",
    "city": "Mumbai",
    "industry": "business",
    "sector": "Other",
    "founded": 2001,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q7503472"
  },
  {
    "slug": "sikhya-entertainment",
    "name": "Sikhya Entertainment",
    "website": "https://sikhyaentertainment.com/",
    "city": "Mumbai",
    "industry": "entertainment",
    "sector": "Media",
    "founded": 2008,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q16949665"
  },
  {
    "slug": "sme-rating-agency-of-india",
    "name": "SME Rating Agency of India",
    "website": "http://smera.in/Aboutus.aspx",
    "city": "Mumbai",
    "industry": "business",
    "sector": "Other",
    "founded": 2005,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q7391155"
  },
  {
    "slug": "sol",
    "name": "Sol",
    "website": "http://www.solworld.co.in/",
    "city": "Mumbai",
    "industry": "business",
    "sector": "Other",
    "founded": 2003,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q7555486"
  },
  {
    "slug": "sports-box",
    "name": "Sports Box",
    "website": "http://galaxycorp.com/",
    "city": "Mumbai",
    "industry": "restaurant",
    "sector": "Other",
    "founded": 2004,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q18201925"
  },
  {
    "slug": "sr-brothers",
    "name": "SR Brothers",
    "website": "https://srbrothers.co/",
    "city": "Mumbai",
    "industry": "digital content",
    "sector": "Other",
    "founded": 2018,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q133829046"
  },
  {
    "slug": "sun-pharma-advanced-research",
    "name": "Sun Pharma Advanced Research",
    "website": "https://sparc.life",
    "city": "Mumbai",
    "industry": "business",
    "sector": "Other",
    "founded": 2007,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q30263032"
  },
  {
    "slug": "super-fight-league",
    "name": "Super Fight League",
    "website": "http://www.superfightleague.com/",
    "city": "Mumbai",
    "industry": "business",
    "sector": "Other",
    "founded": 2012,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q7642337"
  },
  {
    "slug": "svar-media-network",
    "name": "SVAR Media Network",
    "website": "https://svarmedia.com/",
    "city": "Mumbai",
    "industry": "magazine",
    "sector": "Other",
    "founded": 2021,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q138937971"
  },
  {
    "slug": "tata-aig",
    "name": "TATA AIG",
    "website": "https://www.tataaig.com/",
    "city": "Mumbai",
    "industry": "insurance",
    "sector": "FinTech",
    "founded": 2001,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q7669429"
  },
  {
    "slug": "tata-communications",
    "name": "Tata Communications",
    "website": "http://www.tatacommunications.com/",
    "city": "Mumbai",
    "industry": "telecommunications",
    "sector": "Other",
    "founded": 2008,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q2395390"
  },
  {
    "slug": "tata-motors-cars",
    "name": "Tata Motors Cars",
    "website": "http://www.tatacars.com/",
    "city": "Mumbai",
    "industry": "automotive industry",
    "sector": "Other",
    "founded": null,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q7687819"
  },
  {
    "slug": "testriq-qa-lab",
    "name": "TESTRIQ QA LAB",
    "website": "https://www.testriq.com/",
    "city": "Mumbai",
    "industry": "business",
    "sector": "Other",
    "founded": 2010,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q139830574"
  },
  {
    "slug": "the-men-thing",
    "name": "THE MEN THING",
    "website": "https://www.thementhing.com/",
    "city": "Mumbai",
    "industry": "jewelry",
    "sector": "Other",
    "founded": 2016,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q140365914"
  },
  {
    "slug": "transunion-cibil",
    "name": "TransUnion CIBIL",
    "website": "https://www.transunioncibil.com/",
    "city": "Mumbai",
    "industry": "business",
    "sector": "Other",
    "founded": 2000,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q3530909"
  },
  {
    "slug": "travelguru-com",
    "name": "Travelguru.com",
    "website": "http://www.travelguru.com/",
    "city": "Mumbai",
    "industry": "business",
    "sector": "Other",
    "founded": 2005,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q7836007"
  },
  {
    "slug": "utv-global-broadcasting",
    "name": "UTV Global Broadcasting",
    "website": "http://www.utvgroup.com/",
    "city": "Mumbai",
    "industry": "business",
    "sector": "Other",
    "founded": 2007,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q3547543"
  },
  {
    "slug": "vfs-global",
    "name": "VFS Global",
    "website": "https://www.vfsglobal.com",
    "city": "Mumbai",
    "industry": "business",
    "sector": "Other",
    "founded": 2001,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q7906873"
  },
  {
    "slug": "voot",
    "name": "Voot",
    "website": "http://www.Voot.com/",
    "city": "Mumbai",
    "industry": "over-the-top media service",
    "sector": "Media",
    "founded": 2016,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q24884920"
  },
  {
    "slug": "web18",
    "name": "Web18",
    "website": "http://www.in.com/",
    "city": "Mumbai",
    "industry": "Internet",
    "sector": "SaaS",
    "founded": null,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q7978424"
  },
  {
    "slug": "welspun-investments-and-commercials-ltd",
    "name": "Welspun Investments and Commercials Ltd",
    "website": "http://www.welspun.com/content.asp?Link=Y&SubmenuID=66",
    "city": "Mumbai",
    "industry": "investment",
    "sector": "Other",
    "founded": 2008,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q7982076"
  },
  {
    "slug": "welspun-retail-ltd",
    "name": "Welspun Retail Ltd",
    "website": "http://www.welspun-retail.com/",
    "city": "Mumbai",
    "industry": "retail",
    "sector": "E-commerce",
    "founded": 2006,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q16967118"
  },
  {
    "slug": "wishberry",
    "name": "Wishberry",
    "website": "http://www.wishberry.in/",
    "city": "Mumbai",
    "industry": "business",
    "sector": "Other",
    "founded": 2011,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q28127092"
  },
  {
    "slug": "wishtel",
    "name": "Wishtel",
    "website": "http://www.wishtel.com/",
    "city": "Mumbai",
    "industry": "information technology",
    "sector": "SaaS",
    "founded": null,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q8027640"
  },
  {
    "slug": "xstok",
    "name": "XSTOK",
    "website": "http://www.xstok.com",
    "city": "Mumbai",
    "industry": "textile industry",
    "sector": "Other",
    "founded": 2015,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q24952145"
  },
  {
    "slug": "y-films",
    "name": "Y-Films",
    "website": "http://www.yfilms.in",
    "city": "Mumbai",
    "industry": "business",
    "sector": "Other",
    "founded": 2011,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q8045705"
  },
  {
    "slug": "ysk-laboratories-private-limited",
    "name": "YSK Laboratories Private Limited",
    "website": "https://www.ysklabs.com",
    "city": "Mumbai",
    "industry": "pharmaceutical industry",
    "sector": "HealthTech",
    "founded": 2023,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q141015442"
  },
  {
    "slug": "zandra-life-sciences",
    "name": "Zandra Life Sciences",
    "website": "https://reincarn.in",
    "city": "Mumbai",
    "industry": "nutraceutical",
    "sector": "Other",
    "founded": 2010,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q140265573"
  },
  {
    "slug": "ziqitza",
    "name": "Ziqitza",
    "website": "http://zhl.org.in/",
    "city": "Mumbai",
    "industry": "business",
    "sector": "Other",
    "founded": 2002,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q20056389"
  },
  {
    "slug": "zymo",
    "name": "Zymo",
    "website": "https://zymo.app",
    "city": "Mumbai",
    "industry": "automotive industry",
    "sector": "Other",
    "founded": 2023,
    "lat": 19.076,
    "lng": 72.8777,
    "source": "http://www.wikidata.org/entity/Q138778818"
  },
  {
    "slug": "bajaj-allianz-general-insurance",
    "name": "Bajaj Allianz General Insurance",
    "website": "https://www.bajajallianz.com/",
    "city": "Pune",
    "industry": "financial services",
    "sector": "FinTech",
    "founded": null,
    "lat": 18.5204,
    "lng": 73.8567,
    "source": "http://www.wikidata.org/entity/Q804084"
  },
  {
    "slug": "curemeabroad",
    "name": "CureMeAbroad",
    "website": "https://curemeabroad.com/",
    "city": "Pune",
    "industry": "health technology",
    "sector": "SaaS",
    "founded": 2025,
    "lat": 18.5204,
    "lng": 73.8567,
    "source": "http://www.wikidata.org/entity/Q140425461"
  },
  {
    "slug": "i-hub-quantum-technology-foundation",
    "name": "I-HUB Quantum Technology Foundation",
    "website": "https://www.quantech.org.in/",
    "city": "Pune",
    "industry": "business",
    "sector": "Other",
    "founded": null,
    "lat": 18.5204,
    "lng": 73.8567,
    "source": "http://www.wikidata.org/entity/Q123422168"
  },
  {
    "slug": "pallix",
    "name": "Pallix",
    "website": "https://pallix.in",
    "city": "Pune",
    "industry": "artificial intelligence",
    "sector": "Other",
    "founded": 2026,
    "lat": 18.5204,
    "lng": 73.8567,
    "source": "http://www.wikidata.org/entity/Q140817951"
  },
  {
    "slug": "suzlon-group",
    "name": "Suzlon Group",
    "website": "http://www.suzlon.com",
    "city": "Pune",
    "industry": "business",
    "sector": "Other",
    "founded": null,
    "lat": 18.5204,
    "lng": 73.8567,
    "source": "http://www.wikidata.org/entity/Q124361002"
  }
] as const;
